decompiler: address.hh File Reference
address.hh File Reference
Classes for specifying addresses and other low-level constants.
#include "space.hh"
Classes
class Address
A low-level machine address for labelling bytes and data.
class SeqNum
A class for uniquely labelling and comparing PcodeOps.
class Range
A contiguous range of bytes in some address space.
class RangeList
A disjoint set of Ranges, possibly across multiple address spaces.
Functions
uintb calc_mask (int4 size)
Calculate a mask for a given byte size.
uintb pcode_right (uintb val, int4 sa)
uintb pcode_left (uintb val, int4 sa)
uintb minimalmask (uintb val)
Calculate smallest mask that covers the given value.
bool signbit_negative (uintb val, int4 size)
Return true if the sign-bit is set.
uintb uintb_negate (uintb in, int4 size)
Negate the sized value.
uintb sign_extend (uintb in, int4 sizein, int4 sizeout)
Sign-extend a value between two byte sizes.
void sign_extend (intb &val, int4 bit)
Sign extend above given bit.
void zero_extend (intb &val, int4 bit)
Clear all bits above given bit.
void byte_swap (intb &val, int4 size)
Swap bytes in the given value.
uintb byte_swap (uintb val, int4 size)
Return the given value with bytes swapped.
int4 leastsigbit_set (uintb val)
Return index of least significant bit set in given value.
int4 mostsigbit_set (uintb val)
Return index of most significant bit set in given value.
int4 popcount (uintb val)
Return the number of one bits in the given value.
int4 count_leading_zeros (uintb val)
Return the number of leading zero bits in the given value.
uintb coveringmask (uintb val)
Return a mask that covers the given value.
int4 bit_transitions (uintb val, int4 sz)
Calculate the number of bit transitions in the sized value.
void mult64to128 (uint8 *res, uint8 x, uint8 y)
Multiply 2 unsigned 64-bit values, producing a 128-bit value.
void unsignedSubtract128 (uint8 *a, uint8 *b)
Subtract (in-place) a 128-bit value from a base 128-value.
int4 unsignedCompare128 (uint8 *a, uint8 *b)
Compare two unsigned 128-bit values.
int4 power2Divide (int4 n, uint8 divisor, uint8 &q, uint8 &r)
Unsigned division of a power of 2 (upto 2^127) by a 64-bit divisor.
Variables
uintb uintbmasks []
Precalculated masks indexed by size.
Detailed Description
Classes for specifying addresses and other low-level constants.
All addresses are absolute and there are are no registers in CPUI. However, all addresses are prefixed with an "immutable" pointer, which can specify a separate RAM space, a register space, an i/o space etc. Thus a translation from a real machine language will typically simulate registers by placing them in their own space, separate from RAM. Indirection (i.e. pointers) must be simulated through the LOAD and STORE ops.
Function Documentation
bit_transitions()
int4 bit_transitions (uintb val, int4 sz)
Calculate the number of bit transitions in the sized value.
Treat val as a constant of size sz. Scanning across the bits of val return the number of transitions (from 0->1 or 1->0) If there are 2 or less transitions, this is an indication of a bit flag or a mask
Parameters
val is the given value
sz is the size to treat the value as
Returns
the number of transitions
Referenced by ActionConstantPtr::isPointer(), and CircleRange::setNZMask().
byte_swap() [1/2]
void byte_swap (intb & val, int4 size)
Swap bytes in the given value.
Swap the least significant size bytes in val
Parameters
val is a reference to the value to swap
size is the number of bytes to swap
Referenced by MemoryImage::find(), EmulatePcodeOp::getLoadImageValue(), EmulateSnippet::getLoadImageValue(), MemoryBank::getPage(), and MemoryBank::setPage().
byte_swap() [2/2]
uintb byte_swap (uintb val, int4 size)
Return the given value with bytes swapped.
Swap the least significant size bytes in val
Parameters
val is the value to swap
size is the number of bytes to swap
Returns
the swapped value
calc_mask()
uintb calc_mask (int4 size) inline
Calculate a mask for a given byte size.
Parameters
size is the desired size in bytes
Returns
a value appropriate for masking off the first size bytes
References uintbmasks.
Referenced by ActionStackPtrFlow::analyzeExtraPop(), RuleCollectTerms::applyOp(), RuleOrMask::applyOp(), RuleNegateIdentity::applyOp(), RuleShiftBitops::applyOp(), RuleRightShiftAnd::applyOp(), RulePullsubMulti::applyOp(), RulePullsubIndirect::applyOp(), RuleHighOrderAnd::applyOp(), RuleAndDistribute::applyOp(), RuleAndCommute::applyOp(), RuleAndPiece::applyOp(), RuleAndCompare::applyOp(), RuleDoubleShift::applyOp(), RuleShiftCompare::applyOp(), RuleBoolZext::applyOp(), RuleSborrow::applyOp(), RuleSignShift::applyOp(), RuleTestSign::applyOp(), RuleTransformCpool::applyOp(), Rule2Comp2Mult::applyOp(), RuleCarryElim::applyOp(), RuleSub2Add::applyOp(), RuleSubCommute::applyOp(), RuleConcatCommute::applyOp(), RuleShiftAnd::applyOp(), RuleSubZext::applyOp(), RuleHumptyOr::applyOp(), RuleEmbed::applyOp(), RuleLess2Zero::applyOp(), RuleLessEqual2Zero::applyOp(), RuleSLess2Zero::applyOp(), RuleEqual2Zero::applyOp(), RuleEqual2Constant::applyOp(), RuleMultNegOne::applyOp(), RuleAddUnsigned::applyOp(), RuleDivTermAdd2::applyOp(), RuleSignDiv2::applyOp(), RuleSignNearMult::applyOp(), RuleModOpt::applyOp(), RuleSubvarAnd::applyOp(), RuleSubvarSubpiece::applyOp(), RuleSubvarCompZero::applyOp(), RuleSubvarZext::applyOp(), RuleSubvarSext::applyOp(), RuleFuncPtrEncoding::applyOp(), RuleThreeWayCompare::applyOp(), Funcdata::calcNZMask(), JumpBasic::calcRange(), AddrSpace::calcScaleMask(), ActionStackPtrFlow::checkClog(), ValueSetSolver::checkRelativeConstant(), CircleRange::CircleRange(), RuleThreeWayCompare::detectThreeWay(), OpBehaviorIntAdd::evaluateBinary(), OpBehaviorIntSub::evaluateBinary(), OpBehaviorIntCarry::evaluateBinary(), OpBehaviorIntLeft::evaluateBinary(), OpBehaviorIntRight::evaluateBinary(), OpBehaviorIntSright::evaluateBinary(), OpBehaviorIntMult::evaluateBinary(), OpBehaviorSubpiece::evaluateBinary(), JumpTable::foldInNormalization(), ActionDeadCode::gatherConsumedReturn(), AliasChecker::gatherOffset(), RuleSLess2Zero::getHiBit(), EmulatePcodeOp::getLoadImageValue(), EmulateSnippet::getLoadImageValue(), PcodeOp::getNZMaskLocal(), ContextDatabase::getTrackedValue(), MemoryBank::getValue(), EquateSymbol::isValueClose(), ActionDeadCode::markConsumedParameters(), TransformManager::newConstant(), TransformManager::newSplit(), FloatFormat::opTrunc(), Funcdata::opUndoPtradd(), ActionDeadCode::propagateConsumed(), CircleRange::pullBack(), CircleRange::pullBackBinary(), CircleRange::pullBackUnary(), PrintC::push_integer(), ActionDeadCode::pushConsumed(), PrintC::pushEquate(), CircleRange::pushForwardBinary(), CircleRange::pushForwardUnary(), OpBehaviorIntAdd::recoverInputBinary(), OpBehaviorIntSub::recoverInputBinary(), OpBehaviorIntLeft::recoverInputBinary(), OpBehaviorIntZext::recoverInputUnary(), OpBehaviorIntSext::recoverInputUnary(), Funcdata::replaceLessequal(), SegmentedResolver::resolve(), TypeFactory::setEnumValues(), CircleRange::setFull(), CircleRange::setNZMask(), CircleRange::setRange(), SubvariableFlow::setReplacement(), MemoryBank::setValue(), sign_extend(), SubvariableFlow::traceBackward(), SubvariableFlow::traceBackwardSext(), SubvariableFlow::traceForward(), SubvariableFlow::traceForwardSext(), ActionLikelyTrash::traceTrash(), Funcdata::transferVarnodeProperties(), RulePtrArith::transformPtr(), and uintb_negate().
count_leading_zeros()
int4 count_leading_zeros (uintb val)
Return the number of leading zero bits in the given value.
Count the number of more significant zero bits before the most significant one bit in the representation of the given value;
Parameters
val is the given value
Returns
the number of zero bits
Referenced by RuleDivOpt::findForm(), CircleRange::getMaxInfo(), CircleRange::pushForwardBinary(), and JumpValuesRange::truncate().
coveringmask()
uintb coveringmask (uintb val)
Return a mask that covers the given value.
Return smallest number of form 2^n-1, bigger or equal to the given value
Parameters
val is the given value
Returns
the mask
Referenced by JumpBasic::calcRange(), PcodeOp::getNZMaskLocal(), and ActionDeadCode::propagateConsumed().
leastsigbit_set()
int4 leastsigbit_set (uintb val)
Return index of least significant bit set in given value.
The least significant bit is index 0.
Parameters
val is the given value
Returns
the index of the least significant set bit, or -1 if none are set
Referenced by SubvariableFlow::addConstant(), SubvariableFlow::addSuggestedPatch(), RuleShiftBitops::applyOp(), RuleDoubleShift::applyOp(), RuleShiftCompare::applyOp(), RuleShiftAnd::applyOp(), RuleSubvarCompZero::applyOp(), RulePopcountBoolXor::applyOp(), PcodeOp::getNZMaskLocal(), SubvariableFlow::getReplacementAddress(), CircleRange::minimalContainer(), ActionDeadCode::propagateConsumed(), CircleRange::setNZMask(), SubvariableFlow::SubvariableFlow(), SubvariableFlow::traceBackward(), and SubvariableFlow::traceForward().
minimalmask()
uintb minimalmask (uintb val) inline
Calculate smallest mask that covers the given value.
Calculcate a mask that covers either the least significant byte, uint2, uint4, or uint8, whatever is smallest.
Parameters
val is the given value
Returns
the minimal mask
Referenced by JumpTable::foldInNormalization(), ActionDeadCode::gatherConsumedReturn(), and ActionDeadCode::markConsumedParameters().
mostsigbit_set()
int4 mostsigbit_set (uintb val)
Return index of most significant bit set in given value.
The least significant bit is index 0.
Parameters
val is the given value
Returns
the index of the most significant set bit, or -1 if none are set
Referenced by RulePopcountBoolXor::applyOp(), PrintLanguage::formatBinary(), PcodeOp::getNZMaskLocal(), CircleRange::minimalContainer(), CircleRange::pullBack(), GuardRecord::quasiCopy(), SubvariableFlow::SubvariableFlow(), and PrintLanguage::writeUtf8().
mult64to128()
void mult64to128 (uint8 * res, uint8 x, uint8 y)
Multiply 2 unsigned 64-bit values, producing a 128-bit value.
TODO: Remove once we import a full multiprecision library.
Parameters
res points to the result array (2 uint8 pieces)
x is the first 64-bit value
y is the second 64-bit value
Referenced by power2Divide().
pcode_left()
uintb pcode_left (uintb val, int4 sa) inline
Perform a CPUI_INT_LEFT on the given val
Parameters
val is the value to shift
sa is the number of bits to shift
Returns
the shifted value
Referenced by RuleShiftBitops::applyOp(), and PcodeOp::getNZMaskLocal().
pcode_right()
uintb pcode_right (uintb val, int4 sa) inline
Perform a CPUI_INT_RIGHT on the given val
Parameters
val is the value to shift
sa is the number of bits to shift
Returns
the shifted value
Referenced by RuleShiftBitops::applyOp(), and PcodeOp::getNZMaskLocal().
popcount()
int4 popcount (uintb val)
Return the number of one bits in the given value.
Count the number (population) bits set.
Parameters
val is the given value
Returns
the number of one bits
Referenced by RulePopcountBoolXor::applyOp(), OpBehaviorPopcount::evaluateUnary(), and PcodeOp::getNZMaskLocal().
power2Divide()
int4 power2Divide (int4 n, uint8 divisor, uint8 & q, uint8 & r)
Unsigned division of a power of 2 (upto 2^127) by a 64-bit divisor.
The result must be less than 2^64. The remainder is calculated.
Parameters
n is the power of 2 for the numerand
divisor is the 64-bit divisor
q is the passed back 64-bit quotient
r is the passed back 64-bit remainder
Returns
0 if successful, 1 if result is too big, 2 if divide by 0
References mult64to128(), unsignedCompare128(), and unsignedSubtract128().
Referenced by RuleDivOpt::calcDivisor().
sign_extend() [1/2]
void sign_extend (intb & val, int4 bit)
Sign extend above given bit.
Sign extend val starting at bit
Parameters
val is a reference to the value to be sign-extended
bit is the index of the bit to extend from (0=least significant bit)
sign_extend() [2/2]
uintb sign_extend (uintb in, int4 sizein, int4 sizeout)
Sign-extend a value between two byte sizes.
Take the first sizein bytes of the given in and sign-extend this to sizeout bytes, keeping any more significant bytes zero
Parameters
in is the given value
sizein is the size to treat that value as an input
sizeout is the size to sign-extend the value to
Returns
the sign-extended value
References calc_mask().
Referenced by MapState::addRange(), RuleSubCommute::applyOp(), ScopeLocal::buildVariableName(), RulePtrArith::checkTerm(), OpBehaviorIntSdiv::evaluateBinary(), OpBehaviorIntSrem::evaluateBinary(), OpBehaviorIntSext::evaluateUnary(), PcodeOp::getNZMaskLocal(), MapState::initialize(), EquateSymbol::isValueClose(), FloatFormat::opInt2Float(), CircleRange::pullBackUnary(), PrintC::pushEquate(), CircleRange::pushForwardBinary(), CircleRange::pushForwardUnary(), Funcdata::replaceLessequal(), SubvariableFlow::setReplacement(), and RulePtrArith::transformPtr().
signbit_negative()
bool signbit_negative (uintb val, int4 size)
Return true if the sign-bit is set.
Treat the given val as a constant of size bytes
Parameters
val is the given value
size is the size in bytes
Returns
true if the constant (as sized) has its sign bit set
Referenced by RuleSlessToLess::applyOp(), RuleDivTermAdd::applyOp(), OpBehaviorIntSright::evaluateBinary(), CastStrategyC::localExtensionType(), and ConditionMarker::sameOpComplement().
uintb_negate()
uintb uintb_negate (uintb in, int4 size)
Negate the sized value.
Treat the given in as a constant of size bytes. Negate this constant keeping the upper bytes zero.
Parameters
in is the given value
size is the size in bytes
Returns
the negation of the sized constant
References calc_mask().
Referenced by RuleSborrow::applyOp(), RuleEqual2Zero::applyOp(), OpBehaviorInt2Comp::evaluateUnary(), OpBehaviorIntNegate::evaluateUnary(), and RulePtrArith::transformPtr().
unsignedCompare128()
int4 unsignedCompare128 (uint8 * a, uint8 * b)
Compare two unsigned 128-bit values.
TODO: Remove once we import a full multiprecision library. Given a first and second value, return -1, 0, or 1 depending on whether the first value is less, equal, or greater than the second value.
Parameters
a is the first 128-bit value (as an array of 2 uint8 elements)
b is the second 128-bit value
Returns
the comparison code
Referenced by power2Divide().
unsignedSubtract128()
void unsignedSubtract128 (uint8 * a, uint8 * b)
Subtract (in-place) a 128-bit value from a base 128-value.
The base value is altered in place. TODO: Remove once we import a full multiprecision library.
Parameters
a is the base 128-bit value being subtracted from in-place
b is the other 128-bit value being subtracted
Referenced by power2Divide().
zero_extend()
void zero_extend (intb & val, int4 bit)
Clear all bits above given bit.
Zero extend val starting at bit
Parameters
val is a reference to the value to be zero extended
bit is the index of the bit to extend from (0=least significant bit)
Referenced by OpBehaviorIntSdiv::evaluateBinary(), and OpBehaviorIntSrem::evaluateBinary().