decompiler: PrintC Class Reference
PrintC Class Reference
The c-language token emitter.
#include <printc.hh>
Public Member Functions
PrintC (Architecture *g, const string &nm="c-language")
Constructor.
virtual void adjustTypeOperators (void)
Set basic data-type information for p-code operators.
virtual void setCommentStyle (const string &nm)
Set the way comments are displayed in decompiler output.
virtual bool isCharacterConstant (const uint1 *buf, int4 size, int4 charsize) const
Decide is the given byte array looks like a character string.
virtual void docTypeDefinitions (const TypeFactory *typegrp)
Emit definitions of data-types.
virtual void docAllGlobals (void)
Emit declarations of global variables.
virtual void docSingleGlobal (const Symbol *sym)
Emit the declaration for a single (global) Symbol.
virtual void docFunction (const Funcdata *fd)
Emit the declaration (and body) of a function.
virtual void emitBlockBasic (const BlockBasic *bb)
Emit statements in a basic block.
virtual void emitBlockGraph (const BlockGraph *bl)
Emit (an unspecified) list of blocks.
virtual void emitBlockCopy (const BlockCopy *bl)
Emit a basic block (with any labels)
virtual void emitBlockGoto (const BlockGoto *bl)
Emit a block ending with a goto statement.
virtual void emitBlockLs (const BlockList *bl)
Emit a sequence of blocks.
virtual void emitBlockCondition (const BlockCondition *bl)
Emit a conditional statement.
virtual void emitBlockIf (const BlockIf *bl)
Emit an if/else style construct.
virtual void emitBlockWhileDo (const BlockWhileDo *bl)
Emit a loop structure, check at top.
virtual void emitBlockDoWhile (const BlockDoWhile *bl)
Emit a loop structure, check at bottom.
virtual void emitBlockInfLoop (const BlockInfLoop *bl)
Emit an infinite loop structure.
virtual void emitBlockSwitch (const BlockSwitch *bl)
Emit a switch structure.
virtual void opCopy (const PcodeOp *op)
Emit a COPY operator.
virtual void opLoad (const PcodeOp *op)
Emit a LOAD operator.
virtual void opStore (const PcodeOp *op)
Emit a STORE operator.
virtual void opBranch (const PcodeOp *op)
Emit a BRANCH operator.
virtual void opCbranch (const PcodeOp *op)
virtual void opBranchind (const PcodeOp *op)
Emit a BRANCHIND operator.
virtual void opCall (const PcodeOp *op)
Emit a CALL operator.
virtual void opCallind (const PcodeOp *op)
Emit a CALLIND operator.
virtual void opCallother (const PcodeOp *op)
Emit a CALLOTHER operator.
virtual void opConstructor (const PcodeOp *op, bool withNew)
Emit an operator constructing an object.
virtual void opReturn (const PcodeOp *op)
Emit a RETURN operator.
virtual void opIntEqual (const PcodeOp *op)
Emit a INT_EQUAL operator.
virtual void opIntNotEqual (const PcodeOp *op)
Emit a INT_NOTEQUAL operator.
virtual void opIntSless (const PcodeOp *op)
Emit a INT_SLESS operator.
virtual void opIntSlessEqual (const PcodeOp *op)
Emit a INT_SLESSEQUAL operator.
virtual void opIntLess (const PcodeOp *op)
Emit a INT_LESS operator.
virtual void opIntLessEqual (const PcodeOp *op)
Emit a INT_LESSEQUAL operator.
virtual void opIntZext (const PcodeOp *op, const PcodeOp *readOp)
Emit a INT_ZEXT operator.
virtual void opIntSext (const PcodeOp *op, const PcodeOp *readOp)
Emit a INT_SEXT operator.
virtual void opIntAdd (const PcodeOp *op)
Emit a INT_ADD operator.
virtual void opIntSub (const PcodeOp *op)
Emit a INT_SUB operator.
virtual void opIntCarry (const PcodeOp *op)
Emit a INT_CARRY operator.
virtual void opIntScarry (const PcodeOp *op)
Emit a INT_SCARRY operator.
virtual void opIntSborrow (const PcodeOp *op)
Emit a INT_SBORROW operator.
virtual void opInt2Comp (const PcodeOp *op)
Emit a INT_2COMP operator.
virtual void opIntNegate (const PcodeOp *op)
Emit a INT_NEGATE operator.
virtual void opIntXor (const PcodeOp *op)
Emit a INT_XOR operator.
virtual void opIntAnd (const PcodeOp *op)
Emit a INT_AND operator.
virtual void opIntOr (const PcodeOp *op)
Emit a INT_OR operator.
virtual void opIntLeft (const PcodeOp *op)
Emit a INT_LEFT operator.
virtual void opIntRight (const PcodeOp *op)
Emit a INT_RIGHT operator.
virtual void opIntSright (const PcodeOp *op)
Emit a INT_SRIGHT operator.
virtual void opIntMult (const PcodeOp *op)
Emit a INT_MULT operator.
virtual void opIntDiv (const PcodeOp *op)
Emit a INT_DIV operator.
virtual void opIntSdiv (const PcodeOp *op)
Emit a INT_SDIV operator.
virtual void opIntRem (const PcodeOp *op)
Emit a INT_REM operator.
virtual void opIntSrem (const PcodeOp *op)
Emit a INT_SREM operator.
virtual void opBoolNegate (const PcodeOp *op)
virtual void opBoolXor (const PcodeOp *op)
Emit a BOOL_XOR operator.
virtual void opBoolAnd (const PcodeOp *op)
Emit a BOOL_AND operator.
virtual void opBoolOr (const PcodeOp *op)
Emit a BOOL_OR operator.
virtual void opFloatEqual (const PcodeOp *op)
Emit a FLOAT_EQUAL operator.
virtual void opFloatNotEqual (const PcodeOp *op)
Emit a FLOAT_NOTEQUAL operator.
virtual void opFloatLess (const PcodeOp *op)
Emit a FLOAT_LESS operator.
virtual void opFloatLessEqual (const PcodeOp *op)
Emit a FLOAT_LESSEQUAL operator.
virtual void opFloatNan (const PcodeOp *op)
Emit a FLOAT_NAN operator.
virtual void opFloatAdd (const PcodeOp *op)
Emit a FLOAT_ADD operator.
virtual void opFloatDiv (const PcodeOp *op)
Emit a FLOAT_DIV operator.
virtual void opFloatMult (const PcodeOp *op)
Emit a FLOAT_MULT operator.
virtual void opFloatSub (const PcodeOp *op)
Emit a FLOAT_SUB operator.
virtual void opFloatNeg (const PcodeOp *op)
Emit a FLOAT_NEG operator.
virtual void opFloatAbs (const PcodeOp *op)
Emit a FLOAT_ABS operator.
virtual void opFloatSqrt (const PcodeOp *op)
Emit a FLOAT_SQRT operator.
virtual void opFloatInt2Float (const PcodeOp *op)
Emit a FLOAT_INT2FLOAT operator.
virtual void opFloatFloat2Float (const PcodeOp *op)
Emit a FLOAT_FLOAT2FLOAT operator.
virtual void opFloatTrunc (const PcodeOp *op)
Emit a FLOAT_TRUNC operator.
virtual void opFloatCeil (const PcodeOp *op)
Emit a FLOAT_CEIL operator.
virtual void opFloatFloor (const PcodeOp *op)
Emit a FLOAT_FLOOR operator.
virtual void opFloatRound (const PcodeOp *op)
Emit a FLOAT_ROUND operator.
virtual void opMultiequal (const PcodeOp *op)
Emit a MULTIEQUAL operator.
virtual void opIndirect (const PcodeOp *op)
Emit a INDIRECT operator.
virtual void opPiece (const PcodeOp *op)
Emit a PIECE operator.
virtual void opSubpiece (const PcodeOp *op)
Emit a SUBPIECE operator.
virtual void opCast (const PcodeOp *op)
Emit a CAST operator.
virtual void opPtradd (const PcodeOp *op)
Emit a PTRADD operator.
virtual void opPtrsub (const PcodeOp *op)
virtual void opSegmentOp (const PcodeOp *op)
virtual void opCpoolRefOp (const PcodeOp *op)
Emit a CPOOLREF operator.
virtual void opNewOp (const PcodeOp *op)
Emit a NEW operator.
virtual void opInsertOp (const PcodeOp *op)
Emit an INSERT operator.
virtual void opExtractOp (const PcodeOp *op)
Emit an EXTRACT operator.
virtual void opPopcountOp (const PcodeOp *op)
Emit a POPCOUNT operator.
Public Member Functions inherited from PrintLanguage
PrintLanguage (Architecture *g, const string &nm)
Constructor.
virtual ~PrintLanguage (void)
Destructor.
void setLineCommentIndent (int4 val)
Set the number of characters to indent comment lines.
void setCommentDelimeter (const string &start, const string &stop, bool usecommentfill)
Establish comment delimiters for the language.
void setXML (bool val)
Set whether the low-level emitter, emits XML markup.
void setFlat (bool val)
Set whether nesting code structure should be emitted.
virtual void clear (void)
Clear the RPN stack and the low-level emitter.
virtual void setIntegerFormat (const string &nm)
Set the default integer format.
Protected Member Functions
void buildTypeStack (const Datatype *ct, vector< const Datatype * > &typestack)
Prepare to push components of a data-type declaration.
void pushPrototypeInputs (const FuncProto *proto)
Push input parameters.
virtual void pushTypeStart (const Datatype *ct, bool noident)
Push part of a data-type declaration onto the RPN stack, up to the identifier.
virtual void pushTypeEnd (const Datatype *ct)
Push the tail ends of a data-type declaration onto the RPN stack.
void pushBoolConstant (uintb val, const TypeBase *ct, const Varnode *vn, const PcodeOp *op)
Push a true or false token to the RPN stack.
void pushCharConstant (uintb val, const TypeChar *ct, const Varnode *vn, const PcodeOp *op)
Push a single character constant to the RPN stack.
void pushEnumConstant (uintb val, const TypeEnum *ct, const Varnode *vn, const PcodeOp *op)
Push an enumerated value to the RPN stack.
virtual bool pushPtrCharConstant (uintb val, const TypePointer *ct, const Varnode *vn, const PcodeOp *op)
Attempt to push a quoted string representing a given constant pointer onto the RPN stack.
bool pushPtrCodeConstant (uintb val, const TypePointer *ct, const Varnode *vn, const PcodeOp *op)
Attempt to push a function name representing a constant pointer onto the RPN stack.
virtual bool doEmitWideCharPrefix (void) const
Return true if this language requires a prefix when expressing wide characters.
bool checkArrayDeref (const Varnode *vn) const
Determine whether a LOAD/STORE expression requires pointer '*' syntax.
void emitStructDefinition (const TypeStruct *ct)
Emit the definition of a structure data-type.
void emitEnumDefinition (const TypeEnum *ct)
Emit the definition of an enumeration data-type.
void emitPrototypeOutput (const FuncProto *proto, const Funcdata *fd)
Emit the output data-type of a function prototype.
void emitPrototypeInputs (const FuncProto *proto)
Emit the input data-types of a function prototype.
void emitGlobalVarDeclsRecursive (Scope *scope)
Emit variable declarations for all global symbols under given scope.
void emitLocalVarDecls (const Funcdata *fd)
Emit variable declarations for a function.
void emitStatement (const PcodeOp *inst)
Emit a statement in the body of a function.
bool emitInplaceOp (const PcodeOp *op)
Attempt to emit an expression rooted at an in-place operator.
void emitGotoStatement (const FlowBlock *bl, const FlowBlock *exp_bl, uint4 type)
Emit a statement representing an unstructured branch.
void emitSwitchCase (int4 casenum, const BlockSwitch *switchbl)
Emit labels for a case block.
void emitLabel (const FlowBlock *bl)
Emit a formal label for a given control-flow block.
void emitLabelStatement (const FlowBlock *bl)
Emit any required label statement for a given basic block.
void emitAnyLabelStatement (const FlowBlock *bl)
Emit any required label statement for a given control-flow block.
void emitCommentGroup (const PcodeOp *inst)
Emit comments associated with a given statement.
void emitCommentFuncHeader (const Funcdata *fd)
Emit comments in the given function's header.
void opFunc (const PcodeOp *op)
Push a functional expression based on the given p-code op to the RPN stack.
void opTypeCast (const PcodeOp *op)
Push the given p-code op using type-cast syntax to the RPN stack.
void opHiddenFunc (const PcodeOp *op)
Push the given p-code op as a hidden token.
bool printCharacterConstant (ostream &s, const Address &addr, int4 charsize) const
Print a quoted (unicode) string at the given address.
virtual void pushConstant (uintb val, const Datatype *ct, const Varnode *vn, const PcodeOp *op)
Push a constant onto the RPN stack.
virtual bool pushEquate (uintb val, int4 sz, const EquateSymbol *sym, const Varnode *vn, const PcodeOp *op)
Push a constant marked up by and EquateSymbol onto the RPN stack.
virtual void pushAnnotation (const Varnode *vn, const PcodeOp *op)
Push an address which is not in the normal data-flow.
virtual void pushSymbol (const Symbol *sym, const Varnode *vn, const PcodeOp *op)
Push a specific Symbol onto the RPN stack.
virtual void pushUnnamedLocation (const Address &addr, const Varnode *vn, const PcodeOp *op)
Push an address as a substitute for a Symbol onto the RPN stack.
virtual void pushPartialSymbol (const Symbol *sym, int4 off, int4 sz, const Varnode *vn, const PcodeOp *op, Datatype *outtype)
Push a variable that represents only part of a symbol onto the RPN stack.
virtual void pushMismatchSymbol (const Symbol *sym, int4 off, int4 sz, const Varnode *vn, const PcodeOp *op)
Push an identifier for a variable that mismatches with its Symbol.
virtual void push_integer (uintb val, int4 sz, bool sign, const Varnode *vn, const PcodeOp *op)
Push a constant with an integer data-type to the RPN stack.
virtual void push_float (uintb val, int4 sz, const Varnode *vn, const PcodeOp *op)
Push a constant with a floating-point data-type to the RPN stack.
virtual void printUnicode (ostream &s, int4 onechar) const
Print a single unicode character as a character constant for the high-level language.
virtual void pushType (const Datatype *ct)
Push a data-type name onto the RPN expression stack.
virtual string genericFunctionName (const Address &addr)
Create a generic function name base on the entry point address.
virtual string genericTypeName (const Datatype *ct)
Generate a generic name for an unnamed data-type.
virtual void emitExpression (const PcodeOp *op)
Emit a full expression.
virtual void emitVarDecl (const Symbol *sym)
Emit a variable declaration.
virtual void emitVarDeclStatement (const Symbol *sym)
Emit a variable declaration statement.
virtual bool emitScopeVarDecls (const Scope *scope, int4 cat)
Emit all the variable declarations for a given scope.
virtual void emitFunctionDeclaration (const Funcdata *fd)
Emit a function declaration.
virtual void emitTypeDefinition (const Datatype *ct)
Emit the definition of the given data-type.
virtual bool checkPrintNegation (const Varnode *vn)
Check whether a given boolean Varnode can be printed in negated form.
Protected Member Functions inherited from PrintLanguage
void pushOp (const OpToken *tok, const PcodeOp *op)
Push an operator token onto the RPN stack.
void pushAtom (const Atom &atom)
Push a variable token onto the RPN stack.
void pushVnImplied (const Varnode *vn, const PcodeOp *op, uint4 m)
Push an implied variable onto the RPN stack.
void pushVnExplicit (const Varnode *vn, const PcodeOp *op)
Push an explicit variable onto the RPN stack.
void pushVnLHS (const Varnode *vn, const PcodeOp *op)
Push a variable as the left-hand side of an expression.
bool parentheses (const OpToken *op2)
Determine if the given token should be emitted in its own parenthetic expression.
void emitOp (const ReversePolish &entry)
Send an operator token from the RPN to the emitter.
void emitAtom (const Atom &atom)
Send an variable token from the RPN to the emitter.
bool escapeCharacterData (ostream &s, const uint1 *buf, int4 count, int4 charsize, bool bigend) const
Emit a byte buffer to the stream as unicode characters.
void recurse (void)
Emit from the RPN stack as much as possible.
void opBinary (const OpToken *tok, const PcodeOp *op)
Push a binary operator onto the RPN stack.
void opUnary (const OpToken *tok, const PcodeOp *op)
Push a unary operator onto the RPN stack.
virtual void emitLineComment (int4 indent, const Comment *comm)
Emit a comment line.
Static Protected Member Functions
static bool hasCharTerminator (uint1 *buffer, int4 size, int4 charsize)
Check if the byte buffer has a (unicode) string terminator.
Static Protected Member Functions inherited from PrintLanguage
static bool unicodeNeedsEscape (int4 codepoint)
Determine if the given codepoint needs to be escaped.
static void writeUtf8 (ostream &s, int4 codepoint)
Write unicode character to stream in UTF8 encoding.
static int4 readUtf16 (const uint1 *buf, bool bigend)
Read a 2-byte UTF16 element from a byte array.
static int4 getCodepoint (const uint1 *buf, int4 charsize, bool bigend, int4 &skip)
Extract the next unicode codepoint from an array of character data.
Protected Attributes
bool option_NULL
Set to true if we should emit NULL keyword.
bool option_inplace_ops
Set to true if we should use '+=' '&=' etc.
bool option_convention
Set to true if we should print calling convention.
bool option_nocasts
Don't print a cast if true.
bool option_unplaced
Set to true if we should display unplaced comments.
bool option_hide_exts
Set to true if we should hide implied extension operations.
string nullToken
Token to use for 'null'.
CommentSorter commsorter
Container/organizer for comments in the current function.
Protected Attributes inherited from PrintLanguage
Architecture * glb
The Architecture owning the language emitter.
CastStrategy * castStrategy
The strategy for emitting explicit case operations.
EmitXml * emit
The low-level token emitter.
uint4 mods
Currently active printing modifications.
uint4 instr_comment_type
Type of instruction comments to display.
uint4 head_comment_type
Type of header comments to display.
Static Protected Attributes
static OpToken hidden = { "", 1, 70, false, OpToken::hiddenfunction, 0, 0, (OpToken *)0 }
Hidden functional (that may force parentheses)
static OpToken scope = { "::", 2, 70, true, OpToken::binary, 0, 0, (OpToken *)0 }
The sub-scope/namespace operator.
static OpToken object_member = { ".", 2, 66, true, OpToken::binary, 0, 0, (OpToken *)0 }
The member operator.
static OpToken pointer_member = { "->", 2, 66, true, OpToken::binary, 0, 0, (OpToken *)0 }
The points to member operator.
static OpToken subscript = { "[]", 2, 66, false, OpToken::postsurround, 0, 0, (OpToken *)0 }
The array subscript operator.
static OpToken function_call = { "()", 2, 66, false, OpToken::postsurround, 0, 10, (OpToken *)0 }
The function call operator.
static OpToken bitwise_not = { "~", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
The bitwise negate operator.
static OpToken boolean_not = { "!", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
The boolean not operator.
static OpToken unary_minus = { "-", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
The unary minus operator.
static OpToken unary_plus = { "+", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
The unary plus operator.
static OpToken addressof = { "&", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
The address of operator.
static OpToken dereference = { "*", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
The pointer dereference operator.
static OpToken typecast = { "()", 2, 62, false, OpToken::presurround, 0, 0, (OpToken *)0 }
The type cast operator.
static OpToken multiply = { "*", 2, 54, true, OpToken::binary, 1, 0, (OpToken *)0 }
The multiplication operator.
static OpToken divide = { "/", 2, 54, false, OpToken::binary, 1, 0, (OpToken *)0 }
The division operator.
static OpToken modulo = { "%", 2, 54, false, OpToken::binary, 1, 0, (OpToken *)0 }
The modulo operator.
static OpToken binary_plus = { "+", 2, 50, true, OpToken::binary, 1, 0, (OpToken *)0 }
The binary addition operator.
static OpToken binary_minus = { "-", 2, 50, false, OpToken::binary, 1, 0, (OpToken *)0 }
The binary subtraction operator.
static OpToken shift_left = { "<<", 2, 46, false, OpToken::binary, 1, 0, (OpToken *)0 }
The left shift operator.
static OpToken shift_right = { ">>", 2, 46, false, OpToken::binary, 1, 0, (OpToken *)0 }
The right shift operator.
static OpToken less_than = { "<", 2, 42, false, OpToken::binary, 1, 0, (OpToken *)0 }
The less than operator.
static OpToken less_equal = { "<=", 2, 42, false, OpToken::binary, 1, 0, (OpToken *)0 }
The less than or equal operator.
static OpToken greater_than = { ">", 2, 42, false, OpToken::binary, 1, 0, (OpToken *)0 }
The greater than operator.
static OpToken greater_equal = { ">=", 2, 42, false, OpToken::binary, 1, 0, (OpToken *)0 }
The greater than or equal operator.
static OpToken equal = { "==", 2, 38, false, OpToken::binary, 1, 0, (OpToken *)0 }
The equal operator.
static OpToken not_equal = { "!=", 2, 38, false, OpToken::binary, 1, 0, (OpToken *)0 }
The not equal operator.
static OpToken bitwise_and = { "&", 2, 34, true, OpToken::binary, 1, 0, (OpToken *)0 }
The logical and operator.
static OpToken bitwise_xor = { "^", 2, 30, true, OpToken::binary, 1, 0, (OpToken *)0 }
The logical xor operator.
static OpToken bitwise_or = { "|", 2, 26, true, OpToken::binary, 1, 0, (OpToken *)0 }
The logical or operator.
static OpToken boolean_and = { "&&", 2, 22, false, OpToken::binary, 1, 0, (OpToken *)0 }
The boolean and operator.
static OpToken boolean_or = { "||", 2, 18, false, OpToken::binary, 1, 0, (OpToken *)0 }
The boolean or operator.
static OpToken boolean_xor = { "^^", 2, 20, false, OpToken::binary, 1, 0, (OpToken *)0 }
The boolean xor operator.
static OpToken assignment = { "=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The assignment operator.
static OpToken comma = { ",", 2, 2, true, OpToken::binary, 0, 0, (OpToken *)0 }
The comma operator (for parameter lists)
static OpToken new_op = { "", 2, 62, false, OpToken::space, 1, 0, (OpToken *)0 }
The new operator.
static OpToken multequal = { "*=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place multiplication operator.
static OpToken divequal = { "/=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place division operator.
static OpToken remequal = { "%=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place modulo operator.
static OpToken plusequal = { "+=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place addition operator.
static OpToken minusequal = { "-=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place subtraction operator.
static OpToken leftequal = { "<<=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place left shift operator.
static OpToken rightequal = { ">>=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place right shift operator.
static OpToken andequal = { "&=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place logical and operator.
static OpToken orequal = { "|=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place logical or operator.
static OpToken xorequal = { "^=", 2, 14, false, OpToken::binary, 1, 5, (OpToken *)0 }
The in-place logical xor operator.
static OpToken type_expr_space = { "", 2, 10, false, OpToken::space, 1, 0, (OpToken *)0 }
Type declaration involving a space (identifier or adornment)
static OpToken type_expr_nospace = { "", 2, 10, false, OpToken::space, 0, 0, (OpToken *)0 }
Type declaration with no space.
static OpToken ptr_expr = { "*", 1, 62, false, OpToken::unary_prefix, 0, 0, (OpToken *)0 }
Pointer adornment for a type declaration.
static OpToken array_expr = { "[]", 2, 66, false, OpToken::postsurround, 1, 0, (OpToken *)0 }
Array adornment for a type declaration.
static OpToken enum_cat = { "|", 2, 26, true, OpToken::binary, 0, 0, (OpToken *)0 }
The concatenation operator for enumerated values.
Additional Inherited Members
Public Types inherited from PrintLanguage
enum modifiers {
force_hex = 1, force_dec = 2, bestfit = 4, force_scinote = 8,
force_pointer = 0x10, print_load_value = 0x20, print_store_value = 0x40, no_branch = 0x80,
only_branch = 0x100, comma_separate = 0x200, flat = 0x400, falsebranch = 0x800,
nofallthru = 0x1000, negatetoken = 0x2000, hide_thisparam = 0x4000
}
Possible context sensitive modifiers to how tokens get emitted.
enum tagtype {
syntax, vartoken, functoken, optoken,
typetoken, fieldtoken, blanktoken
}
Possible types of Atom.
Static Public Member Functions inherited from PrintLanguage
static int4 mostNaturalBase (uintb val)
Determine the most natural base for an integer.
static void formatBinary (ostream &s, uintb val)
Print a number in binary form.
Detailed Description
The c-language token emitter.
The c-language specific rules for emitting:
expressions
statements
function prototypes
variable declarations
if/else structures
loop structures
etc.
Constructor & Destructor Documentation
PrintC()
PrintC::PrintC (Architecture * g, const string & nm = "c-language")
Constructor.
Parameters
g is the Architecture owning this c-language emitter
nm is the name assigned to this emitter
References PrintLanguage::castStrategy, equal, greater_equal, greater_than, less_equal, less_than, OpToken::negate, not_equal, nullToken, option_convention, option_hide_exts, option_inplace_ops, option_nocasts, option_NULL, and option_unplaced.
Member Function Documentation
buildTypeStack()
void PrintC::buildTypeStack (const Datatype * ct, vector< const Datatype * > & typestack) protected
Prepare to push components of a data-type declaration.
Push nested components of a data-type declaration onto a stack, so we can access it bottom up
Parameters
ct is the data-type being emitted
typestack will hold the sub-types involved in the displaying the declaration
References TypeFactory::getTypeVoid(), PrintLanguage::glb, Datatype::size, TYPE_ARRAY, TYPE_CODE, TYPE_PTR, and Architecture::types.
Referenced by pushTypeStart().
checkArrayDeref()
bool PrintC::checkArrayDeref (const Varnode * vn) const protected
Determine whether a LOAD/STORE expression requires pointer '*' syntax.
An expression involving a LOAD or STORE can sometimes be emitted using array syntax (or field member syntax). This method determines if this kind of syntax is appropriate or if a '*' operator is required.
Parameters
vn is the root of the pointer expression (feeding into LOAD or STORE)
Returns
false if '*' syntax is required, true if some other syntax is used
References CPUI_PTRADD, CPUI_PTRSUB, and CPUI_SEGMENTOP.
Referenced by opLoad(), and opStore().
checkPrintNegation()
bool PrintC::checkPrintNegation (const Varnode * vn) protected virtual
Check whether a given boolean Varnode can be printed in negated form.
In many situations a boolean value can be inverted by flipping the operator token producing it to a complementary token.
Parameters
vn is the given boolean Varnode
Returns
true if the value can be easily inverted
Implements PrintLanguage.
References CPUI_MAX, and get_booleanflip().
Referenced by opBoolNegate(), and opCbranch().
docFunction()
void PrintC::docFunction (const Funcdata * fd) virtual
Emit the declaration (and body) of a function.
Parameters
fd is the function to emit
Implements PrintLanguage.
References EmitXml::beginFunction(), PrintLanguage::clear(), commsorter, PrintLanguage::emit, emitBlockGraph(), emitCommentFuncHeader(), emitFunctionDeclaration(), emitLocalVarDecls(), EmitXml::endFunction(), PrintLanguage::flat, EmitXml::flush(), PrintLanguage::head_comment_type, PrintLanguage::instr_comment_type, PrintLanguage::mods, option_unplaced, EmitXml::print(), CommentSorter::setupFunctionList(), EmitXml::startIndent(), EmitXml::stopIndent(), and EmitXml::tagLine().
docSingleGlobal()
void PrintC::docSingleGlobal (const Symbol * sym) virtual
Emit the declaration for a single (global) Symbol.
Parameters
sym is the Symbol to declare
Implements PrintLanguage.
References EmitXml::beginDocument(), PrintLanguage::emit, emitVarDeclStatement(), EmitXml::endDocument(), EmitXml::flush(), and EmitXml::tagLine().
docTypeDefinitions()
void PrintC::docTypeDefinitions (const TypeFactory * typegrp) virtual
Emit definitions of data-types.
Parameters
typegrp is the container for the data-types that should be defined
Implements PrintLanguage.
References TypeFactory::dependentOrder(), and emitTypeDefinition().
doEmitWideCharPrefix()
bool PrintC::doEmitWideCharPrefix (void) const protected virtual
Return true if this language requires a prefix when expressing wide characters.
The c-language standard requires that strings (and character constants) made up of wide character elements have an 'L' prefix added before the quote characters. Other related languages may not do this. Having this as a virtual method lets derived languages to tailor their strings while still using the basic PrintC functionality
Returns
true if a prefix should be printed
Reimplemented in PrintJava.
Referenced by printCharacterConstant(), push_integer(), and pushCharConstant().
emitAnyLabelStatement()
void PrintC::emitAnyLabelStatement (const FlowBlock * bl) protected
Emit any required label statement for a given control-flow block.
The block does not have to be a basic block. This routine finds the entry basic block and prints any necessary labels for that.
Parameters
bl is the given control-flow block
References emitLabelStatement(), and FlowBlock::getFrontLeaf().
Referenced by emitBlockCopy(), emitBlockDoWhile(), emitBlockInfLoop(), and emitBlockWhileDo().
emitCommentFuncHeader()
void PrintC::emitCommentFuncHeader (const Funcdata * fd) protected
Emit comments in the given function's header.
Collect all comment lines marked as header for the function and emit them with the appropriate delimiters.
Parameters
fd is the given function
References commsorter, PrintLanguage::emit, PrintLanguage::emitLineComment(), PrintLanguage::head_comment_type, CommentSorter::header_basic, CommentSorter::header_unplaced, option_nocasts, option_unplaced, CommentSorter::setupHeader(), EmitXml::tagLine(), and Comment::warningheader.
Referenced by docFunction().
emitCommentGroup()
void PrintC::emitCommentGroup (const PcodeOp * inst) protected
Emit comments associated with a given statement.
Collect any comment lines the sorter has associated with a statement rooted at a given PcodeOp and emit them using appropriate delimiters
Parameters
inst is the given PcodeOp
References commsorter, PrintLanguage::emitLineComment(), PrintLanguage::instr_comment_type, and CommentSorter::setupOpList().
Referenced by emitBlockBasic().
emitEnumDefinition()
void PrintC::emitEnumDefinition (const TypeEnum * ct) protected
Emit the definition of an enumeration data-type.
Print all the named values making up the data-type, using the enum keyword
Parameters
ct is the enumerated data-type
References PrintLanguage::clear(), EmitXml::const_color, PrintLanguage::emit, EmitXml::keyword_color, EmitXml::no_color, EmitXml::print(), push_integer(), PrintLanguage::recurse(), Datatype::size, EmitXml::spaces(), EmitXml::startIndent(), EmitXml::stopIndent(), EmitXml::tagLine(), and TYPE_INT.
Referenced by emitTypeDefinition().
emitExpression()
void PrintC::emitExpression (const PcodeOp * op) protected virtual
Emit a full expression.
This can be an assignment statement, if the given PcodeOp has an output Varnode, or it can be a statement with no left-hand side.
Parameters
op is the given PcodeOp performing the final operation of the expression
Implements PrintLanguage.
References assignment, emitInplaceOp(), opConstructor(), option_inplace_ops, PrintLanguage::pushOp(), PrintLanguage::pushVnLHS(), and PrintLanguage::recurse().
Referenced by emitBlockBasic(), and emitStatement().
emitFunctionDeclaration()
void PrintC::emitFunctionDeclaration (const Funcdata * fd) protected virtual
Emit a function declaration.
This prints the formal defining prototype for a function.
Parameters
fd is the Funcdata object representing the function to be emitted
Implements PrintLanguage.
References EmitXml::beginFuncProto(), OpToken::bump, EmitXml::closeGroup(), EmitXml::closeParen(), PrintLanguage::emit, emitPrototypeInputs(), emitPrototypeOutput(), EmitXml::endFuncProto(), EmitXml::funcname_color, function_call, EmitXml::keyword_color, EmitXml::openGroup(), EmitXml::openParen(), option_convention, EmitXml::print(), EmitXml::spaces(), OpToken::spacing, and EmitXml::tagFuncName().
Referenced by docFunction().
emitGlobalVarDeclsRecursive()
void PrintC::emitGlobalVarDeclsRecursive (Scope * scope) protected
Emit variable declarations for all global symbols under given scope.
For the given scope and all of its children that are not function scopes, emit a variable declaration for each symbol.
Parameters
scope is the given scope
References emitScopeVarDecls(), and scope.
Referenced by docAllGlobals().
emitGotoStatement()
void PrintC::emitGotoStatement (const FlowBlock * bl, const FlowBlock * exp_bl, uint4 type) protected
Emit a statement representing an unstructured branch.
Given the type of unstructured branch, with source and destination blocks, construct a statement with the appropriate c-language keyword (goto, break, continue) representing a control-flow branch between the blocks.
Parameters
bl is the source block
exp_bl is the destination block (which may provide a label)
type is the given type of the branch
References EmitXml::beginStatement(), PrintLanguage::emit, emitLabel(), EmitXml::endStatement(), FlowBlock::f_break_goto, FlowBlock::f_continue_goto, FlowBlock::f_goto_goto, EmitXml::keyword_color, EmitXml::print(), and EmitXml::spaces().
Referenced by emitBlockGoto(), emitBlockIf(), emitBlockSwitch(), and emitBlockWhileDo().
emitInplaceOp()
bool PrintC::emitInplaceOp (const PcodeOp * op) protected
Attempt to emit an expression rooted at an in-place operator.
Check that the given p-code op has an in-place token form and if the first input and the output are references to the same variable. If so, emit the expression using the in-place token.
Parameters
op is the given PcodeOp
Returns
true if the expression was emitted (as in-place), or false if not emitted at all
References andequal, CPUI_INT_ADD, CPUI_INT_AND, CPUI_INT_DIV, CPUI_INT_LEFT, CPUI_INT_MULT, CPUI_INT_OR, CPUI_INT_REM, CPUI_INT_RIGHT, CPUI_INT_SDIV, CPUI_INT_SREM, CPUI_INT_SRIGHT, CPUI_INT_SUB, CPUI_INT_XOR, divequal, Varnode::getHigh(), leftequal, minusequal, PrintLanguage::mods, multequal, orequal, plusequal, PrintLanguage::pushOp(), PrintLanguage::pushVnExplicit(), PrintLanguage::pushVnImplied(), PrintLanguage::recurse(), remequal, rightequal, and xorequal.
Referenced by emitExpression().
emitLabel()
void PrintC::emitLabel (const FlowBlock * bl) protected
Emit a formal label for a given control-flow block.
Check for an explicit label that has been registered with the basic block. Otherwise, construct a generic label based on the entry address of the block. Emit the label as a single token.
Parameters
bl is the given block
References PrintLanguage::emit, BlockBasic::getEntryAddr(), FlowBlock::getFrontLeaf(), Address::getOffset(), Address::getShortcut(), Address::getSpace(), EmitXml::no_color, Address::printRaw(), scope, and EmitXml::tagLabel().
Referenced by emitBlockBasic(), emitGotoStatement(), and emitLabelStatement().
emitLabelStatement()
void PrintC::emitLabelStatement (const FlowBlock * bl) protected
Emit any required label statement for a given basic block.
If the basic block is the destination of a goto statement, emit a label for the block followed by the ':' terminator.
Parameters
bl is the given control-flow block
References PrintLanguage::emit, emitLabel(), PrintLanguage::flat, FlowBlock::isJumpTarget(), PrintLanguage::only_branch, EmitXml::print(), and EmitXml::tagLine().
Referenced by emitAnyLabelStatement(), and emitBlockBasic().
emitLocalVarDecls()
void PrintC::emitLocalVarDecls (const Funcdata * fd) protected
Emit variable declarations for a function.
A formal variable declaration is emitted for every symbol in the given function scope. I.e. all local variables are declared.
Parameters
fd is the function being emitted
References PrintLanguage::emit, emitScopeVarDecls(), and EmitXml::tagLine().
Referenced by docFunction().
emitPrototypeInputs()
void PrintC::emitPrototypeInputs (const FuncProto * proto) protected
Emit the input data-types of a function prototype.
This emits the individual type declarations of the input parameters to the function as a comma separated list.
Parameters
proto is the given prototype of the function
References PrintLanguage::blanktoken, PrintLanguage::emit, emitVarDecl(), ProtoParameter::getSymbol(), ProtoParameter::getType(), EmitXml::keyword_color, EmitXml::no_color, EmitXml::print(), PrintLanguage::pushAtom(), pushTypeEnd(), pushTypeStart(), and PrintLanguage::recurse().
Referenced by emitFunctionDeclaration().
emitPrototypeOutput()
void PrintC::emitPrototypeOutput (const FuncProto * proto, const Funcdata * fd) protected
Emit the output data-type of a function prototype.
In C, when printing a function prototype, the function's output data-type is displayed first as a type declaration, where the function name acts as the declaration's identifier. This method emits the declaration in preparation for this.
Parameters
proto is the function prototype object
fd is the (optional) Funcdata object providing additional meta-data about the function
References EmitXml::beginReturnType(), PrintLanguage::emit, EmitXml::endReturnType(), Funcdata::getFirstReturnOp(), pushType(), PrintLanguage::recurse(), and TYPE_VOID.
Referenced by emitFunctionDeclaration().
emitScopeVarDecls()
bool PrintC::emitScopeVarDecls (const Scope * scope, int4 cat) protected virtual
Emit all the variable declarations for a given scope.
A subset of all variables can be declared by specifying a category, 0 for parameters, -1 for everything.
Parameters
scope is the given Scope
cat is the category of variable to declare
Implements PrintLanguage.
References emitVarDeclStatement(), Symbol::getFirstWholeMap(), Symbol::isNameUndefined(), and scope.
Referenced by emitGlobalVarDeclsRecursive(), and emitLocalVarDecls().
emitStatement()
void PrintC::emitStatement (const PcodeOp * inst) protected
Emit a statement in the body of a function.
This emits an entire statement rooted at a given operation. All associated expressions on the right-hand and left-hand sides are recursively emitted. Depending on the current printing properties, the statement is usually terminated with ';' character.
Parameters
inst is the given root PcodeOp of the statement
References EmitXml::beginStatement(), PrintLanguage::comma_separate, PrintLanguage::emit, emitExpression(), EmitXml::endStatement(), and EmitXml::print().
Referenced by emitBlockBasic().
emitStructDefinition()
void PrintC::emitStructDefinition (const TypeStruct * ct) protected
Emit the definition of a structure data-type.
Print all the components making up the data-type, using the struct keyword
Parameters
ct is the structure data-type
References PrintLanguage::clear(), PrintLanguage::emit, EmitXml::keyword_color, EmitXml::print(), PrintLanguage::pushAtom(), pushTypeEnd(), pushTypeStart(), Datatype::size, EmitXml::spaces(), EmitXml::startIndent(), EmitXml::stopIndent(), PrintLanguage::syntax, EmitXml::tagLine(), and EmitXml::var_color.
Referenced by emitTypeDefinition().
emitSwitchCase()
void PrintC::emitSwitchCase (int4 casenum, const BlockSwitch * switchbl) protected
Emit labels for a case block.
Given a switch block and an index indicating a particular case block, look up all the labels associated with that case and emit them using formal labels with the case keyword and a ':' terminator.
Parameters
casenum is the given index of the case block
switchbl is the root block of the switch
References PrintLanguage::emit, BlockSwitch::getLabel(), BlockSwitch::getNumLabels(), BlockSwitch::getSwitchType(), EmitXml::keyword_color, EmitXml::print(), pushConstant(), PrintLanguage::recurse(), EmitXml::spaces(), and EmitXml::tagLine().
Referenced by emitBlockSwitch().
emitTypeDefinition()
void PrintC::emitTypeDefinition (const Datatype * ct) protected virtual
Emit the definition of the given data-type.
This is currently limited to a 'struct' or 'enum' definitions. The definition is emitted so that name associated with data-type object will be associated with the definition (in anything that parses it)
Parameters
ct is the given data-type
References PrintLanguage::clear(), emitEnumDefinition(), emitStructDefinition(), and TYPE_STRUCT.
Referenced by docTypeDefinitions().
emitVarDecl()
void PrintC::emitVarDecl (const Symbol * sym) protected virtual
Emit a variable declaration.
This can be part of a full a statement, or just the declaration of a function parameter
Parameters
sym is the Symbol to be declared
Implements PrintLanguage.
References EmitXml::beginVarDecl(), PrintLanguage::emit, EmitXml::endVarDecl(), pushSymbol(), pushTypeEnd(), pushTypeStart(), and PrintLanguage::recurse().
Referenced by emitPrototypeInputs(), and emitVarDeclStatement().
emitVarDeclStatement()
void PrintC::emitVarDeclStatement (const Symbol * sym) protected virtual
Emit a variable declaration statement.
Parameters
sym is the Symbol to be declared
Implements PrintLanguage.
References PrintLanguage::emit, emitVarDecl(), EmitXml::print(), and EmitXml::tagLine().
Referenced by docSingleGlobal(), and emitScopeVarDecls().
genericFunctionName()
string PrintC::genericFunctionName (const Address & addr) protected virtual
Create a generic function name base on the entry point address.
Parameters
addr is the entry point address of the function
Returns
the generated name
References Address::printRaw().
Referenced by opCall().
genericTypeName()
string PrintC::genericTypeName (const Datatype * ct) protected virtual
Generate a generic name for an unnamed data-type.
Parameters
ct is the given data-type
Returns
the generated name
References TYPE_FLOAT, TYPE_INT, TYPE_SPACEBASE, TYPE_UINT, and TYPE_UNKNOWN.
Referenced by PrintJava::pushTypeStart(), and pushTypeStart().
hasCharTerminator()
bool PrintC::hasCharTerminator (uint1 * buffer, int4 size, int4 charsize) static protected
Check if the byte buffer has a (unicode) string terminator.
Parameters
buffer is the byte buffer
size is the number of bytes in the buffer
charsize is the presumed size (in bytes) of character elements
Returns
true if a string terminator is found
Referenced by printCharacterConstant().
isCharacterConstant()
bool PrintC::isCharacterConstant (const uint1 * buf, int4 size, int4 charsize) const virtual
Decide is the given byte array looks like a character string.
This looks for encodings and/or a terminator that is appropriate for the high-level language
Parameters
buf is a pointer to the byte array
size is the number of bytes in the array
charsize is the size in bytes of the encoding element (i.e. UTF8, UTF16, etc.) to assume
Implements PrintLanguage.
References PrintLanguage::getCodepoint(), PrintLanguage::glb, Translate::isBigEndian(), and Architecture::translate.
Referenced by printCharacterConstant().
opBoolNegate()
void PrintC::opBoolNegate (const PcodeOp * op) virtual
Print the BOOL_NEGATE but check for opportunities to flip the next operator instead
Parameters
op is the BOOL_NEGATE PcodeOp
Implements PrintLanguage.
References boolean_not, checkPrintNegation(), PrintLanguage::mods, PrintLanguage::negatetoken, PrintLanguage::pushOp(), and PrintLanguage::pushVnImplied().
opCbranch()
void PrintC::opCbranch (const PcodeOp * op) virtual
Print the branching condition:
If it is the first condition, print if
If there is no block structure, print goto
Parameters
op is the CBRANCH PcodeOp
Implements PrintLanguage.
References boolean_not, checkPrintNegation(), EmitXml::closeGroup(), EmitXml::closeParen(), PrintLanguage::comma_separate, PrintLanguage::emit, PrintLanguage::falsebranch, PrintLanguage::flat, PcodeOp::isBooleanFlip(), PcodeOp::isFallthruTrue(), EmitXml::keyword_color, PrintLanguage::mods, PrintLanguage::negatetoken, EmitXml::openGroup(), EmitXml::openParen(), EmitXml::print(), PrintLanguage::pushOp(), PrintLanguage::pushVnImplied(), PrintLanguage::recurse(), EmitXml::spaces(), and EmitXml::tagOp().
opFunc()
void PrintC::opFunc (const PcodeOp * op) protected
Push a functional expression based on the given p-code op to the RPN stack.
This is used for expression that require functional syntax, where the name of the function is the name of the operator. The inputs to the p-code op form the roots of the comma separated list of parameters within the syntax.
Parameters
op is the given PcodeOp
References PrintLanguage::blanktoken, comma, function_call, PrintLanguage::mods, EmitXml::no_color, PrintLanguage::optoken, PrintLanguage::pushAtom(), PrintLanguage::pushOp(), and PrintLanguage::pushVnImplied().
Referenced by opExtractOp(), opFloatAbs(), opFloatCeil(), opFloatFloor(), opFloatNan(), opFloatRound(), opFloatSqrt(), opInsertOp(), opIntCarry(), opIntSborrow(), opIntScarry(), opIntSext(), opIntZext(), opPiece(), opPopcountOp(), and opSubpiece().
opHiddenFunc()
void PrintC::opHiddenFunc (const PcodeOp * op) protected
Push the given p-code op as a hidden token.
The syntax represents the given op using a function with one input, where the function name is not printed. The input expression is simply printed without adornment inside the larger expression, with one minor difference. The hidden operator protects against confusing evaluation order between the operators inside and outside the hidden function. If both the inside and outside operators are the same associative token, the hidden token makes sure the inner expression is surrounded with parentheses.
Parameters
op is the given PcodeOp
References hidden, PrintLanguage::mods, PrintLanguage::pushOp(), and PrintLanguage::pushVnImplied().
Referenced by opIntSext(), and opIntZext().
opPtrsub()
void PrintC::opPtrsub (const PcodeOp * op) virtual
We need to distinguish between the following cases:
ptr-> struct spacebase or array
valueoption on/off (from below)
valueflex yes/no (can we turn valueoption above?)
Then the printing breaks up into the following table:
        val flex   |   val flex   |   val flex   |   val flex
        off  yes       off   no        on  yes        on   no
struct  &().name      &()->name     ().name       ()->name
spcbase n/a            &name          n/a            name
array   ()            *()           ()[0]         *()[0]
The '&' is dropped if the output type is an array
Parameters
op is the PTRSUB PcodeOp
Implements PrintLanguage.
References addressof, AddrSpace::addressToByte(), PrintLanguage::clear(), dereference, PrintLanguage::fieldtoken, TypeSpacebase::getAddress(), Varnode::getHigh(), PrintLanguage::mods, TypeField::name, EmitXml::no_color, object_member, TypeField::offset, pointer_member, PrintLanguage::print_load_value, PrintLanguage::print_store_value, push_integer(), PrintLanguage::pushAtom(), PrintLanguage::pushOp(), pushPartialSymbol(), pushSymbol(), pushUnnamedLocation(), PrintLanguage::pushVnImplied(), subscript, TypeField::type, TYPE_ARRAY, TYPE_CODE, TYPE_PTR, TYPE_SPACEBASE, and TYPE_STRUCT.
opSegmentOp()
void PrintC::opSegmentOp (const PcodeOp * op) virtual
slot 0 is the spaceid constant
slot 1 is the segment, we could conceivably try to annotate the segment here
slot 2 is the pointer we are really interested in printing
Parameters
op is the SEGMENTOP PcodeOp
Implements PrintLanguage.
References PrintLanguage::mods, and PrintLanguage::pushVnImplied().
opTypeCast()
void PrintC::opTypeCast (const PcodeOp * op) protected
Push the given p-code op using type-cast syntax to the RPN stack.
The syntax represents the given op using a standard c-language cast. The data-type being cast to is obtained from the output variable of the op. The input expression is also recursively pushed.
Parameters
op is the given PcodeOp
References PrintLanguage::mods, option_nocasts, PrintLanguage::pushOp(), pushType(), PrintLanguage::pushVnImplied(), and typecast.
Referenced by opCast(), opFloatFloat2Float(), opFloatInt2Float(), opFloatTrunc(), opIntSext(), opIntZext(), and opSubpiece().
printCharacterConstant()
bool PrintC::printCharacterConstant (ostream & s, const Address & addr, int4 charsize) const protected
Print a quoted (unicode) string at the given address.
Data for the string is obtained directly from the LoadImage. The bytes are checked for appropriate unicode encoding and the presence of a terminator. If all these checks pass, the string is emitted.
Parameters
s is the output stream to print to
addr is the address of the string data within the LoadImage
charsize is the number of bytes in an encoded element (i.e. UTF8, UTF16, or UTF32)
Returns
true if a proper string was found and printed to the stream
References doEmitWideCharPrefix(), PrintLanguage::escapeCharacterData(), PrintLanguage::glb, hasCharTerminator(), Translate::isBigEndian(), isCharacterConstant(), Architecture::loader, LoadImage::loadFill(), and Architecture::translate.
Referenced by pushPtrCharConstant(), and pushSymbol().
printUnicode()
void PrintC::printUnicode (ostream & s, int4 onechar) const protected virtual
Print a single unicode character as a character constant for the high-level language.
For most languages, this prints the character surrounded by single quotes.
Parameters
s is the output stream
onechar is the unicode code point of the character to print
Implements PrintLanguage.
Reimplemented in PrintJava.
References PrintLanguage::unicodeNeedsEscape(), and PrintLanguage::writeUtf8().
Referenced by push_integer(), and pushCharConstant().
push_float()
void PrintC::push_float (uintb val, int4 sz, const Varnode * vn, const PcodeOp * op) protected virtual
Push a constant with a floating-point data-type to the RPN stack.
The encoding is drawn from the underlying Translate object, and the print properties are checked for formatting overrides. In any case, a format is decided upon, and the constant is pushed as a single token.
Parameters
val is the given encoded floating-point value
sz is the size (in bytes) of the encoded value
vn is the Varnode holding the value
op is the PcodeOp using the value
References EmitXml::const_color, FloatFormat::extractSign(), PrintLanguage::force_scinote, Translate::getFloatFormat(), FloatFormat::getHostFloat(), PrintLanguage::glb, FloatFormat::infinity, PrintLanguage::mods, FloatFormat::nan, PrintLanguage::pushAtom(), PrintLanguage::syntax, Architecture::translate, and PrintLanguage::vartoken.
Referenced by pushConstant().
push_integer()
void PrintC::push_integer (uintb val, int4 sz, bool sign, const Varnode * vn, const PcodeOp * op) protected virtual
Push a constant with an integer data-type to the RPN stack.
Various checks are made to see if the integer should be printed as an equate symbol or if there is other overriding information about what format it should be printed in. In any case, a final determination of the format is made and the integer is pushed as a single token.
Parameters
val is the given integer value
sz is the size (in bytes) to associate with the integer
sign is set to true if the integer should be treated as a signed value
vn is the Varnode holding the value
op is the PcodeOp using the value
References calc_mask(), EmitXml::const_color, doEmitWideCharPrefix(), Symbol::force_char, PrintLanguage::force_dec, Symbol::force_dec, PrintLanguage::force_hex, Symbol::force_hex, Symbol::force_oct, PrintLanguage::formatBinary(), Varnode::getHigh(), PrintLanguage::mods, PrintLanguage::mostNaturalBase(), printUnicode(), PrintLanguage::pushAtom(), pushEquate(), PrintLanguage::syntax, and PrintLanguage::vartoken.
Referenced by emitEnumDefinition(), PrintJava::opLoad(), opPtrsub(), PrintJava::opStore(), pushCharConstant(), pushConstant(), pushEnumConstant(), pushEquate(), and pushTypeEnd().
pushAnnotation()
void PrintC::pushAnnotation (const Varnode * vn, const PcodeOp * op) protected virtual
Push an address which is not in the normal data-flow.
The given Varnode is treated as an address, which may or may not have a symbol name.
Parameters
vn is the annotation Varnode
op is the PcodeOp which takes the annotation as input
Implements PrintLanguage.
References AddrSpace::byteToAddress(), CPUI_CALLOTHER, TypeFactory::getBase(), Translate::getRegisterName(), PrintLanguage::glb, PrintLanguage::pushAtom(), pushConstant(), pushPartialSymbol(), pushSymbol(), scope, Architecture::translate, TYPE_UINT, Architecture::types, Architecture::userops, EmitXml::var_color, and PrintLanguage::vartoken.
pushBoolConstant()
void PrintC::pushBoolConstant (uintb val, const TypeBase * ct, const Varnode * vn, const PcodeOp * op) protected
Push a true or false token to the RPN stack.
A single Atom representing the boolean value is emitted
Parameters
val is the boolean value (non-zero for true)
ct is the data-type associated with the value
vn is the Varnode holding the value
op is the PcodeOp using the value
References EmitXml::const_color, PrintLanguage::pushAtom(), and PrintLanguage::vartoken.
Referenced by pushConstant().
pushCharConstant()
void PrintC::pushCharConstant (uintb val, const TypeChar * ct, const Varnode * vn, const PcodeOp * op) protected
Push a single character constant to the RPN stack.
For C, a character constant is usually emitted as the character in single quotes. Handle unicode, wide characters, etc. Characters come in with the compiler's raw encoding.
Parameters
val is the constant value
ct is data-type attached to the value
vn is the Varnode holding the value
op is the PcodeOp using the value
References EmitXml::const_color, doEmitWideCharPrefix(), printUnicode(), push_integer(), PrintLanguage::pushAtom(), and PrintLanguage::vartoken.
Referenced by pushConstant().
pushConstant()
void PrintC::pushConstant (uintb val, const Datatype * ct, const Varnode * vn, const PcodeOp * op) protected virtual
Push a constant onto the RPN stack.
The value is ultimately emitted based on its data-type and other associated mark-up
Parameters
val is the value of the constant
ct is the data-type of the constant
vn is the Varnode holding the constant (optional)
op is the PcodeOp using the constant (optional)
Implements PrintLanguage.
References PrintLanguage::clear(), PrintLanguage::force_dec, PrintLanguage::force_hex, nullToken, option_nocasts, option_NULL, push_float(), push_integer(), PrintLanguage::pushAtom(), pushBoolConstant(), pushCharConstant(), pushEnumConstant(), PrintLanguage::pushOp(), pushPtrCharConstant(), pushPtrCodeConstant(), pushType(), TYPE_ARRAY, TYPE_BOOL, TYPE_CODE, TYPE_FLOAT, TYPE_INT, TYPE_PTR, TYPE_SPACEBASE, TYPE_STRUCT, TYPE_UINT, TYPE_UNKNOWN, TYPE_VOID, typecast, EmitXml::var_color, and PrintLanguage::vartoken.
Referenced by emitSwitchCase(), and pushAnnotation().
pushEnumConstant()
void PrintC::pushEnumConstant (uintb val, const TypeEnum * ct, const Varnode * vn, const PcodeOp * op) protected
Push an enumerated value to the RPN stack.
Handle cases where the value is built out of multiple named elements of the enumeration or where the value cannot be expressed using named elements
Parameters
val is the enumerated value being pushed
ct is the enumerated data-type attached to the value
vn is the Varnode holding the value
op is the PcodeOp using the value
References bitwise_not, EmitXml::const_color, enum_cat, TypeEnum::getMatches(), push_integer(), PrintLanguage::pushAtom(), PrintLanguage::pushOp(), and PrintLanguage::vartoken.
Referenced by pushConstant().
pushEquate()
bool PrintC::pushEquate (uintb val, int4 sz, const EquateSymbol * sym, const Varnode * vn, const PcodeOp * op) protected virtual
Push a constant marked up by and EquateSymbol onto the RPN stack.
The equate may substitute a name or force a conversion for the constant
Parameters
val is the value of the constant
sz is the number of bytes to use for the encoding
sym is the EquateSymbol that marks up the constant
vn is the Varnode holding the constant (optional)
op is the PcodeOp using the constant (optional)
Implements PrintLanguage.
References binary_minus, binary_plus, bitwise_not, calc_mask(), push_integer(), PrintLanguage::pushOp(), pushSymbol(), sign_extend(), and unary_minus.
Referenced by push_integer().
pushMismatchSymbol()
void PrintC::pushMismatchSymbol (const Symbol * sym, int4 off, int4 sz, const Varnode * vn, const PcodeOp * op) protected virtual
Push an identifier for a variable that mismatches with its Symbol.
This happens when a Varnode overlaps, but is not contained by a Symbol. This most commonly happens when the size of a Symbol is unknown
Parameters
sym is the overlapped symbol
off is the byte offset of the variable relative to the symbol
sz is the size of the variable in bytes
vn is the Varnode representing the variable
op is a PcodeOp associated with the Varnode
Implements PrintLanguage.
References PrintLanguage::name, PrintLanguage::pushAtom(), pushUnnamedLocation(), EmitXml::var_color, and PrintLanguage::vartoken.
pushPartialSymbol()
void PrintC::pushPartialSymbol (const Symbol * sym, int4 off, int4 sz, const Varnode * vn, const PcodeOp * op, Datatype * outtype) protected virtual
Push a variable that represents only part of a symbol onto the RPN stack.
Generally member syntax specifying a field within a structure gets emitted.
Parameters
sym is the root Symbol
off is the byte offset, within the Symbol, of the partial variable
sz is the number of bytes in the partial variable
vn is the Varnode holding the partial value
op is a PcodeOp associate with the Varnode
outtype is the data-type expected by expression using the partial variable
Implements PrintLanguage.
References PrintLanguage::castStrategy, EmitXml::const_color, PartialSymbolEntry::field, PartialSymbolEntry::fieldname, PrintLanguage::fieldtoken, Symbol::getFirstWholeMap(), PartialSymbolEntry::hilite, CastStrategy::isSubpieceCastEndian(), TypeField::name, EmitXml::no_color, object_member, TypeField::offset, option_nocasts, PartialSymbolEntry::parent, PrintLanguage::pushAtom(), PrintLanguage::pushOp(), pushSymbol(), pushType(), subscript, PrintLanguage::syntax, PartialSymbolEntry::token, TypeField::type, TYPE_ARRAY, TYPE_STRUCT, and typecast.
Referenced by opPtrsub(), and pushAnnotation().
pushPrototypeInputs()
void PrintC::pushPrototypeInputs (const FuncProto * proto) protected
Push input parameters.
Push the comma separated list of data-type declarations onto the RPN stack as part of emitting a given function prototype
Parameters
proto is the given function prototype
References PrintLanguage::blanktoken, comma, ProtoParameter::getType(), EmitXml::keyword_color, EmitXml::no_color, PrintLanguage::pushAtom(), PrintLanguage::pushOp(), pushTypeEnd(), pushTypeStart(), and PrintLanguage::syntax.
Referenced by pushTypeEnd().
pushPtrCharConstant()
bool PrintC::pushPtrCharConstant (uintb val, const TypePointer * ct, const Varnode * vn, const PcodeOp * op) protected virtual
Attempt to push a quoted string representing a given constant pointer onto the RPN stack.
Check if the constant pointer refers to character data that can be emitted as a quoted string. If so push the string, if not return false to indicate a token was not pushed
Parameters
val is the value of the given constant pointer
ct is the pointer data-type attached to the value
vn is the Varnode holding the value
op is the PcodeOp using the value
Returns
true if a quoted string was pushed to the RPN stack
References EmitXml::const_color, AddrSpaceManager::getDefaultDataSpace(), PrintLanguage::glb, Address::isInvalid(), printCharacterConstant(), PrintLanguage::pushAtom(), AddrSpaceManager::resolveConstant(), Architecture::symboltab, and PrintLanguage::vartoken.
Referenced by pushConstant().
pushPtrCodeConstant()
bool PrintC::pushPtrCodeConstant (uintb val, const TypePointer * ct, const Varnode * vn, const PcodeOp * op) protected
Attempt to push a function name representing a constant pointer onto the RPN stack.
Given the pointer value, try to look up the function at that address and push the function's name as a single Atom.
Parameters
val is the given constant pointer value
ct is the pointer data-type attached to the value
vn is the Varnode holding the value
op is the PcodeOp using the value
Returns
true if a name was pushed to the RPN stack, return false otherwise
References AddrSpace::addressToByte(), EmitXml::funcname_color, PrintLanguage::functoken, AddrSpaceManager::getDefaultCodeSpace(), AddrSpace::getWordSize(), PrintLanguage::glb, PrintLanguage::pushAtom(), and Architecture::symboltab.
Referenced by pushConstant().
pushSymbol()
void PrintC::pushSymbol (const Symbol * sym, const Varnode * vn, const PcodeOp * op) protected virtual
Push a specific Symbol onto the RPN stack.
Parameters
sym is the given Symbol
vn is the Varnode holding the Symbol value
op is a PcodeOp associated with the Varnode
Implements PrintLanguage.
References EmitXml::const_color, Symbol::getFirstWholeMap(), Varnode::getHigh(), HighVariable::getSymbolEntry(), EmitXml::global_color, EmitXml::param_color, printCharacterConstant(), PrintLanguage::pushAtom(), Varnode::readonly, TYPE_ARRAY, EmitXml::var_color, and PrintLanguage::vartoken.
Referenced by emitVarDecl(), opPtrsub(), pushAnnotation(), pushEquate(), and pushPartialSymbol().
pushType()
void PrintC::pushType (const Datatype * ct) protected virtual
Push a data-type name onto the RPN expression stack.
The data-type is generally emitted as if for a cast.
Parameters
ct is the data-type to push
Implements PrintLanguage.
References PrintLanguage::blanktoken, EmitXml::no_color, PrintLanguage::pushAtom(), pushTypeEnd(), and pushTypeStart().
Referenced by emitPrototypeOutput(), opTypeCast(), pushConstant(), and pushPartialSymbol().
pushTypeEnd()
void PrintC::pushTypeEnd (const Datatype * ct) protected virtual
Push the tail ends of a data-type declaration onto the RPN stack.
Because the front-ends were pushed on base-type -> final-modifier, the tail-ends are pushed on final-modifier -> base-type. The tail-ends amount to
array subscripts . [ # ] and
function parameters . (paramlist)
Parameters
ct is the data-type being pushed
Reimplemented in PrintJava.
References PrintLanguage::blanktoken, PrintLanguage::force_dec, EmitXml::no_color, push_integer(), PrintLanguage::pushAtom(), pushPrototypeInputs(), Datatype::size, TYPE_ARRAY, TYPE_CODE, and TYPE_PTR.
Referenced by emitPrototypeInputs(), emitStructDefinition(), emitVarDecl(), pushPrototypeInputs(), and pushType().
pushTypeStart()
void PrintC::pushTypeStart (const Datatype * ct, bool noident) protected virtual
Push part of a data-type declaration onto the RPN stack, up to the identifier.
Store off array sizes for printing after the identifier
Parameters
ct is the data-type to push
noident is true if an identifier will not be pushed as part of the declaration
Reimplemented in PrintJava.
References array_expr, buildTypeStack(), PrintLanguage::clear(), function_call, genericTypeName(), PrintLanguage::name, ptr_expr, PrintLanguage::pushAtom(), PrintLanguage::pushOp(), Datatype::size, TYPE_ARRAY, TYPE_CODE, EmitXml::type_color, type_expr_nospace, type_expr_space, TYPE_PTR, and PrintLanguage::typetoken.
Referenced by emitPrototypeInputs(), emitStructDefinition(), emitVarDecl(), pushPrototypeInputs(), and pushType().
pushUnnamedLocation()
void PrintC::pushUnnamedLocation (const Address & addr, const Varnode * vn, const PcodeOp * op) protected virtual
Push an address as a substitute for a Symbol onto the RPN stack.
If there is no Symbol or other name source for an explicit variable, this method is used to print something to represent the variable based on its storage address.
Parameters
addr is the storage address
vn is the Varnode representing the variable (if present)
op is a PcodeOp associated with the variable
Implements PrintLanguage.
References AddrSpace::getName(), Address::getSpace(), Address::printRaw(), PrintLanguage::pushAtom(), EmitXml::var_color, and PrintLanguage::vartoken.
Referenced by opPtrsub(), and pushMismatchSymbol().
setCommentStyle()
void PrintC::setCommentStyle (const string & nm) virtual
Set the way comments are displayed in decompiler output.
This method can either be provided a formal name or a sample of the initial delimiter, then it will choose from among the schemes it knows
Parameters
nm is the configuration description
Implements PrintLanguage.
The documentation for this class was generated from the following files:
printc.hh
printc.cc