decompiler: TypeOpIntSrem Class Reference
TypeOpIntSrem Class Reference
Information about the INT_SREM op-code.
#include <typeop.hh>
Public Member Functions
TypeOpIntSrem (TypeFactory *t)
Constructor.
virtual void push (PrintLanguage *lng, const PcodeOp *op, const PcodeOp *readOp) const
Push the specific PcodeOp to the emitter's RPN stack.
virtual Datatype * getInputCast (const PcodeOp *op, int4 slot, const CastStrategy *castStrategy) const
Find the data-type of the input to a specific PcodeOp.
Public Member Functions inherited from TypeOpBinary
virtual Datatype * getOutputLocal (const PcodeOp *op) const
Find the minimal (or suggested) data-type of an output to this op-code.
virtual Datatype * getInputLocal (const PcodeOp *op, int4 slot) const
Find the minimal (or suggested) data-type of an input to this op-code.
virtual void printRaw (ostream &s, const PcodeOp *op)
Print (for debugging purposes) this specific PcodeOp to the stream.
Public Member Functions inherited from TypeOp
TypeOp (TypeFactory *t, OpCode opc, const string &n)
Constructor.
virtual ~TypeOp (void)
Destructor.
bool markExplicitUnsigned (PcodeOp *op, int4 slot) const
Check if a constant input should be explicitly labeled as unsigned.
uintb evaluateUnary (int4 sizeout, int4 sizein, uintb in1) const
Emulate the unary op-code on an input value.
uintb evaluateBinary (int4 sizeout, int4 sizein, uintb in1, uintb in2) const
Emulate the binary op-code on an input value.
uintb recoverInputBinary (int4 slot, int4 sizeout, uintb out, int4 sizein, uintb in) const
Reverse the binary op-code operation, recovering a constant input value.
uintb recoverInputUnary (int4 sizeout, uintb out, int4 sizein) const
Reverse the unary op-code operation, recovering a constant input value.
bool isCommutative (void) const
Return true if this op-code is commutative.
bool inheritsSign (void) const
Return true if the op-code inherits it signedness from its inputs.
virtual Datatype * getOutputToken (const PcodeOp *op, CastStrategy *castStrategy) const
Find the data-type of the output that would be assigned by a compiler.
virtual string getOperatorName (const PcodeOp *op) const
Get the name of the op-code as it should be displayed in context.
Additional Inherited Members
Public Types inherited from TypeOp
enum { inherits_sign = 1, inherits_sign_zero = 2 }
Static Public Member Functions inherited from TypeOp
static void registerInstructions (vector< TypeOp * > &inst, TypeFactory *tlst, const Translate *trans)
Build a map from op-code value to the TypeOp information objects.
static void selectJavaOperators (vector< TypeOp * > &inst, bool val)
Toggle Java specific aspects of the op-code information.
Protected Attributes inherited from TypeOp
TypeFactory * tlst
Pointer to data-type factory.
OpCode opcode
The op-code value.
uint4 opflags
Cached pcode-op properties for this op-code.
uint4 addlflags
Additional properties.
string name
Symbol denoting this operation.
OpBehavior * behave
Object for emulating the behavior of the op-code.
Detailed Description
Information about the INT_SREM op-code.
Member Function Documentation
getInputCast()
Datatype * TypeOpIntSrem::getInputCast (const PcodeOp * op, int4 slot, const CastStrategy * castStrategy) const virtual
Find the data-type of the input to a specific PcodeOp.
Calculate the actual data-type of the input to the specific PcodeOp. A null result indicates the input data-type is the same as or otherwise doesn't need a cast from the data-type of the actual input Varnode
Parameters
op is the specific PcodeOp
slot is the input to consider
castStrategy is the current casting strategy
Returns
the data-type
Reimplemented from TypeOp.
References CastStrategy::castStandard(), Varnode::getHigh(), CastStrategy::intPromotionType(), CastStrategy::NO_PROMOTION, and CastStrategy::SIGNED_EXTENSION.
push()
virtual void TypeOpIntSrem::push (PrintLanguage * lng, const PcodeOp * op, const PcodeOp * readOp) const inline virtual
Push the specific PcodeOp to the emitter's RPN stack.
Given a specific language and PcodeOp, emit the expression rooted at the operation.
Parameters
lng is the PrintLanguage to emit
op is the specific PcodeOp
Implements TypeOp.
References PrintLanguage::opIntSrem().
The documentation for this class was generated from the following files:
typeop.hh
typeop.cc