decompiler: ArchitectureGhidra Class Reference
ArchitectureGhidra Class Reference
An implementation of the Architecture interface and connection to a Ghidra client.
#include <ghidra_arch.hh>
Public Member Functions
ArchitectureGhidra (const string &pspec, const string &cspec, const string &tspec, const string &corespec, istream &i, ostream &o)
Construct given specification files and i/o streams.
Document * getRegister (const string &regname)
Retrieve a register description given a name.
string getRegisterName (const VarnodeData &vndata)
Retrieve a register name given its storage location.
Document * getTrackedRegisters (const Address &addr)
Retrieve tracked register values at the given address.
string getUserOpName (int4 index)
Get the name of a user-defined p-code op.
uint1 * getPcodePacked (const Address &addr)
Get p-code for a single instruction.
Document * getMappedSymbolsXML (const Address &addr)
Get symbols associated with the given address.
Document * getExternalRefXML (const Address &addr)
Retrieve a description of an external function.
string getCodeLabel (const Address &addr)
Retrieve a label at the given address.
Document * getType (const string &name, uint8 id)
Retrieve a data-type description for the given name and id.
Document * getComments (const Address &fad, uint4 flags)
Retrieve comments for a particular function.
void getBytes (uint1 *buf, int4 size, const Address &inaddr)
Retrieve bytes in the LoadImage at the given address.
Document * getPcodeInject (const string &name, int4 type, const InjectContext &con)
Retrieve p-code to inject for a specific context.
Document * getCPoolRef (const vector< uintb > &refs)
Resolve a constant pool reference.
void setSendSyntaxTree (bool val)
Toggle whether the data-flow and control-flow is emitted as part of the main decompile action.
void setSendCCode (bool val)
Toggle whether the recovered source code is emitted as part of the main decompile action.
void setSendParamMeasures (bool val)
Toggle whether recovered parameter information is emitted as part of the main decompile action.
virtual void printMessage (const string &message) const
Print an error message to console.
Public Member Functions inherited from Architecture
Architecture (void)
Construct an uninitialized Architecture.
void init (DocumentStorage &store)
Load the image and configure architecture.
ProtoModel * getModel (const string &nm) const
Get a specific PrototypeModel.
bool hasModel (const string &nm) const
Does this Architecture have a specific PrototypeModel.
bool highPtrPossible (const Address &loc, int4 size) const
Are pointers possible to the given location?
AddrSpace * getSpaceBySpacebase (const Address &loc, int4 size) const
Get space associated with a spacebase register.
const LanedRegister * getLanedRegister (const Address &loc, int4 size) const
Get LanedRegister associated with storage.
int4 getMinimumLanedRegisterSize (void) const
Get the minimum size of a laned register in bytes.
void setDefaultModel (const string &nm)
Set the default PrototypeModel.
void clearAnalysis (Funcdata *fd)
Clear analysis specific to a function.
void readLoaderSymbols (void)
Read any symbols from loader into database.
void collectBehaviors (vector< OpBehavior * > &behave) const
Provide a list of OpBehavior objects.
SegmentOp * getSegmentOp (AddrSpace *spc) const
Retrieve the segment op for the given space if any.
void setPrototype (const PrototypePieces &pieces)
Set the prototype for a particular function.
void setPrintLanguage (const string &nm)
Establish a particular output language.
void globalify (void)
Mark all spaces as global.
void restoreFlowOverride (const Element *el)
Set flow overrides from XML.
virtual ~Architecture (void)
Destructor.
virtual void saveXml (ostream &s) const
Serialize this architecture to XML.
virtual void restoreXml (DocumentStorage &store)
Restore the Architecture state from an XML stream.
virtual void nameFunction (const Address &addr, string &name) const
Pick a default name for a function.
Public Member Functions inherited from AddrSpaceManager
AddrSpaceManager (void)
Construct an empty address space manager.
virtual ~AddrSpaceManager (void)
Destroy the manager.
int4 getDefaultSize (void) const
Get size of addresses for the default space.
AddrSpace * getSpaceByName (const string &nm) const
Get address space by name.
AddrSpace * getSpaceByShortcut (char sc) const
Get address space from its shortcut.
AddrSpace * getIopSpace (void) const
Get the internal pcode op space.
AddrSpace * getFspecSpace (void) const
Get the internal callspec space.
AddrSpace * getJoinSpace (void) const
Get the joining space.
AddrSpace * getStackSpace (void) const
Get the stack space for this processor.
AddrSpace * getUniqueSpace (void) const
Get the temporary register space for this processor.
AddrSpace * getDefaultCodeSpace (void) const
Get the default address space of this processor.
AddrSpace * getDefaultDataSpace (void) const
Get the default address space where data is stored.
AddrSpace * getConstantSpace (void) const
Get the constant space.
Address getConstant (uintb val) const
Get a constant encoded as an Address.
Address createConstFromSpace (AddrSpace *spc) const
Create a constant address encoding an address space.
Address resolveConstant (AddrSpace *spc, uintb val, int4 sz, const Address &point, uintb &fullEncoding) const
Resolve a native constant into an Address.
int4 numSpaces (void) const
Get the number of address spaces for this processor.
AddrSpace * getSpace (int4 i) const
Get an address space via its index.
AddrSpace * getNextSpaceInOrder (AddrSpace *spc) const
Get the next contiguous address space.
JoinRecord * findAddJoin (const vector< VarnodeData > &pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
JoinRecord * findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
void setDeadcodeDelay (AddrSpace *spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
void truncateSpace (const TruncationTag &tag)
Mark a space as truncated from its original size.
Address constructFloatExtensionAddress (const Address &realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
Address constructJoinAddress (const Translate *translate, const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz)
Build a logical whole from register pairs.
void renormalizeJoinAddress (Address &addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
Static Public Member Functions
static void segvHandler (int4 sig)
Handler for a segment violation (SIGSEGV) signal.
static int4 readToAnyBurst (istream &s)
Read the next message protocol marker.
static void readStringStream (istream &s, string &res)
Receive a string from the client.
static void writeStringStream (ostream &s, const string &msg)
Send a string to the client.
static void readToResponse (istream &s)
Read the query response protocol marker.
static void readResponseEnd (istream &s)
Read the ending query response protocol marker.
static Document * readXMLAll (istream &s)
Read a whole response as an XML document.
static Document * readXMLStream (istream &s)
Receive an XML document from the client.
static uint1 * readPackedStream (istream &s)
Read packed p-code op information.
static uint1 * readPackedAll (istream &s)
Read a whole response as packed p-code op information.
static void passJavaException (ostream &s, const string &tp, const string &msg)
Send an exception message to the Ghidra client.
Private Member Functions
virtual Scope * buildGlobalScope (void)
Build the global scope for this executable.
virtual Translate * buildTranslator (DocumentStorage &store)
Build the Translator object.
virtual void buildLoader (DocumentStorage &store)
Build the LoadImage object and load the executable image.
virtual PcodeInjectLibrary * buildPcodeInjectLibrary (void)
Build the injection library.
virtual void buildTypegrp (DocumentStorage &store)
Build the data-type factory/container.
virtual void buildCommentDB (DocumentStorage &store)
Build the comment database.
virtual void buildConstantPool (DocumentStorage &store)
Build the constant pool.
virtual void buildContext (DocumentStorage &store)
Build the Context database.
virtual void buildSpecFile (DocumentStorage &store)
Load any relevant specification files.
virtual void modifySpaces (Translate *trans)
Modify address spaces as required by this Architecture.
virtual void postSpecFile (void)
Let components initialize after Translate is built.
virtual void resolveArchitecture (void)
Figure out the processor and compiler of the target executable.
Private Attributes
istream & sin
Input stream for interfacing with Ghidra.
ostream & sout
Output stream for interfacing with Ghidra.
string warnings
Warnings accumulated by the decompiler.
string pspecxml
XML pspec passed from Ghidra.
string cspecxml
XML cspec passed from Ghidra.
string tspecxml
Stripped down .sla file passed from Ghidra.
string corespecxml
A specification of the core data-types.
bool sendsyntaxtree
True if the syntax tree should be sent with function output.
bool sendCcode
True if C code should be sent with function output.
bool sendParamMeasures
True if measurements for argument and return parameters should be sent.
Additional Inherited Members
Public Attributes inherited from Architecture
string archid
ID string uniquely describing this architecture.
int4 trim_recurse_max
How many levels to let parameter trims recurse.
int4 max_implied_ref
Maximum number of references to an implied var.
int4 max_term_duplication
Max terms duplicated without a new variable.
int4 max_basetype_size
Maximum size of an "integer" type before creating an array type.
int4 min_funcsymbol_size
Minimum size of a function symbol.
bool aggressive_ext_trim
Aggressively trim inputs that look like they are sign extended.
bool readonlypropagate
true if readonly values should be treated as constants
bool infer_pointers
True if we should infer pointers from constants that are likely addresses.
vector< AddrSpace * > inferPtrSpaces
Set of address spaces in which a pointer constant is inferable.
int4 funcptr_align
How many bits of alignment a function ptr has.
uint4 flowoptions
options passed to flow following engine
int4 alias_block_level
Aliases blocked by 0=none, 1=struct, 2=array, 3=all.
vector< Rule * > extra_pool_rules
Extra rules that go in the main pool (cpu specific, experimental)
Database * symboltab
Memory map of global variables and functions.
ContextDatabase * context
Map from addresses to context settings.
map< string, ProtoModel * > protoModels
Parsed forms of possible prototypes.
ProtoModel * defaultfp
Parsed form of default prototype.
VarnodeData defaultReturnAddr
Default storage location of return address (for current function)
ProtoModel * evalfp_current
Function proto to use when evaluating current function.
ProtoModel * evalfp_called
Function proto to use when evaluating called functions.
TypeFactory * types
List of types for this binary.
const Translate * translate
Translation method for this binary.
LoadImage * loader
Method for loading portions of binary.
PcodeInjectLibrary * pcodeinjectlib
Pcode injection manager.
RangeList nohighptr
Ranges for which high-level pointers are not possible.
CommentDatabase * commentdb
Comments for this architecture.
ConstantPool * cpool
Deferred constant values.
PrintLanguage * print
Current high-level language printer.
vector< PrintLanguage * > printlist
List of high-level language printers supported.
OptionDatabase * options
Options that can be configured.
vector< TypeOp * > inst
Registered p-code instructions.
UserOpManage userops
Specifically registered user-defined p-code ops.
vector< PreferSplitRecord > splitrecords
registers that we would prefer to see split for this processor
vector< LanedRegister > lanerecords
Vector registers that have preferred lane sizes.
ActionDatabase allacts
Actions that can be applied in this architecture.
bool loadersymbols_parsed
True if loader symbols have been read.
Protected Member Functions inherited from Architecture
void addSpacebase (AddrSpace *basespace, const string &nm, const VarnodeData &ptrdata, int4 truncSize, bool isreversejustified, bool stackGrowth)
Create a new space and associated pointer.
void addNoHighPtr (const Range &rng)
Add a new region where pointers do not exist.
virtual void buildInstructions (DocumentStorage &store)
Register the p-code operations.
virtual void buildAction (DocumentStorage &store)
Build the Action framework.
void restoreFromSpec (DocumentStorage &store)
Fully initialize the Translate object.
void fillinReadOnlyFromLoader (void)
Load info about read-only sections.
void initializeSegments ()
Set up segment resolvers.
void cacheAddrSpaceProperties (void)
Calculate some frequently used space properties and cache them.
void parseProcessorConfig (DocumentStorage &store)
Apply processor specific configuration.
void parseCompilerConfig (DocumentStorage &store)
Apply compiler specific configuration.
void parseExtraRules (DocumentStorage &store)
Apply any Rule tags.
void parseDynamicRule (const Element *el)
Apply details of a dynamic Rule object.
ProtoModel * parseProto (const Element *el)
Build a proto-type model from an XML tag.
void parseProtoEval (const Element *el)
Apply prototype evaluation configuration.
void parseDefaultProto (const Element *el)
Apply default prototype model configuration.
void parseGlobal (const Element *el)
Apply global space configuration.
void addOtherSpace (void)
Add OTHER space and all of its overlays to the symboltab.
void parseReadOnly (const Element *el)
Apply read-only region configuration.
void parseVolatile (const Element *el)
Apply volatile region configuration.
void parseReturnAddress (const Element *el)
Apply return address configuration.
void parseIncidentalCopy (const Element *el)
Apply incidental copy configuration.
void parseLaneSizes (const Element *el)
Apply lane size configuration.
void parseStackPointer (const Element *el)
Apply stack pointer configuration.
void parseDeadcodeDelay (const Element *el)
Apply dead-code delay configuration.
void parseFuncPtrAlign (const Element *el)
Apply function pointer alignment configuration.
void parseSpacebase (const Element *el)
Create an additional indexed space.
void parseNoHighPtr (const Element *el)
Apply memory alias configuration.
void parsePreferSplit (const Element *el)
Designate registers to be split.
void parseAggressiveTrim (const Element *el)
Designate how to trim extension p-code ops.
Protected Member Functions inherited from AddrSpaceManager
AddrSpace * restoreXmlSpace (const Element *el, const Translate *trans)
Add a space to the model based an on XML tag.
void restoreXmlSpaces (const Element *el, const Translate *trans)
Restore address spaces in the model from an XML tag.
void setDefaultCodeSpace (int4 index)
Set the default address space (for code)
void setDefaultDataSpace (int4 index)
Set the default address space for data.
void setReverseJustified (AddrSpace *spc)
Set reverse justified property on this space.
void assignShortcut (AddrSpace *spc)
Select a shortcut character for a new space.
void markNearPointers (AddrSpace *spc, int4 size)
Mark that given space can be accessed with near pointers.
void insertSpace (AddrSpace *spc)
Add a new address space to the model.
void copySpaces (const AddrSpaceManager *op2)
Copy spaces from another manager.
void addSpacebasePointer (SpacebaseSpace *basespace, const VarnodeData &ptrdata, int4 truncSize, bool stackGrowth)
Set the base register of a spacebase space.
void insertResolver (AddrSpace *spc, AddressResolver *rsolv)
Override the base resolver for a space.
JoinRecord * findJoinInternal (uintb offset) const
Find JoinRecord for offset in the join space.
Detailed Description
An implementation of the Architecture interface and connection to a Ghidra client.
In addition to managing the major pieces of the architecture (LoadImage, Translate, Database, TypeFactory, ContextDatbase, CommentDatabase etc.), this class manages a communication channel between the decompiler and a Ghidra client for a single executable. The protocol supports a simple query/response format with exceptions. On top of the low level protocol, this class manages a higher level interface that performs specific queries, providing addresses, names, and other info as input, and returning an XML document or other structure as a result.
This class overrides the build* methods to produce Architecture components that are also backed by the Ghidra client. These all use this same object to do their communication.
This class acts as a main control point for what information gets sent back to the Ghidra client when it requests the main decompilation action. Generally the decompiler sends back the recovered source representation of the function but optionally it can send back:
Recovered source code (with mark up)
Data-flow and control-flow structures
Local symbol and jump-table information
Parameter identification information
Constructor & Destructor Documentation
ArchitectureGhidra()
ArchitectureGhidra::ArchitectureGhidra (const string & pspec, const string & cspec, const string & tspec, const string & corespec, istream & i, ostream & o)
Construct given specification files and i/o streams.
Parameters
pspec is the processor specification presented as an XML string
cspec is the compiler specification presented as an XML string
tspec is a stripped down form of the SLEIGH specification presented as an XML string
corespec is a list of core data-types presented as a <coretypes> XML tag
i is the input stream from the Ghidra client
o is the output stream to the Ghidra client
References corespecxml, cspecxml, Architecture::print, pspecxml, sendCcode, sendParamMeasures, sendsyntaxtree, PrintLanguage::setXML(), sout, and tspecxml.
Member Function Documentation
buildCommentDB()
void ArchitectureGhidra::buildCommentDB (DocumentStorage & store) private virtual
Build the comment database.
Build the container that holds comments for executable in this Architecture.
Parameters
store may hold configuration information
Reimplemented from Architecture.
References Architecture::commentdb.
buildConstantPool()
void ArchitectureGhidra::buildConstantPool (DocumentStorage & store) private virtual
Build the constant pool.
Some processor models (Java byte-code) need a database of constants. The database is always built, but may remain empty.
Parameters
store may hold configuration information
Reimplemented from Architecture.
References Architecture::cpool.
buildContext()
void ArchitectureGhidra::buildContext (DocumentStorage & store) private virtual
Build the Context database.
This builds the database which holds the status registers setings and other information that can affect disassembly depending on context.
Parameters
store may hold configuration information
Reimplemented from Architecture.
References Architecture::context.
buildGlobalScope()
Scope * ArchitectureGhidra::buildGlobalScope (void) private virtual
Build the global scope for this executable.
If it does not already exist create the glocal Scope object
Returns
the global Scope object
Reimplemented from Architecture.
References Database::attachScope(), and Architecture::symboltab.
buildLoader()
void ArchitectureGhidra::buildLoader (DocumentStorage & store) private virtual
Build the LoadImage object and load the executable image.
Parameters
store may hold configuration information
Implements Architecture.
References Architecture::loader.
buildPcodeInjectLibrary()
PcodeInjectLibrary * ArchitectureGhidra::buildPcodeInjectLibrary (void) private virtual
Build the injection library.
This creates the container for p-code injections. It is initially empty.
Returns
the PcodeInjectLibrary object
Implements Architecture.
buildSpecFile()
void ArchitectureGhidra::buildSpecFile (DocumentStorage & store) private virtual
Load any relevant specification files.
Processor/architecture specific configuration files are loaded into the XML store
Parameters
store is the document store that will hold the configuration
Implements Architecture.
References corespecxml, cspecxml, DocumentStorage::parseDocument(), pspecxml, DocumentStorage::registerTag(), and tspecxml.
buildTranslator()
Translate * ArchitectureGhidra::buildTranslator (DocumentStorage & store) private virtual
Build the Translator object.
This builds the main disassembly component for the Architecture This does not initially the engine for a specific processor.
Parameters
store may hold configuration information
Returns
the Translate object
Implements Architecture.
buildTypegrp()
void ArchitectureGhidra::buildTypegrp (DocumentStorage & store) private virtual
Build the data-type factory/container.
This builds the TypeFactory object specific to this architecture and prepopulates it with the core types. Core types may be pulled from the configuration information, or default core types are used.
Parameters
store contains possible configuration information
Reimplemented from Architecture.
References TypeFactory::cacheCoreTypes(), DocumentStorage::getTag(), TypeFactory::restoreXmlCoreTypes(), TypeFactory::setCoreType(), TYPE_BOOL, TYPE_CODE, TYPE_FLOAT, TYPE_INT, TYPE_UINT, TYPE_UNKNOWN, TYPE_VOID, and Architecture::types.
getBytes()
void ArchitectureGhidra::getBytes (uint1 * buf, int4 size, const Address & inaddr)
Retrieve bytes in the LoadImage at the given address.
The Ghidra client is queried for a range of bytes, which are returned in the given array. This method throws a DataUnavailError if the provided address doesn't make sense.
Parameters
buf is the preallocated array in which to store the bytes
size is the number of bytes requested
inaddr is the address in the LoadImage from which to grab bytes
References Address::getShortcut(), Address::printRaw(), readResponseEnd(), readToAnyBurst(), readToResponse(), Address::saveXml(), sin, sout, and writeStringStream().
Referenced by LoadImageGhidra::loadFill().
getCodeLabel()
string ArchitectureGhidra::getCodeLabel (const Address & addr)
Retrieve a label at the given address.
Get the name of the primary symbol at the given address. This is used to fetch within function labels. Only a name is returned.
Parameters
addr is the given address
Returns
the symbol name or ""
References readResponseEnd(), readStringStream(), readToResponse(), Address::saveXml(), sin, sout, and writeStringStream().
Referenced by ScopeGhidra::findCodeLabel().
getComments()
Document * ArchitectureGhidra::getComments (const Address & fad, uint4 flags)
Retrieve comments for a particular function.
Ask Ghidra client for all comments associated with one function. The caller must provide the sub-set of properties (Comment::comment_type) for the query to match. The client will return a <commentdb> tag with a <comment> tag child for each comment found.
Parameters
fad is the address of the function to query
flags specifies the properties the query will match (must be non-zero)
Returns
an XML document describing each comment
References readXMLAll(), Address::saveXml(), sin, sout, and writeStringStream().
Referenced by CommentDatabaseGhidra::fillCache().
getCPoolRef()
Document * ArchitectureGhidra::getCPoolRef (const vector< uintb > & refs)
Resolve a constant pool reference.
The Ghidra client is provided a sequence of 1 or more integer values extracted from a CPOOLREF op. It returns an XML document describing the constant pool record referenced by the integer(s) or will throw an exception if record isn't properly referenced.
Parameters
refs is an array of 1 or more integer values referencing a constant pool record
Returns
a description of the record as a <cpoolrec> XML document.
References readXMLAll(), sin, sout, and writeStringStream().
Referenced by ConstantPoolGhidra::getRecord().
getExternalRefXML()
Document * ArchitectureGhidra::getExternalRefXML (const Address & addr)
Retrieve a description of an external function.
This asks the Ghidra client to resolve an external reference. This is an address for which the client holds a reference to a function that is elsewhere in memory or not in memory at all. The client should unravel the reference from the given address and return either a <function> tag describing the referred to function symbol or a <hole> tag if the reference can't be resolved
Parameters
addr is the given address
Returns
a description of the referred to function
References readXMLAll(), Address::saveXml(), sin, sout, and writeStringStream().
Referenced by ScopeGhidra::resolveExternalRefFunction().
getMappedSymbolsXML()
Document * ArchitectureGhidra::getMappedSymbolsXML (const Address & addr)
Get symbols associated with the given address.
The Ghidra client will return a <symbol> tag, <function> tag, or some other related Symbol information. If there no symbol at the address the client should return a <hole> tag describing the size of the memory region that is free of symbols.
Parameters
addr is the given address
Returns
the symbol document
References readXMLAll(), Address::saveXml(), sin, sout, and writeStringStream().
Referenced by ScopeGhidra::removeQuery().
getPcodeInject()
Document * ArchitectureGhidra::getPcodeInject (const string & name, int4 type, const InjectContext & con)
Retrieve p-code to inject for a specific context.
The particular injection is named and is of one of the types:
CALLFIXUP_TYPE
CALLOTHERFIXUP_TYPE
CALLMECHANISM_TYPE
EXECUTABLEPCODE_TYPE
This and additional context is provided to the Ghidra client which returns an XML document describing the p-code. The document will be an <inst> tag containing individual <op> tags corresponding to individual p-code ops.
Parameters
name is the name of the injection
type is the type of injection
con is the context object
Returns
an XML document describing the p-code ops to inject
References InjectPayload::CALLFIXUP_TYPE, InjectPayload::CALLMECHANISM_TYPE, InjectPayload::CALLOTHERFIXUP_TYPE, readXMLAll(), InjectContext::saveXml(), sin, sout, and writeStringStream().
Referenced by InjectPayloadGhidra::inject(), and ExecutablePcodeGhidra::inject().
getPcodePacked()
uint1 * ArchitectureGhidra::getPcodePacked (const Address & addr)
Get p-code for a single instruction.
Get a description of all the p-code ops for the instruction at the given address. The information is stored in a special compressed format. (See PcodeEmit::restorePackedOp)
Parameters
addr is the address of the instruction
Returns
an array of the packed data
References readPackedAll(), Address::saveXml(), sin, sout, and writeStringStream().
Referenced by GhidraTranslate::oneInstruction().
getRegister()
Document * ArchitectureGhidra::getRegister (const string & regname)
Retrieve a register description given a name.
Ask the Ghidra client if it knows about a specific processor register. The client responds with a <addr> XML element describing the storage location of the register.
Parameters
regname is the name to query for
Returns
the storage address as XML or NULL if the register is unknown
References readXMLAll(), sin, sout, and writeStringStream().
Referenced by GhidraTranslate::getRegister().
getRegisterName()
string ArchitectureGhidra::getRegisterName (const VarnodeData & vndata)
Retrieve a register name given its storage location.
Given a storage location and size, ask the Ghidra client if it knows of a register that occupies those bytes. The register name is passed back. The name may not exactly match the given memory range, it may contain it.
Parameters
vndata is the location and size
Returns
the register name or ""
References VarnodeData::offset, readResponseEnd(), readStringStream(), readToResponse(), Address::saveXml(), sin, VarnodeData::size, sout, VarnodeData::space, and writeStringStream().
Referenced by GhidraTranslate::getRegisterName().
getTrackedRegisters()
Document * ArchitectureGhidra::getTrackedRegisters (const Address & addr)
Retrieve tracked register values at the given address.
The Ghidra client will return a description of registers that have known values at the given address. The response is generally a <tracked_pointset> which contains <set> children which contains a storage location and value.
Parameters
addr is the given address
Returns
the response Document
References readXMLAll(), Address::saveXml(), sin, sout, and writeStringStream().
getType()
Document * ArchitectureGhidra::getType (const string & name, uint8 id)
Retrieve a data-type description for the given name and id.
The Ghidra client should respond with a <type> tag giving details about the data-type.
Parameters
name is the name of the data-type
id is a unique id associated with the data-type, pass 0 if unknown
Returns
the data-type XML element or NULL
References readXMLAll(), sin, sout, and writeStringStream().
getUserOpName()
string ArchitectureGhidra::getUserOpName (int4 index)
Get the name of a user-defined p-code op.
The first operand to a CALLOTHER op indicates the specific user-defined op. This method queries the Ghidra client and passes back the name of the op.
Parameters
index is the value of the CALLOTHER operand
Returns
the recovered name or ""
References readResponseEnd(), readStringStream(), readToResponse(), sin, sout, and writeStringStream().
Referenced by GhidraTranslate::getUserOpNames().
modifySpaces()
virtual void ArchitectureGhidra::modifySpaces (Translate * trans) inline private virtual
Modify address spaces as required by this Architecture.
If spaces need to be truncated or otherwise changed from processor defaults, this routine performs the modification.
Parameters
trans is the processor disassembly object
Implements Architecture.
passJavaException()
void ArchitectureGhidra::passJavaException (ostream & s, const string & tp, const string & msg) static
Send an exception message to the Ghidra client.
This generally called because of some sort of alignment issue in the message protocol and lets the client know to abort (and hopefully resync)
Parameters
s is the output stream to the client
tp is the type of exception
msg is the exception message
References writeStringStream().
Referenced by GhidraCommand::doit().
printMessage()
void ArchitectureGhidra::printMessage (const string & message) const virtual
Print an error message to console.
Write the given message to whatever the registered error stream is
Parameters
message is the error message
Implements Architecture.
References warnings.
Referenced by GhidraCommand::doit().
readPackedAll()
uint1 * ArchitectureGhidra::readPackedAll (istream & s) static
Read a whole response as packed p-code op information.
Read up to the beginning of a query response, check for an exception record, otherwise read in packed p-code op data.
Parameters
s is the input stream from the client
Returns
the array of packed p-coded data
References readPackedStream(), readResponseEnd(), and readToResponse().
Referenced by getPcodePacked().
readPackedStream()
uint1 * ArchitectureGhidra::readPackedStream (istream & s) static
Read packed p-code op information.
The method expects to see protocol markers indicating a string from the client, otherwise it throws and exception. An array size is encoded in the first 4 characters of the string. An array of this size is allocated and filled with the rest of the string.
Parameters
s is the input stream from the client
Returns
the array of packed p-code data
References readToAnyBurst().
Referenced by readPackedAll().
readResponseEnd()
void ArchitectureGhidra::readResponseEnd (istream & s) static
Read the ending query response protocol marker.
Read the next protocol marker. If it does not indicate the end of a query response, throw an exception
Parameters
s is the input stream from the client
References readToAnyBurst().
Referenced by getBytes(), getCodeLabel(), getRegisterName(), getUserOpName(), readPackedAll(), and readXMLAll().
readStringStream()
void ArchitectureGhidra::readStringStream (istream & s, string & res) static
Receive a string from the client.
Characters are read up to the next protocol marked and placed into a string. The protocol marker is consumed and must indicate the end of a string or an exception is thrown.
Parameters
s is the input stream from the client
res will hold the string
References readToAnyBurst().
Referenced by getCodeLabel(), getRegisterName(), getUserOpName(), RegisterProgram::loadParameters(), SetAction::loadParameters(), GhidraCapability::readCommand(), and readToResponse().
readToAnyBurst()
int4 ArchitectureGhidra::readToAnyBurst (istream & s) static
Read the next message protocol marker.
All communications between the Ghidra client and the decompiler are surrounded by alignment bursts. A burst is 1 or more zero bytes followed by an 0x01 byte, then followed by a code byte. Open alignment (as in open paren) is even. Close alignment is odd. Code bytes are as follows:
Command open=2 close=3
Query open=4 close=5
Command response open=6 close=7
Query response open=8 close=9
Exception open=a close=b
Byte stream open=c close=d
String stream open=e close=f
The protocol is as follows:
ghidra sends a command
[ decompiler sends a query
ghidra sends a query response ] zero or more occurences
decompiler sends a command response
Commands, queries, and responses all consist of zero or more string streams or byte streams.
In place of any response an exception can be sent. The decompiler can interrupt a command response with a query or exception once the query is finished the response picks up where it left off an exception however permanently cancels the query. Ghidra cannot interrupt either of its responses.
Parameters
s is the input stream from the client
Returns
the command code
Referenced by GhidraCommand::doit(), getBytes(), GhidraCommand::loadParameters(), DeregisterProgram::loadParameters(), GhidraCapability::readCommand(), readPackedStream(), readResponseEnd(), readStringStream(), readToResponse(), and readXMLStream().
readToResponse()
void ArchitectureGhidra::readToResponse (istream & s) static
Read the query response protocol marker.
Consume the query response header. If it indicates an exception, read details of the exception and throw JavaError.
Parameters
s is the input stream from the client
References readStringStream(), and readToAnyBurst().
Referenced by getBytes(), getCodeLabel(), getRegisterName(), getUserOpName(), readPackedAll(), and readXMLAll().
readXMLAll()
Document * ArchitectureGhidra::readXMLAll (istream & s) static
Read a whole response as an XML document.
Read up to the beginning of a query response, check for an exception record, otherwise read in a string as an XML document.
Parameters
s is the input stream from the client
Returns
the XML document
References readResponseEnd(), readToResponse(), and readXMLStream().
Referenced by getComments(), getCPoolRef(), getExternalRefXML(), getMappedSymbolsXML(), getPcodeInject(), getRegister(), getTrackedRegisters(), and getType().
readXMLStream()
Document * ArchitectureGhidra::readXMLStream (istream & s) static
Receive an XML document from the client.
The method expects to see protocol markers indicating a string from the client, otherwise it throws and exception. The string is read in and then parsed as XML.
Parameters
s is the input stream from the client.
Returns
the XML document
References readToAnyBurst(), and xml_tree().
Referenced by DecompileAt::loadParameters(), StructureGraph::loadParameters(), SetOptions::loadParameters(), and readXMLAll().
segvHandler()
void ArchitectureGhidra::segvHandler (int4 sig) static
Handler for a segment violation (SIGSEGV) signal.
Catch the signal so the OS doesn't pop up a dialog
Parameters
sig is the OS signal (should always be SIGSEGV)
setSendCCode()
void ArchitectureGhidra::setSendCCode (bool val) inline
Toggle whether the recovered source code is emitted as part of the main decompile action.
If the toggle is on, the decompiler will emit source code (marked up in an XML document)
Parameters
val is true to enable emitting
References sendCcode.
Referenced by SetAction::rawAction().
setSendParamMeasures()
void ArchitectureGhidra::setSendParamMeasures (bool val) inline
Toggle whether recovered parameter information is emitted as part of the main decompile action.
If the toggle is on, the decompiler will emit a more detailed description of what it thinks the input parameters to the function are.
Parameters
val is true enable emitting
References sendParamMeasures.
Referenced by SetAction::rawAction().
setSendSyntaxTree()
void ArchitectureGhidra::setSendSyntaxTree (bool val) inline
Toggle whether the data-flow and control-flow is emitted as part of the main decompile action.
If the toggle is on, the decompiler will emit complete descriptions of the graphs.
Parameters
val is true to enable emitting
References sendsyntaxtree.
Referenced by SetAction::rawAction().
writeStringStream()
void ArchitectureGhidra::writeStringStream (ostream & s, const string & msg) static
Send a string to the client.
Write out a string with correct protocol markers
Parameters
s is the output stream to the client
msg is the string to send
Referenced by getBytes(), getCodeLabel(), getComments(), getCPoolRef(), getExternalRefXML(), getMappedSymbolsXML(), getPcodeInject(), getPcodePacked(), getRegister(), getRegisterName(), getTrackedRegisters(), getType(), getUserOpName(), passJavaException(), SetAction::sendResult(), and SetOptions::sendResult().
The documentation for this class was generated from the following files:
ghidra_arch.hh
ghidra_arch.cc