decompiler: ScopeLocal Class Reference
ScopeLocal Class Reference
A Symbol scope for local variables of a particular function.
#include <varmap.hh>
Public Member Functions
ScopeLocal (AddrSpace *spc, Funcdata *fd, Architecture *g)
Constructor.
bool isUnaffectedStorage (Varnode *vn) const
Is this a storage location for unaffected registers.
void markNotMapped (AddrSpace *spc, uintb first, int4 sz, bool param)
Mark a specific address range is not mapped.
virtual void saveXml (ostream &s) const
Write out this as a <scope> XML tag.
virtual void restoreXml (const Element *el)
Restore this Scope from a <scope> XML tag.
virtual string buildVariableName (const Address &addr, const Address &pc, Datatype *ct, int4 &index, uint4 flags) const
Given an address and data-type, build a suitable generic symbol name.
void resetLocalWindow (void)
Reset the set of addresses that are considered mapped by the scope to the default.
void restructureVarnode (bool aliasyes)
Layout mapped symbols based on Varnode information.
void restructureHigh (void)
Layout mapped symbols based on HighVariable information.
SymbolEntry * remapSymbol (Symbol *sym, const Address &addr, const Address &usepoint)
Change the primary mapping for the given Symbol to be a specific storage address and use point.
SymbolEntry * remapSymbolDynamic (Symbol *sym, uint8 hash, const Address &usepoint)
Make the primary mapping for the given Symbol, dynamic.
void recoverNameRecommendationsForSymbols (void)
Run through name recommendations, checking if any match unnamed symbols.
Public Member Functions inherited from ScopeInternal
ScopeInternal (const string &nm, Architecture *g)
Construct the Scope.
virtual void clear (void)
Clear all symbols from this scope.
virtual void categorySanity (void)
Make sure Symbol categories are sane.
virtual void clearCategory (int4 cat)
Clear all symbols of the given category from this scope.
virtual void clearUnlocked (void)
Clear all unlocked symbols from this scope.
virtual void clearUnlockedCategory (int4 cat)
Clear unlocked symbols of the given category from this scope.
virtual MapIterator begin (void) const
Beginning iterator to mapped SymbolEntrys.
virtual MapIterator end (void) const
Ending iterator to mapped SymbolEntrys.
virtual list< SymbolEntry >::const_iterator beginDynamic (void) const
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::const_iterator endDynamic (void) const
Ending iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator beginDynamic (void)
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator endDynamic (void)
Ending iterator to dynamic SymbolEntrys.
virtual void removeSymbolMappings (Symbol *symbol)
Remove all SymbolEntrys from the given Symbol.
virtual void removeSymbol (Symbol *symbol)
Remove the given Symbol from this Scope.
virtual void renameSymbol (Symbol *sym, const string &newname)
Rename a Symbol within this Scope.
virtual void retypeSymbol (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol within this Scope.
virtual void setAttribute (Symbol *sym, uint4 attr)
Set boolean Varnode properties on a Symbol.
virtual void clearAttribute (Symbol *sym, uint4 attr)
Clear boolean Varnode properties on a Symbol.
virtual void setDisplayFormat (Symbol *sym, uint4 attr)
Set the display format for a Symbol.
virtual SymbolEntry * findAddr (const Address &addr, const Address &usepoint) const
Find a Symbol at a given address and usepoint.
virtual SymbolEntry * findContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest Symbol containing the given memory range.
virtual SymbolEntry * findClosestFit (const Address &addr, int4 size, const Address &usepoint) const
Find Symbol which is the closest fit to the given memory range.
virtual Funcdata * findFunction (const Address &addr) const
Find the function starting at the given address.
virtual ExternRefSymbol * findExternalRef (const Address &addr) const
Find an external reference at the given address.
virtual LabSymbol * findCodeLabel (const Address &addr) const
Find a label Symbol at the given address.
virtual SymbolEntry * findOverlap (const Address &addr, int4 size) const
Find first Symbol overlapping the given memory range.
virtual void findByName (const string &name, vector< Symbol * > &res) const
Find a Symbol by name within this Scope.
virtual bool isNameUsed (const string &name) const
Check if the given name is used within this scope.
virtual Funcdata * resolveExternalRefFunction (ExternRefSymbol *sym) const
Convert an external reference to the referenced function.
virtual string buildUndefinedName (void) const
Build a formal undefined name, used internally when a Symbol is not given a name.
virtual string makeNameUnique (const string &nm) const
Produce a version of the given symbol name that won't collide with other names in this Scope.
virtual void printEntries (ostream &s) const
Dump a description of all SymbolEntry objects to a stream.
virtual int4 getCategorySize (int4 cat) const
Get the number of Symbols in the given category.
virtual Symbol * getCategorySymbol (int4 cat, int4 ind) const
Retrieve a Symbol by index within a specific category.
virtual void setCategory (Symbol *sym, int4 cat, int4 ind)
Set the category and index for the given Symbol.
void assignDefaultNames (int4 &base)
Assign a default name (via buildVariableName) to any unnamed symbol.
Public Member Functions inherited from Scope
Scope (const string &nm, Architecture *g)
Construct an empty scope, given a name and Architecture.
virtual ~Scope (void)
Destructor.
virtual bool inScope (const Address &addr, int4 size, const Address &usepoint) const
Query if the given range is owned by this Scope.
virtual SymbolEntry * addSymbol (const string &name, Datatype *ct, const Address &addr, const Address &usepoint)
Add a new Symbol to this Scope, given a name, data-type, and a single mapping.
void queryByName (const string &name, vector< Symbol * > &res) const
Look-up symbols by name.
Funcdata * queryFunction (const string &name) const
Look-up a function by name.
SymbolEntry * queryByAddr (const Address &addr, const Address &usepoint) const
Get Symbol with matching address.
SymbolEntry * queryContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest containing Symbol.
SymbolEntry * queryProperties (const Address &addr, int4 size, const Address &usepoint, uint4 &flags) const
Find a Symbol or properties at the given address.
Funcdata * queryFunction (const Address &addr) const
Look-up a function by address.
Funcdata * queryExternalRefFunction (const Address &addr) const
Look-up a function thru an external reference.
LabSymbol * queryCodeLabel (const Address &addr) const
Look-up a code label by address.
Scope * resolveScope (const string &name) const
Find a child Scope of this.
Scope * discoverScope (const Address &addr, int4 sz, const Address &usepoint)
Find the owning Scope of a given memory range.
void saveXmlRecursive (ostream &s, bool onlyGlobal) const
Save all contained scopes as an XML stream.
void overrideSizeLockType (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol that is sizelocked.
void resetSizeLockType (Symbol *sym)
Clear a Symbol's size-locked data-type.
bool isSubScope (const Scope *scp) const
Is this a sub-scope of the given Scope.
string getFullName (void) const
Get the full name of this Scope.
void getNameSegments (vector< string > &vec) const
Get the fullname of this in segments.
void getScopePath (vector< Scope * > &vec) const
Get the ordered list of parent scopes to this.
bool isNameUsed (const string &nm, const Scope *op2) const
Is the given name in use within given scope path.
const Scope * findDistinguishingScope (const Scope *op2) const
Find first ancestor of this not shared by given scope.
Symbol * addSymbol (const string &name, Datatype *ct)
Add a new Symbol without mapping it to an address.
SymbolEntry * addMapPoint (Symbol *sym, const Address &addr, const Address &usepoint)
Map a Symbol to a specific address.
Symbol * addMapSym (const Element *el)
Add a mapped Symbol from a <mapsym> XML tag.
FunctionSymbol * addFunction (const Address &addr, const string &nm)
Create a function Symbol at the given address in this Scope.
ExternRefSymbol * addExternalRef (const Address &addr, const Address &refaddr, const string &nm)
LabSymbol * addCodeLabel (const Address &addr, const string &nm)
Create a code label at the given address in this Scope.
Symbol * addDynamicSymbol (const string &nm, Datatype *ct, const Address &caddr, uint8 hash)
Create a dynamically mapped Symbol attached to a specific data-flow.
string buildDefaultName (Symbol *sym, int4 &base, Varnode *vn) const
Create a default name for the given Symbol.
bool isReadOnly (const Address &addr, int4 size, const Address &usepoint) const
Is the given memory range marked as read-only.
Private Member Functions
bool adjustFit (RangeHint &a) const
Make the given RangeHint fit in the current Symbol map.
void createEntry (const RangeHint &a)
Create a Symbol entry corresponding to the given (fitted) RangeHint.
bool restructure (MapState &state)
Merge hints into a formal Symbol layout of the address space.
void markUnaliased (const vector< uintb > &alias)
Mark all local symbols for which there are no aliases.
void fakeInputSymbols (void)
Make sure all stack inputs have an associated Symbol.
void addRecommendName (Symbol *sym)
Convert the given symbol to a name recommendation.
void collectNameRecs (void)
Collect names of unlocked Symbols on the stack.
Private Attributes
AddrSpace * space
Address space containing the local stack.
RangeList localRange
The set of addresses that might hold mapped locals (not parameters)
list< NameRecommend > nameRecommend
Symbol name recommendations for specific addresses.
list< DynamicRecommend > dynRecommend
Symbol name recommendations for dynamic locations.
bool stackGrowsNegative
Marked true if the stack is considered to grow towards smaller offsets.
bool rangeLocked
True if the subset of addresses mapped to this scope has been locked.
Additional Inherited Members
Static Public Member Functions inherited from ScopeInternal
static void savePathXml (ostream &s, const vector< string > &vec)
Save a path with <val> tags.
static void restorePathXml (vector< string > &vec, const Element *el)
Restore path from <val> tags.
Protected Member Functions inherited from ScopeInternal
virtual void addSymbolInternal (Symbol *sym)
Put a Symbol into the name map.
virtual SymbolEntry * addMapInternal (Symbol *sym, uint4 exfl, const Address &addr, int4 off, int4 sz, const RangeList &uselim)
Create a new SymbolEntry for a Symbol given a memory range.
virtual SymbolEntry * addDynamicMapInternal (Symbol *sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList &uselim)
Create a new SymbolEntry for a Symbol given a dynamic hash.
Protected Member Functions inherited from Scope
virtual void restrictScope (Funcdata *f)
Convert this to a local Scope.
virtual void addRange (AddrSpace *spc, uintb first, uintb last)
Add a memory range to the ownership of this Scope.
virtual void removeRange (AddrSpace *spc, uintb first, uintb last)
Remove a memory range from the ownership of this Scope.
SymbolEntry * addMap (const SymbolEntry &entry)
Integrate a SymbolEntry into the range maps.
Static Protected Member Functions inherited from Scope
static const Scope * stackAddr (const Scope *scope1, const Scope *scope2, const Address &addr, const Address &usepoint, SymbolEntry **addrmatch)
Query for Symbols starting at a given address, which match a given usepoint.
static const Scope * stackContainer (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackClosestFit (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackFunction (const Scope *scope1, const Scope *scope2, const Address &addr, Funcdata **addrmatch)
static const Scope * stackExternalRef (const Scope *scope1, const Scope *scope2, const Address &addr, ExternRefSymbol **addrmatch)
static const Scope * stackCodeLabel (const Scope *scope1, const Scope *scope2, const Address &addr, LabSymbol **addrmatch)
Protected Attributes inherited from ScopeInternal
SymbolNameTree nametree
The set of Symbol objects, sorted by name.
vector< EntryMap * > maptable
Rangemaps of SymbolEntry, one map for each address space.
vector< vector< Symbol * > > category
References to Symbol objects organized by category.
list< SymbolEntry > dynamicentry
Dynamic symbol entries.
SymbolNameTree multiEntrySet
Set of symbols with multiple entries.
uint8 nextUniqueId
Next available symbol id.
Protected Attributes inherited from Scope
Architecture * glb
Architecture of this scope.
string name
Name of this scope.
Funcdata * fd
(If non-null) the function which this is the local Scope for
uint4 uniqueId
Unique id for the scope, for deduping scope names, assigning symbol ids.
Detailed Description
A Symbol scope for local variables of a particular function.
This acts like any other variable Scope, but is associated with a specific function and the address space where the function maps its local variables and parameters, typically the stack space. This object in addition to managing the local Symbols, builds up information about the stack address space: what portions of it are used for mapped local variables, what portions are used for temporary storage (not mapped), and what portion is for parameters.
Constructor & Destructor Documentation
ScopeLocal()
ScopeLocal::ScopeLocal (AddrSpace * spc, Funcdata * fd, Architecture * g)
Constructor.
Parameters
spc is the (stack) address space associated with this function's local variables
fd is the function associated with these local variables
g is the Architecture
References Scope::fd, rangeLocked, Scope::restrictScope(), space, and stackGrowsNegative.
Member Function Documentation
addRecommendName()
void ScopeLocal::addRecommendName (Symbol * sym) private
Convert the given symbol to a name recommendation.
The symbol is stored as a name recommendation and then removed from the scope. Name recommendations are associated either with a storage address and usepoint, or a dynamic hash. The name may be reattached to a Symbol after decompilation.
Parameters
sym is the given Symbol to treat as a name recommendation
References dynRecommend, SymbolEntry::getFirstUseAddress(), Symbol::getFirstWholeMap(), nameRecommend, and ScopeInternal::removeSymbol().
Referenced by collectNameRecs().
adjustFit()
bool ScopeLocal::adjustFit (RangeHint & a) const private
Make the given RangeHint fit in the current Symbol map.
Shrink the RangeHint as necessary so that it fits in the mapped region of the Scope and doesn't overlap any other Symbols. If this is not possible, return false.
Parameters
a is the given RangeHint to fit
Returns
true if a valid adjustment was made
References ScopeInternal::findOverlap(), RangeHint::flags, RangeHint::size, space, RangeHint::start, and Varnode::typelock.
Referenced by restructure().
buildVariableName()
string ScopeLocal::buildVariableName (const Address & addr, const Address & pc, Datatype * ct, int4 & index, uint4 flags) const virtual
Given an address and data-type, build a suitable generic symbol name.
Parameters
addr is the given address
pc is the address at which the name is getting used
ct is a data-type used to inform the name
index is a reference to an index used to make the name unique, which will be updated
flags are boolean properties of the variable we need the name for
Returns
the new variable name
Reimplemented from ScopeInternal.
References Varnode::addrtied, ScopeInternal::buildVariableName(), AddrSpace::byteToAddress(), Scope::fd, Address::getAddrSize(), AddrSpace::getName(), Address::getOffset(), Address::getSpace(), AddrSpace::getWordSize(), ScopeInternal::makeNameUnique(), Varnode::persist, sign_extend(), space, and stackGrowsNegative.
collectNameRecs()
void ScopeLocal::collectNameRecs (void) private
Collect names of unlocked Symbols on the stack.
Turn any symbols that are name locked but not type locked into name recommendations removing the symbol in the process. This allows the decompiler to decide on how the stack is layed out without forcing specific variables to mapped. But, if the decompiler does create a variable at the specific location, it will use the original name.
References addRecommendName(), dynRecommend, nameRecommend, and ScopeInternal::nametree.
Referenced by restoreXml().
createEntry()
void ScopeLocal::createEntry (const RangeHint & a) private
Create a Symbol entry corresponding to the given (fitted) RangeHint.
A name and final data-type is constructed for the RangeHint, and they are entered as a new Symbol into this scope.
Parameters
a is the given RangeHint to create a Symbol for
References Scope::addSymbol(), TypeFactory::concretize(), TypeFactory::getTypeArray(), Scope::glb, RangeHint::size, space, RangeHint::start, RangeHint::type, and Architecture::types.
Referenced by restructure().
fakeInputSymbols()
void ScopeLocal::fakeInputSymbols (void) private
Make sure all stack inputs have an associated Symbol.
This assigns a Symbol to any input Varnode stored in our address space, which could be a parameter but isn't in the formal prototype of the function (these should already be in the scope marked as category '0').
References Scope::addSymbol(), Funcdata::beginDef(), Funcdata::endDef(), LowlevelError::explain, Scope::fd, ScopeInternal::getCategorySize(), Address::getOffset(), Address::getSpace(), Varnode::input, Scope::queryProperties(), space, TYPE_UNKNOWN, and Funcdata::warningHeader().
Referenced by restructureVarnode().
isUnaffectedStorage()
bool ScopeLocal::isUnaffectedStorage (Varnode * vn) const inline
Is this a storage location for unaffected registers.
Parameters
vn is the Varnode storing an unaffected register
Returns
true is the Varnode can be used as unaffected storage
References space.
markNotMapped()
void ScopeLocal::markNotMapped (AddrSpace * spc, uintb first, int4 sz, bool parameter)
Mark a specific address range is not mapped.
The given range can no longer hold a mapped local variable. This indicates the range is being used for temporary storage.
Parameters
spc is the address space holding the given range
first is the starting offset of the given range
sz is the number of bytes in the range
parameter is true if the range is being used to store a sub-function parameter
References Scope::fd, ScopeInternal::findOverlap(), AddrSpace::getHighest(), RangeList::getRange(), Scope::glb, localRange, Database::removeRange(), ScopeInternal::removeSymbol(), space, stackGrowsNegative, Architecture::symboltab, Varnode::typelock, and Funcdata::warningHeader().
markUnaliased()
void ScopeLocal::markUnaliased (const vector< uintb > & alias) private
Mark all local symbols for which there are no aliases.
Given a set of alias starting offsets, calculate whether each Symbol within this scope might be aliased by a pointer. The method uses locked Symbol information when available to determine how far an alias start might extend. Otherwise a heuristic is used to determine if the Symbol is far enough away from the start of the alias to be considered unaliased.
Parameters
alias is the given set of alias starting offsets
References Architecture::alias_block_level, AddrSpace::getIndex(), Scope::glb, ScopeInternal::maptable, Varnode::nolocalalias, space, TYPE_ARRAY, and TYPE_STRUCT.
Referenced by restructureVarnode().
recoverNameRecommendationsForSymbols()
void ScopeLocal::recoverNameRecommendationsForSymbols (void)
Run through name recommendations, checking if any match unnamed symbols.
Unlocked symbols that are presented to the decompiler are stored off as recommended names. These can be reattached after the decompiler makes a determination of what the final Symbols are. This method runs through the recommended names and checks if they can be applied to an existing unnamed Symbol.
References Varnode::addrtied, DynamicHash::clear(), dynRecommend, Scope::fd, Funcdata::findLinkedVarnode(), ScopeInternal::findOverlap(), DynamicHash::findVarnode(), Funcdata::findVarnodeWritten(), Symbol::getFirstWholeMap(), Varnode::getHigh(), Address::isInvalid(), Symbol::isNameUndefined(), ScopeInternal::makeNameUnique(), Varnode::namelock, nameRecommend, Funcdata::remapDynamicVarnode(), Funcdata::remapVarnode(), ScopeInternal::renameSymbol(), and ScopeInternal::setAttribute().
remapSymbol()
SymbolEntry * ScopeLocal::remapSymbol (Symbol * sym, const Address & addr, const Address & usepoint)
Change the primary mapping for the given Symbol to be a specific storage address and use point.
Remove any other mapping and create a mapping based on the given storage.
Parameters
sym is the given Symbol to remap
addr is the starting address of the storage
usepoint is the use point for the mapping
Returns
the new mapping
References ScopeInternal::addMapInternal(), SymbolEntry::getFirstUseAddress(), Symbol::getFirstWholeMap(), Address::getOffset(), Address::getSpace(), RangeList::insertRange(), Address::isInvalid(), Varnode::mapped, and ScopeInternal::removeSymbolMappings().
Referenced by Funcdata::remapVarnode().
remapSymbolDynamic()
SymbolEntry * ScopeLocal::remapSymbolDynamic (Symbol * sym, uint8 hash, const Address & usepoint)
Make the primary mapping for the given Symbol, dynamic.
Remove any other mapping and create a new dynamic mapping based on a given size and hash
Parameters
sym is the given Symbol to remap
hash is the dynamic hash
usepoint is the use point for the mapping
Returns
the new dynamic mapping
References ScopeInternal::addDynamicMapInternal(), SymbolEntry::getFirstUseAddress(), Symbol::getFirstWholeMap(), Address::getOffset(), Address::getSpace(), RangeList::insertRange(), Address::isInvalid(), Varnode::mapped, and ScopeInternal::removeSymbolMappings().
Referenced by Funcdata::remapDynamicVarnode().
resetLocalWindow()
void ScopeLocal::resetLocalWindow (void)
Reset the set of addresses that are considered mapped by the scope to the default.
This resets the discovery process for new local variables mapped to the scope's address space. Any analysis removing specific ranges from the mapped set (via markNotMapped()) is cleared.
References Scope::fd, Scope::glb, RangeList::insertRange(), localRange, rangeLocked, Database::setRange(), stackGrowsNegative, and Architecture::symboltab.
Referenced by Funcdata::clear(), Funcdata::Funcdata(), and Funcdata::restoreXml().
restructure()
bool ScopeLocal::restructure (MapState & state) private
Merge hints into a formal Symbol layout of the address space.
RangeHints from the given collection are merged into a definitive set of Symbols for this scope. Overlapping or open RangeHints are adjusted to form a disjoint cover of the mapped portion of the address space. Names for the disjoint cover elements are chosen, and these form the final Symbols.
Parameters
state is the given collection of RangeHints
Returns
true if there were overlaps that could not be reconciled
References RangeHint::absorb(), adjustFit(), createEntry(), Scope::glb, MapState::initialize(), RangeHint::merge(), RangeHint::open, RangeHint::rangeType, RangeHint::size, space, RangeHint::sstart, and Architecture::types.
Referenced by restructureHigh(), and restructureVarnode().
restructureHigh()
void ScopeLocal::restructureHigh (void)
Layout mapped symbols based on HighVariable information.
Define stack Symbols based on HighVariables. This method is called once at the end of decompilation to create the final set of stack Symbols after all data-type propagation has settled. It creates a consistent data-type for all Varnode instances of a HighVariable.
References ScopeInternal::clearUnlockedCategory(), Scope::fd, MapState::gatherHighs(), MapState::gatherOpen(), MapState::gatherSymbols(), TypeFactory::getBase(), AddrSpace::getIndex(), Scope::glb, ScopeInternal::maptable, restructure(), space, TYPE_UNKNOWN, Architecture::types, and Funcdata::warningHeader().
Referenced by ActionRestructureHigh::apply().
restructureVarnode()
void ScopeLocal::restructureVarnode (bool aliasyes)
Layout mapped symbols based on Varnode information.
Define stack Symbols based on Varnodes. This method can be called repeatedly during decompilation. It helps propagate data-types. Unaliased symbols can optionally be marked to facilitate removal of INDIRECT ops, but this is generally done later in the process.
Parameters
aliasyes is true if unaliased Symbols should be marked
References ScopeInternal::clearUnlockedCategory(), fakeInputSymbols(), Scope::fd, MapState::gatherOpen(), MapState::gatherSymbols(), MapState::gatherVarnodes(), TypeFactory::getBase(), AddrSpace::getIndex(), Scope::glb, ScopeInternal::maptable, markUnaliased(), restructure(), space, TYPE_UNKNOWN, and Architecture::types.
Referenced by ActionRestructureVarnode::apply().
The documentation for this class was generated from the following files:
varmap.hh
varmap.cc