decompiler: ConstantPoolInternal Class Reference
ConstantPoolInternal Class Reference
An implementation of the ConstantPool interface storing records internally in RAM.
#include <cpool.hh>
Classes
class CheapSorter
A cheap (efficient) placeholder for a reference to a constant pool record.
Public Member Functions
virtual const CPoolRecord * getRecord (const vector< uintb > &refs) const
Retrieve a constant pool record (CPoolRecord) given a reference to it.
virtual bool empty (void) const
Is the container empty of records.
virtual void clear (void)
Release any (local) resources.
virtual void saveXml (ostream &s) const
Save all records in this container to an XML stream.
virtual void restoreXml (const Element *el, TypeFactory &typegrp)
Restore constant pool records from an XML stream.
Public Member Functions inherited from ConstantPool
void putRecord (const vector< uintb > &refs, uint4 tag, const string &tok, Datatype *ct)
A a new constant pool record to this database.
const CPoolRecord * restoreXmlRecord (const vector< uintb > &refs, const Element *el, TypeFactory &typegrp)
Restore a CPoolRecord given a reference and an XML stream.
Private Member Functions
virtual CPoolRecord * createRecord (const vector< uintb > &refs)
Allocate a new CPoolRecord object, given a reference to it.
Private Attributes
map< CheapSorter, CPoolRecord > cpoolMap
A map from reference to constant pool record.
Detailed Description
An implementation of the ConstantPool interface storing records internally in RAM.
The CPoolRecord objects are held directly in a map container. This class can be used as a stand-alone ConstantPool that holds all its records in RAM. Or, it can act as a local CPoolRecord cache for some other implementation.
Member Function Documentation
createRecord()
CPoolRecord * ConstantPoolInternal::createRecord (const vector< uintb > & refs) private virtual
Allocate a new CPoolRecord object, given a reference to it.
The object will still need to be initialized but is already associated with the reference. Any issue with allocation (like a dupicate reference) causes an exception.
Parameters
refs is the reference of 1 or more identifying integers
Returns
the new CPoolRecord
Implements ConstantPool.
References cpoolMap.
Referenced by restoreXml().
getRecord()
const CPoolRecord * ConstantPoolInternal::getRecord (const vector< uintb > & refs) const virtual
Retrieve a constant pool record (CPoolRecord) given a reference to it.
Parameters
refs is the reference (made up of 1 or more identifying integers)
Returns
the matching CPoolRecord or NULL if none matches the reference
Implements ConstantPool.
References cpoolMap.
Referenced by ConstantPoolGhidra::getRecord().
restoreXml()
void ConstantPoolInternal::restoreXml (const Element * el, TypeFactory & typegrp) virtual
Restore constant pool records from an XML stream.
(If supported) The container is populated with CPooLRecords initialized from a <constantpool> XML tag.
Parameters
el is the XML element
typegrp is the TypeFactory used to resolve data-type references in the XML
Implements ConstantPool.
References ConstantPoolInternal::CheapSorter::apply(), createRecord(), CPoolRecord::restoreXml(), and ConstantPoolInternal::CheapSorter::restoreXml().
saveXml()
void ConstantPoolInternal::saveXml (ostream & s) const virtual
Save all records in this container to an XML stream.
(If supported) An <constantpool> element is written containing <cpoolrec> child elements for each CPoolRecord in the container.
Parameters
s is the output stream
Implements ConstantPool.
References cpoolMap.
The documentation for this class was generated from the following files:
cpool.hh
cpool.cc