decompiler: Element Class Reference
Element Class Reference
An XML element. A node in the DOM tree.
#include <xml.hh>
Public Member Functions
~Element (void)
Destructor.
void addContent (const char *str, int4 start, int4 length)
Append new character content to this element.
void addChild (Element *child)
Add a new child Element to the model, with this as the parent.
void addAttribute (const string &nm, const string &vl)
Add a new name/value attribute pair to this element.
const string & getAttributeValue (const string &nm) const
Get an attribute value by name.
Protected Attributes
Element * parent
The parent Element (or null)
List children
A list of child Element objects.
Private Attributes
string name
The (local) name of the element.
string content
Character content of the element.
vector< string > attr
A list of attribute names for this element.
vector< string > value
a (corresponding) list of attribute values for this element
Detailed Description
An XML element. A node in the DOM tree.
This is the main node for the in-memory representation of the XML (DOM) tree.
Member Function Documentation
addAttribute()
void Element::addAttribute (const string & nm, const string & vl) inline
Add a new name/value attribute pair to this element.
Parameters
nm is the name of the attribute
vl is the value of the attribute
addChild()
void Element::addChild (Element * child) inline
Add a new child Element to the model, with this as the parent.
Parameters
child is the new child Element
addContent()
void Element::addContent (const char * str, int4 start, int4 length) inline
Append new character content to this element.
Parameters
str is an array of character data
start is the index of the first character to append
length is the number of characters to append
getAttributeValue()
const string& Element::getAttributeValue (const string & nm) const
Get an attribute value by name.
Look up the value for the given attribute name and return it. An exception is thrown if the attribute does not exist.
Parameters
nm is the name of the attribute
Returns
the corresponding attribute value
Referenced by ScopeGhidra::dump2Cache(), LoadImageXml::LoadImageXml(), LoadImageXml::open(), Architecture::parseAggressiveTrim(), TypeFactory::parseDataOrganization(), Architecture::parseDeadcodeDelay(), Architecture::parseDynamicRule(), TypeFactory::parseEnumConfig(), Architecture::parseFuncPtrAlign(), Database::parseParentTag(), Architecture::parsePreferSplit(), Architecture::parseProtoEval(), Architecture::parseSpacebase(), Architecture::parseStackPointer(), ScopeGhidra::processHole(), ScopeInternal::processHole(), InjectPayload::readParameter(), ContextInternal::restoreContext(), Architecture::restoreFlowOverride(), CompilerTag::restoreXml(), GhidraTranslate::restoreXml(), XmlArchitecture::restoreXml(), SleighBase::restoreXml(), RawBinaryArchitecture::restoreXml(), VarnodeData::restoreXml(), BfdArchitecture::restoreXml(), BlockEdge::restoreXml(), LoadTable::restoreXml(), InjectCallfixupGhidra::restoreXml(), InjectCallotherGhidra::restoreXml(), Comment::restoreXml(), LanguageDescription::restoreXml(), TruncationTag::restoreXml(), TrackedContext::restoreXml(), Override::restoreXml(), CPoolRecord::restoreXml(), FloatFormat::restoreXml(), ParamEntry::restoreXml(), LanedRegister::restoreXml(), VolatileReadOp::restoreXml(), InjectPayload::restoreXml(), VolatileWriteOp::restoreXml(), SymbolEntry::restoreXml(), SeqNum::restoreXml(), AddrSpace::restoreXml(), OpFollow::restoreXml(), Funcdata::restoreXml(), SpacebaseSpace::restoreXml(), ConstantPoolInternal::CheapSorter::restoreXml(), Architecture::restoreXml(), Range::restoreXml(), ScopeLocal::restoreXml(), SegmentOp::restoreXml(), JumpAssistOp::restoreXml(), OverlaySpace::restoreXml(), FunctionSymbol::restoreXml(), ExternRefSymbol::restoreXml(), TypeFactory::restoreXml(), ParamListStandard::restoreXml(), JumpTable::restoreXml(), ProtoModel::restoreXml(), Database::restoreXml(), ProtoModelMerged::restoreXml(), ProtoStoreInternal::restoreXml(), FuncProto::restoreXml(), AddrSpace::restoreXmlAttributes(), JoinSpace::restoreXmlAttributes(), Datatype::restoreXmlBasic(), BlockGraph::restoreXmlBody(), SleighArchitecture::restoreXmlHeader(), FlowBlock::restoreXmlHeader(), Symbol::restoreXmlHeader(), PcodeEmit::restoreXmlOp(), AddrSpaceManager::restoreXmlSpaces(), TypeFactory::restoreXmlType(), TypeFactory::restoreXmlTypeNoRef(), and TypeFactory::restoreXmlTypeWithCodeFlags().
The documentation for this class was generated from the following file:
xml.hh