decompiler: PrintLanguage Class Reference
PrintLanguage Class Reference abstract
The base class API for emitting a high-level language.
#include <printlanguage.hh>
Classes
struct Atom
A single non-operator token emitted by the decompiler.
struct NodePending
A pending data-flow node; waiting to be placed on the reverse polish notation stack.
struct ReversePolish
An entry on the reverse polish notation (RPN) stack.
Public Types
enum modifiers {
force_hex = 1, force_dec = 2, bestfit = 4, force_scinote = 8,
force_pointer = 0x10, print_load_value = 0x20, print_store_value = 0x40, no_branch = 0x80,
only_branch = 0x100, comma_separate = 0x200, flat = 0x400, falsebranch = 0x800,
nofallthru = 0x1000, negatetoken = 0x2000, hide_thisparam = 0x4000
}
Possible context sensitive modifiers to how tokens get emitted.
enum tagtype {
syntax, vartoken, functoken, optoken,
typetoken, fieldtoken, blanktoken
}
Possible types of Atom.
Public Member Functions
PrintLanguage (Architecture *g, const string &nm)
Constructor.
virtual ~PrintLanguage (void)
Destructor.
void setLineCommentIndent (int4 val)
Set the number of characters to indent comment lines.
void setCommentDelimeter (const string &start, const string &stop, bool usecommentfill)
Establish comment delimiters for the language.
void setXML (bool val)
Set whether the low-level emitter, emits XML markup.
void setFlat (bool val)
Set whether nesting code structure should be emitted.
virtual void adjustTypeOperators (void)=0
Set basic data-type information for p-code operators.
virtual void clear (void)
Clear the RPN stack and the low-level emitter.
virtual void setIntegerFormat (const string &nm)
Set the default integer format.
virtual void setCommentStyle (const string &nm)=0
Set the way comments are displayed in decompiler output.
virtual bool isCharacterConstant (const uint1 *buf, int4 size, int4 charsize) const =0
Decide is the given byte array looks like a character string.
virtual void docTypeDefinitions (const TypeFactory *typegrp)=0
Emit definitions of data-types.
virtual void docAllGlobals (void)=0
Emit declarations of global variables.
virtual void docSingleGlobal (const Symbol *sym)=0
Emit the declaration for a single (global) Symbol.
virtual void docFunction (const Funcdata *fd)=0
Emit the declaration (and body) of a function.
virtual void emitBlockBasic (const BlockBasic *bb)=0
Emit statements in a basic block.
virtual void emitBlockGraph (const BlockGraph *bl)=0
Emit (an unspecified) list of blocks.
virtual void emitBlockCopy (const BlockCopy *bl)=0
Emit a basic block (with any labels)
virtual void emitBlockGoto (const BlockGoto *bl)=0
Emit a block ending with a goto statement.
virtual void emitBlockLs (const BlockList *bl)=0
Emit a sequence of blocks.
virtual void emitBlockCondition (const BlockCondition *bl)=0
Emit a conditional statement.
virtual void emitBlockIf (const BlockIf *bl)=0
Emit an if/else style construct.
virtual void emitBlockWhileDo (const BlockWhileDo *bl)=0
Emit a loop structure, check at top.
virtual void emitBlockDoWhile (const BlockDoWhile *bl)=0
Emit a loop structure, check at bottom.
virtual void emitBlockInfLoop (const BlockInfLoop *bl)=0
Emit an infinite loop structure.
virtual void emitBlockSwitch (const BlockSwitch *bl)=0
Emit a switch structure.
virtual void opCopy (const PcodeOp *op)=0
Emit a COPY operator.
virtual void opLoad (const PcodeOp *op)=0
Emit a LOAD operator.
virtual void opStore (const PcodeOp *op)=0
Emit a STORE operator.
virtual void opBranch (const PcodeOp *op)=0
Emit a BRANCH operator.
virtual void opCbranch (const PcodeOp *op)=0
Emit a CBRANCH operator.
virtual void opBranchind (const PcodeOp *op)=0
Emit a BRANCHIND operator.
virtual void opCall (const PcodeOp *op)=0
Emit a CALL operator.
virtual void opCallind (const PcodeOp *op)=0
Emit a CALLIND operator.
virtual void opCallother (const PcodeOp *op)=0
Emit a CALLOTHER operator.
virtual void opConstructor (const PcodeOp *op, bool withNew)=0
Emit an operator constructing an object.
virtual void opReturn (const PcodeOp *op)=0
Emit a RETURN operator.
virtual void opIntEqual (const PcodeOp *op)=0
Emit a INT_EQUAL operator.
virtual void opIntNotEqual (const PcodeOp *op)=0
Emit a INT_NOTEQUAL operator.
virtual void opIntSless (const PcodeOp *op)=0
Emit a INT_SLESS operator.
virtual void opIntSlessEqual (const PcodeOp *op)=0
Emit a INT_SLESSEQUAL operator.
virtual void opIntLess (const PcodeOp *op)=0
Emit a INT_LESS operator.
virtual void opIntLessEqual (const PcodeOp *op)=0
Emit a INT_LESSEQUAL operator.
virtual void opIntZext (const PcodeOp *op, const PcodeOp *readOp)=0
Emit a INT_ZEXT operator.
virtual void opIntSext (const PcodeOp *op, const PcodeOp *readOp)=0
Emit a INT_SEXT operator.
virtual void opIntAdd (const PcodeOp *op)=0
Emit a INT_ADD operator.
virtual void opIntSub (const PcodeOp *op)=0
Emit a INT_SUB operator.
virtual void opIntCarry (const PcodeOp *op)=0
Emit a INT_CARRY operator.
virtual void opIntScarry (const PcodeOp *op)=0
Emit a INT_SCARRY operator.
virtual void opIntSborrow (const PcodeOp *op)=0
Emit a INT_SBORROW operator.
virtual void opInt2Comp (const PcodeOp *op)=0
Emit a INT_2COMP operator.
virtual void opIntNegate (const PcodeOp *op)=0
Emit a INT_NEGATE operator.
virtual void opIntXor (const PcodeOp *op)=0
Emit a INT_XOR operator.
virtual void opIntAnd (const PcodeOp *op)=0
Emit a INT_AND operator.
virtual void opIntOr (const PcodeOp *op)=0
Emit a INT_OR operator.
virtual void opIntLeft (const PcodeOp *op)=0
Emit a INT_LEFT operator.
virtual void opIntRight (const PcodeOp *op)=0
Emit a INT_RIGHT operator.
virtual void opIntSright (const PcodeOp *op)=0
Emit a INT_SRIGHT operator.
virtual void opIntMult (const PcodeOp *op)=0
Emit a INT_MULT operator.
virtual void opIntDiv (const PcodeOp *op)=0
Emit a INT_DIV operator.
virtual void opIntSdiv (const PcodeOp *op)=0
Emit a INT_SDIV operator.
virtual void opIntRem (const PcodeOp *op)=0
Emit a INT_REM operator.
virtual void opIntSrem (const PcodeOp *op)=0
Emit a INT_SREM operator.
virtual void opBoolNegate (const PcodeOp *op)=0
Emit a BOOL_NEGATE operator.
virtual void opBoolXor (const PcodeOp *op)=0
Emit a BOOL_XOR operator.
virtual void opBoolAnd (const PcodeOp *op)=0
Emit a BOOL_AND operator.
virtual void opBoolOr (const PcodeOp *op)=0
Emit a BOOL_OR operator.
virtual void opFloatEqual (const PcodeOp *op)=0
Emit a FLOAT_EQUAL operator.
virtual void opFloatNotEqual (const PcodeOp *op)=0
Emit a FLOAT_NOTEQUAL operator.
virtual void opFloatLess (const PcodeOp *op)=0
Emit a FLOAT_LESS operator.
virtual void opFloatLessEqual (const PcodeOp *op)=0
Emit a FLOAT_LESSEQUAL operator.
virtual void opFloatNan (const PcodeOp *op)=0
Emit a FLOAT_NAN operator.
virtual void opFloatAdd (const PcodeOp *op)=0
Emit a FLOAT_ADD operator.
virtual void opFloatDiv (const PcodeOp *op)=0
Emit a FLOAT_DIV operator.
virtual void opFloatMult (const PcodeOp *op)=0
Emit a FLOAT_MULT operator.
virtual void opFloatSub (const PcodeOp *op)=0
Emit a FLOAT_SUB operator.
virtual void opFloatNeg (const PcodeOp *op)=0
Emit a FLOAT_NEG operator.
virtual void opFloatAbs (const PcodeOp *op)=0
Emit a FLOAT_ABS operator.
virtual void opFloatSqrt (const PcodeOp *op)=0
Emit a FLOAT_SQRT operator.
virtual void opFloatInt2Float (const PcodeOp *op)=0
Emit a FLOAT_INT2FLOAT operator.
virtual void opFloatFloat2Float (const PcodeOp *op)=0
Emit a FLOAT_FLOAT2FLOAT operator.
virtual void opFloatTrunc (const PcodeOp *op)=0
Emit a FLOAT_TRUNC operator.
virtual void opFloatCeil (const PcodeOp *op)=0
Emit a FLOAT_CEIL operator.
virtual void opFloatFloor (const PcodeOp *op)=0
Emit a FLOAT_FLOOR operator.
virtual void opFloatRound (const PcodeOp *op)=0
Emit a FLOAT_ROUND operator.
virtual void opMultiequal (const PcodeOp *op)=0
Emit a MULTIEQUAL operator.
virtual void opIndirect (const PcodeOp *op)=0
Emit a INDIRECT operator.
virtual void opPiece (const PcodeOp *op)=0
Emit a PIECE operator.
virtual void opSubpiece (const PcodeOp *op)=0
Emit a SUBPIECE operator.
virtual void opCast (const PcodeOp *op)=0
Emit a CAST operator.
virtual void opPtradd (const PcodeOp *op)=0
Emit a PTRADD operator.
virtual void opPtrsub (const PcodeOp *op)=0
Emit a PTRSUB operator.
virtual void opSegmentOp (const PcodeOp *op)=0
Emit a SEGMENTOP operator.
virtual void opCpoolRefOp (const PcodeOp *op)=0
Emit a CPOOLREF operator.
virtual void opNewOp (const PcodeOp *op)=0
Emit a NEW operator.
virtual void opInsertOp (const PcodeOp *op)=0
Emit an INSERT operator.
virtual void opExtractOp (const PcodeOp *op)=0
Emit an EXTRACT operator.
virtual void opPopcountOp (const PcodeOp *op)=0
Emit a POPCOUNT operator.
Static Public Member Functions
static int4 mostNaturalBase (uintb val)
Determine the most natural base for an integer.
static void formatBinary (ostream &s, uintb val)
Print a number in binary form.
Protected Member Functions
void pushOp (const OpToken *tok, const PcodeOp *op)
Push an operator token onto the RPN stack.
void pushAtom (const Atom &atom)
Push a variable token onto the RPN stack.
void pushVnImplied (const Varnode *vn, const PcodeOp *op, uint4 m)
Push an implied variable onto the RPN stack.
void pushVnExplicit (const Varnode *vn, const PcodeOp *op)
Push an explicit variable onto the RPN stack.
void pushVnLHS (const Varnode *vn, const PcodeOp *op)
Push a variable as the left-hand side of an expression.
bool parentheses (const OpToken *op2)
Determine if the given token should be emitted in its own parenthetic expression.
void emitOp (const ReversePolish &entry)
Send an operator token from the RPN to the emitter.
void emitAtom (const Atom &atom)
Send an variable token from the RPN to the emitter.
bool escapeCharacterData (ostream &s, const uint1 *buf, int4 count, int4 charsize, bool bigend) const
Emit a byte buffer to the stream as unicode characters.
void recurse (void)
Emit from the RPN stack as much as possible.
void opBinary (const OpToken *tok, const PcodeOp *op)
Push a binary operator onto the RPN stack.
void opUnary (const OpToken *tok, const PcodeOp *op)
Push a unary operator onto the RPN stack.
virtual void printUnicode (ostream &s, int4 onechar) const =0
Print a single unicode character as a character constant for the high-level language.
virtual void pushType (const Datatype *ct)=0
Push a data-type name onto the RPN expression stack.
virtual void pushConstant (uintb val, const Datatype *ct, const Varnode *vn, const PcodeOp *op)=0
Push a constant onto the RPN stack.
virtual bool pushEquate (uintb val, int4 sz, const EquateSymbol *sym, const Varnode *vn, const PcodeOp *op)=0
Push a constant marked up by and EquateSymbol onto the RPN stack.
virtual void pushAnnotation (const Varnode *vn, const PcodeOp *op)=0
Push an address which is not in the normal data-flow.
virtual void pushSymbol (const Symbol *sym, const Varnode *vn, const PcodeOp *op)=0
Push a specific Symbol onto the RPN stack.
virtual void pushUnnamedLocation (const Address &addr, const Varnode *vn, const PcodeOp *op)=0
Push an address as a substitute for a Symbol onto the RPN stack.
virtual void pushPartialSymbol (const Symbol *sym, int4 off, int4 sz, const Varnode *vn, const PcodeOp *op, Datatype *outtype)=0
Push a variable that represents only part of a symbol onto the RPN stack.
virtual void pushMismatchSymbol (const Symbol *sym, int4 off, int4 sz, const Varnode *vn, const PcodeOp *op)=0
Push an identifier for a variable that mismatches with its Symbol.
virtual void emitLineComment (int4 indent, const Comment *comm)
Emit a comment line.
virtual void emitVarDecl (const Symbol *sym)=0
Emit a variable declaration.
virtual void emitVarDeclStatement (const Symbol *sym)=0
Emit a variable declaration statement.
virtual bool emitScopeVarDecls (const Scope *scope, int4 cat)=0
Emit all the variable declarations for a given scope.
virtual void emitExpression (const PcodeOp *op)=0
Emit a full expression.
virtual void emitFunctionDeclaration (const Funcdata *fd)=0
Emit a function declaration.
virtual bool checkPrintNegation (const Varnode *vn)=0
Check whether a given boolean Varnode can be printed in negated form.
Static Protected Member Functions
static bool unicodeNeedsEscape (int4 codepoint)
Determine if the given codepoint needs to be escaped.
static void writeUtf8 (ostream &s, int4 codepoint)
Write unicode character to stream in UTF8 encoding.
static int4 readUtf16 (const uint1 *buf, bool bigend)
Read a 2-byte UTF16 element from a byte array.
static int4 getCodepoint (const uint1 *buf, int4 charsize, bool bigend, int4 &skip)
Extract the next unicode codepoint from an array of character data.
Protected Attributes
Architecture * glb
The Architecture owning the language emitter.
CastStrategy * castStrategy
The strategy for emitting explicit case operations.
EmitXml * emit
The low-level token emitter.
uint4 mods
Currently active printing modifications.
uint4 instr_comment_type
Type of instruction comments to display.
uint4 head_comment_type
Type of header comments to display.
Private Attributes
string name
The name of the high-level language.
vector< uint4 > modstack
Printing modification stack.
vector< Scope * > scopestack
The symbol scope stack.
Scope * curscope
The current symbol scope.
vector< ReversePolish > revpol
The Reverse Polish Notation (RPN) token stack.
vector< NodePending > nodepend
Data-flow nodes waiting to be pushed onto the RPN stack.
int4 pending
Number of data-flow nodes waiting to be pushed.
int4 line_commentindent
Number of characters a comment line should be indented.
string commentstart
Delimiter characters for the start of a comment.
string commentend
Delimiter characters (if any) for the end of a comment.
Detailed Description
The base class API for emitting a high-level language.
Instances of this object are responsible for converting a function's (transformed) data-flow graph into the final stream of tokens of a high-level source code language. There a few main entry points including:
docFunction()
docAllGlobals()
docTypeDefinitions()
The system is responsible for printing:
Control-flow structures
Expressions
Type declarations
Function prototypes
Comments
As part of all this printing, the system is also responsible for
Emitting integers, floats, and character constants
Placing parentheses within expressions to properly represent data-flow
Deciding whether cast operations need an explicit cast token
Indenting and line wrapping
To accomplish this, the API is broken up into three sections. The first section are the main entry point 'doc' methods. The second section are 'emit' methods, which are responsible for printing a representation of a particular high-level code construct. The third section are 'push' and 'op' methods, which are responsible for walking expression trees. The order in which tokens are emitted for an expression is determined by a Reverse Polish Notation (RPN) stack, that the 'push' methods manipulate. Operators and variables are pushed onto this stack and are ultimately emitted in the correct order.
The base class provides a generic printing modifications stack and a symbol scope stack to provide a printing context mechanism for derived classes.
Member Enumeration Documentation
modifiers
enum PrintLanguage::modifiers
Possible context sensitive modifiers to how tokens get emitted.
Enumerator
force_hex
Force printing of hex.
force_dec
Force printing of dec.
bestfit
Decide on most aesthetic form.
force_scinote
Force scientific notation for floats.
force_pointer
Force '*' notation for pointers.
print_load_value
Hide pointer deref for load with other ops.
print_store_value
Hide pointer deref for store with other ops.
no_branch
Do not print branch instruction.
only_branch
Print only the branch instruction.
comma_separate
Statements within condition.
flat
Do not print block structure.
falsebranch
Print the false branch (for flat)
nofallthru
Fall-thru no longer exists.
negatetoken
Print the token representing the negation of current token.
hide_thisparam
Do not print the 'this' parameter in argument lists.
tagtype
enum PrintLanguage::tagtype
Possible types of Atom.
Enumerator
syntax
Emit atom as syntax.
vartoken
Emit atom as variable.
functoken
Emit atom as function name.
optoken
Emit atom as operator.
typetoken
Emit atom as operator.
fieldtoken
Emit atom as structure field.
blanktoken
For anonymous types.
Constructor & Destructor Documentation
PrintLanguage()
PrintLanguage::PrintLanguage (Architecture * g, const string & nm)
Constructor.
Parameters
g is the Architecture that owns and will use this PrintLanguage
nm is the formal name of the language
References castStrategy, curscope, emit, glb, head_comment_type, Comment::header, instr_comment_type, line_commentindent, mods, name, pending, Comment::user2, Comment::warning, and Comment::warningheader.
Member Function Documentation
checkPrintNegation()
virtual bool PrintLanguage::checkPrintNegation (const Varnode * vn) protected pure virtual
Check whether a given boolean Varnode can be printed in negated form.
In many situations a boolean value can be inverted by flipping the operator token producing it to a complementary token.
Parameters
vn is the given boolean Varnode
Returns
true if the value can be easily inverted
Implemented in PrintC.
docFunction()
virtual void PrintLanguage::docFunction (const Funcdata * fd) pure virtual
Emit the declaration (and body) of a function.
Parameters
fd is the function to emit
Implemented in PrintC.
Referenced by DecompileAt::rawAction().
docSingleGlobal()
virtual void PrintLanguage::docSingleGlobal (const Symbol * sym) pure virtual
Emit the declaration for a single (global) Symbol.
Parameters
sym is the Symbol to declare
Implemented in PrintC.
docTypeDefinitions()
virtual void PrintLanguage::docTypeDefinitions (const TypeFactory * typegrp) pure virtual
Emit definitions of data-types.
Parameters
typegrp is the container for the data-types that should be defined
Implemented in PrintC.
emitAtom()
void PrintLanguage::emitAtom (const Atom & atom) protected
Send an variable token from the RPN to the emitter.
Send the given Atom to the low-level emitter, marking it up according to its type
Parameters
atom is the given Atom to emit
References blanktoken, PrintLanguage::Atom::ct, emit, PrintLanguage::Atom::fd, fieldtoken, functoken, PrintLanguage::Atom::highlight, PrintLanguage::Atom::name, PrintLanguage::Atom::offset, PrintLanguage::Atom::op, optoken, EmitXml::print(), PrintLanguage::Atom::ptr_second, syntax, EmitXml::tagField(), EmitXml::tagFuncName(), EmitXml::tagOp(), EmitXml::tagType(), EmitXml::tagVariable(), PrintLanguage::Atom::type, typetoken, vartoken, and PrintLanguage::Atom::vn.
Referenced by pushAtom().
emitExpression()
virtual void PrintLanguage::emitExpression (const PcodeOp * op) protected pure virtual
Emit a full expression.
This can be an assignment statement, if the given PcodeOp has an output Varnode, or it can be a statement with no left-hand side.
Parameters
op is the given PcodeOp performing the final operation of the expression
Implemented in PrintC.
emitFunctionDeclaration()
virtual void PrintLanguage::emitFunctionDeclaration (const Funcdata * fd) protected pure virtual
Emit a function declaration.
This prints the formal defining prototype for a function.
Parameters
fd is the Funcdata object representing the function to be emitted
Implemented in PrintC.
emitLineComment()
void PrintLanguage::emitLineComment (int4 indent, const Comment * comm) protected virtual
Emit a comment line.
The comment will get emitted as a single line using the high-level language's delimiters with the given indent level
Parameters
indent is the number of characters to indent
comm is the Comment object containing the character data and associated markup info
References EmitXml::comment_color, commentend, commentstart, emit, line_commentindent, EmitXml::spaces(), EmitXml::startComment(), EmitXml::stopComment(), EmitXml::tagComment(), and EmitXml::tagLine().
Referenced by PrintC::emitCommentFuncHeader(), and PrintC::emitCommentGroup().
emitOp()
void PrintLanguage::emitOp (const ReversePolish & entry) protected
Send an operator token from the RPN to the emitter.
An OpToken directly from the RPN is sent to the low-level emitter, resolving any final spacing or parentheses.
Parameters
entry is the RPN entry to be emitted
References OpToken::binary, OpToken::bump, EmitXml::closeParen(), emit, OpToken::hiddenfunction, PrintLanguage::ReversePolish::id2, EmitXml::no_color, PrintLanguage::ReversePolish::op, EmitXml::openParen(), OpToken::postsurround, OpToken::presurround, OpToken::print, OpToken::space, EmitXml::spaces(), OpToken::spacing, EmitXml::tagOp(), PrintLanguage::ReversePolish::tok, OpToken::type, OpToken::unary_prefix, and PrintLanguage::ReversePolish::visited.
Referenced by PrintC::emitBlockCondition(), pushAtom(), and pushOp().
emitScopeVarDecls()
virtual bool PrintLanguage::emitScopeVarDecls (const Scope * scope, int4 cat) protected pure virtual
Emit all the variable declarations for a given scope.
A subset of all variables can be declared by specifying a category, 0 for parameters, -1 for everything.
Parameters
scope is the given Scope
cat is the category of variable to declare
Implemented in PrintC.
emitVarDecl()
virtual void PrintLanguage::emitVarDecl (const Symbol * sym) protected pure virtual
Emit a variable declaration.
This can be part of a full a statement, or just the declaration of a function parameter
Parameters
sym is the Symbol to be declared
Implemented in PrintC.
emitVarDeclStatement()
virtual void PrintLanguage::emitVarDeclStatement (const Symbol * sym) protected pure virtual
Emit a variable declaration statement.
Parameters
sym is the Symbol to be declared
Implemented in PrintC.
escapeCharacterData()
bool PrintLanguage::escapeCharacterData (ostream & s, const uint1 * buf, int4 count, int4 charsize, bool bigend) const protected
Emit a byte buffer to the stream as unicode characters.
Characters are emitted until we reach a terminator character or count bytes is consumed.
Parameters
s is the output stream
buf is the byte buffer
count is the maximum number of bytes to consume
charsize is 1 for UTF8, 2 for UTF16, or 4 for UTF32
bigend is true for a big endian encoding of UTF elements
Returns
true if we reach a terminator character
References getCodepoint(), and printUnicode().
Referenced by PrintJava::opCpoolRefOp(), PrintC::opCpoolRefOp(), and PrintC::printCharacterConstant().
formatBinary()
void PrintLanguage::formatBinary (ostream & s, uintb val) static
Print a number in binary form.
Print a string a '0' and '1' characters representing the given value
Parameters
s is the output stream
val is the given value
References mostsigbit_set().
Referenced by PrintC::push_integer().
getCodepoint()
int4 PrintLanguage::getCodepoint (const uint1 * buf, int4 charsize, bool bigend, int4 & skip) static protected
Extract the next unicode codepoint from an array of character data.
One or more bytes is consumed from the array, and the number of bytes used is passed back.
Parameters
buf is a pointer to the bytes in the character array
charsize is 1 for UTF8, 2 for UTF16, or 4 for UTF32
bigend is true for big endian encoding of the UTF element
skip is a reference for passing back the number of bytes consumed
Returns
the codepoint or -1 if the encoding is invalid
References readUtf16().
Referenced by escapeCharacterData(), and PrintC::isCharacterConstant().
isCharacterConstant()
virtual bool PrintLanguage::isCharacterConstant (const uint1 * buf, int4 size, int4 charsize) const pure virtual
Decide is the given byte array looks like a character string.
This looks for encodings and/or a terminator that is appropriate for the high-level language
Parameters
buf is a pointer to the byte array
size is the number of bytes in the array
charsize is the size in bytes of the encoding element (i.e. UTF8, UTF16, etc.) to assume
Implemented in PrintC.
mostNaturalBase()
int4 PrintLanguage::mostNaturalBase (uintb val) static
Determine the most natural base for an integer.
Count '0' and '9' digits base 10. Count '0' and 'f' digits base 16. The highest count is the preferred base.
Parameters
val is the given integer
Returns
10 for decimal or 16 for hexidecimal
Referenced by PrintC::push_integer().
opBinary()
void PrintLanguage::opBinary (const OpToken * tok, const PcodeOp * op) protected
Push a binary operator onto the RPN stack.
Push an operator onto the stack that has a normal binary format. Both of its input expressions are also pushed.
Parameters
tok is the operator token to push
op is the associated PcodeOp
References mods, OpToken::negate, negatetoken, pushOp(), and pushVnImplied().
Referenced by PrintC::opBoolAnd(), PrintC::opBoolOr(), PrintC::opBoolXor(), PrintC::opFloatAdd(), PrintC::opFloatDiv(), PrintC::opFloatEqual(), PrintC::opFloatLess(), PrintC::opFloatLessEqual(), PrintC::opFloatMult(), PrintC::opFloatNotEqual(), PrintC::opFloatSub(), PrintC::opIntAdd(), PrintC::opIntAnd(), PrintC::opIntDiv(), PrintC::opIntEqual(), PrintC::opIntLeft(), PrintC::opIntLess(), PrintC::opIntLessEqual(), PrintC::opIntMult(), PrintC::opIntNotEqual(), PrintC::opIntOr(), PrintC::opIntRem(), PrintC::opIntRight(), PrintC::opIntSdiv(), PrintC::opIntSless(), PrintC::opIntSlessEqual(), PrintC::opIntSrem(), PrintC::opIntSright(), PrintC::opIntSub(), and PrintC::opIntXor().
opUnary()
void PrintLanguage::opUnary (const OpToken * tok, const PcodeOp * op) protected
Push a unary operator onto the RPN stack.
Push an operator onto the stack that has a normal unary format. Its input expression is also pushed.
Parameters
tok is the operator token to push
op is the associated PcodeOp
References mods, pushOp(), and pushVnImplied().
Referenced by PrintC::opFloatNeg(), PrintC::opInt2Comp(), and PrintC::opIntNegate().
parentheses()
bool PrintLanguage::parentheses (const OpToken * op2) protected
Determine if the given token should be emitted in its own parenthetic expression.
The token at the top of the stack is being emitted. Check if its input expression, ending with the given operator token, needs to be surrounded by parentheses to convey the proper meaning.
Parameters
op2 is the input token to this operator
Returns
true if op2 (as input to this) should be parenthesized
References OpToken::associative, OpToken::binary, OpToken::hiddenfunction, OpToken::postsurround, OpToken::precedence, OpToken::presurround, revpol, OpToken::space, PrintLanguage::ReversePolish::tok, OpToken::type, OpToken::unary_prefix, and PrintLanguage::ReversePolish::visited.
Referenced by pushOp().
printUnicode()
virtual void PrintLanguage::printUnicode (ostream & s, int4 onechar) const protected pure virtual
Print a single unicode character as a character constant for the high-level language.
For most languages, this prints the character surrounded by single quotes.
Parameters
s is the output stream
onechar is the unicode code point of the character to print
Implemented in PrintC, and PrintJava.
Referenced by escapeCharacterData().
pushAnnotation()
virtual void PrintLanguage::pushAnnotation (const Varnode * vn, const PcodeOp * op) protected pure virtual
Push an address which is not in the normal data-flow.
The given Varnode is treated as an address, which may or may not have a symbol name.
Parameters
vn is the annotation Varnode
op is the PcodeOp which takes the annotation as input
Implemented in PrintC.
Referenced by pushVnExplicit().
pushAtom()
void PrintLanguage::pushAtom (const Atom & atom) protected
Push a variable token onto the RPN stack.
Push a single token (an Atom) onto the RPN stack. This may trigger some amount of the RPN stack to get emitted, depending on what was pushed previously. The 'emit' routines are called, popping off as much as possible.
Parameters
atom is the token to be pushed
References EmitXml::closeGroup(), EmitXml::closeParen(), emit, emitAtom(), emitOp(), nodepend, pending, recurse(), and revpol.
Referenced by PrintC::emitPrototypeInputs(), PrintC::emitStructDefinition(), PrintC::opCall(), PrintJava::opCallind(), PrintC::opCallind(), PrintC::opCallother(), PrintC::opConstructor(), PrintJava::opCpoolRefOp(), PrintC::opCpoolRefOp(), PrintC::opFunc(), PrintC::opNewOp(), PrintC::opPtrsub(), PrintC::opReturn(), PrintC::push_float(), PrintC::push_integer(), PrintC::pushAnnotation(), PrintC::pushBoolConstant(), PrintC::pushCharConstant(), PrintC::pushConstant(), PrintC::pushEnumConstant(), PrintC::pushMismatchSymbol(), PrintC::pushPartialSymbol(), PrintC::pushPrototypeInputs(), PrintC::pushPtrCharConstant(), PrintC::pushPtrCodeConstant(), PrintC::pushSymbol(), PrintC::pushType(), PrintC::pushTypeEnd(), PrintJava::pushTypeStart(), PrintC::pushTypeStart(), and PrintC::pushUnnamedLocation().
pushConstant()
virtual void PrintLanguage::pushConstant (uintb val, const Datatype * ct, const Varnode * vn, const PcodeOp * op) protected pure virtual
Push a constant onto the RPN stack.
The value is ultimately emitted based on its data-type and other associated mark-up
Parameters
val is the value of the constant
ct is the data-type of the constant
vn is the Varnode holding the constant (optional)
op is the PcodeOp using the constant (optional)
Implemented in PrintC.
Referenced by pushVnExplicit().
pushEquate()
virtual bool PrintLanguage::pushEquate (uintb val, int4 sz, const EquateSymbol * sym, const Varnode * vn, const PcodeOp * op) protected pure virtual
Push a constant marked up by and EquateSymbol onto the RPN stack.
The equate may substitute a name or force a conversion for the constant
Parameters
val is the value of the constant
sz is the number of bytes to use for the encoding
sym is the EquateSymbol that marks up the constant
vn is the Varnode holding the constant (optional)
op is the PcodeOp using the constant (optional)
Implemented in PrintC.
pushMismatchSymbol()
virtual void PrintLanguage::pushMismatchSymbol (const Symbol * sym, int4 off, int4 sz, const Varnode * vn, const PcodeOp * op) protected pure virtual
Push an identifier for a variable that mismatches with its Symbol.
This happens when a Varnode overlaps, but is not contained by a Symbol. This most commonly happens when the size of a Symbol is unknown
Parameters
sym is the overlapped symbol
off is the byte offset of the variable relative to the symbol
sz is the size of the variable in bytes
vn is the Varnode representing the variable
op is a PcodeOp associated with the Varnode
Implemented in PrintC.
Referenced by pushVnExplicit(), and pushVnLHS().
pushOp()
void PrintLanguage::pushOp (const OpToken * tok, const PcodeOp * op) protected
Push an operator token onto the RPN stack.
This generally will recursively push an entire expression onto the RPN stack, up to Varnode objects marked as explicit, and will decide token order and parenthesis placement. As the ordering gets resolved, some amount of the expression may get emitted.
Parameters
tok is the operator token to push
op is the PcodeOp associated with the token
References emit, emitOp(), nodepend, EmitXml::openGroup(), EmitXml::openParen(), parentheses(), pending, recurse(), and revpol.
Referenced by PrintC::emitExpression(), PrintC::emitInplaceOp(), opBinary(), PrintC::opBoolNegate(), PrintC::opCall(), PrintJava::opCallind(), PrintC::opCallind(), PrintC::opCallother(), PrintC::opCbranch(), PrintC::opConstructor(), PrintJava::opCpoolRefOp(), PrintC::opCpoolRefOp(), PrintC::opFunc(), PrintC::opHiddenFunc(), PrintJava::opLoad(), PrintC::opLoad(), PrintC::opNewOp(), PrintC::opPtradd(), PrintC::opPtrsub(), PrintC::opReturn(), PrintJava::opStore(), PrintC::opStore(), PrintC::opTypeCast(), opUnary(), PrintC::pushConstant(), PrintC::pushEnumConstant(), PrintC::pushEquate(), PrintC::pushPartialSymbol(), PrintC::pushPrototypeInputs(), PrintJava::pushTypeStart(), and PrintC::pushTypeStart().
pushPartialSymbol()
virtual void PrintLanguage::pushPartialSymbol (const Symbol * sym, int4 off, int4 sz, const Varnode * vn, const PcodeOp * op, Datatype * outtype) protected pure virtual
Push a variable that represents only part of a symbol onto the RPN stack.
Generally member syntax specifying a field within a structure gets emitted.
Parameters
sym is the root Symbol
off is the byte offset, within the Symbol, of the partial variable
sz is the number of bytes in the partial variable
vn is the Varnode holding the partial value
op is a PcodeOp associate with the Varnode
outtype is the data-type expected by expression using the partial variable
Implemented in PrintC.
Referenced by pushVnExplicit(), and pushVnLHS().
pushSymbol()
virtual void PrintLanguage::pushSymbol (const Symbol * sym, const Varnode * vn, const PcodeOp * op) protected pure virtual
Push a specific Symbol onto the RPN stack.
Parameters
sym is the given Symbol
vn is the Varnode holding the Symbol value
op is a PcodeOp associated with the Varnode
Implemented in PrintC.
Referenced by pushVnExplicit(), and pushVnLHS().
pushType()
virtual void PrintLanguage::pushType (const Datatype * ct) protected pure virtual
Push a data-type name onto the RPN expression stack.
The data-type is generally emitted as if for a cast.
Parameters
ct is the data-type to push
Implemented in PrintC.
pushUnnamedLocation()
virtual void PrintLanguage::pushUnnamedLocation (const Address & addr, const Varnode * vn, const PcodeOp * op) protected pure virtual
Push an address as a substitute for a Symbol onto the RPN stack.
If there is no Symbol or other name source for an explicit variable, this method is used to print something to represent the variable based on its storage address.
Parameters
addr is the storage address
vn is the Varnode representing the variable (if present)
op is a PcodeOp associated with the variable
Implemented in PrintC.
Referenced by pushVnExplicit(), and pushVnLHS().
pushVnExplicit()
void PrintLanguage::pushVnExplicit (const Varnode * vn, const PcodeOp * op) protected
Push an explicit variable onto the RPN stack.
This method pushes a given Varnode as a leaf of the current expression. It decides how the Varnode should get emitted, as a symbol, constant, etc., and then pushes the resulting leaf Atom onto the stack.
Parameters
vn is the given explicit Varnode
op is the PcodeOp incorporating the Varnode into the current expression
References Varnode::getHigh(), HighVariable::getNameRepresentative(), pushAnnotation(), pushConstant(), pushMismatchSymbol(), pushPartialSymbol(), pushSymbol(), and pushUnnamedLocation().
Referenced by PrintC::emitInplaceOp(), and recurse().
pushVnImplied()
void PrintLanguage::pushVnImplied (const Varnode * vn, const PcodeOp * op, uint4 m) protected
Push an implied variable onto the RPN stack.
For a given implied Varnode, the entire expression producing it is recursively pushed onto the RPN stack.
When calling this method multiple times to push Varnode inputs for a single p-code op, the inputs must be pushed in reverse order.
Parameters
vn is the given implied Varnode
op is PcodeOp taking the Varnode as input
m is the set of printing modifications to apply for this sub-expression
References nodepend.
Referenced by PrintC::emitInplaceOp(), opBinary(), PrintC::opBoolNegate(), PrintC::opBranch(), PrintC::opBranchind(), PrintC::opCall(), PrintJava::opCallind(), PrintC::opCallind(), PrintC::opCallother(), PrintC::opCbranch(), PrintC::opConstructor(), PrintC::opCopy(), PrintJava::opCpoolRefOp(), PrintC::opCpoolRefOp(), PrintC::opFunc(), PrintC::opHiddenFunc(), PrintJava::opLoad(), PrintC::opLoad(), PrintC::opNewOp(), PrintC::opPtradd(), PrintC::opPtrsub(), PrintC::opReturn(), PrintC::opSegmentOp(), PrintJava::opStore(), PrintC::opStore(), PrintC::opTypeCast(), and opUnary().
pushVnLHS()
void PrintLanguage::pushVnLHS (const Varnode * vn, const PcodeOp * op) protected
Push a variable as the left-hand side of an expression.
The given Varnode will ultimately be emitted as an explicit variable on the left-hand side of an assignment statement. As with pushVnExplicit(), this method decides how the Varnode will be emitted and pushes the resulting Atom onto the RPN stack.
Parameters
vn is the given LSH Varnode
op is the PcodeOp which produces the Varnode as an output
References Varnode::getHigh(), HighVariable::getNameRepresentative(), pushMismatchSymbol(), pushPartialSymbol(), pushSymbol(), and pushUnnamedLocation().
Referenced by PrintC::emitExpression().
readUtf16()
int4 PrintLanguage::readUtf16 (const uint1 * buf, bool bigend) inline static protected
Read a 2-byte UTF16 element from a byte array.
Pull the first two bytes from the byte array and combine them in the indicated endian order
Parameters
buf is the byte array
bigend is true to request big endian encoding
Returns
the decoded UTF16 element
Referenced by getCodepoint().
recurse()
void PrintLanguage::recurse (void) protected
Emit from the RPN stack as much as possible.
Any complete sub-expressions that are still on the RPN will get emitted.
References mods, nodepend, pending, and pushVnExplicit().
Referenced by PrintC::emitEnumDefinition(), PrintC::emitExpression(), PrintC::emitInplaceOp(), PrintC::emitPrototypeInputs(), PrintC::emitPrototypeOutput(), PrintC::emitSwitchCase(), PrintC::emitVarDecl(), PrintC::opBranchind(), PrintC::opCbranch(), pushAtom(), and pushOp().
setCommentDelimeter()
void PrintLanguage::setCommentDelimeter (const string & start, const string & stop, bool usecommentfill)
Establish comment delimiters for the language.
By default, comments are indicated in the high-level language by preceding them with a specific sequence of delimiter characters, and optionally by ending the comment with another set of delimiter characters.
Parameters
start is the initial sequence of characters delimiting a comment
stop if not empty is the sequence delimiting the end of the comment
usecommentfill is true if the delimiter needs to be emitted after every line break
References commentend, commentstart, emit, and EmitXml::setCommentFill().
setCommentStyle()
virtual void PrintLanguage::setCommentStyle (const string & nm) pure virtual
Set the way comments are displayed in decompiler output.
This method can either be provided a formal name or a sample of the initial delimiter, then it will choose from among the schemes it knows
Parameters
nm is the configuration description
Implemented in PrintC.
Referenced by OptionCommentStyle::apply().
setFlat()
void PrintLanguage::setFlat (bool val)
Set whether nesting code structure should be emitted.
Emitting formal code structuring can be turned off, causing all control-flow to be represented as goto statements and labels.
Parameters
val is true if no code structuring should be emitted
References flat, and mods.
setIntegerFormat()
void PrintLanguage::setIntegerFormat (const string & nm) virtual
Set the default integer format.
This determines how integers are displayed by default. Possible values are "hex" and "dec" to force a given format, or "best" can be used to let the decompiler select what it thinks best for each individual integer.
Parameters
nm is "hex", "dec", or "best"
References force_dec, force_hex, and mods.
Referenced by OptionIntegerFormat::apply().
setLineCommentIndent()
void PrintLanguage::setLineCommentIndent (int4 val)
Set the number of characters to indent comment lines.
Parameters
val is the number of characters
References emit, EmitXml::getMaxLineSize(), and line_commentindent.
Referenced by OptionCommentIndent::apply().
setXML()
void PrintLanguage::setXML (bool val)
Set whether the low-level emitter, emits XML markup.
Tell the emitter whether to emit just the raw tokens or if output is in XML format with additional mark-up on the raw tokens.
Parameters
val is true for XML mark-up
References emit.
Referenced by ArchitectureGhidra::ArchitectureGhidra(), and Architecture::setPrintLanguage().
unicodeNeedsEscape()
bool PrintLanguage::unicodeNeedsEscape (int4 codepoint) static protected
Determine if the given codepoint needs to be escaped.
Separate unicode characters that can be clearly emitted in a source code string (letters, numbers, punctuation, symbols) from characters that are better represented in source code with an escape sequence (control characters, unusual spaces, separators, private use characters etc.
Parameters
codepoint is the given unicode codepoint to categorize.
Returns
true if the codepoint needs to be escaped
Referenced by PrintJava::printUnicode(), and PrintC::printUnicode().
writeUtf8()
void PrintLanguage::writeUtf8 (ostream & s, int4 codepoint) static protected
Write unicode character to stream in UTF8 encoding.
Encode the given unicode codepoint as UTF8 (1, 2, 3, or 4 bytes) and write the bytes to the stream.
Parameters
s is the output stream
codepoint is the unicode codepoint
References mostsigbit_set().
Referenced by PrintJava::printUnicode(), and PrintC::printUnicode().
The documentation for this class was generated from the following files:
printlanguage.hh
printlanguage.cc