decompiler: SetAction Class Reference
SetAction Class Reference
Command to set the root Action used by the decompiler or toggle output components.
#include <ghidra_process.hh>
Public Member Functions
virtual void rawAction (void)
Perform the action of the command.
Public Member Functions inherited from GhidraCommand
int4 doit (void)
Configure and execute the command, then send back results.
Public Attributes
bool res
Set to true if the configuration action was successful.
Private Member Functions
virtual void loadParameters (void)
Read parameters directing command execution.
virtual void sendResult (void)
Send results of the command (if any) back to the Ghidra client.
Private Attributes
string actionstring
The root Action to switch to.
string printstring
The printing output configuration to toggle.
Additional Inherited Members
Protected Attributes inherited from GhidraCommand
istream & sin
The input stream from the Ghidra client.
ostream & sout
The output stream to the Ghidra client.
ArchitectureGhidra * ghidra
The Architecture on which to perform the command.
int4 status
Meta-command to system (0=wait for next command, 1=terminate process)
Detailed Description
Command to set the root Action used by the decompiler or toggle output components.
The command expects 3 string parameters, the encoded integer id of the program being decompiled, the root action name, and the name of the output printing configuration. If the root action name is empty, no change is made to the root action. If the printing name is empty, no change is made to what gets output. The root action name can be:
decompile – The main decompiler action
normalize – Decompilation tuned for normalization
jumptable – Simplify just enough to recover a jump-table
paramid – Simplify enough to recover function parameters
register – Perform one analysis pass on registers, without stack variables
firstpass – Construct the initial raw syntax tree, with no simplification
The printing configuration can be:
tree – Send data-flow and control-flow structures
notree – Do not send data-flow and control-flow
c – Send recovered source code
noc – Do not send recovered source code
parammeasures – Send parameter measures
noparammeasures – Do not send parameter measures
jumpload – Send addresses of jump-table entries, when recovering switch destinations
nojumpload – Do not send addresses of jump-table entries
The command returns a single character message, 't' or 'f', indicating whether the action succeeded.
Member Function Documentation
loadParameters()
void SetAction::loadParameters (void) private virtual
Read parameters directing command execution.
This method reads an id selecting the Architecture to act on, but it can be overloaded to read any set of data from the Ghidra client to configure how the command is executed. Individual parameters are read using the method protocol.
Reimplemented from GhidraCommand.
References actionstring, GhidraCommand::loadParameters(), printstring, ArchitectureGhidra::readStringStream(), and GhidraCommand::sin.
rawAction()
void SetAction::rawAction (void) virtual
Perform the action of the command.
Configuration is assumed to have happened, and this object can immediately begin examining and manipulating data under the active Architecture object to perform the command.
Implements GhidraCommand.
References actionstring, Architecture::allacts, Architecture::flowoptions, GhidraCommand::ghidra, printstring, FlowInfo::record_jumploads, res, ActionDatabase::setCurrent(), ArchitectureGhidra::setSendCCode(), ArchitectureGhidra::setSendParamMeasures(), and ArchitectureGhidra::setSendSyntaxTree().
sendResult()
void SetAction::sendResult (void) private virtual
Send results of the command (if any) back to the Ghidra client.
This method sends any warnings accumulated during execution back, but it can be overloaded to send back any kind of information. Individual records are sent using the message protocol.
Reimplemented from GhidraCommand.
References res, GhidraCommand::sendResult(), GhidraCommand::sout, and ArchitectureGhidra::writeStringStream().
The documentation for this class was generated from the following files:
ghidra_process.hh
ghidra_process.cc