decompiler: ActionRestartGroup Class Reference
ActionRestartGroup Class Reference
Action which checks if restart (sub)actions have been generated and restarts itself.
#include <action.hh>
Public Member Functions
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
Public Member Functions inherited from ActionGroup
virtual ~ActionGroup (void)
Destructor.
void addAction (Action *ac)
Add an Action to the group.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
Private Attributes
int4 maxrestarts
Maximum number of restarts allowed.
int4 curstart
Current restart iteration.
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
Protected Attributes inherited from ActionGroup
vector< Action * > list
List of actions to perform in the group.
vector< Action * >::iterator state
Current action being applied.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Action which checks if restart (sub)actions have been generated and restarts itself.
Actions or Rules can request a restart on a Funcdata object by calling setRestartPending(true) on it. This action checks for the request then resets and reruns the group of Actions as appropriate.
Member Function Documentation
apply()
int4 ActionRestartGroup::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Reimplemented from ActionGroup.
References ActionGroup::apply(), curstart, Funcdata::hasRestartPending(), ActionGroup::list, maxrestarts, Action::status, Action::status_start, and Funcdata::warningHeader().
clone()
Action * ActionRestartGroup::clone (const ActionGroupList & grouplist) const virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Reimplemented from ActionGroup.
References ActionGroup::addAction(), Action::clone(), Action::flags, ActionGroup::list, and maxrestarts.
reset()
void ActionRestartGroup::reset (Funcdata & data) virtual
Reset the Action for a new function.
Parameters
data is the new function this Action may affect
Reimplemented from ActionGroup.
References curstart, and ActionGroup::reset().
The documentation for this class was generated from the following files:
action.hh
action.cc