decompiler: RuleCollectTerms Class Reference
RuleCollectTerms Class Reference
Collect terms in a sum: V * c + V * d => V * (c + d)
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Private Member Functions
static Varnode * getMultCoeff (Varnode *vn, uintb &coef)
Get the multiplicative coefficient.
static int4 doDistribute (Funcdata &data, PcodeOp *op)
Distribute coefficient within one term.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Collect terms in a sum: V * c + V * d => V * (c + d)
Member Function Documentation
applyOp()
int4 RuleCollectTerms::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References calc_mask(), TermOrder::collect(), CPUI_INT_ADD, CPUI_INT_MULT, doDistribute(), getMultCoeff(), Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::opInsertBefore(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and TermOrder::sortTerms().
clone()
virtual Rule* RuleCollectTerms::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
doDistribute()
int4 RuleCollectTerms::doDistribute (Funcdata & data, PcodeOp * op) static private
Distribute coefficient within one term.
If a term has a multiplicative coefficient, but the underlying term is still additive, in some situations we may need to distribute the coefficient before simplifying further. The given PcodeOp is a INT_MULT where the second input is a constant. We also know the first input is formed with INT_ADD. Distribute the coefficient to the INT_ADD inputs.
Parameters
data is the function being analyzed
op is the given PcodeOp
Returns
1 if the action was performed
References CPUI_INT_ADD, CPUI_INT_MULT, Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::opInsertBefore(), Funcdata::opSetInput(), and Funcdata::opSetOpcode().
Referenced by applyOp().
getMultCoeff()
Varnode * RuleCollectTerms::getMultCoeff (Varnode * vn, uintb & coef) static private
Get the multiplicative coefficient.
Given a Varnode term in the expression, check if the last operation producing it is to multiply by a constant. If so pass back the constant coefficient and return the underlying Varnode. Otherwise pass back the constant 1, and return the original Varnode
Parameters
vn is the given Varnode
coef is the reference for passing back the coefficient
Returns
the underlying Varnode of the term
References CPUI_INT_MULT.
Referenced by applyOp().
getOpList()
void RuleCollectTerms::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_ADD.
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc