decompiler: FuncProto Class Reference
FuncProto Class Reference
A function prototype.
#include <fspec.hh>
Public Member Functions
FuncProto (void)
Constructor.
~FuncProto (void)
Destructor.
void copy (const FuncProto &op2)
Copy another function prototype.
void copyFlowEffects (const FuncProto &op2)
Copy properties that affect data-flow.
void getPieces (PrototypePieces &pieces) const
Get the raw pieces of the prototype.
void setPieces (const PrototypePieces &pieces)
Set this prototype based on raw pieces.
void setScope (Scope *s, const Address &startpoint)
Set a backing symbol Scope for this.
void setInternal (ProtoModel *m, Datatype *vt)
Set internal backing storage for this.
void setModel (ProtoModel *m)
Set the prototype model for this.
bool isInputLocked (void) const
Are input data-types locked.
void setInputLock (bool val)
Toggle the data-type lock on input parameters.
void setOutputLock (bool val)
Toggle the data-type lock on the return value.
void setModelLock (bool val)
Toggle the lock on the prototype model for this.
void setInline (bool val)
Toggle the in-line setting for functions with this prototype.
int4 getInjectId (void) const
Get the injection id associated with this.
int4 getReturnBytesConsumed (void) const
Get an estimate of the number of bytes consumed by callers of this prototype.
bool setReturnBytesConsumed (int4 val)
Set the number of bytes consumed by callers of this.
bool isNoReturn (void) const
Does a function with this prototype never return.
void setNoReturn (bool val)
Toggle the no-return setting for functions with this prototype.
bool hasThisPointer (void) const
Is this a prototype for a class method, taking a this pointer.
void setThisPointer (bool val)
Toggle the this-call setting for this prototype.
bool isConstructor (void) const
Is this prototype for a class constructor method.
void setConstructor (bool val)
Toggle whether this prototype is a constructor method.
bool isDestructor (void) const
Is this prototype for a class destructor method.
void setDestructor (bool val)
Toggle whether this prototype is a destructor method.
bool hasInputErrors (void) const
Has this prototype been marked as having an incorrect input parameter descriptions.
bool hasOutputErrors (void) const
Has this prototype been marked as having an incorrect return value description.
void setInputErrors (bool val)
Toggle the input error setting for this prototype.
void setOutputErrors (bool val)
Toggle the output error setting for this prototype.
void resolveExtraPop (void)
Assuming this prototype is locked, calculate the extrapop.
void clearUnlockedInput (void)
Clear input parameters that have not been locked.
void clearUnlockedOutput (void)
Clear the return value if it has not been locked.
void clearInput (void)
Clear all input parameters regardless of lock.
void cancelInjectId (void)
Turn-off any in-lining for this function.
void resolveModel (ParamActive *active)
If this has a merged model, pick the most likely model (from the merged set)
void deriveInputMap (ParamActive *active) const
Given a list of input trials, derive the most likely inputs for this prototype.
void deriveOutputMap (ParamActive *active) const
Given a list of output trials, derive the most likely return value for this prototype.
bool checkInputJoin (const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz) const
Check if the given two input storage locations can represent a single logical parameter.
bool checkInputSplit (const Address &loc, int4 size, int4 splitpoint) const
Check if it makes sense to split a single storage location into two input parameters.
void updateInputTypes (const vector< Varnode * > &triallist, ParamActive *activeinput)
Update input parameters based on Varnode trials.
void updateInputNoTypes (const vector< Varnode * > &triallist, ParamActive *activeinput, TypeFactory *factory)
Update input parameters based on Varnode trials, but do not store the data-type.
void updateOutputTypes (const vector< Varnode * > &triallist)
Update the return value based on Varnode trials.
void updateOutputNoTypes (const vector< Varnode * > &triallist, TypeFactory *factory)
Update the return value based on Varnode trials, but don't store the data-type.
void updateAllTypes (const vector< string > &namelist, const vector< Datatype * > &typelist, bool dtdtdt)
Set this entire function prototype based on a list of names and data-types.
uint4 hasEffect (const Address &addr, int4 size) const
Calculate the effect this has an a given storage location.
vector< EffectRecord >::const_iterator effectBegin (void) const
Get iterator to front of EffectRecord list.
vector< EffectRecord >::const_iterator effectEnd (void) const
Get iterator to end of EffectRecord list.
int4 numLikelyTrash (void) const
Get the number of likely-trash locations.
const VarnodeData & getLikelyTrash (int4 i) const
Get the i-th likely-trash location.
int4 characterizeAsInputParam (const Address &addr, int4 size) const
Decide whether a given storage location could be, or could hold, an input parameter.
bool possibleInputParam (const Address &addr, int4 size) const
Decide whether a given storage location could be an input parameter.
bool possibleOutputParam (const Address &addr, int4 size) const
Decide whether a given storage location could be a return value.
int4 getMaxInputDelay (void) const
Return the maximum heritage delay across all possible input parameters.
int4 getMaxOutputDelay (void) const
Return the maximum heritage delay across all possible return values.
bool unjustifiedInputParam (const Address &addr, int4 size, VarnodeData &res) const
Check if the given storage location looks like an unjustified input parameter.
OpCode assumedInputExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing input parameter for the given storage.
OpCode assumedOutputExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing return value location for the given storage.
bool getBiggestContainedInputParam (const Address &loc, int4 size, VarnodeData &res) const
Pass-back the biggest potential input parameter contained within the given range.
bool isCompatible (const FuncProto &op2) const
Decide if this can be safely restricted to match another prototype.
void printRaw (const string &funcname, ostream &s) const
Print this prototype as a single line of text.
uint4 getComparableFlags (void) const
Get the comparable properties of this prototype.
void saveXml (ostream &s) const
Save this to an XML stream as a <prototype> tag.
void restoreXml (const Element *el, Architecture *glb)
Restore this from an XML stream.
Protected Member Functions
void paramShift (int4 paramshift)
Add parameters to the front of the input parameter list.
void setParamshiftApplied (bool val)
Toggle whether a parameter shift has been applied.
Private Types
enum {
dotdotdot = 1, voidinputlock = 2, modellock = 4, is_inline = 8,
no_return = 16, paramshift_applied = 32, error_inputparam = 64, error_outputparam = 128,
custom_storage = 256, unknown_model = 512, is_constructor = 0x400, is_destructor = 0x800,
has_thisptr = 0x1000, is_override = 0x2000
}
Private Attributes
ProtoModel * model
Model of for this prototype.
ProtoStore * store
Storage interface for parameters.
int4 extrapop
Extra bytes popped from stack.
uint4 flags
Boolean properties of the function prototype.
vector< EffectRecord > effectlist
Side-effects associated with non-parameter storage locations.
vector< VarnodeData > likelytrash
Locations that may contain trash values.
int4 injectid
(If non-negative) id of p-code snippet that should replace this function
int4 returnBytesConsumed
Number of bytes of return value that are consumed by callers (0 = all bytes)
Detailed Description
A function prototype.
A description of the parameters and return value for a specific function. Parameter descriptions include both source code features like name and data-type but also give the storage location. Storage follows a specific parameter passing convention (ProtoModel), although individual parameters may be customized. The prototype describes numerous properties related to calling the specific function:
Side-effects on non-parameter storage locations (like save registers)
P-code injection associated with the function (uponentry, uponreturn, callfixup)
Additional bytes (extrapop) popped from the stack by the function
Method flags (thiscall, is_constructor, is_destructor)
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
dotdotdot
Set if this prototype takes variable arguments (varargs)
voidinputlock
Set if this prototype takes no inputs and is locked.
modellock
Set if the PrototypeModel is locked for this prototype.
is_inline
Should this be inlined (within calling function) by decompiler.
no_return
Function does not return.
paramshift_applied
paramshift parameters have been added and removed
error_inputparam
Set if the input parameters are not properly represented.
error_outputparam
Set if the return value(s) are not properly represented.
custom_storage
Parameter storage is custom (not derived from ProtoModel)
unknown_model
Set if the PrototypeModel isn't known.
is_constructor
Function is an (object-oriented) constructor.
is_destructor
Function is an (object-oriented) destructor.
has_thisptr
Function is a method with a 'this' pointer as an argument.
is_override
Set if this prototype is created to override a single call site.
Member Function Documentation
assumedInputExtension()
OpCode FuncProto::assumedInputExtension (const Address & addr, int4 size, VarnodeData & res) const inline
Get the type of extension and containing input parameter for the given storage.
If the given storage is properly contained within a normal parameter and the model typically extends a small value into the full container, pass back the full container and the type of extension.
Parameters
addr is the starting address of the given storage
size is the number of bytes in the given storage
res is the parameter storage to pass back
Returns
the extension operator (INT_ZEXT INT_SEXT) or INT_COPY if there is no extension. INT_PIECE indicates the extension is determined by the specific prototype.
References ProtoModel::assumedInputExtension(), and model.
assumedOutputExtension()
OpCode FuncProto::assumedOutputExtension (const Address & addr, int4 size, VarnodeData & res) const inline
Get the type of extension and containing return value location for the given storage.
If the given storage is properly contained within a normal return value location and the model typically extends a small value into the full container, pass back the full container and the type of extension.
Parameters
addr is the starting address of the given storage
size is the number of bytes in the given storage
res is the parameter storage to pass back
Returns
the extension operator (INT_ZEXT INT_SEXT) or INT_COPY if there is no extension. INT_PIECE indicates the extension is determined by the specific prototype.
References ProtoModel::assumedOutputExtension(), and model.
Referenced by FuncCallSpecs::commitNewOutputs(), and ActionFuncLink::funcLinkOutput().
characterizeAsInputParam()
int4 FuncProto::characterizeAsInputParam (const Address & addr, int4 size) const
Decide whether a given storage location could be, or could hold, an input parameter.
If the input is locked, check if the location overlaps one of the current parameters. Otherwise, check if the location overlaps an entry in the prototype model. Return:
0 if the location neither contains or is contained by a parameter storage location
1 if the location is contained by a parameter storage location
2 if the location contains a parameter storage location
Parameters
addr is the starting address of the given storage location
size is the number of bytes in the storage
Returns
the characterization code
References ProtoModel::characterizeAsInputParam(), Address::containedBy(), flags, ProtoParameter::getAddress(), ProtoParameter::getSize(), ProtoParameter::isTypeLocked(), Address::justifiedContain(), model, and voidinputlock.
Referenced by Heritage::guardCalls().
checkInputJoin()
bool FuncProto::checkInputJoin (const Address & hiaddr, int4 hisz, const Address & loaddr, int4 losz) const inline
Check if the given two input storage locations can represent a single logical parameter.
For this prototype, do the two (hi/lo) locations represent consecutive input parameter locations that can be replaced by a single logical parameter.
Parameters
hiaddr is the address of the most significant part of the value
hisz is the size of the most significant part in bytes
loaddr is the address of the least significant part of the value
losz is the size of the least significant part in bytes
Returns
true if the two pieces can be joined
References ProtoModel::checkInputJoin(), and model.
Referenced by FuncCallSpecs::checkInputJoin().
checkInputSplit()
bool FuncProto::checkInputSplit (const Address & loc, int4 size, int4 splitpoint) const inline
Check if it makes sense to split a single storage location into two input parameters.
A storage location and split point is provided, implying two new storage locations. Does this prototype allow these locations to be considered separate parameters.
Parameters
loc is the starting address of provided storage location
size is the size of the location in bytes
splitpoint is the number of bytes to consider in the first (in address order) piece
Returns
true if the storage location can be split
References ProtoModel::checkInputSplit(), and model.
Referenced by ActionParamDouble::apply().
copy()
void FuncProto::copy (const FuncProto & op2)
Copy another function prototype.
Parameters
op2 is the other function prototype to copy into this
References ProtoStore::clone(), effectlist, extrapop, flags, injectid, likelytrash, model, and store.
Referenced by ActionDefaultParams::apply(), Override::applyPrototype(), FuncCallSpecs::clone(), FuncCallSpecs::forceSet(), and FuncCallSpecs::lateRestriction().
deriveInputMap()
void FuncProto::deriveInputMap (ParamActive * active) const inline
Given a list of input trials, derive the most likely inputs for this prototype.
Trials are sorted and marked as used or not.
Parameters
active is the collection of Varnode input trials
References ProtoModel::deriveInputMap(), and model.
Referenced by ActionActiveParam::apply().
deriveOutputMap()
void FuncProto::deriveOutputMap (ParamActive * active) const inline
Given a list of output trials, derive the most likely return value for this prototype.
One trial (at most) is marked used and moved to the front of the list
Parameters
active is the collection of output trials
References ProtoModel::deriveOutputMap(), and model.
Referenced by ActionActiveReturn::apply().
getBiggestContainedInputParam()
bool FuncProto::getBiggestContainedInputParam (const Address & loc, int4 size, VarnodeData & res) const
Pass-back the biggest potential input parameter contained within the given range.
Pass-back the biggest input parameter contained within the given range.
Parameters
loc is the starting address of the given range
size is the number of bytes in the range
res will hold the parameter storage description being passed back
Returns
true if there is at least one parameter contained in the range
References Address::containedBy(), flags, ProtoParameter::getAddress(), ProtoModel::getBiggestContainedInputParam(), Address::getOffset(), ProtoParameter::getSize(), Address::getSpace(), ProtoParameter::isTypeLocked(), model, VarnodeData::offset, VarnodeData::size, VarnodeData::space, and voidinputlock.
Referenced by Heritage::guardCallOverlappingInput().
getComparableFlags()
uint4 FuncProto::getComparableFlags (void) const inline
Get the comparable properties of this prototype.
Get properties not including locking, error, and inlining flags.
Returns
the active set of flags for this prototype
References dotdotdot, flags, has_thisptr, is_constructor, and is_destructor.
getInjectId()
int4 FuncProto::getInjectId (void) const inline
Get the injection id associated with this.
A non-negative id indicates a call-fixup is used to in-line function's with this prototype.
Returns
the id value corresponding to the specific call-fixup or -1 if there is no call-fixup
References injectid.
Referenced by FlowInfo::injectPcode(), and FlowInfo::injectSubFunction().
getLikelyTrash()
const VarnodeData & FuncProto::getLikelyTrash (int4 i) const
Get the i-th likely-trash location.
Parameters
i is the index of the storage location
Returns
the storage location which may hold a trash value
References likelytrash, and model.
getMaxInputDelay()
int4 FuncProto::getMaxInputDelay (void) const inline
Return the maximum heritage delay across all possible input parameters.
Depending on the address space, data-flow for a parameter may not be available until extra transform passes have completed. This method returns the number of passes that must occur before we can guarantee that all parameters have data-flow info.
Returns
the maximum number of passes across all input parameters in this prototype
References ProtoModel::getMaxInputDelay(), and model.
Referenced by FuncCallSpecs::initActiveInput().
getMaxOutputDelay()
int4 FuncProto::getMaxOutputDelay (void) const inline
Return the maximum heritage delay across all possible return values.
Depending on the address space, data-flow for a parameter may not be available until extra transform passes have completed. This method returns the number of passes that must occur before we can guarantee that any return value has data-flow info.
Returns
the maximum number of passes across all output parameters in this prototype
References ProtoModel::getMaxOutputDelay(), and model.
Referenced by Funcdata::initActiveOutput().
getPieces()
void FuncProto::getPieces (PrototypePieces & pieces) const
Get the raw pieces of the prototype.
Copy out the raw pieces of this prototype as stand-alone objects, includings model, names, and data-types
Parameters
pieces will hold the raw pieces
References PrototypePieces::dotdotdot, ProtoStore::getInput(), ProtoParameter::getName(), ProtoStore::getNumInputs(), ProtoStore::getOutput(), ProtoParameter::getType(), PrototypePieces::innames, PrototypePieces::intypes, PrototypePieces::model, model, PrototypePieces::outtype, and store.
getReturnBytesConsumed()
int4 FuncProto::getReturnBytesConsumed (void) const inline
Get an estimate of the number of bytes consumed by callers of this prototype.
A value of 0 means all possible bytes of the storage location are consumed.
Returns
the number of bytes or 0
References returnBytesConsumed.
hasEffect()
uint4 FuncProto::hasEffect (const Address & addr, int4 size) const
Calculate the effect this has an a given storage location.
For a storage location that is active before and after a call to a function with this prototype, we determine the type of side-effect the function will have on the storage.
Parameters
addr is the starting address of the storage location
size is the number of bytes in the storage
Returns
the type of side-effect: EffectRecord::unaffected, EffectRecord::killedbycall, etc.
References effectlist, ProtoModel::hasEffect(), ProtoModel::lookupEffect(), and model.
Referenced by FuncCallSpecs::hasEffectTranslate(), and Funcdata::setInputVarnode().
isCompatible()
bool FuncProto::isCompatible (const FuncProto & op2) const
Decide if this can be safely restricted to match another prototype.
Do this and another given function prototype share enough of their model, that if we restrict this to the other prototype, we know we won't miss data-flow.
Parameters
op2 is the other restricting prototype
Returns
true if the two prototypes are compatible enough to restrict
References effectlist, extrapop, ProtoModel::extrapop_unknown, flags, ProtoStore::getOutput(), injectid, is_inline, isInputLocked(), likelytrash, model, no_return, and store.
Referenced by FuncCallSpecs::lateRestriction().
numLikelyTrash()
int4 FuncProto::numLikelyTrash (void) const
Get the number of likely-trash locations.
Returns
the number of individual storage locations
References likelytrash, and model.
paramShift()
void FuncProto::paramShift (int4 paramshift) protected
Add parameters to the front of the input parameter list.
Prepend the indicated number of input parameters to this. The new parameters have a data-type of xunknown4. If they were originally locked, the existing parameters are preserved.
Parameters
paramshift is the number of parameters to add (must be >0)
References ProtoModel::assignParameterStorage(), flags, TypeFactory::getBase(), ProtoParameter::getName(), ProtoParameter::getType(), TypeFactory::getTypeVoid(), Varnode::hiddenretparm, isInputLocked(), model, ProtoStore::setInput(), setInputLock(), ProtoStore::setOutput(), store, and TYPE_UNKNOWN.
Referenced by FuncCallSpecs::paramshiftModifyStart().
possibleInputParam()
bool FuncProto::possibleInputParam (const Address & addr, int4 size) const
Decide whether a given storage location could be an input parameter.
If the input is locked, check if the location matches one of the current parameters. Otherwise, check if the location could be a parameter based on the prototype model.
Parameters
addr is the starting address of the given storage location
size is the number of bytes in the storage
Returns
false if the location is definitely not an input parameter
References flags, ProtoParameter::getAddress(), ProtoParameter::getSize(), ProtoParameter::isTypeLocked(), Address::justifiedContain(), model, ProtoModel::possibleInputParam(), and voidinputlock.
possibleOutputParam()
bool FuncProto::possibleOutputParam (const Address & addr, int4 size) const
Decide whether a given storage location could be a return value.
If the output is locked, check if the location matches the current return value. Otherwise, check if the location could be a return value based on the prototype model.
Parameters
addr is the starting address of the given storage location
size is the number of bytes in the storage
Returns
false if the location is definitely not the return value
References ProtoParameter::getAddress(), ProtoParameter::getSize(), ProtoParameter::getType(), Address::justifiedContain(), model, ProtoModel::possibleOutputParam(), and TYPE_VOID.
Referenced by Heritage::guardCalls().
printRaw()
void FuncProto::printRaw (const string & funcname, ostream & s) const
Print this prototype as a single line of text.
Parameters
funcname is an identifier of the function using this prototype
s is the output stream
References extrapop, and model.
Referenced by FspecSpace::printRaw().
resolveExtraPop()
void FuncProto::resolveExtraPop (void)
Assuming this prototype is locked, calculate the extrapop.
If extrapop is unknown and this prototype is locked, try to directly calculate what the extrapop should be. This is really only designed to work with 32-bit x86 binaries.
References ProtoParameter::getAddress(), Address::getOffset(), ProtoParameter::getSize(), Address::getSpace(), AddrSpace::getType(), IPTR_SPACEBASE, and isInputLocked().
Referenced by restoreXml().
resolveModel()
void FuncProto::resolveModel (ParamActive * active)
If this has a merged model, pick the most likely model (from the merged set)
The given parameter trials are used to pick from among the merged ProtoModels and this prototype is changed (specialized) to the pick
Parameters
active is the set of parameter trials to evaluate with
References model, ProtoModelMerged::selectModel(), and setModel().
Referenced by ActionActiveParam::apply().
restoreXml()
void FuncProto::restoreXml (const Element * el, Architecture * glb)
Restore this from an XML stream.
The backing store for the parameters must already be established using either setStore() or setInternal().
Parameters
el is the <prototype> XML element
glb is the Architecture owning the prototype
References ParameterPieces::addr, InjectPayload::CALLFIXUP_TYPE, custom_storage, Architecture::defaultfp, dotdotdot, effectlist, extrapop, ProtoModel::extrapop_unknown, ParameterPieces::flags, flags, ProtoParameter::getAddress(), Element::getAttributeValue(), Architecture::getModel(), ProtoStore::getOutput(), PcodeInjectLibrary::getPayloadId(), ProtoParameter::getType(), has_thisptr, injectid, is_constructor, is_destructor, is_inline, isInputLocked(), Address::isInvalid(), EffectRecord::killedbycall, likelytrash, model, modellock, no_return, Architecture::pcodeinjectlib, resolveExtraPop(), Address::restoreXml(), ProtoStore::restoreXml(), TypeFactory::restoreXmlType(), EffectRecord::return_address, setModel(), ProtoStore::setOutput(), ProtoParameter::setTypeLock(), store, ParameterPieces::type, TYPE_VOID, Architecture::types, EffectRecord::unaffected, unknown_model, voidinputlock, and xml_readbool().
Referenced by Override::restoreXml(), and Funcdata::restoreXml().
saveXml()
void FuncProto::saveXml (ostream & s) const
Save this to an XML stream as a <prototype> tag.
Save everything under the control of this prototype, which may not include input parameters, as these are typically controlled by the function's symbol table scope.
Parameters
s is the output stream
References a_v(), a_v_b(), a_v_i(), effectlist, extrapop, ProtoModel::extrapop_unknown, flags, ProtoParameter::getAddress(), PcodeInjectLibrary::getCallFixupName(), ProtoStore::getOutput(), ProtoParameter::getSize(), ProtoParameter::getType(), hasThisPointer(), injectid, isConstructor(), isDestructor(), isNoReturn(), ProtoParameter::isTypeLocked(), EffectRecord::killedbycall, likelytrash, model, VarnodeData::offset, Architecture::pcodeinjectlib, EffectRecord::return_address, Address::saveXml(), Datatype::saveXml(), ProtoStore::saveXml(), AddrSpace::saveXmlAttributes(), VarnodeData::size, VarnodeData::space, store, EffectRecord::unaffected, and voidinputlock.
Referenced by Funcdata::saveXml().
setConstructor()
void FuncProto::setConstructor (bool val) inline
Toggle whether this prototype is a constructor method.
Parameters
val is true if this is a constructor, false otherwise
References flags, and is_constructor.
setDestructor()
void FuncProto::setDestructor (bool val) inline
Toggle whether this prototype is a destructor method.
Parameters
val is true if this is a destructor
References flags, and is_destructor.
setInline()
void FuncProto::setInline (bool val) inline
Toggle the in-line setting for functions with this prototype.
In-lining can be based on a call-fixup, or the full body of the function can be in-lined.
Parameters
val is true if in-lining should be performed.
References flags, and is_inline.
setInputErrors()
void FuncProto::setInputErrors (bool val) inline
Toggle the input error setting for this prototype.
Parameters
val is true if input parameters should be marked as in error
References error_inputparam, and flags.
Referenced by FuncCallSpecs::forceSet().
setInputLock()
void FuncProto::setInputLock (bool val)
Toggle the data-type lock on input parameters.
The lock on the data-type of input parameters is set as specified. A true value indicates that future analysis will not change the number of input parameters or their data-type. Zero parameters or void can be locked.
Parameters
val is true to indicate a lock, false for unlocked
References flags, modellock, ProtoParameter::setTypeLock(), and voidinputlock.
Referenced by FuncCallSpecs::forceSet(), paramShift(), and setPieces().
setInternal()
void FuncProto::setInternal (ProtoModel * m, Datatype * vt)
Set internal backing storage for this.
A prototype model is set, and any parameters added to this during analysis will be backed internally.
Parameters
m is the prototype model to set
vt is the default void data-type to use if the return-value remains unassigned
References model, setModel(), and store.
Referenced by ActionDefaultParams::apply(), and Override::restoreXml().
setModel()
void FuncProto::setModel (ProtoModel * m)
Set the prototype model for this.
Establish a specific prototype model for this function prototype. Some basic properties are inherited from the model, otherwise parameters are unchanged.
Parameters
m is the new prototype model to set
References extrapop, ProtoModel::extrapop_unknown, flags, has_thisptr, is_constructor, model, and unknown_model.
Referenced by ActionDefaultParams::apply(), resolveModel(), restoreXml(), setInternal(), setPieces(), setScope(), and updateAllTypes().
setModelLock()
void FuncProto::setModelLock (bool val) inline
Toggle the lock on the prototype model for this.
The prototype model can be locked while still leaving parameters unlocked. Parameter recovery will follow the rules of the locked model.
Parameters
val is true to indicate a lock, false for unlocked
References flags, and modellock.
Referenced by ActionNormalizeSetup::apply(), and setPieces().
setNoReturn()
void FuncProto::setNoReturn (bool val) inline
Toggle the no-return setting for functions with this prototype.
Parameters
val is true to treat the function as never returning
References flags, and no_return.
setOutputErrors()
void FuncProto::setOutputErrors (bool val) inline
Toggle the output error setting for this prototype.
Parameters
val is true if return value should be marked as in error
References error_outputparam, and flags.
Referenced by FuncCallSpecs::forceSet().
setOutputLock()
void FuncProto::setOutputLock (bool val)
Toggle the data-type lock on the return value.
The lock of the data-type of the return value is set as specified. A true value indicates that future analysis will not change the presence of or the data-type of the return value. A void return value can be locked.
Parameters
val is true to indicate a lock, false for unlocked
References flags, ProtoStore::getOutput(), modellock, ProtoParameter::setTypeLock(), and store.
Referenced by ActionNormalizeSetup::apply(), and setPieces().
setPieces()
void FuncProto::setPieces (const PrototypePieces & pieces)
Set this prototype based on raw pieces.
The full function prototype is (re)set from a model, names, and data-types The new input and output parameters are both assumed to be locked.
Parameters
pieces is the raw collection of names and data-types
References PrototypePieces::dotdotdot, PrototypePieces::innames, PrototypePieces::intypes, PrototypePieces::model, PrototypePieces::outtype, setInputLock(), setModel(), setModelLock(), setOutputLock(), and updateAllTypes().
setReturnBytesConsumed()
bool FuncProto::setReturnBytesConsumed (int4 val)
Set the number of bytes consumed by callers of this.
This value can be used as a hint as to how much of the return value is important and is used to inform the dead code consume algorithm.
Parameters
val is the estimated number of bytes or 0
Returns
true if the value was changed
References returnBytesConsumed.
setScope()
void FuncProto::setScope (Scope * s, const Address & startpoint)
Set a backing symbol Scope for this.
Input parameters are set based on an existing function Scope and if there is no prototype model the default model is set. Parameters that are added to this during analysis will automatically be reflected in the symbol table. This should only be called during initialization of this prototype.
Parameters
s is the Scope to set
startpoint is a usepoint to associate with the parameters
References model, setModel(), and store.
Referenced by Funcdata::Funcdata(), and Funcdata::restoreXml().
setThisPointer()
void FuncProto::setThisPointer (bool val) inline
Toggle the this-call setting for this prototype.
Parameters
val is true if this prototype uses a this pointer
References flags, and has_thisptr.
unjustifiedInputParam()
bool FuncProto::unjustifiedInputParam (const Address & addr, int4 size, VarnodeData & res) const
Check if the given storage location looks like an unjustified input parameter.
The storage for a value may be contained in a normal parameter location but be unjustified within that container, i.e. the least significant bytes are not being used. If this is the case, pass back the full parameter location and return true. If the input is locked, checking is againt the set parameters, otherwise the check is against the prototype model.
Parameters
addr is the starting address of the given storage
size is the number of bytes in the given storage
res is the full parameter storage to pass back
Returns
true if the given storage is unjustified within its parameter container
References flags, ProtoParameter::getAddress(), Address::getOffset(), ProtoParameter::getSize(), Address::getSpace(), ProtoParameter::isTypeLocked(), Address::justifiedContain(), model, VarnodeData::offset, VarnodeData::size, VarnodeData::space, ProtoModel::unjustifiedInputParam(), and voidinputlock.
Referenced by ActionUnjustifiedParams::apply().
updateAllTypes()
void FuncProto::updateAllTypes (const vector< string > & namelist, const vector< Datatype * > & typelist, bool dtdtdt)
Set this entire function prototype based on a list of names and data-types.
Prototype information is provided as separate lists of names and data-types, where the first entry corresponds to the output parameter (return value) and the remaining entries correspond to input parameters. Storage locations and hidden return parameters are calculated, creating a complete function protototype. Existing locks are overridden.
Parameters
namelist is the list of parameter names
typelist is the list of data-types
dtdtdt is true if the new prototype accepts variable argument lists
References ProtoModel::assignParameterStorage(), ProtoStore::clearAllInputs(), ProtoStore::clearOutput(), error_inputparam, flags, Varnode::hiddenretparm, model, ProtoStore::setInput(), setModel(), ProtoStore::setOutput(), store, and voidinputlock.
Referenced by setPieces().
updateInputNoTypes()
void FuncProto::updateInputNoTypes (const vector< Varnode * > & triallist, ParamActive * activeinput, TypeFactory * factory)
Update input parameters based on Varnode trials, but do not store the data-type.
This is accomplished in the same way as if there were data-types but instead of pulling a data-type from the Varnode, only the size is used. Undefined data-types are pulled from the given TypeFactory
Parameters
triallist is the list of Varnodes
activeinput is the trial container
factory is the given TypeFactory
References ParameterPieces::addr, ProtoStore::clearAllInputs(), ParameterPieces::flags, TypeFactory::getBase(), isInputLocked(), ProtoStore::setInput(), store, ParameterPieces::type, and TYPE_UNKNOWN.
updateInputTypes()
void FuncProto::updateInputTypes (const vector< Varnode * > & triallist, ParamActive * activeinput)
Update input parameters based on Varnode trials.
If the input parameters are locked, don't do anything. Otherwise, given a list of Varnodes and their associated trial information, create an input parameter for each trial in order, grabbing data-type information from the Varnode. Any old input parameters are cleared.
Parameters
triallist is the list of Varnodes
activeinput is the trial container
References ParameterPieces::addr, ProtoStore::clearAllInputs(), ParameterPieces::flags, Varnode::getHigh(), isInputLocked(), ProtoStore::setInput(), store, and ParameterPieces::type.
updateOutputNoTypes()
void FuncProto::updateOutputNoTypes (const vector< Varnode * > & triallist, TypeFactory * factory)
Update the return value based on Varnode trials, but don't store the data-type.
If the output parameter is locked, don't do anything. Otherwise, given a list of (at most 1) Varnode, create a return value, grabbing size information from the Varnode. An undefined data-type is created from the given TypeFactory. Any old return value is removed.
Parameters
triallist is the list of Varnodes
factory is the given TypeFactory
References ParameterPieces::addr, ProtoStore::clearOutput(), ParameterPieces::flags, TypeFactory::getBase(), ProtoStore::setOutput(), store, ParameterPieces::type, and TYPE_UNKNOWN.
updateOutputTypes()
void FuncProto::updateOutputTypes (const vector< Varnode * > & triallist)
Update the return value based on Varnode trials.
If the output parameter is locked, don't do anything. Otherwise, given a list of (at most 1) Varnode, create a return value, grabbing data-type information from the Varnode. Any old return value is removed.
Parameters
triallist is the list of Varnodes
References ParameterPieces::addr, ProtoStore::clearOutput(), ParameterPieces::flags, ProtoParameter::getAddress(), ProtoParameter::getSize(), ProtoParameter::isSizeTypeLocked(), ProtoParameter::isTypeLocked(), ProtoParameter::overrideSizeLockType(), ProtoStore::setOutput(), store, and ParameterPieces::type.
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc