decompiler: Range Class Reference
Range Class Reference
A contiguous range of bytes in some address space.
#include <address.hh>
Public Member Functions
Range (AddrSpace *s, uintb f, uintb l)
Construct a Range from offsets.
Address getLastAddrOpen (const AddrSpaceManager *manage) const
Get address of first byte after this.
bool contains (const Address &addr) const
Determine if the address is in this Range.
bool operator< (const Range &op2) const
Sorting operator for Ranges.
void printBounds (ostream &s) const
Print this Range to a stream.
void saveXml (ostream &s) const
Save this Range to an XML stream.
void restoreXml (const Element *el, const AddrSpaceManager *manage)
Restore this from XML stream.
Private Attributes
AddrSpace * spc
Space containing range.
uintb first
Offset of first byte in this Range.
uintb last
Offset of last byte in this Range.
Friends
class RangeList
Detailed Description
A contiguous range of bytes in some address space.
Constructor & Destructor Documentation
Range()
Range::Range (AddrSpace * s, uintb f, uintb l) inline
Construct a Range from offsets.
Offsets must expressed in bytes as opposed to addressable words
Parameters
s is the address space containing the range
f is the offset of the first byte in the range
l is the offset of the last byte in the range
References first, last, and spc.
Member Function Documentation
contains()
bool Range::contains (const Address & addr) const inline
Determine if the address is in this Range.
Parameters
addr is the Address to test for containment
Returns
true if addr is in this Range
References first, Address::getOffset(), Address::getSpace(), last, and spc.
getLastAddrOpen()
Address Range::getLastAddrOpen (const AddrSpaceManager * manage) const
Get address of first byte after this.
Get the last address +1, updating the space, or returning the extremal address if necessary
Parameters
manage is used to fetch the next address space
References AddrSpace::getHighest(), AddrSpaceManager::getNextSpaceInOrder(), last, Address::m_maximal, and spc.
Referenced by ContextInternal::restoreFromSpec(), and Database::setPropertyRange().
operator<()
bool Range::operator< (const Range & op2) const inline
Sorting operator for Ranges.
Compare based on address space, then the starting offset
Parameters
op2 is the Range to compare with this
Returns
true if this comes before op2
References first, AddrSpace::getIndex(), and spc.
printBounds()
void Range::printBounds (ostream & s) const
Print this Range to a stream.
Output a description of this Range like: ram: 7f-9c
Parameters
s is the output stream
References first, AddrSpace::getName(), last, and spc.
restoreXml()
void Range::restoreXml (const Element * el, const AddrSpaceManager * manage)
Restore this from XML stream.
Reconstruct this object from an XML <range> element
Parameters
el is the XML element
manage is the space manage for recovering AddrSpace objects
References first, Element::getAttributeValue(), AddrSpaceManager::getDefaultCodeSpace(), Translate::getRegister(), AddrSpaceManager::getSpaceByName(), AddrSpace::getTrans(), last, VarnodeData::offset, VarnodeData::size, VarnodeData::space, spc, and AddrSpace::wrapOffset().
Referenced by Architecture::parseGlobal(), Architecture::parseNoHighPtr(), Architecture::parseReadOnly(), Architecture::parseVolatile(), ScopeGhidra::processHole(), ScopeInternal::processHole(), ContextInternal::restoreFromSpec(), RangeList::restoreXml(), and ProtoModel::restoreXml().
saveXml()
void Range::saveXml (ostream & s) const
Save this Range to an XML stream.
Write this object to a stream as a <range> tag.
Parameters
s is the output stream
References a_v(), a_v_u(), first, AddrSpace::getName(), last, and spc.
The documentation for this class was generated from the following files:
address.hh
address.cc