decompiler: UserOpManage Class Reference
UserOpManage Class Reference
Manager/container for description objects (UserPcodeOp) of user defined p-code ops.
#include <userop.hh>
Public Member Functions
UserOpManage (void)
Construct an empty manager.
~UserOpManage (void)
Destructor.
void initialize (Architecture *glb)
Initialize description objects for all user defined ops.
void setDefaults (Architecture *glb)
Create any required operations if they weren't explicitly defined.
UserPcodeOp * getOp (int4 i) const
UserPcodeOp * getOp (const string &nm) const
Retrieve description by name.
SegmentOp * getSegmentOp (int4 i) const
void parseSegmentOp (const Element *el, Architecture *glb)
Parse a <segmentop> XML tag.
void parseVolatile (const Element *el, Architecture *glb)
Parse a <volatile> XML tag.
void parseCallOtherFixup (const Element *el, Architecture *glb)
Parse a <callotherfixup> XML tag.
void parseJumpAssist (const Element *el, Architecture *glb)
Parse a <jumpassist> XML tag.
void manualCallOtherFixup (const string &useropname, const string &outname, const vector< string > &inname, const string &snippet, Architecture *glb)
Manually install an InjectedUserOp given just names of the user defined op and the p-code snippet.
Private Member Functions
void registerOp (UserPcodeOp *op)
Insert a new UserPcodeOp description object in the map(s)
Private Attributes
vector< UserPcodeOp * > useroplist
Description objects indexed by CALLOTHER constant id.
map< string, UserPcodeOp * > useropmap
A map from the name of the user defined operation to a description object.
vector< SegmentOp * > segmentop
Segment operations supported by this Architecture.
VolatileReadOp * vol_read
(Single) volatile read operation
VolatileWriteOp * vol_write
(Single) volatile write operation
Detailed Description
Manager/container for description objects (UserPcodeOp) of user defined p-code ops.
The description objects are referenced by the CALLOTHER constant id, (or by name during initialization). During initialize(), every user defined p-code op presented by the Architecture is assigned a default UnspecializedPcodeOp description. Further processing of the .cspec or .pspec may reassign a more specialized description object by parsing specific tags using on of this class's parse* methods.
Member Function Documentation
getOp() [1/2]
UserPcodeOp * UserOpManage::getOp (const string & nm) const
Retrieve description by name.
Parameters
nm is the low-level operation name
Returns
the matching description object or NULL
References useropmap.
getOp() [2/2]
UserPcodeOp* UserOpManage::getOp (int4 i) const inline
Retrieve a user-op description object by index
Parameters
i is the index
Returns
the indicated user-op description
References useroplist.
Referenced by TypeOpCallother::getOperatorName(), FlowInfo::injectUserOp(), manualCallOtherFixup(), InjectedUserOp::restoreXml(), SegmentOp::restoreXml(), JumpAssistOp::restoreXml(), and FlowInfo::xrefControlFlow().
getSegmentOp()
SegmentOp* UserOpManage::getSegmentOp (int4 i) const inline
Retrieve a segment-op description object by index
Parameters
i is the index
Returns
the indicated segment-op description
References segmentop.
Referenced by Funcdata::createStackRef(), EmulatePcodeOp::executeSegmentOp(), Architecture::getSegmentOp(), and Architecture::initializeSegments().
initialize()
void UserOpManage::initialize (Architecture * glb)
Initialize description objects for all user defined ops.
Every user defined p-code op is initially assigned an UnspecializedPcodeOp description, which may get overridden later.
Parameters
glb is the Architecture from which to draw user defined operations
References Translate::getUserOpNames(), registerOp(), and Architecture::translate.
Referenced by Architecture::restoreFromSpec().
manualCallOtherFixup()
void UserOpManage::manualCallOtherFixup (const string & useropname, const string & outname, const vector< string > & inname, const string & snippet, Architecture * glb)
Manually install an InjectedUserOp given just names of the user defined op and the p-code snippet.
An alternate way to attach a call-fixup to user defined p-code ops, without using XML. The p-code to inject is presented as a raw string to be handed to the p-code parser.
Parameters
useropname is the name of the user defined op
outname is the name of the output variable in the snippet
inname is the list of input variable names in the snippet
snippet is the raw p-code source snippet
glb is the owning Architecture
References getOp(), PcodeInjectLibrary::manualCallOtherFixup(), Architecture::pcodeinjectlib, and registerOp().
parseCallOtherFixup()
void UserOpManage::parseCallOtherFixup (const Element * el, Architecture * glb)
Parse a <callotherfixup> XML tag.
Create an InjectedUserOp description object based on the XML description and register it with this manager.
Parameters
el is the root <callotherfixup> element
glb is the owning Architecture
References registerOp(), and InjectedUserOp::restoreXml().
Referenced by Architecture::parseCompilerConfig().
parseJumpAssist()
void UserOpManage::parseJumpAssist (const Element * el, Architecture * glb)
Parse a <jumpassist> XML tag.
Create a JumpAssistOp description object based on the XML description and register it with this manager.
Parameters
el is the root <jumpassist> element
glb is the owning Architecture
References registerOp(), and JumpAssistOp::restoreXml().
Referenced by Architecture::parseProcessorConfig().
parseSegmentOp()
void UserOpManage::parseSegmentOp (const Element * el, Architecture * glb)
Parse a <segmentop> XML tag.
Create a SegmentOp description object based on the tag details and register it with this manager.
Parameters
el is the root <segmentop> element
glb is the owning Architecture
References registerOp(), SegmentOp::restoreXml(), and useroplist.
Referenced by Architecture::parseCompilerConfig(), and Architecture::parseProcessorConfig().
parseVolatile()
void UserOpManage::parseVolatile (const Element * el, Architecture * glb)
Parse a <volatile> XML tag.
Create either a VolatileReadOp or VolatileWriteOp description object based on the XML details and register it with this manager.
Parameters
el is the root <volatile> element
glb is the owning Architecture
References registerOp(), VolatileReadOp::restoreXml(), VolatileWriteOp::restoreXml(), and useroplist.
Referenced by Architecture::parseVolatile().
registerOp()
void UserOpManage::registerOp (UserPcodeOp * op) private
Insert a new UserPcodeOp description object in the map(s)
Add the description to the mapping by index and the mapping by name. Make same basic sanity checks for conflicting values and duplicate operations and throw an exception if there's a problem.
Parameters
op is the new description object
References segmentop, useroplist, useropmap, vol_read, and vol_write.
Referenced by initialize(), manualCallOtherFixup(), parseCallOtherFixup(), parseJumpAssist(), parseSegmentOp(), parseVolatile(), and setDefaults().
setDefaults()
void UserOpManage::setDefaults (Architecture * glb)
Create any required operations if they weren't explicitly defined.
Establish defaults for necessary operators not already defined. Currently this forces volatile read/write operations to exist.
Parameters
glb is the owning Architecture
References registerOp(), useroplist, vol_read, and vol_write.
Referenced by Architecture::parseCompilerConfig().
The documentation for this class was generated from the following files:
userop.hh
userop.cc