decompiler: DocumentStorage Class Reference
DocumentStorage Class Reference
A container for parsed XML documents.
#include <xml.hh>
Public Member Functions
~DocumentStorage (void)
Destructor.
Document * parseDocument (istream &s)
Parse an XML document from the given stream.
Document * openDocument (const string &filename)
Open and parse an XML file.
void registerTag (const Element *el)
Register the given XML Element object under its tag name.
const Element * getTag (const string &nm) const
Retrieve a registered XML Element by name.
Private Attributes
vector< Document * > doclist
The list of documents held by this container.
map< string, const Element * > tagmap
The map from name to registered XML elements.
Detailed Description
A container for parsed XML documents.
This holds multiple XML documents that have already been parsed. Documents can be put in this container, either by handing it a stream via parseDocument() or a filename via openDocument(). If they are explicitly registered, specific XML Elements can be looked up by name via getTag().
Member Function Documentation
getTag()
const Element* DocumentStorage::getTag (const string & nm) const
Retrieve a registered XML Element by name.
Parameters
nm is the XML tag name
Returns
the matching registered Element or null
Referenced by XmlArchitecture::buildLoader(), ArchitectureGhidra::buildTypegrp(), Architecture::buildTypegrp(), GhidraTranslate::initialize(), Sleigh::initialize(), Architecture::parseCompilerConfig(), Architecture::parseExtraRules(), Architecture::parseProcessorConfig(), XmlArchitecture::restoreXml(), RawBinaryArchitecture::restoreXml(), BfdArchitecture::restoreXml(), and Architecture::restoreXml().
openDocument()
Document* DocumentStorage::openDocument (const string & filename)
Open and parse an XML file.
The given filename is opened on the local filesystem and an attempt is made to parse its contents into an in-memory DOM tree. An XmlException is thrown for any parsing error.
Parameters
filename is the name of the XML document file
Returns
the in-memory DOM tree
Referenced by XmlArchitecture::buildLoader(), and SleighArchitecture::buildSpecFile().
parseDocument()
Document* DocumentStorage::parseDocument (istream & s)
Parse an XML document from the given stream.
Parsing starts immediately on the stream, attempting to make an in-memory DOM tree. An XmlException is thrown for any parsing error.
Parameters
s is the given stream to parse
Returns
the in-memory DOM tree
Referenced by ArchitectureGhidra::buildSpecFile().
registerTag()
void DocumentStorage::registerTag (const Element * el)
Register the given XML Element object under its tag name.
Only one Element can be stored on this object per tag name.
Parameters
el is the given XML element
Referenced by XmlArchitecture::buildLoader(), ArchitectureGhidra::buildSpecFile(), SleighArchitecture::buildSpecFile(), XmlArchitecture::restoreXml(), RawBinaryArchitecture::restoreXml(), and BfdArchitecture::restoreXml().
The documentation for this class was generated from the following file:
xml.hh