decompiler: LoadTable Class Reference
LoadTable Class Reference
A description where and how data was loaded from memory.
#include <jumptable.hh>
Public Member Functions
void saveXml (ostream &s) const
Save a description of this as an <loadtable> XML tag.
void restoreXml (const Element *el, Architecture *glb)
Read in this table from a <loadtable> XML description.
Static Public Member Functions
static void collapseTable (vector< LoadTable > &table)
Collapse a sequence of table descriptions.
Private Attributes
Address addr
Starting address of table.
int4 size
Size of table entry.
int4 num
Number of entries in table;.
Friends
class EmulateFunction
Detailed Description
A description where and how data was loaded from memory.
This is a generic table description, giving the starting address of the table, the size of an entry, and number of entries.
Member Function Documentation
collapseTable()
void LoadTable::collapseTable (vector< LoadTable > & table) static
Collapse a sequence of table descriptions.
We assume the list of LoadTable entries is sorted and perform an in-place collapse of any sequences into a single LoadTable entry.
Parameters
table is the list of entries to collapse
Referenced by EmulateFunction::collectLoadPoints().
restoreXml()
void LoadTable::restoreXml (const Element * el, Architecture * glb)
Read in this table from a <loadtable> XML description.
Parameters
el is the root <loadtable> tag
glb is the architecture for resolving address space tags
References addr, Element::getAttributeValue(), num, Address::restoreXml(), and size.
saveXml()
void LoadTable::saveXml (ostream & s) const
Save a description of this as an <loadtable> XML tag.
Parameters
s is the XML stream to write to
References a_v_i(), addr, num, Address::saveXml(), and size.
The documentation for this class was generated from the following files:
jumptable.hh
jumptable.cc