decompiler: RulePtrArith Class Reference
RulePtrArith Class Reference
Transform pointer arithmetic.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Private Member Functions
static bool checkTerm (Varnode *vn, AddTreeState *state)
Accumulate details of given term and continue tree traversal.
static bool spanAddTree (PcodeOp *op, AddTreeState *state)
Traverse the additive expression accumulating offset information.
static int4 transformPtr (PcodeOp *bottom_op, PcodeOp *ptr_op, int4 slot, Funcdata &data)
Rewrite a pointer expression using PTRSUB and PTRADD.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Transform pointer arithmetic.
Rule for converting integer arithmetic to pointer arithmetic. A string of INT_ADDs is converted into PTRADDs and PTRSUBs.
Basic algorithm: Starting with a varnode of known pointer type (with known size):
Generate list of terms added to pointer
Find all terms that are multiples of pointer size
Find all terms that are smaller than pointer size
Find sum of constants smaller than pointer size
Multiples get converted to PTRADD
Constant gets converted to nearest subfield offset
Everything else is just added back on
We need to be wary of most things being in the units of the space being pointed at. Type calculations are always in bytes so we need to convert between space units and bytes.
Member Function Documentation
applyOp()
int4 RulePtrArith::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References AddrSpace::addressToByteInt(), CPUI_INT_ADD, CPUI_LOAD, CPUI_PTRADD, CPUI_STORE, Funcdata::newConstant(), Funcdata::opSetAllInput(), Funcdata::opSetOpcode(), transformPtr(), and TYPE_PTR.
checkTerm()
bool RulePtrArith::checkTerm (Varnode * vn, AddTreeState * state) static private
Accumulate details of given term and continue tree traversal.
If the given Varnode is a constant or multiplicative term, update totals in the state object. If the Varnode is additive, traverse its sub-terms.
Parameters
vn is the given Varnode term
state is the state object
Returns
true if Varnode is a NON-multiple
References AddTreeState::coeff, CPUI_COPY, CPUI_INT_ADD, CPUI_INT_MULT, AddTreeState::multiple, AddTreeState::multsum, AddTreeState::nonmultsum, AddTreeState::ptr, sign_extend(), AddTreeState::size, spanAddTree(), and AddTreeState::valid.
Referenced by spanAddTree().
clone()
virtual Rule* RulePtrArith::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
getOpList()
void RulePtrArith::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_ADD.
spanAddTree()
bool RulePtrArith::spanAddTree (PcodeOp * op, AddTreeState * state) static private
Traverse the additive expression accumulating offset information.
Parameters
op is the root of the sub-expression to traverse
state holds the offset information
Returns
true if the sub-expression is invalid or a NON-multiple
References checkTerm(), AddTreeState::nonmult, and AddTreeState::valid.
Referenced by checkTerm(), and transformPtr().
transformPtr()
int4 RulePtrArith::transformPtr (PcodeOp * bottom_op, PcodeOp * ptr_op, int4 slot, Funcdata & data) static private
Rewrite a pointer expression using PTRSUB and PTRADD.
Given a base pointer of known data-type and an additive expression involving the pointer, group the terms of the expression into:
Constant multiple of the base data-type
Non-constant multiples of the base data-type
Multiples of an array element size: rewrite using PTRADD
Drill down into sub-components of the base data-type: rewrite using PTRSUB
Remaining offsets
Parameters
bottom_op is the root Varnode of the expression
ptr_op is the PcodeOp taking the base pointer as input
slot is the input slot of the base pointer
data is the function being analyzed
Returns
1 if modifications are made, 0 otherwise
References AddrSpace::addressToByte(), AddrSpace::byteToAddress(), AddrSpace::byteToAddressInt(), calc_mask(), AddTreeState::coeff, CPUI_INT_ADD, CPUI_INT_MULT, CPUI_PTRADD, CPUI_PTRSUB, Datatype::getSubType(), AddTreeState::multiple, AddTreeState::multsum, Funcdata::newConstant(), Funcdata::newOpBefore(), AddTreeState::nonmult, AddTreeState::nonmultsum, Funcdata::opDestroy(), Funcdata::opSetOutput(), AddTreeState::ptr, sign_extend(), AddTreeState::size, spanAddTree(), TYPE_ARRAY, TYPE_SPACEBASE, TYPE_STRUCT, uintb_negate(), AddTreeState::valid, and Funcdata::warning().
Referenced by applyOp().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc