decompiler: LaneDescription Class Reference
LaneDescription Class Reference
Description of logical lanes within a big Varnode.
#include <transform.hh>
Public Member Functions
LaneDescription (const LaneDescription &op2)
Copy constructor.
LaneDescription (int4 origSize, int4 sz)
Construct uniform lanes.
LaneDescription (int4 origSize, int4 lo, int4 hi)
Construct two lanes of arbitrary size.
bool subset (int4 lsbOffset, int4 size)
Trim this to a subset of the original lanes.
int4 getBoundary (int4 bytePos) const
Get index of lane that starts at the given byte position.
bool restriction (int4 numLanes, int4 skipLanes, int4 bytePos, int4 size, int4 &resNumLanes, int4 &resSkipLanes) const
Decide if a given truncation is natural for this description.
bool extension (int4 numLanes, int4 skipLanes, int4 bytePos, int4 size, int4 &resNumLanes, int4 &resSkipLanes) const
Decide if a given subset of lanes can be extended naturally for this description.
Private Attributes
int4 wholeSize
Size of the region being split in bytes.
vector< int4 > laneSize
Size of lanes in bytes.
vector< int4 > lanePosition
Significance positions of lanes in bytes.
Detailed Description
Description of logical lanes within a big Varnode.
A lane is a byte offset and size within a Varnode. Lanes within a Varnode are disjoint. In general, we expect a Varnode to be tiled with lanes all of the same size, but the API allows for possibly non-uniform lanes.
Constructor & Destructor Documentation
LaneDescription() [1/3]
LaneDescription::LaneDescription (const LaneDescription & op2)
Copy constructor.
Parameters
op2 is the lane description to copy from
References lanePosition, laneSize, and wholeSize.
LaneDescription() [2/3]
LaneDescription::LaneDescription (int4 origSize, int4 sz)
Construct uniform lanes.
Create lanes that are all the same size
Parameters
origSize is the size of the whole in bytes
sz is the size of a lane in bytes
References lanePosition, laneSize, and wholeSize.
LaneDescription() [3/3]
LaneDescription::LaneDescription (int4 origSize, int4 lo, int4 hi)
Construct two lanes of arbitrary size.
Parameters
origSize is the size of the whole in bytes
lo is the size of the least significant lane in bytes
hi is the size of the most significant lane in bytes
References lanePosition, laneSize, and wholeSize.
Member Function Documentation
extension()
bool LaneDescription::extension (int4 numLanes, int4 skipLanes, int4 bytePos, int4 size, int4 & resNumLanes, int4 & resSkipLanes) const
Decide if a given subset of lanes can be extended naturally for this description.
A subset of lanes are specified and their position within an extension (given by a byte position). The size in bytes of the extension is also given. If the extension is contained within this description, and the boundaries of the extension don't split any lanes, then return true and pass back the number of lanes and starting lane of the extension.
Parameters
numLanes is the number of lanes in the original subset
skipLanes is the starting (least significant) lane index of the original subset
bytePos is the number of bytes to truncate from the front (least significant portion) of the extension
size is the number of bytes in the extension
resNumLanes will hold the number of lanes in the extension
resSkipLanes will hold the starting lane in the extension
Returns
true if the extension is natural
References getBoundary(), and lanePosition.
Referenced by LaneDivide::traceBackward(), and LaneDivide::traceForward().
getBoundary()
int4 LaneDescription::getBoundary (int4 bytePos) const
Get index of lane that starts at the given byte position.
Position 0 will map to index 0 and a position equal to whole size will map to the number of lanes. Positions that are out of bounds or that do not fall on a lane boundary will return -1.
Parameters
bytePos is the given byte position to test
Returns
the index of the lane that start at the given position
References lanePosition, and wholeSize.
Referenced by LaneDivide::buildRightShift(), extension(), restriction(), subset(), and LaneDivide::traceForward().
restriction()
bool LaneDescription::restriction (int4 numLanes, int4 skipLanes, int4 bytePos, int4 size, int4 & resNumLanes, int4 & resSkipLanes) const
Decide if a given truncation is natural for this description.
A subset of lanes are specified and a truncation (given by a byte position and byte size). If the truncation, relative to the subset, contains at least 1 lane and does not split any lanes, then return true and pass back the number of lanes and starting lane of the truncation.
Parameters
numLanes is the number of lanes in the original subset
skipLanes is the starting (least significant) lane index of the original subset
bytePos is the number of bytes to truncate from the front (least significant portion) of the subset
size is the number of bytes to include in the truncation
resNumLanes will hold the number of lanes in the truncation
resSkipLanes will hold the starting lane in the truncation
Returns
true if the truncation is natural
References getBoundary(), and lanePosition.
Referenced by LaneDivide::buildPiece(), and LaneDivide::traceForward().
subset()
bool LaneDescription::subset (int4 lsbOffset, int4 size)
Trim this to a subset of the original lanes.
Given a subrange, specified as an offset into the whole and size, throw out any lanes in this that aren't in the subrange, so that the size of whole is the size of the subrange. If the subrange intersects partially with any of the lanes, return false.
Parameters
lsbOffset is the number of bytes to remove from the front of the description
size is the number of bytes in the subrange
Returns
true if this was successfully transformed to the subrange
References getBoundary(), lanePosition, laneSize, and wholeSize.
The documentation for this class was generated from the following files:
transform.hh
transform.cc