decompiler: ProtoStore Class Reference
ProtoStore Class Reference abstract
A collection parameter descriptions making up a function prototype.
#include <fspec.hh>
Public Member Functions
virtual ProtoParameter * setInput (int4 i, const string &nm, const ParameterPieces &pieces)=0
Establish name, data-type, storage of a specific input parameter.
virtual void clearInput (int4 i)=0
Clear the input parameter at the specified slot.
virtual void clearAllInputs (void)=0
Clear all input parameters (and any backing symbols)
virtual int4 getNumInputs (void) const =0
Get the number of input parameters for this prototype.
virtual ProtoParameter * getInput (int4 i)=0
Get the i-th input parameter (or NULL if it doesn't exist)
virtual ProtoParameter * setOutput (const ParameterPieces &piece)=0
Establish the data-type and storage of the return value.
virtual void clearOutput (void)=0
Clear the return value to TYPE_VOID.
virtual ProtoParameter * getOutput (void)=0
Get the return-value description.
virtual ProtoStore * clone (void) const =0
Clone the entire collection of parameter descriptions.
virtual void saveXml (ostream &s) const =0
Save any parameters that are not backed by symbols to an XML stream.
virtual void restoreXml (const Element *el, ProtoModel *model)=0
Restore any internal parameter descriptions from an XML stream.
Detailed Description
A collection parameter descriptions making up a function prototype.
A unified interface for accessing descriptions of individual parameters in a function prototype. Both input parameters and return values are described.
Member Function Documentation
clearInput()
virtual void ProtoStore::clearInput (int4 i) pure virtual
Clear the input parameter at the specified slot.
The parameter is excised, any following parameters are shifted to fill its spot. If there is a backing Symbol, it is removed from the SymbolTable
Parameters
i is the specified parameter slot to remove
Implemented in ProtoStoreInternal, and ProtoStoreSymbol.
restoreXml()
virtual void ProtoStore::restoreXml (const Element * el, ProtoModel * model) pure virtual
Restore any internal parameter descriptions from an XML stream.
Parameters
el is a root <internallist> element containing <param> and <retparam> sub-tags.
model is prototype model for determining storage for unassigned parameters
Implemented in ProtoStoreInternal, and ProtoStoreSymbol.
Referenced by FuncProto::restoreXml().
saveXml()
virtual void ProtoStore::saveXml (ostream & s) const pure virtual
Save any parameters that are not backed by symbols to an XML stream.
Symbols are stored elsewhere, so symbol backed parameters are not serialized. If there are any internal parameters an <internallist> tag is emitted.
Parameters
s is the output stream
Implemented in ProtoStoreInternal, and ProtoStoreSymbol.
Referenced by FuncProto::saveXml().
setInput()
virtual ProtoParameter* ProtoStore::setInput (int4 i, const string & nm, const ParameterPieces & pieces) pure virtual
Establish name, data-type, storage of a specific input parameter.
This either allocates a new parameter or replaces the existing one at the specified input slot. If there is a backing symbol table, a Symbol is created or modified.
Parameters
i is the specified input slot
nm is the (optional) name of the parameter
pieces holds the raw storage address and data-type to set
Returns
the new/modified ProtoParameter
Implemented in ProtoStoreInternal, and ProtoStoreSymbol.
Referenced by FuncProto::paramShift(), FuncProto::updateAllTypes(), FuncProto::updateInputNoTypes(), and FuncProto::updateInputTypes().
setOutput()
virtual ProtoParameter* ProtoStore::setOutput (const ParameterPieces & piece) pure virtual
Establish the data-type and storage of the return value.
This either allocates a new parameter or replaces the existing one. A void return value can be specified with an invalid address and TYPE_VOID data-type.
Parameters
piece holds the raw storage address and data-type to set
Returns
the new/modified ProtoParameter
Implemented in ProtoStoreInternal, and ProtoStoreSymbol.
Referenced by FuncProto::paramShift(), FuncProto::restoreXml(), FuncProto::updateAllTypes(), FuncProto::updateOutputNoTypes(), and FuncProto::updateOutputTypes().
The documentation for this class was generated from the following file:
fspec.hh