decompiler: ProtoStoreSymbol Class Reference
ProtoStoreSymbol Class Reference
A collection of parameter descriptions backed by Symbol information.
#include <fspec.hh>
Public Member Functions
ProtoStoreSymbol (Scope *sc, const Address &usepoint)
Constructor.
virtual ProtoParameter * setInput (int4 i, const string &nm, const ParameterPieces &pieces)
Establish name, data-type, storage of a specific input parameter.
virtual void clearInput (int4 i)
Clear the input parameter at the specified slot.
virtual void clearAllInputs (void)
Clear all input parameters (and any backing symbols)
virtual int4 getNumInputs (void) const
Get the number of input parameters for this prototype.
virtual ProtoParameter * getInput (int4 i)
Get the i-th input parameter (or NULL if it doesn't exist)
virtual ProtoParameter * setOutput (const ParameterPieces &piece)
Establish the data-type and storage of the return value.
virtual void clearOutput (void)
Clear the return value to TYPE_VOID.
virtual ProtoParameter * getOutput (void)
Get the return-value description.
virtual ProtoStore * clone (void) const
Clone the entire collection of parameter descriptions.
virtual void saveXml (ostream &s) const
Save any parameters that are not backed by symbols to an XML stream.
virtual void restoreXml (const Element *el, ProtoModel *model)
Restore any internal parameter descriptions from an XML stream.
Private Member Functions
ParameterSymbol * getSymbolBacked (int4 i)
Fetch or allocate the parameter for the indicated slot.
Private Attributes
Scope * scope
Backing Scope for input parameters.
Address restricted_usepoint
A usepoint reference for storage locations (usually function entry -1)
vector< ProtoParameter * > inparam
Cache of allocated input parameters.
ProtoParameter * outparam
The return-value parameter.
Detailed Description
A collection of parameter descriptions backed by Symbol information.
Input parameters are determined by symbols a function Scope (category 0). Information about the return-value is stored internally. ProtoParameter objects are constructed on the fly as requested and cached.
Constructor & Destructor Documentation
ProtoStoreSymbol()
ProtoStoreSymbol::ProtoStoreSymbol (Scope * sc, const Address & usepoint)
Constructor.
Parameters
sc is the function Scope that will back this store
usepoint is the starting address of the function (-1)
References ParameterPieces::flags, outparam, restricted_usepoint, scope, setOutput(), and ParameterPieces::type.
Referenced by clone().
Member Function Documentation
clearInput()
void ProtoStoreSymbol::clearInput (int4 i) virtual
Clear the input parameter at the specified slot.
The parameter is excised, any following parameters are shifted to fill its spot. If there is a backing Symbol, it is removed from the SymbolTable
Parameters
i is the specified parameter slot to remove
Implements ProtoStore.
References Scope::getCategorySize(), Scope::getCategorySymbol(), Scope::removeSymbol(), scope, and Scope::setCategory().
getSymbolBacked()
ParameterSymbol * ProtoStoreSymbol::getSymbolBacked (int4 i) private
Fetch or allocate the parameter for the indicated slot.
Retrieve the specified ProtoParameter object, making sure it is a ParameterSymbol. If it doesn't exist, or if the object in the specific slot is not a ParameterSymbol, allocate an (unitialized) parameter.
Parameters
i is the specified input slot
Returns
the corresponding parameter
References inparam.
Referenced by getInput(), and setInput().
restoreXml()
void ProtoStoreSymbol::restoreXml (const Element * el, ProtoModel * model) virtual
Restore any internal parameter descriptions from an XML stream.
Parameters
el is a root <internallist> element containing <param> and <retparam> sub-tags.
model is prototype model for determining storage for unassigned parameters
Implements ProtoStore.
saveXml()
void ProtoStoreSymbol::saveXml (ostream & s) const virtual
Save any parameters that are not backed by symbols to an XML stream.
Symbols are stored elsewhere, so symbol backed parameters are not serialized. If there are any internal parameters an <internallist> tag is emitted.
Parameters
s is the output stream
Implements ProtoStore.
setInput()
ProtoParameter * ProtoStoreSymbol::setInput (int4 i, const string & nm, const ParameterPieces & pieces) virtual
Establish name, data-type, storage of a specific input parameter.
This either allocates a new parameter or replaces the existing one at the specified input slot. If there is a backing symbol table, a Symbol is created or modified.
Parameters
i is the specified input slot
nm is the (optional) name of the parameter
pieces holds the raw storage address and data-type to set
Returns
the new/modified ProtoParameter
Implements ProtoStore.
References ParameterPieces::addr, Scope::addSymbol(), Scope::clearAttribute(), Scope::discoverScope(), ParameterPieces::flags, Scope::getCategorySymbol(), Symbol::getFirstWholeMap(), getSymbolBacked(), Varnode::hiddenretparm, Varnode::indirectstorage, Scope::removeSymbol(), Scope::renameSymbol(), restricted_usepoint, Scope::retypeSymbol(), scope, Scope::setAttribute(), Scope::setCategory(), ParameterSymbol::sym, and ParameterPieces::type.
setOutput()
ProtoParameter * ProtoStoreSymbol::setOutput (const ParameterPieces & piece) virtual
Establish the data-type and storage of the return value.
This either allocates a new parameter or replaces the existing one. A void return value can be specified with an invalid address and TYPE_VOID data-type.
Parameters
piece holds the raw storage address and data-type to set
Returns
the new/modified ProtoParameter
Implements ProtoStore.
References ParameterPieces::addr, ParameterPieces::flags, outparam, and ParameterPieces::type.
Referenced by clearOutput(), and ProtoStoreSymbol().
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc