decompiler: ActionStackPtrFlow Class Reference
ActionStackPtrFlow Class Reference
Analyze change to the stack pointer across sub-function calls.
#include <coreaction.hh>
Public Member Functions
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
Static Private Member Functions
static void analyzeExtraPop (Funcdata &data, AddrSpace *stackspace, int4 spcbase)
Calculate stack-pointer change across undetermined sub-functions.
static bool isStackRelative (Varnode *spcbasein, Varnode *vn, uintb &constval)
Is the given Varnode defined as a pointer relative to the stack-pointer?
static bool adjustLoad (Funcdata &data, PcodeOp *loadop, PcodeOp *storeop)
Adjust the LOAD where the stack-pointer alias has been recovered.
static int4 repair (Funcdata &data, AddrSpace *id, Varnode *spcbasein, PcodeOp *loadop, uintb constz)
Link LOAD to matching STORE of a constant.
static int4 checkClog (Funcdata &data, AddrSpace *id, int4 spcbase)
Find any stack pointer clogs and pass it on to the repair routines.
Private Attributes
AddrSpace * stackspace
Stack space associated with stack-pointer register.
bool analysis_finished
True if analysis already performed.
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Analyze change to the stack pointer across sub-function calls.
Member Function Documentation
adjustLoad()
bool ActionStackPtrFlow::adjustLoad (Funcdata & data, PcodeOp * loadop, PcodeOp * storeop) static private
Adjust the LOAD where the stack-pointer alias has been recovered.
We've matched a LOAD with its matching store, now convert the LOAD op to a COPY of what was stored.
Parameters
data is the function being analyzed
loadop is the LOAD op to adjust
storeop is the matching STORE op
Returns
true if the adjustment is successful
References CPUI_COPY, Funcdata::newConstant(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), and Funcdata::opSetOpcode().
Referenced by repair().
analyzeExtraPop()
void ActionStackPtrFlow::analyzeExtraPop (Funcdata & data, AddrSpace * stackspace, int4 spcbase) static private
Calculate stack-pointer change across undetermined sub-functions.
If there are sub-functions for which extra pop is not explicit, do full linear analysis to (attempt to) recover the values.
Parameters
data is the function to analyze
stackspace is the space associated with the stack-pointer
spcbase is the index (relative to the stackspace) of the stack-pointer
References StackSolver::build(), calc_mask(), CPUI_INDIRECT, CPUI_INT_ADD, LowlevelError::explain, ProtoModel::extrapop_unknown, Funcdata::getCallSpecs(), AddrSpace::getName(), PcodeOp::getOpFromConst(), IPTR_IOP, Funcdata::newConstant(), Funcdata::opSetAllInput(), Funcdata::opSetOpcode(), StackSolver::solve(), stackspace, and Funcdata::warningHeader().
Referenced by apply().
apply()
int4 ActionStackPtrFlow::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implements Action.
References analysis_finished, analyzeExtraPop(), checkClog(), Action::count, and stackspace.
checkClog()
int4 ActionStackPtrFlow::checkClog (Funcdata & data, AddrSpace * id, int4 spcbase) static private
Find any stack pointer clogs and pass it on to the repair routines.
A stack pointer clog is a constant addition to the stack-pointer, but where the constant comes from the stack.
Parameters
data is the function to analyze
id is the stack space
spcbase is the index of the stack-pointer relative to the stack space
Returns
the number of clogs that were repaired
References Funcdata::beginLoc(), calc_mask(), CPUI_INT_ADD, CPUI_INT_MULT, CPUI_LOAD, Funcdata::endLoc(), AddrSpace::getSpacebase(), isStackRelative(), VarnodeData::offset, repair(), VarnodeData::size, and VarnodeData::space.
Referenced by apply().
clone()
virtual Action* ActionStackPtrFlow::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implements Action.
References ActionGroupList::contains(), and stackspace.
isStackRelative()
bool ActionStackPtrFlow::isStackRelative (Varnode * spcbasein, Varnode * vn, uintb & constval) static private
Is the given Varnode defined as a pointer relative to the stack-pointer?
Return true if -vn- is defined as the stackpointer input plus a constant (or zero) This works through the general case and the special case when the constant is zero. The constant value is passed-back to the caller.
Parameters
spcbasein is the Varnode holding the input value of the stack-pointer
vn is the Varnode to check for relativeness
constval is a reference for passing back the constant offset
Returns
true if vn is stack relative
References CPUI_INT_ADD.
Referenced by checkClog(), and repair().
repair()
int4 ActionStackPtrFlow::repair (Funcdata & data, AddrSpace * id, Varnode * spcbasein, PcodeOp * loadop, uintb constz) static private
Link LOAD to matching STORE of a constant.
Try to find STORE op using same stack relative pointer as a given LOAD op. If we find it and the STORE stores a constant, change the LOAD to a COPY.
Parameters
data is the function owning the LOAD
id is the stackspace
spcbasein is the stack-pointer
loadop is the given LOAD op
constz is the stack relative offset of the LOAD pointer
Returns
1 if we successfully change LOAD to COPY, 0 otherwise
References adjustLoad(), CPUI_STORE, and isStackRelative().
Referenced by checkClog().
reset()
virtual void ActionStackPtrFlow::reset (Funcdata & data) inline virtual
Reset the Action for a new function.
Parameters
data is the new function this Action may affect
Reimplemented from Action.
References analysis_finished.
The documentation for this class was generated from the following files:
coreaction.hh
coreaction.cc