decompiler: PcodeInjectLibraryGhidra Class Reference
PcodeInjectLibraryGhidra Class Reference
A p-code injection library that uses a Ghidra client to generate/compile the injection p-code.
#include <inject_ghidra.hh>
Public Member Functions
PcodeInjectLibraryGhidra (ArchitectureGhidra *ghi)
Constructor.
virtual int4 manualCallFixup (const string &name, const string &snippet)
Manually add a call-fixup payload given a compilable snippet of p-code source.
virtual int4 manualCallOtherFixup (const string &name, const string &outname, const vector< string > &inname, const string &snippet)
Manually add a callother-fixup payload given a compilable snippet of p-code source.
virtual InjectContext & getCachedContext (void)
Retrieve a reusable context object for this library.
virtual const vector< OpBehavior * > & getBehaviors (void)
Get the array of op-code behaviors for initializing and emulator.
Public Member Functions inherited from PcodeInjectLibrary
virtual ~PcodeInjectLibrary (void)
Destructor.
int4 getPayloadId (int4 type, const string &nm) const
Map name and type to the payload id.
string getCallFixupName (int4 injectid) const
Get the call-fixup name associated with an id.
string getCallOtherTarget (int4 injectid) const
Get the callother-fixup name associated with an id.
string getCallMechanismName (int4 injectid) const
Get the call mechanism name associated with an id.
int4 restoreXmlInject (const string &src, const string &nm, int4 tp, const Element *el)
Read in and register an injection payload from an XML stream.
virtual void restoreDebug (const Element *el)
A method for reading in p-code generated externally for use in debugging.
Private Member Functions
virtual int4 allocateInject (const string &sourceName, const string &name, int4 type)
Allocate a new InjectPayload object.
virtual void registerInject (int4 injectid)
Finalize a payload within the library, once the payload is initialized.
Private Attributes
InjectContextGhidra contextCache
A context object that wraps data in XML for the Ghidra client.
vector< OpBehavior * > inst
Collected behaviors for the ExecutablePcode payloads.
Additional Inherited Members
Protected Member Functions inherited from PcodeInjectLibrary
void registerCallFixup (const string &fixupName, int4 injectid)
Map a call-fixup name to a payload id.
void registerCallOtherFixup (const string &fixupName, int4 injectid)
Map a callother-fixup name to a payload id.
void registerCallMechanism (const string &fixupName, int4 injectid)
Map a call mechanism name to a payload id.
void registerExeScript (const string &scriptName, int4 injectid)
Map a p-code script name to a payload id.
Protected Attributes inherited from PcodeInjectLibrary
Architecture * glb
The Architecture to which the injection payloads apply.
uintb tempbase
Offset within unique space for allocating temporaries within a payload.
vector< InjectPayload * > injection
Registered injections.
map< string, int4 > callFixupMap
Map of registered call-fixup names to injection id.
map< string, int4 > callOtherFixupMap
Map of registered callother-fixup names to injection id.
map< string, int4 > callMechFixupMap
Map of registered mechanism names to injection id.
map< string, int4 > scriptMap
Map of registered script names to ExecutablePcode id.
vector< string > callFixupNames
Map from injectid to call-fixup name.
vector< string > callOtherTarget
Map from injectid to callother-fixup target-op name.
vector< string > callMechTarget
Map from injectid to call-mech name.
vector< string > scriptNames
Map from injectid to script name.
Detailed Description
A p-code injection library that uses a Ghidra client to generate/compile the injection p-code.
The InjectPayload objects produced by this library are just placeholders (see InjectPayloadGhidra). At the time of injection, final p-code is generated by the Ghidra client.
Member Function Documentation
allocateInject()
int4 PcodeInjectLibraryGhidra::allocateInject (const string & sourceName, const string & name, int4 type) private virtual
Allocate a new InjectPayload object.
This acts as an InjectPayload factory. The formal name and type of the payload are given, this library allocates a new object that fits with its storage scheme and returns the id.
Parameters
sourceName is a string describing the source of the new payload
name is the formal name of the payload
type is the formal type (CALLFIXUP_TYPE, CALLOTHERFIXUP_TYPE, etc.) of the payload
Returns
the id associated with the new InjectPayload object
Implements PcodeInjectLibrary.
References InjectPayload::CALLFIXUP_TYPE, InjectPayload::CALLMECHANISM_TYPE, InjectPayload::CALLOTHERFIXUP_TYPE, contextCache, InjectPayload::EXECUTABLEPCODE_TYPE, InjectContext::glb, and PcodeInjectLibrary::injection.
getBehaviors()
const vector< OpBehavior * > & PcodeInjectLibraryGhidra::getBehaviors (void) virtual
Get the array of op-code behaviors for initializing and emulator.
Behaviors are pulled from the underlying architecture in order to initialize the Emulate object which services the p-code script payloads.
Returns
the array of OpBehavior objects indexed by op-code
Implements PcodeInjectLibrary.
References Architecture::collectBehaviors(), PcodeInjectLibrary::glb, and inst.
getCachedContext()
virtual InjectContext& PcodeInjectLibraryGhidra::getCachedContext (void) inline virtual
Retrieve a reusable context object for this library.
The object returned by this method gets passed to the payload inject() method. The clear() method must be called between uses.
Returns
the cached context object
Implements PcodeInjectLibrary.
References contextCache.
manualCallFixup()
int4 PcodeInjectLibraryGhidra::manualCallFixup (const string & name, const string & snippetstring) virtual
Manually add a call-fixup payload given a compilable snippet of p-code source.
The snippet is compiled immediately to produce the payload.
Parameters
name is the formal name of the new payload
snippetstring is the compilable snippet of p-code source
Returns
the id of the new payload
Implements PcodeInjectLibrary.
manualCallOtherFixup()
int4 PcodeInjectLibraryGhidra::manualCallOtherFixup (const string & name, const string & outname, const vector< string > & inname, const string & snippet) virtual
Manually add a callother-fixup payload given a compilable snippet of p-code source.
The snippet is compiled immediately to produce the payload. Symbol names for input and output parameters must be provided to the compiler.
Parameters
name is the formal name of the new payload
outname is the name of the output symbol
inname is the ordered list of input symbol names
snippet is the compilable snippet of p-code source
Returns
the id of the new payload
Implements PcodeInjectLibrary.
registerInject()
void PcodeInjectLibraryGhidra::registerInject (int4 injectid) private virtual
Finalize a payload within the library, once the payload is initialized.
This provides the derived class the opportunity to add the payload name to the symbol tables or do anything else it needs to once the InjectPayload object has been fully initialized.
Parameters
injectid is the id of the InjectPayload to finalize
Implements PcodeInjectLibrary.
References InjectPayload::CALLFIXUP_TYPE, InjectPayload::CALLMECHANISM_TYPE, InjectPayload::CALLOTHERFIXUP_TYPE, InjectPayload::EXECUTABLEPCODE_TYPE, PcodeInjectLibrary::injection, PcodeInjectLibrary::registerCallFixup(), PcodeInjectLibrary::registerCallMechanism(), PcodeInjectLibrary::registerCallOtherFixup(), and PcodeInjectLibrary::registerExeScript().
The documentation for this class was generated from the following files:
inject_ghidra.hh
inject_ghidra.cc