decompiler: EmitXml Class Reference
EmitXml Class Reference
Base class (and interface) for pretty printing and XML markup of tokens.
#include <prettyprint.hh>
Public Types
enum syntax_highlight {
keyword_color = 0, comment_color = 1, type_color = 2, funcname_color = 3,
var_color = 4, const_color = 5, param_color = 6, global_color = 7,
no_color = 8
}
Possible types of syntax highlighting.
Public Member Functions
virtual int4 beginDocument (void)
Begin a whole document of output.
virtual void endDocument (int4 id)
End a whole document of output.
virtual int4 beginFunction (const Funcdata *fd)
Begin a whole declaration and body of a function.
virtual void endFunction (int4 id)
End a whole declaration and body of a function.
virtual int4 beginBlock (const FlowBlock *bl)
Begin a control-flow element.
virtual void endBlock (int4 id)
End a control-flow element.
virtual void tagLine (void)
Force a line break.
virtual void tagLine (int4 indent)
Force a line break and indent level.
virtual int4 beginReturnType (const Varnode *vn)
Begin a return type declaration.
virtual void endReturnType (int4 id)
End a return type declaration.
virtual int4 beginVarDecl (const Symbol *sym)
Begin a variable declaration.
virtual void endVarDecl (int4 id)
End a variable declaration.
virtual int4 beginStatement (const PcodeOp *op)
Begin a source code statement.
virtual void endStatement (int4 id)
End a source code statement.
virtual int4 beginFuncProto (void)
Begin a function prototype declaration.
virtual void endFuncProto (int4 id)
End a function prototype declaration.
virtual void tagVariable (const char *ptr, syntax_highlight hl, const Varnode *vn, const PcodeOp *op)
Emit a variable token.
virtual void tagOp (const char *ptr, syntax_highlight hl, const PcodeOp *op)
Emit an operation token.
virtual void tagFuncName (const char *ptr, syntax_highlight hl, const Funcdata *fd, const PcodeOp *op)
Emit a function identifier.
virtual void tagType (const char *ptr, syntax_highlight hl, const Datatype *ct)
Emit a data-type identifier.
virtual void tagField (const char *ptr, syntax_highlight hl, const Datatype *ct, int4 off)
Emit an identifier for a field within a structured data-type.
virtual void tagComment (const char *ptr, syntax_highlight hl, const AddrSpace *spc, uintb off)
Emit a comment string as part of the generated source code.
virtual void tagLabel (const char *ptr, syntax_highlight hl, const AddrSpace *spc, uintb off)
Emit a code label identifier.
virtual void print (const char *str, syntax_highlight hl=no_color)
Emit other (more unusual) syntax as part of source code generation.
virtual int4 openParen (char o, int4 id=0)
Emit an open parenthesis.
virtual void closeParen (char c, int4 id)
Emit a close parenthesis.
virtual int4 openGroup (void)
Start a group of things that are printed together.
virtual void closeGroup (int4 id)
End a group of things that are printed together.
virtual void spaces (int4 num, int4 bump=0)
Emit a sequence of space characters as part of source code.
virtual int4 startIndent (void)
Start a new indent level.
virtual void stopIndent (int4 id)
End an indent level.
virtual int4 startComment (void)
Start a comment block within the emitted source code.
virtual void stopComment (int4 id)
End a comment block.
virtual void flush (void)
Flush any remaining character data.
virtual void setMaxLineSize (int4 mls)
Provide a maximum line size to the pretty printer.
virtual int4 getMaxLineSize (void) const
Get the current maximum line size.
virtual void setCommentFill (const string &fill)
Set the comment fill characters for when line breaks are forced.
virtual bool emitsXml (void) const
Determine if this is an XML markup emitter.
int4 getParenLevel (void) const
Get the current parentheses depth.
int4 getIndentIncrement (void) const
Get the number of characters indented per level of nesting.
void setIndentIncrement (int4 val)
Set the number of characters indented per level of nesting.
Protected Attributes
ostream * s
Stream being emitted to.
int4 indentlevel
Current indent level (in fixed width characters)
int4 parenlevel
Current depth of parentheses.
int4 indentincrement
Change in indentlevel per level of nesting.
Static Private Attributes
static const char * highlight []
Map from syntax_highlight enumeration to color attribute string.
Detailed Description
Base class (and interface) for pretty printing and XML markup of tokens.
There are two basic functions being implemented through this interface:
XML markup: allows recording of the natural grouping of the high-level tokens and directly links the nodes of the abstract syntax tree to the emitted tokens.
Pretty printing: Line breaks and additional white space characters are inserted within the emitted source code to enforce a maximum number of characters per line while minimizing breaks in important groups of syntax. Where extra line breaks are necessary, additional indenting is provided to reduce the impact on readability.
All printing must be surrounded by at least one begin and end tag pair:
beginDocument endDocument surrounds a whole document of code output
beginFunction endFunction surrounds a whole declaration and body of a function
beginBlock endBlock surrounds control-flow elements
beginReturnType endReturnType
beginVarDecl endVarDecl surrounds variable declarations
beginStatement endStatement surrounds a single statement
beginFuncProto endFuncProto surrounds a function prototype declaration
Additional printing groups can be specified with tag pairs:
openParen closeParen creates a unit surrounded by parentheses and treats
openGroup closeGroup create an arbitrary printing unit
startIndent stopIndent prints a unit at a given indent level
startComment stopComment delimit comments for special indenting and filling
The tag* functions, emit the actual language tokens, supplying appropriate markup.
tagVariable to print variables
tagOp to print operators
tagFuncName to print a function identifiers
tagType to print data-type identifiers
tagField to print field identifiers for structured data-types
tagComment to print words in a comment
tagLabel to print control-flow labels
print is used for any other syntax
spaces is used to print whitespace
tagLine forces a line break
tagLine(indent) forces a line break with an indent override
This base class does not actually do any pretty printing it only does the XML markup. For an implementation that actually does pretty printing, see EmitPrettyPrint. This class can be used as the low-level back-end to EmitPrettyPrint to provide a solution that does both pretty printing and XML markup.
Member Enumeration Documentation
syntax_highlight
enum EmitXml::syntax_highlight
Possible types of syntax highlighting.
Enumerator
keyword_color
Keyword in the high-level language.
comment_color
Comments.
type_color
Data-type identifiers.
funcname_color
Function identifiers.
var_color
Local variable identifiers.
const_color
Constant values.
param_color
Function parameters.
global_color
Global variable identifiers.
no_color
Un-highlighted.
Member Function Documentation
beginBlock()
int4 EmitXml::beginBlock (const FlowBlock * bl) virtual
Begin a control-flow element.
Inform the emitter that a new control-flow section is starting. This is a source code unit usually surrounded with curly braces '{' and '}'.
Parameters
bl is the block structure object associated with the section
Returns
an id associated with the section
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitBlockCondition(), PrintC::emitBlockDoWhile(), PrintC::emitBlockGraph(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockLs(), PrintC::emitBlockSwitch(), and PrintC::emitBlockWhileDo().
beginDocument()
int4 EmitXml::beginDocument (void) virtual
Begin a whole document of output.
Inform the emitter that generation of the source code document has begun
Returns
an id associated with the document
Reimplemented in EmitPrettyPrint, and EmitNoXml.
References highlight, no_color, and s.
Referenced by PrintC::docAllGlobals(), and PrintC::docSingleGlobal().
beginFuncProto()
int4 EmitXml::beginFuncProto (void) virtual
Begin a function prototype declaration.
Inform the emitter that a function prototype is starting.
Returns
an id associated with the prototype
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitFunctionDeclaration().
beginFunction()
int4 EmitXml::beginFunction (const Funcdata * fd) virtual
Begin a whole declaration and body of a function.
Inform the emitter that generation of a function body has begun
Returns
an id associated with the function body
Reimplemented in EmitPrettyPrint, and EmitNoXml.
References highlight, no_color, and s.
Referenced by PrintC::docFunction().
beginReturnType()
int4 EmitXml::beginReturnType (const Varnode * vn) virtual
Begin a return type declaration.
Inform the emitter that generation of a function's return type is starting.
Parameters
vn (if non-null) is the storage location for the return value
Returns
an id associated with the return type
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitPrototypeOutput().
beginStatement()
int4 EmitXml::beginStatement (const PcodeOp * op) virtual
Begin a source code statement.
Inform the emitter that a source code statement is beginning.
Parameters
op is the root p-code operation of the statement
Returns
an id associated with the statement
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitBlockBasic(), PrintC::emitGotoStatement(), and PrintC::emitStatement().
beginVarDecl()
int4 EmitXml::beginVarDecl (const Symbol * sym) virtual
Begin a variable declaration.
Inform the emitter that a variable declaration has started.
Parameters
sym is the symbol being declared
Returns
an id associated with the declaration
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitVarDecl().
closeGroup()
virtual void EmitXml::closeGroup (int4 id) inline virtual
End a group of things that are printed together.
Inform the emitter that a printing group is ending.
Parameters
id is the id associated with the group (as returned by openGroup)
Reimplemented in EmitPrettyPrint.
Referenced by PrintC::emitFunctionDeclaration(), PrintC::opCbranch(), and PrintLanguage::pushAtom().
closeParen()
void EmitXml::closeParen (char c, int4 id) virtual
Emit a close parenthesis.
This method emits the parenthesis character itself and ends the printing unit that was started by the matching open parenthesis.
Parameters
c is the close parenthesis character to emit
id is the id associated with the matching open parenthesis (as returned by openParen)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitBlockCondition(), PrintC::emitBlockInfLoop(), PrintC::emitBlockWhileDo(), PrintC::emitFunctionDeclaration(), PrintLanguage::emitOp(), PrintC::opBranchind(), PrintC::opCbranch(), and PrintLanguage::pushAtom().
emitsXml()
virtual bool EmitXml::emitsXml (void) const inline virtual
Determine if this is an XML markup emitter.
Returns
true if this produces an XML markup of its emitted source code
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by EmitPrettyPrint::emitsXml().
endBlock()
void EmitXml::endBlock (int4 id) virtual
End a control-flow element.
Inform the emitter that a control-flow section is ending.
Parameters
id is the id associated with the section (as returned by beginBlock)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitBlockCondition(), PrintC::emitBlockDoWhile(), PrintC::emitBlockGraph(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockLs(), PrintC::emitBlockSwitch(), and PrintC::emitBlockWhileDo().
endDocument()
void EmitXml::endDocument (int4 id) virtual
End a whole document of output.
Inform the emitter that generation of the source code document is finished
Parameters
id is the id associated with the document (as returned by beginDocument)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
References s.
Referenced by PrintC::docAllGlobals(), and PrintC::docSingleGlobal().
endFuncProto()
void EmitXml::endFuncProto (int4 id) virtual
End a function prototype declaration.
Inform the emitter that a function prototype is ending.
Parameters
id is the id associated with the prototype (as returned by beginFuncProto)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitFunctionDeclaration().
endFunction()
void EmitXml::endFunction (int4 id) virtual
End a whole declaration and body of a function.
Inform the emitter that generation of a function body has ended
Parameters
id is the id associated with the function body (as returned by beginFunction)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::docFunction().
endReturnType()
void EmitXml::endReturnType (int4 id) virtual
End a return type declaration.
Inform the emitter that generation of a function's return type is ending.
Parameters
id is the id associated with the return type (as returned by beginReturnType)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitPrototypeOutput().
endStatement()
void EmitXml::endStatement (int4 id) virtual
End a source code statement.
Inform the emitter that a source code statement is ending.
Parameters
id is the id associated with the statement (as returned by beginStatement)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitBlockBasic(), PrintC::emitGotoStatement(), and PrintC::emitStatement().
endVarDecl()
void EmitXml::endVarDecl (int4 id) virtual
End a variable declaration.
Inform the emitter that a variable declaration has ended.
Parameters
id is the id associated with the declaration (as returned by beginVarDecl)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitVarDecl().
flush()
virtual void EmitXml::flush (void) inline virtual
Flush any remaining character data.
Depending on the particular emitter, tokens and syntax that have been submitted to the emitter may be held internally for a time before getting output to the final stream. This routine makes sure submitted syntax is fully output.
Reimplemented in EmitPrettyPrint.
Referenced by PrintC::docAllGlobals(), PrintC::docFunction(), PrintC::docSingleGlobal(), and EmitPrettyPrint::flush().
getIndentIncrement()
int4 EmitXml::getIndentIncrement (void) const inline
Get the number of characters indented per level of nesting.
Returns
the number of characters
References indentincrement.
getMaxLineSize()
virtual int4 EmitXml::getMaxLineSize (void) const inline virtual
Get the current maximum line size.
If the emitter respects a maximum line size, return that size.
Returns
the maximum line size or -1 if the emitter does not have a maximum
Reimplemented in EmitPrettyPrint.
Referenced by PrintLanguage::setLineCommentIndent().
getParenLevel()
int4 EmitXml::getParenLevel (void) const inline
Get the current parentheses depth.
Returns
the current number of open parenthetical groups
References parenlevel.
openGroup()
virtual int4 EmitXml::openGroup (void) inline virtual
Start a group of things that are printed together.
Inform the emitter that a new printing group is starting.
Returns
an id associated with the group
Reimplemented in EmitPrettyPrint.
Referenced by PrintC::emitFunctionDeclaration(), PrintC::opCbranch(), and PrintLanguage::pushOp().
openParen()
int4 EmitXml::openParen (char o, int4 id = 0) virtual
Emit an open parenthesis.
This method emits the parenthesis character itself and also starts a printing unit of the source code being surrounded by the parentheses.
Parameters
o is the open parenthesis character to emit
id is an id to associate with the parenthesis
Returns
an id associated with the parenthesis
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitBlockCondition(), PrintC::emitBlockInfLoop(), PrintC::emitBlockWhileDo(), PrintC::emitFunctionDeclaration(), PrintLanguage::emitOp(), PrintC::opBranchind(), PrintC::opCbranch(), and PrintLanguage::pushOp().
print()
void EmitXml::print (const char * str, syntax_highlight hl = no_color) virtual
Emit other (more unusual) syntax as part of source code generation.
This method is used to emit syntax not covered by the other methods, such as spaces, semi-colons, braces, and other punctuation.
Parameters
str is the character data of the syntax being emitted
hl indicates how the syntax should be highlighted
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::docFunction(), PrintLanguage::emitAtom(), PrintC::emitBlockBasic(), PrintC::emitBlockDoWhile(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockSwitch(), PrintC::emitBlockWhileDo(), PrintC::emitEnumDefinition(), PrintC::emitFunctionDeclaration(), PrintC::emitGotoStatement(), PrintC::emitLabelStatement(), PrintC::emitPrototypeInputs(), PrintC::emitStatement(), PrintC::emitStructDefinition(), PrintC::emitSwitchCase(), PrintC::emitVarDeclStatement(), PrintC::opCbranch(), and EmitPrettyPrint::print().
setCommentFill()
virtual void EmitXml::setCommentFill (const string & fill) inline virtual
Set the comment fill characters for when line breaks are forced.
If the pretty printer forces a line break in the middle of a comment, this string is emitted to provide proper syntax and indenting to continue the comment.
Parameters
fill is the set of fill characters
Reimplemented in EmitPrettyPrint.
Referenced by PrintLanguage::setCommentDelimeter().
setIndentIncrement()
void EmitXml::setIndentIncrement (int4 val) inline
Set the number of characters indented per level of nesting.
Parameters
val is the desired number of characters to indent
References indentincrement.
setMaxLineSize()
virtual void EmitXml::setMaxLineSize (int4 mls) inline virtual
Provide a maximum line size to the pretty printer.
The emitter may insert line breaks to enforce this maximum.
Parameters
mls is the number of characters to set for the maximum line size
Reimplemented in EmitPrettyPrint.
spaces()
void EmitXml::spaces (int4 num, int4 bump = 0) virtual
Emit a sequence of space characters as part of source code.
Parameters
num is the number of space characters to emit
bump is the number of characters to indent if the spaces force a line break
Reimplemented in EmitPrettyPrint.
Referenced by PrintC::emitBlockBasic(), PrintC::emitBlockDoWhile(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockSwitch(), PrintC::emitBlockWhileDo(), PrintC::emitEnumDefinition(), PrintC::emitFunctionDeclaration(), PrintC::emitGotoStatement(), PrintLanguage::emitLineComment(), PrintLanguage::emitOp(), PrintC::emitStructDefinition(), PrintC::emitSwitchCase(), PrintC::opBranch(), PrintC::opCbranch(), PrintC::opReturn(), and EmitPrettyPrint::print().
startComment()
virtual int4 EmitXml::startComment (void) inline virtual
Start a comment block within the emitted source code.
Inform the emitter that a set of comment tokens/lines is starting.
Returns
an id associated with the comment block
Reimplemented in EmitPrettyPrint.
Referenced by PrintLanguage::emitLineComment().
startIndent()
virtual int4 EmitXml::startIndent (void) inline virtual
Start a new indent level.
Inform the emitter that one level of nesting is being added.
Returns
an id associated with the nesting
Reimplemented in EmitPrettyPrint.
References indentincrement, and indentlevel.
Referenced by PrintC::docFunction(), PrintC::emitBlockDoWhile(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockSwitch(), PrintC::emitBlockWhileDo(), PrintC::emitEnumDefinition(), and PrintC::emitStructDefinition().
stopComment()
virtual void EmitXml::stopComment (int4 id) inline virtual
End a comment block.
Inform the emitter that a set of comment tokens/lines is ending.
Parameters
id is the id associated with the block (as returned by startComment)
Reimplemented in EmitPrettyPrint.
Referenced by PrintLanguage::emitLineComment().
stopIndent()
virtual void EmitXml::stopIndent (int4 id) inline virtual
End an indent level.
Inform the emitter that the current nesting has ended, and we are returning to the previous level.
Parameters
id is the id associated with the nesting (as returned by startIndent)
Reimplemented in EmitPrettyPrint.
References indentincrement, and indentlevel.
Referenced by PrintC::docFunction(), PrintC::emitBlockDoWhile(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockSwitch(), PrintC::emitBlockWhileDo(), PrintC::emitEnumDefinition(), and PrintC::emitStructDefinition().
tagComment()
void EmitXml::tagComment (const char * ptr, syntax_highlight hl, const AddrSpace * spc, uintb off) virtual
Emit a comment string as part of the generated source code.
Individual comments can be broken up and emitted using multiple calls to this method, but ultimately the comment delimiters and the body of the comment are both emitted with this method, which may provide addition markup.
Parameters
ptr is the character data for the comment
hl indicates how the comment should be highlighted
spc is the address space of the address where the comment is attached
off is the offset of the address where the comment is attached
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintLanguage::emitLineComment().
tagField()
void EmitXml::tagField (const char * ptr, syntax_highlight hl, const Datatype * ct, int4 o) virtual
Emit an identifier for a field within a structured data-type.
A string representing an individual component of a structured data-type is emitted, possibly with additional markup.
Parameters
ptr is the character data for the identifier
hl indicates how the identifier should be highlighted
ct is the data-type associated with the field
o is the (byte) offset of the field within its structured data-type
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintLanguage::emitAtom().
tagFuncName()
void EmitXml::tagFuncName (const char * ptr, syntax_highlight hl, const Funcdata * fd, const PcodeOp * op) virtual
Emit a function identifier.
An identifier string representing the symbol name of the function is emitted, possible with additional markup.
Parameters
ptr is the character data for the identifier
hl indicates how the identifier should be highlighted
fd is the function
op is the CALL operation associated within the syntax tree or null for a declaration
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintLanguage::emitAtom(), and PrintC::emitFunctionDeclaration().
tagLabel()
void EmitXml::tagLabel (const char * ptr, syntax_highlight hl, const AddrSpace * spc, uintb off) virtual
Emit a code label identifier.
A string describing a control-flow destination, as appropriate for the source language is output, possibly with additional markup.
Parameters
ptr is the character data of the label
hl indicates how the label should be highlighted
spc is the address space of the code address being labeled
off is the offset of the code address being labeled
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintC::emitLabel().
tagLine() [1/2]
void EmitXml::tagLine (int4 indent) virtual
Force a line break and indent level.
Tell the emitter that a new line is desired at a specific indent level. The indent level is overridden only for the line, then it returns to its previous value.
Parameters
indent is the desired indent level for the new line
Reimplemented in EmitPrettyPrint, and EmitNoXml.
tagLine() [2/2]
void EmitXml::tagLine (void) virtual
Force a line break.
Tell the emitter that a new line is desired at the current indent level.
Reimplemented in EmitPrettyPrint.
Referenced by PrintC::docAllGlobals(), PrintC::docFunction(), PrintC::docSingleGlobal(), PrintC::emitBlockBasic(), PrintC::emitBlockDoWhile(), PrintC::emitBlockGoto(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockSwitch(), PrintC::emitBlockWhileDo(), PrintC::emitCommentFuncHeader(), PrintC::emitEnumDefinition(), PrintC::emitLabelStatement(), PrintLanguage::emitLineComment(), PrintC::emitLocalVarDecls(), PrintC::emitStructDefinition(), PrintC::emitSwitchCase(), PrintC::emitVarDeclStatement(), EmitPrettyPrint::overflow(), and EmitPrettyPrint::print().
tagOp()
void EmitXml::tagOp (const char * ptr, syntax_highlight hl, const PcodeOp * op) virtual
Emit an operation token.
The string representing the operation as appropriate for the source language is emitted, possibly with additional markup.
Parameters
ptr is the character data for the emitted representation
hl indicates how the token should be highlighted
op is the PcodeOp object associated with the operation with the syntax tree
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintLanguage::emitAtom(), PrintC::emitBlockDoWhile(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockWhileDo(), PrintLanguage::emitOp(), PrintC::opBranch(), PrintC::opBranchind(), PrintC::opCbranch(), and PrintC::opReturn().
tagType()
void EmitXml::tagType (const char * ptr, syntax_highlight hl, const Datatype * ct) virtual
Emit a data-type identifier.
A string representing the name of a data-type, as appropriate for the source language is emitted, possibly with additional markup.
Parameters
ptr is the character data for the identifier
hl indicates how the identifier should be highlighted
ct is the data-type description object
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintLanguage::emitAtom().
tagVariable()
void EmitXml::tagVariable (const char * ptr, syntax_highlight hl, const Varnode * vn, const PcodeOp * op) virtual
Emit a variable token.
An identifier string representing the variable is output, possibly with additional markup.
Parameters
ptr is the character data for the identifier
hl indicates how the identifier should be highlighted
vn is the Varnode representing the variable within the syntax tree
op is a p-code operation related to the use of the variable (may be null)
Reimplemented in EmitPrettyPrint, and EmitNoXml.
Referenced by PrintLanguage::emitAtom().
Member Data Documentation
highlight
const char * EmitXml::highlight static private
Initial value:
= { "color=\"keyword\"",
                                              "color=\"comment\"",
                                              "color=\"type\"",
                                              "color=\"funcname\"",
                                              "color=\"var\"",
                                              "color=\"const\"",
                                              "color=\"param\"",
                                              "color=\"global\"",
                                              "" }
Map from syntax_highlight enumeration to color attribute string.
Referenced by beginDocument(), and beginFunction().
The documentation for this class was generated from the following files:
prettyprint.hh
prettyprint.cc