decompiler: ParamList Class Reference
ParamList Class Reference abstract
#include <fspec.hh>
Public Types
enum { p_standard, p_standard_out, p_register, p_merged }
Public Member Functions
virtual uint4 getType (void) const =0
Get the type of parameter list.
virtual void assignMap (const vector< Datatype * > &proto, bool isinput, TypeFactory &typefactory, vector< ParameterPieces > &res) const =0
Given list of data-types, map the list positions to storage locations.
virtual void fillinMap (ParamActive *active) const =0
Given an unordered list of storage locations, calculate a function prototype.
virtual bool checkJoin (const Address &hiaddr, int4 hisize, const Address &loaddr, int4 losize) const =0
Check if the given two storage locations can represent a single logical parameter.
virtual bool checkSplit (const Address &loc, int4 size, int4 splitpoint) const =0
Check if it makes sense to split a single storage location into two parameters.
virtual int4 characterizeAsParam (const Address &loc, int4 size) const =0
Characterize whether the given range overlaps parameter storage.
virtual bool possibleParam (const Address &loc, int4 size) const =0
Does the given storage location make sense as a parameter.
virtual bool possibleParamWithSlot (const Address &loc, int4 size, int4 &slot, int4 &slotsize) const =0
Pass-back the slot and slot size for the given storage location as a parameter.
virtual bool getBiggestContainedParam (const Address &loc, int4 size, VarnodeData &res) const =0
Pass-back the biggest parameter contained within the given range.
virtual bool unjustifiedContainer (const Address &loc, int4 size, VarnodeData &res) const =0
Check if the given storage location looks like an unjustified parameter.
virtual OpCode assumedExtension (const Address &addr, int4 size, VarnodeData &res) const =0
Get the type of extension and containing parameter for the given storage.
virtual AddrSpace * getSpacebase (void) const =0
Get the address space associated with any stack based parameters in this list.
virtual void getRangeList (AddrSpace *spc, RangeList &res) const =0
For a given address space, collect all the parameter locations within that space.
virtual int4 getMaxDelay (void) const =0
Return the maximum heritage delay across all possible parameters.
virtual void restoreXml (const Element *el, const AddrSpaceManager *manage, vector< EffectRecord > &effectlist, bool normalstack)=0
Restore the model from an XML stream.
virtual ParamList * clone (void) const =0
Clone this parameter list model.
Detailed Description
A group of ParamEntry objects that form a complete set for passing parameters in one direction (either input or output). The main tasks this class must perform are:
possibleParam() Quick test if a Varnode could ever be a parameter with this prototype
fillinMap() Select trials completing prototype, given analysis info
assignMap() Derive slot->address map, given a list of types
checkJoin() Can two parameters be considered/converted into a single logical parameter
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
p_standard
Standard input parameter model.
p_standard_out
Standard output (return value) model.
p_register
Unordered parameter passing locations model.
p_merged
A merged model (multiple models merged together)
Member Function Documentation
assignMap()
virtual void ParamList::assignMap (const vector< Datatype * > & proto, bool isinput, TypeFactory & typefactory, vector< ParameterPieces > & res) const pure virtual
Given list of data-types, map the list positions to storage locations.
If we know the function prototype, recover how parameters are actually stored using the model.
Parameters
proto is the ordered list of data-types
isinput is true for the input prototype, false for output prototype
typefactory is the TypeFactory (for constructing pointers)
res will contain the storage locations corresponding to the datatypes
Implemented in ParamListMerged, ParamListStandardOut, and ParamListStandard.
Referenced by ProtoModel::assignParameterStorage().
assumedExtension()
virtual OpCode ParamList::assumedExtension (const Address & addr, int4 size, VarnodeData & res) const pure virtual
Get the type of extension and containing parameter for the given storage.
If the given storage is properly contained within a normal parameter and the model typically extends a small value into the full container, pass back the full container and the type of extension.
Parameters
addr is the starting address of the given storage
size is the number of bytes in the given storage
res is the parameter storage to pass back
Returns
the extension operator (INT_ZEXT INT_SEXT) or INT_COPY if there is no extension. INT_PIECE indicates the extension is determined by the specific prototype.
Implemented in ParamListStandard.
Referenced by ProtoModel::assumedInputExtension(), and ProtoModel::assumedOutputExtension().
characterizeAsParam()
virtual int4 ParamList::characterizeAsParam (const Address & loc, int4 size) const pure virtual
Characterize whether the given range overlaps parameter storage.
Does the range naturally fit inside a potential parameter entry from this list or does it contain a parameter entry. Return one of three values indicating this characterization:
0 means there is no intersection between the range and any parameter in this list
1 means that at least one parameter contains the range in a properly justified manner
2 means no parameter contains the range, but the range contains at least one ParamEntry
Parameters
loc is the starting address of the given range
size is the number of bytes in the given range
Returns
the characterization code
Implemented in ParamListStandard.
Referenced by ProtoModel::characterizeAsInputParam().
checkJoin()
virtual bool ParamList::checkJoin (const Address & hiaddr, int4 hisize, const Address & loaddr, int4 losize) const pure virtual
Check if the given two storage locations can represent a single logical parameter.
Within the conventions of this model, do the two (hi/lo) locations represent consecutive parameter locations that can be replaced by a single logical parameter.
Parameters
hiaddr is the address of the most significant part of the value
hisize is the size of the most significant part in bytes
loaddr is the address of the least significant part of the value
losize is the size of the least significant part in bytes
Returns
true if the two pieces can be joined
Implemented in ParamListStandard.
Referenced by ProtoModel::checkInputJoin(), and ProtoModel::checkOutputJoin().
checkSplit()
virtual bool ParamList::checkSplit (const Address & loc, int4 size, int4 splitpoint) const pure virtual
Check if it makes sense to split a single storage location into two parameters.
A storage location and split point is provided, implying two new storage locations. Does this model allow these locations to be considered parameters.
Parameters
loc is the starting address of provided storage location
size is the size of the location in bytes
splitpoint is the number of bytes to consider in the first (in address order) piece
Returns
true if the storage location can be split
Implemented in ParamListStandard.
Referenced by ProtoModel::checkInputSplit().
fillinMap()
virtual void ParamList::fillinMap (ParamActive * active) const pure virtual
Given an unordered list of storage locations, calculate a function prototype.
A list of input (or output) trials is given, which may have holes, invalid inputs etc. Decide on the formal ordered parameter list. Trials within the ParamActive are added, removed, or reordered as needed.
Parameters
active is the given list of trials
Implemented in ParamListMerged, ParamListRegister, ParamListStandardOut, and ParamListStandard.
Referenced by ProtoModel::deriveInputMap(), and ProtoModel::deriveOutputMap().
getBiggestContainedParam()
virtual bool ParamList::getBiggestContainedParam (const Address & loc, int4 size, VarnodeData & res) const pure virtual
Pass-back the biggest parameter contained within the given range.
Parameters
loc is the starting address of the given range
size is the number of bytes in the range
res will hold the parameter storage description being passed back
Returns
true if there is at least one parameter contained in the range
Implemented in ParamListStandard.
Referenced by ProtoModel::getBiggestContainedInputParam().
getMaxDelay()
virtual int4 ParamList::getMaxDelay (void) const pure virtual
Return the maximum heritage delay across all possible parameters.
Depending on the address space, data-flow for a parameter may not be available until extra transform passes have completed. This method returns the number of passes that must occur before we can guarantee that all parameters have data-flow info.
Returns
the maximum number of passes across all parameters in this model
Implemented in ParamListStandard.
Referenced by ProtoModel::getMaxInputDelay(), and ProtoModel::getMaxOutputDelay().
getRangeList()
virtual void ParamList::getRangeList (AddrSpace * spc, RangeList & res) const pure virtual
For a given address space, collect all the parameter locations within that space.
Pass back the memory ranges for any parameter that is stored in the given address space.
Parameters
spc is the given address space
res will hold the set of matching memory ranges
Implemented in ParamListStandard.
Referenced by ProtoModel::restoreXml().
getSpacebase()
virtual AddrSpace* ParamList::getSpacebase (void) const pure virtual
Get the address space associated with any stack based parameters in this list.
Returns
the stack address space, if this models parameters passed on the stack, NULL otherwise
Implemented in ParamListStandard.
possibleParam()
virtual bool ParamList::possibleParam (const Address & loc, int4 size) const pure virtual
Does the given storage location make sense as a parameter.
Within this model, decide if the storage location can be considered a parameter.
Parameters
loc is the starting address of the storage location
size is the number of bytes in the storage location
Returns
true if the location can be a parameter
Implemented in ParamListStandardOut, and ParamListStandard.
Referenced by ProtoModel::possibleInputParam(), and ProtoModel::possibleOutputParam().
possibleParamWithSlot()
virtual bool ParamList::possibleParamWithSlot (const Address & loc, int4 size, int4 & slot, int4 & slotsize) const pure virtual
Pass-back the slot and slot size for the given storage location as a parameter.
This checks if the given storage location acts as a parameter in this model and passes back the number of slots that it occupies.
Parameters
loc is the starting address of the storage location
size is the number of bytes in the storage location
slot if the slot number to pass back
slotsize is the number of consumed slots to pass back
Returns
true if the location can be a parameter
Implemented in ParamListStandard.
Referenced by ProtoModel::possibleInputParamWithSlot(), and ProtoModel::possibleOutputParamWithSlot().
restoreXml()
virtual void ParamList::restoreXml (const Element * el, const AddrSpaceManager * manage, vector< EffectRecord > & effectlist, bool normalstack) pure virtual
Restore the model from an XML stream.
Parameters
el is the root <input> or <output> element
manage is used to resolve references to address spaces
effectlist is a container collecting EffectRecords across all parameters
normalstack is true if parameters are pushed on the stack in the normal order
Implemented in ParamListStandardOut, and ParamListStandard.
Referenced by ProtoModel::restoreXml().
unjustifiedContainer()
virtual bool ParamList::unjustifiedContainer (const Address & loc, int4 size, VarnodeData & res) const pure virtual
Check if the given storage location looks like an unjustified parameter.
The storage for a value may be contained in a normal parameter location but be unjustified within that container, i.e. the least significant bytes are not being used. If this is the case, pass back the full parameter location and return true.
Parameters
loc is the starting address of the given storage
size is the number of bytes in the given storage
res is the full parameter storage to pass back
Returns
true if the given storage is unjustified within its parameter container
Implemented in ParamListStandard.
Referenced by ProtoModel::unjustifiedInputParam().
The documentation for this class was generated from the following file:
fspec.hh