decompiler: VarnodeBank Class Reference
VarnodeBank Class Reference
A container for Varnode objects from a specific function.
#include <varnode.hh>
Public Member Functions
VarnodeBank (AddrSpaceManager *m, AddrSpace *uspace, uintm ubase)
Construct the container.
void clear (void)
Clear out all Varnodes and reset counters.
Varnode * create (int4 s, const Address &m, Datatype *ct)
Create a free Varnode object.
Varnode * createDef (int4 s, const Address &m, Datatype *ct, PcodeOp *op)
Create a Varnode as the output of a PcodeOp.
Varnode * createUnique (int4 s, Datatype *ct)
Create a temporary varnode.
Varnode * createDefUnique (int4 s, Datatype *ct, PcodeOp *op)
Create a temporary Varnode as output of a PcodeOp.
void destroy (Varnode *vn)
Remove a Varnode from the container.
Varnode * setInput (Varnode *vn)
Mark a Varnode as an input to the function.
Varnode * setDef (Varnode *vn, PcodeOp *op)
Change Varnode to be defined by the given PcodeOp.
void makeFree (Varnode *vn)
Convert a Varnode to be free.
void replace (Varnode *oldvn, Varnode *newvn)
Replace every read of one Varnode with another.
Varnode * find (int4 s, const Address &loc, const Address &pc, uintm uniq=~((uintm) 0)) const
Find a Varnode.
Varnode * findInput (int4 s, const Address &loc) const
Find an input Varnode.
Varnode * findCoveredInput (int4 s, const Address &loc) const
Find an input Varnode contained within this range.
Varnode * findCoveringInput (int4 s, const Address &loc) const
Find an input Varnode covering a range.
VarnodeLocSet::const_iterator beginLoc (AddrSpace *spaceid) const
Beginning of Varnodes in given address space sorted by location.
VarnodeLocSet::const_iterator endLoc (AddrSpace *spaceid) const
Ending of Varnodes in given address space sorted by location.
VarnodeLocSet::const_iterator beginLoc (const Address &addr) const
Beginning of Varnodes starting at a given address sorted by location.
VarnodeLocSet::const_iterator endLoc (const Address &addr) const
End of Varnodes starting at a given address sorted by location.
VarnodeLocSet::const_iterator beginLoc (int4 s, const Address &addr) const
Beginning of Varnodes of given size and starting address sorted by location.
VarnodeLocSet::const_iterator endLoc (int4 s, const Address &addr) const
End of Varnodes of given size and starting address sorted by location.
VarnodeLocSet::const_iterator beginLoc (int4 s, const Address &addr, uint4 fl) const
Beginning of Varnodes sorted by location.
VarnodeLocSet::const_iterator endLoc (int4 s, const Address &addr, uint4 fl) const
End of Varnodes sorted by location.
VarnodeLocSet::const_iterator beginLoc (int4 s, const Address &addr, const Address &pc, uintm uniq) const
Beginning of Varnodes sorted by location.
VarnodeLocSet::const_iterator endLoc (int4 s, const Address &addr, const Address &pc, uintm uniq) const
End of Varnodes sorted by location.
VarnodeDefSet::const_iterator beginDef (uint4 fl) const
Beginning of varnodes with set definition property.
VarnodeDefSet::const_iterator endDef (uint4 fl) const
End of varnodes with set definition property.
VarnodeDefSet::const_iterator beginDef (uint4 fl, const Address &addr) const
Beginning of varnodes starting at a given address with a set definition property.
VarnodeDefSet::const_iterator endDef (uint4 fl, const Address &addr) const
End of varnodes starting at a given address with a set definition property.
Private Member Functions
Varnode * xref (Varnode *vn)
Insert a Varnode into the sorted lists.
Private Attributes
AddrSpaceManager * manage
Underlying address space manager.
AddrSpace * uniq_space
Space to allocate unique varnodes from.
uintm uniqbase
Base for unique addresses.
uintm uniqid
Counter for generating unique offsets.
uint4 create_index
Number of varnodes created.
VarnodeLocSet loc_tree
Varnodes sorted by location then def.
VarnodeDefSet def_tree
Varnodes sorted by def then location.
Varnode searchvn
Template varnode for searching trees.
Detailed Description
A container for Varnode objects from a specific function.
The API allows the creation, deletion, search, and iteration of Varnode objects from one function. The class maintains two ordering for efficiency:
Sorting based on storage location (loc)
Sorting based on point of definition (def) The class maintains a last offset counter for allocation temporary Varnode objects in the unique space. Constants are created by passing a constant address to the create() method.
Constructor & Destructor Documentation
VarnodeBank()
VarnodeBank::VarnodeBank (AddrSpaceManager * m, AddrSpace * uspace, uintm ubase)
Construct the container.
Parameters
m is the underlying address space manager
uspace is the unique space
ubase is the base offset for allocating temporaries
References create_index, Varnode::flags, Varnode::input, manage, searchvn, uniq_space, uniqbase, and uniqid.
Member Function Documentation
beginDef() [1/2]
VarnodeDefSet::const_iterator VarnodeBank::beginDef (uint4 fl) const
Beginning of varnodes with set definition property.
Get an iterator to Varnodes in definition order restricted with the following properties:
Varnode::input for Varnodes which are inputs to the function
Varnode::written for Varnodes that are defined by a PcodeOp
0 for free Varnodes
Parameters
fl is the property restriction
Returns
the beginning iterator
References Varnode::def, def_tree, Varnode::flags, Varnode::input, Varnode::loc, Address::m_maximal, Address::m_minimal, searchvn, and Varnode::written.
Referenced by Funcdata::adjustInputVarnodes(), Funcdata::beginDef(), findCoveredInput(), findCoveringInput(), Funcdata::printVarnodeTree(), and Funcdata::setInputVarnode().
beginDef() [2/2]
VarnodeDefSet::const_iterator VarnodeBank::beginDef (uint4 fl, const Address & addr) const
Beginning of varnodes starting at a given address with a set definition property.
Get an iterator to Varnodes in definition order. The starting address of the Varnodes must match the given address, and they are further restricted by the following properties:
Varnode::input for Varnodes which are inputs to the function
Varnode::written for Varnodes that are defined by a PcodeOp
0 for free Varnodes
Parameters
fl is the property restriction
addr is the given starting address
Returns
the beginning iterator
References def_tree, Varnode::flags, Varnode::input, Varnode::loc, searchvn, and Varnode::written.
beginLoc() [1/5]
VarnodeLocSet::const_iterator VarnodeBank::beginLoc (AddrSpace * spaceid) const
Beginning of Varnodes in given address space sorted by location.
Parameters
spaceid is the given address space
Returns
the beginning iterator
References Varnode::loc, loc_tree, and searchvn.
Referenced by Funcdata::beginLoc(), Funcdata::clearDeadVarnodes(), find(), findInput(), Funcdata::findLinkedVarnode(), Funcdata::mapGlobals(), Funcdata::saveXmlTree(), Funcdata::setHighLevel(), Funcdata::spacebase(), and Funcdata::syncVarnodesWithSymbols().
beginLoc() [2/5]
VarnodeLocSet::const_iterator VarnodeBank::beginLoc (const Address & addr) const
Beginning of Varnodes starting at a given address sorted by location.
Parameters
addr is the given starting address
Returns
the beginning iterator
References Varnode::loc, loc_tree, and searchvn.
beginLoc() [3/5]
VarnodeLocSet::const_iterator VarnodeBank::beginLoc (int4 s, const Address & addr) const
Beginning of Varnodes of given size and starting address sorted by location.
Parameters
s is the given size
addr is the given starting address
Returns
the beginning iterator
References Varnode::loc, loc_tree, searchvn, and Varnode::size.
beginLoc() [4/5]
VarnodeLocSet::const_iterator VarnodeBank::beginLoc (int4 s, const Address & addr, const Address & pc, uintm uniq) const
Beginning of Varnodes sorted by location.
Varnodes are restricted by a given size and location and by the sequence number of the PcodeOp defining it
Parameters
s is the given size
addr is the given starting address
pc is the address of the PcodeOp defining the Varnode
uniq is the sequence number of the PcodeOp or -1 for now sequence number restriction
Returns
the beginning iterator
References Varnode::def, Varnode::flags, Varnode::input, Varnode::loc, loc_tree, searchvn, Varnode::size, and Varnode::written.
beginLoc() [5/5]
VarnodeLocSet::const_iterator VarnodeBank::beginLoc (int4 s, const Address & addr, uint4 fl) const
Beginning of Varnodes sorted by location.
Varnodes are restricted by a given size and location and by the property
Varnode::input for Varnodes that are inputs to the function
Varnode::written for Varnodes that are defined by a PcodeOp
0 for free Varnodes
Parameters
s is the given size
addr is the given starting address
fl is the property restriction
Returns
the beginning iterator
References Varnode::def, Varnode::flags, Varnode::input, Varnode::loc, loc_tree, Address::m_maximal, Address::m_minimal, searchvn, Varnode::size, and Varnode::written.
create()
Varnode * VarnodeBank::create (int4 s, const Address & m, Datatype * ct)
Create a free Varnode object.
The Varnode is created and inserted into the maps as free: not defined as the output of a p-code op or the input to a function.
Parameters
s is the size of the Varnode in bytes
m is the starting address
ct is the data-type of the new varnode (must not be NULL)
Returns
the newly allocated Varnode object
References Varnode::create_index, create_index, def_tree, Varnode::defiter, loc_tree, and Varnode::lociter.
Referenced by Funcdata::cloneVarnode(), createUnique(), Funcdata::newCodeRef(), Funcdata::newConstant(), Funcdata::newVarnode(), Funcdata::newVarnodeCallSpecs(), Funcdata::newVarnodeIop(), and Funcdata::newVarnodeSpace().
createDef()
Varnode * VarnodeBank::createDef (int4 s, const Address & m, Datatype * ct, PcodeOp * op)
Create a Varnode as the output of a PcodeOp.
The new Varnode object will already be put in the definition list as if it were the output of the given PcodeOp. The Varnode must still be set as the output.
Parameters
s is the size in bytes
m is the starting address
ct is the data-type to associate
op is the given PcodeOp
References Varnode::create_index, create_index, Varnode::setDef(), and xref().
Referenced by createDefUnique(), and Funcdata::newVarnodeOut().
createDefUnique()
Varnode * VarnodeBank::createDefUnique (int4 s, Datatype * ct, PcodeOp * op)
Create a temporary Varnode as output of a PcodeOp.
The new Varnode will be assigned from the unique space, and it will already be put in the definition list as if it were the output of the given PcodeOp. The Varnode must still be set as the output.
Parameters
s is the size in bytes
ct is the data-type to associate
op is the given PcodeOp
References createDef(), uniq_space, and uniqid.
Referenced by Funcdata::newUniqueOut().
createUnique()
Varnode * VarnodeBank::createUnique (int4 s, Datatype * ct)
Create a temporary varnode.
The Varnode is allocated in the unique space and automatically assigned an offset. The Varnode is initially free.
Parameters
s is the size of the Varnode in bytes
ct is the data-type to assign (must not be NULL)
References create(), uniq_space, and uniqid.
Referenced by Funcdata::newUnique().
destroy()
void VarnodeBank::destroy (Varnode * vn)
Remove a Varnode from the container.
The Varnode object is removed from the sorted lists and its memory reclaimed
Parameters
vn is the Varnode to remove
References def_tree, Varnode::defiter, loc_tree, and Varnode::lociter.
Referenced by Funcdata::clearDeadVarnodes(), and Funcdata::destroyVarnode().
endDef() [1/2]
VarnodeDefSet::const_iterator VarnodeBank::endDef (uint4 fl) const
End of varnodes with set definition property.
Get an iterator to Varnodes in definition order restricted with the following properties:
Varnode::input for Varnodes which are inputs to the function
Varnode::written for Varnodes that are defined by a PcodeOp
0 for free Varnodes
Parameters
fl is the property restriction
Returns
the ending iterator
References Varnode::def, def_tree, Varnode::flags, Varnode::input, Varnode::loc, Address::m_maximal, Address::m_minimal, searchvn, and Varnode::written.
Referenced by Funcdata::adjustInputVarnodes(), Funcdata::endDef(), findCoveredInput(), and Funcdata::printVarnodeTree().
endDef() [2/2]
VarnodeDefSet::const_iterator VarnodeBank::endDef (uint4 fl, const Address & addr) const
End of varnodes starting at a given address with a set definition property.
Get an iterator to Varnodes in definition order. The starting address of the Varnodes must match the given address, and they are further restricted by the following properties:
Varnode::input for Varnodes which are inputs to the function
Varnode::written for Varnodes that are defined by a PcodeOp
0 for free Varnodes
Parameters
fl is the property restriction
addr is the given starting address
Returns
the ending iterator
References def_tree, Varnode::flags, Varnode::input, Varnode::loc, searchvn, Varnode::size, and Varnode::written.
endLoc() [1/5]
VarnodeLocSet::const_iterator VarnodeBank::endLoc (AddrSpace * spaceid) const
Ending of Varnodes in given address space sorted by location.
Parameters
spaceid is the given address space
Returns
the ending iterator
References AddrSpaceManager::getNextSpaceInOrder(), Varnode::loc, loc_tree, manage, and searchvn.
Referenced by Funcdata::clearDeadVarnodes(), Funcdata::endLoc(), Funcdata::findLinkedVarnode(), Funcdata::mapGlobals(), Funcdata::saveXmlTree(), Funcdata::setHighLevel(), Funcdata::spacebase(), Funcdata::syncVarnodesWithSymbol(), and Funcdata::syncVarnodesWithSymbols().
endLoc() [2/5]
VarnodeLocSet::const_iterator VarnodeBank::endLoc (const Address & addr) const
End of Varnodes starting at a given address sorted by location.
Parameters
addr is the given starting address
Returns
the ending iterator
References AddrSpace::getHighest(), AddrSpaceManager::getNextSpaceInOrder(), Address::getOffset(), Address::getSpace(), Varnode::loc, loc_tree, manage, and searchvn.
endLoc() [3/5]
VarnodeLocSet::const_iterator VarnodeBank::endLoc (int4 s, const Address & addr) const
End of Varnodes of given size and starting address sorted by location.
Parameters
s is the given size
addr is the given starting address
Returns
the ending iterator
References Varnode::loc, loc_tree, searchvn, and Varnode::size.
endLoc() [4/5]
VarnodeLocSet::const_iterator VarnodeBank::endLoc (int4 s, const Address & addr, const Address & pc, uintm uniq) const
End of Varnodes sorted by location.
Varnodes are restricted by a given size and location and by the sequence number of the PcodeOp defining it
Parameters
s is the given size
addr is the given starting address
pc is the address of the PcodeOp defining the Varnode
uniq is the sequence number of the PcodeOp or -1 for now sequence number restriction
Returns
the ending iterator
References Varnode::def, Varnode::flags, Varnode::input, Varnode::loc, loc_tree, searchvn, Varnode::size, and Varnode::written.
endLoc() [5/5]
VarnodeLocSet::const_iterator VarnodeBank::endLoc (int4 s, const Address & addr, uint4 fl) const
End of Varnodes sorted by location.
Varnodes are restricted by a given size and location and by the property
Varnode::input for Varnodes that are inputs to the function
Varnode::written for Varnodes that are defined by a PcodeOp
0 for free Varnodes
Parameters
s is the given size
addr is the given starting address
fl is the property restriction
Returns
the ending iterator
References Varnode::def, Varnode::flags, Varnode::input, Varnode::loc, loc_tree, Address::m_maximal, searchvn, Varnode::size, and Varnode::written.
find()
Varnode * VarnodeBank::find (int4 s, const Address & loc, const Address & pc, uintm uniq = ~((uintm)0)) const
Find a Varnode.
Find a Varnode given its (loc,size) and the address where it is defined.
Parameters
s is the size of the Varnode
loc is its starting address
pc is the address where it is defined
uniq is the sequence number or -1 if not specified
Returns
the matching Varnode or NULL
References beginLoc(), and loc_tree.
Referenced by Funcdata::findVarnodeWritten().
findCoveredInput()
Varnode * VarnodeBank::findCoveredInput (int4 s, const Address & loc) const
Find an input Varnode contained within this range.
Find the first Varnode completely contained within the given range, which is also marked as a function input.
Parameters
s is the size of the range
loc is the starting address of the range
Returns
the Varnode object or NULL if no Varnode met the conditions
References beginDef(), endDef(), AddrSpace::getHighest(), Address::getOffset(), Address::getSpace(), and Varnode::input.
Referenced by Funcdata::findCoveredInput().
findCoveringInput()
Varnode * VarnodeBank::findCoveringInput (int4 s, const Address & loc) const
Find an input Varnode covering a range.
Search for the Varnode that completely contains the given range and is marked as an input to the function. If it exists, it is unique.
Parameters
s is the size of the range
loc is the starting address of the range
References beginDef(), def_tree, Address::getOffset(), Address::getSpace(), and Varnode::input.
Referenced by Funcdata::findCoveringInput().
findInput()
Varnode * VarnodeBank::findInput (int4 s, const Address & loc) const
Find an input Varnode.
Find a Varnode marked as a function input given its size and address
Parameters
s is the size
loc is the starting address
Returns
the match Varnode object or NULL
References beginLoc(), Varnode::input, and loc_tree.
Referenced by Funcdata::findSpacebaseInput(), and Funcdata::findVarnodeInput().
makeFree()
void VarnodeBank::makeFree (Varnode * vn)
Convert a Varnode to be free.
The Varnode is removed from the cross-referencing lists and reinserted as as if it were not defined by any PcodeOp and not an input to the function. If the Varnode was originally a PcodeOp output, this must be explicitly cleared.
Parameters
vn is the Varnode to modify
References Varnode::clearFlags(), def_tree, Varnode::defiter, Varnode::indirect_creation, Varnode::input, Varnode::insert, loc_tree, Varnode::lociter, and Varnode::setDef().
Referenced by Funcdata::clearDeadVarnodes(), and Funcdata::opUnsetOutput().
replace()
void VarnodeBank::replace (Varnode * oldvn, Varnode * newvn)
Replace every read of one Varnode with another.
Any PcodeOps that read oldvn are changed to read newvn
Parameters
oldvn is the old Varnode
newvn is the Varnode to replace it with
References Varnode::addDescend(), Varnode::coverdirty, Varnode::descend, PcodeOp::getSlot(), PcodeOp::output, and Varnode::setFlags().
Referenced by xref().
setDef()
Varnode * VarnodeBank::setDef (Varnode * vn, PcodeOp * op)
Change Varnode to be defined by the given PcodeOp.
The Varnode must initially be free. It will be removed from the cross-referencing lists and reinserted as if its were the output of the given PcodeOp. It still must be explicitly set as the output.
Parameters
vn is the Varnode to modify
op is the given PcodeOp
Returns
the modified Varnode, which may be a different object than the original
References def_tree, Varnode::defiter, Address::getShortcut(), loc_tree, Varnode::lociter, Address::printRaw(), Varnode::setDef(), and xref().
Referenced by Funcdata::opSetOutput().
setInput()
Varnode * VarnodeBank::setInput (Varnode * vn)
Mark a Varnode as an input to the function.
Define the Varnode as an input formally; it is no longer considered free. Its position in the cross-referencing lists will change
Parameters
vn is the Varnode to mark
Returns
the modified Varnode, which be a different object than the original
References def_tree, Varnode::defiter, loc_tree, Varnode::lociter, and xref().
Referenced by Funcdata::setInputVarnode().
xref()
Varnode * VarnodeBank::xref (Varnode * vn) private
Insert a Varnode into the sorted lists.
Enter the Varnode into both the location and definition based trees. Update the Varnode iterators and flags
Parameters
vn is the Varnode object to insert
Returns
the inserted object, which may not be the same as the input Varnode
References def_tree, Varnode::defiter, Varnode::insert, loc_tree, Varnode::lociter, replace(), and Varnode::setFlags().
Referenced by createDef(), setDef(), and setInput().
The documentation for this class was generated from the following files:
varnode.hh
varnode.cc