decompiler: RulePopcountBoolXor Class Reference
RulePopcountBoolXor Class Reference
Simplify boolean expressions that are combined through POPCOUNT.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Public Member Functions
static Varnode * getBooleanResult (Varnode *vn, int4 bitPos, int4 &constRes)
Extract boolean Varnode producing bit at given Varnode and position.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Simplify boolean expressions that are combined through POPCOUNT.
Expressions involving boolean values (b1 and b2) are converted, such as:
popcount((b1 << 6) | (b2 << 2)) & 1 => b1 ^ b2
Member Function Documentation
applyOp()
int4 RulePopcountBoolXor::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References CPUI_COPY, CPUI_INT_AND, CPUI_INT_XOR, leastsigbit_set(), mostsigbit_set(), Funcdata::newConstant(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and popcount().
clone()
virtual Rule* RulePopcountBoolXor::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
getBooleanResult()
Varnode * RulePopcountBoolXor::getBooleanResult (Varnode * vn, int4 bitPos, int4 & constRes) static
Extract boolean Varnode producing bit at given Varnode and position.
The boolean value may be shifted, extended and combined with other booleans through a series of operations. We return the Varnode that is the actual result of the boolean operation. If the given Varnode is constant, return null but pass back whether the given bit position is 0 or 1. If no boolean value can be found, return null and pass back -1.
Parameters
vn is the given Varnode containing the extended/shifted boolean
bitPos is the bit position of the desired boolean value
constRes is used to pass back a constant boolean result
Returns
the boolean Varnode producing the desired value or null
References CPUI_INT_AND, CPUI_INT_LEFT, CPUI_INT_OR, CPUI_INT_RIGHT, CPUI_INT_SEXT, CPUI_INT_SRIGHT, CPUI_INT_XOR, CPUI_INT_ZEXT, CPUI_PIECE, and CPUI_SUBPIECE.
getOpList()
void RulePopcountBoolXor::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_POPCOUNT.
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc