decompiler: ProtoStoreInternal Class Reference
ProtoStoreInternal Class Reference
A collection of parameter descriptions without backing symbols.
#include <fspec.hh>
Public Member Functions
ProtoStoreInternal (Datatype *vt)
Constructor.
virtual ProtoParameter * setInput (int4 i, const string &nm, const ParameterPieces &pieces)
Establish name, data-type, storage of a specific input parameter.
virtual void clearInput (int4 i)
Clear the input parameter at the specified slot.
virtual void clearAllInputs (void)
Clear all input parameters (and any backing symbols)
virtual int4 getNumInputs (void) const
Get the number of input parameters for this prototype.
virtual ProtoParameter * getInput (int4 i)
Get the i-th input parameter (or NULL if it doesn't exist)
virtual ProtoParameter * setOutput (const ParameterPieces &piece)
Establish the data-type and storage of the return value.
virtual void clearOutput (void)
Clear the return value to TYPE_VOID.
virtual ProtoParameter * getOutput (void)
Get the return-value description.
virtual ProtoStore * clone (void) const
Clone the entire collection of parameter descriptions.
virtual void saveXml (ostream &s) const
Save any parameters that are not backed by symbols to an XML stream.
virtual void restoreXml (const Element *el, ProtoModel *model)
Restore any internal parameter descriptions from an XML stream.
Private Attributes
Datatype * voidtype
Cached reference to the void data-type.
vector< ProtoParameter * > inparam
Descriptions of input parameters.
ProtoParameter * outparam
Description of the return value.
Detailed Description
A collection of parameter descriptions without backing symbols.
Parameter descriptions are stored internally to the object and are not mirrored by a symbol table.
Constructor & Destructor Documentation
ProtoStoreInternal()
ProtoStoreInternal::ProtoStoreInternal (Datatype * vt)
Constructor.
Parameters
vt is the void data-type used for an unspecified return value
References ParameterPieces::flags, outparam, setOutput(), ParameterPieces::type, and voidtype.
Referenced by clone().
Member Function Documentation
clearInput()
void ProtoStoreInternal::clearInput (int4 i) virtual
Clear the input parameter at the specified slot.
The parameter is excised, any following parameters are shifted to fill its spot. If there is a backing Symbol, it is removed from the SymbolTable
Parameters
i is the specified parameter slot to remove
Implements ProtoStore.
References inparam.
restoreXml()
void ProtoStoreInternal::restoreXml (const Element * el, ProtoModel * model) virtual
Restore any internal parameter descriptions from an XML stream.
Parameters
el is a root <internallist> element containing <param> and <retparam> sub-tags.
model is prototype model for determining storage for unassigned parameters
Implements ProtoStore.
References ParameterPieces::addr, ProtoModel::assignParameterStorage(), ParameterPieces::flags, ProtoParameter::getAddress(), Element::getAttributeValue(), ProtoParameter::getType(), Varnode::hiddenretparm, Varnode::indirectstorage, ProtoParameter::isIndirectStorage(), Address::isInvalid(), ProtoParameter::isTypeLocked(), outparam, Address::restoreXml(), TypeFactory::restoreXmlType(), setInput(), ProtoParameter::setNameLock(), setOutput(), ProtoParameter::setTypeLock(), ParameterPieces::type, Architecture::types, and xml_readbool().
saveXml()
void ProtoStoreInternal::saveXml (ostream & s) const virtual
Save any parameters that are not backed by symbols to an XML stream.
Symbols are stored elsewhere, so symbol backed parameters are not serialized. If there are any internal parameters an <internallist> tag is emitted.
Parameters
s is the output stream
Implements ProtoStore.
References a_v(), a_v_b(), ProtoParameter::getAddress(), ProtoParameter::getName(), ProtoParameter::getType(), inparam, ProtoParameter::isHiddenReturn(), ProtoParameter::isIndirectStorage(), ProtoParameter::isNameLocked(), ProtoParameter::isTypeLocked(), outparam, Address::saveXml(), and Datatype::saveXml().
setInput()
ProtoParameter * ProtoStoreInternal::setInput (int4 i, const string & nm, const ParameterPieces & pieces) virtual
Establish name, data-type, storage of a specific input parameter.
This either allocates a new parameter or replaces the existing one at the specified input slot. If there is a backing symbol table, a Symbol is created or modified.
Parameters
i is the specified input slot
nm is the (optional) name of the parameter
pieces holds the raw storage address and data-type to set
Returns
the new/modified ProtoParameter
Implements ProtoStore.
References ParameterPieces::addr, ParameterPieces::flags, inparam, and ParameterPieces::type.
Referenced by restoreXml().
setOutput()
ProtoParameter * ProtoStoreInternal::setOutput (const ParameterPieces & piece) virtual
Establish the data-type and storage of the return value.
This either allocates a new parameter or replaces the existing one. A void return value can be specified with an invalid address and TYPE_VOID data-type.
Parameters
piece holds the raw storage address and data-type to set
Returns
the new/modified ProtoParameter
Implements ProtoStore.
References ParameterPieces::addr, ParameterPieces::flags, outparam, and ParameterPieces::type.
Referenced by ProtoStoreInternal(), and restoreXml().
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc