decompiler: Architecture Class Reference
Architecture Class Reference abstract
Manager for all the major decompiler subsystems.
#include <architecture.hh>
Public Member Functions
Architecture (void)
Construct an uninitialized Architecture.
void init (DocumentStorage &store)
Load the image and configure architecture.
ProtoModel * getModel (const string &nm) const
Get a specific PrototypeModel.
bool hasModel (const string &nm) const
Does this Architecture have a specific PrototypeModel.
bool highPtrPossible (const Address &loc, int4 size) const
Are pointers possible to the given location?
AddrSpace * getSpaceBySpacebase (const Address &loc, int4 size) const
Get space associated with a spacebase register.
const LanedRegister * getLanedRegister (const Address &loc, int4 size) const
Get LanedRegister associated with storage.
int4 getMinimumLanedRegisterSize (void) const
Get the minimum size of a laned register in bytes.
void setDefaultModel (const string &nm)
Set the default PrototypeModel.
void clearAnalysis (Funcdata *fd)
Clear analysis specific to a function.
void readLoaderSymbols (void)
Read any symbols from loader into database.
void collectBehaviors (vector< OpBehavior * > &behave) const
Provide a list of OpBehavior objects.
SegmentOp * getSegmentOp (AddrSpace *spc) const
Retrieve the segment op for the given space if any.
void setPrototype (const PrototypePieces &pieces)
Set the prototype for a particular function.
void setPrintLanguage (const string &nm)
Establish a particular output language.
void globalify (void)
Mark all spaces as global.
void restoreFlowOverride (const Element *el)
Set flow overrides from XML.
virtual ~Architecture (void)
Destructor.
virtual void printMessage (const string &message) const =0
Print an error message to console.
virtual void saveXml (ostream &s) const
Serialize this architecture to XML.
virtual void restoreXml (DocumentStorage &store)
Restore the Architecture state from an XML stream.
virtual void nameFunction (const Address &addr, string &name) const
Pick a default name for a function.
Public Member Functions inherited from AddrSpaceManager
AddrSpaceManager (void)
Construct an empty address space manager.
virtual ~AddrSpaceManager (void)
Destroy the manager.
int4 getDefaultSize (void) const
Get size of addresses for the default space.
AddrSpace * getSpaceByName (const string &nm) const
Get address space by name.
AddrSpace * getSpaceByShortcut (char sc) const
Get address space from its shortcut.
AddrSpace * getIopSpace (void) const
Get the internal pcode op space.
AddrSpace * getFspecSpace (void) const
Get the internal callspec space.
AddrSpace * getJoinSpace (void) const
Get the joining space.
AddrSpace * getStackSpace (void) const
Get the stack space for this processor.
AddrSpace * getUniqueSpace (void) const
Get the temporary register space for this processor.
AddrSpace * getDefaultCodeSpace (void) const
Get the default address space of this processor.
AddrSpace * getDefaultDataSpace (void) const
Get the default address space where data is stored.
AddrSpace * getConstantSpace (void) const
Get the constant space.
Address getConstant (uintb val) const
Get a constant encoded as an Address.
Address createConstFromSpace (AddrSpace *spc) const
Create a constant address encoding an address space.
Address resolveConstant (AddrSpace *spc, uintb val, int4 sz, const Address &point, uintb &fullEncoding) const
Resolve a native constant into an Address.
int4 numSpaces (void) const
Get the number of address spaces for this processor.
AddrSpace * getSpace (int4 i) const
Get an address space via its index.
AddrSpace * getNextSpaceInOrder (AddrSpace *spc) const
Get the next contiguous address space.
JoinRecord * findAddJoin (const vector< VarnodeData > &pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
JoinRecord * findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
void setDeadcodeDelay (AddrSpace *spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
void truncateSpace (const TruncationTag &tag)
Mark a space as truncated from its original size.
Address constructFloatExtensionAddress (const Address &realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
Address constructJoinAddress (const Translate *translate, const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz)
Build a logical whole from register pairs.
void renormalizeJoinAddress (Address &addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
Public Attributes
string archid
ID string uniquely describing this architecture.
int4 trim_recurse_max
How many levels to let parameter trims recurse.
int4 max_implied_ref
Maximum number of references to an implied var.
int4 max_term_duplication
Max terms duplicated without a new variable.
int4 max_basetype_size
Maximum size of an "integer" type before creating an array type.
int4 min_funcsymbol_size
Minimum size of a function symbol.
bool aggressive_ext_trim
Aggressively trim inputs that look like they are sign extended.
bool readonlypropagate
true if readonly values should be treated as constants
bool infer_pointers
True if we should infer pointers from constants that are likely addresses.
vector< AddrSpace * > inferPtrSpaces
Set of address spaces in which a pointer constant is inferable.
int4 funcptr_align
How many bits of alignment a function ptr has.
uint4 flowoptions
options passed to flow following engine
int4 alias_block_level
Aliases blocked by 0=none, 1=struct, 2=array, 3=all.
vector< Rule * > extra_pool_rules
Extra rules that go in the main pool (cpu specific, experimental)
Database * symboltab
Memory map of global variables and functions.
ContextDatabase * context
Map from addresses to context settings.
map< string, ProtoModel * > protoModels
Parsed forms of possible prototypes.
ProtoModel * defaultfp
Parsed form of default prototype.
VarnodeData defaultReturnAddr
Default storage location of return address (for current function)
ProtoModel * evalfp_current
Function proto to use when evaluating current function.
ProtoModel * evalfp_called
Function proto to use when evaluating called functions.
TypeFactory * types
List of types for this binary.
const Translate * translate
Translation method for this binary.
LoadImage * loader
Method for loading portions of binary.
PcodeInjectLibrary * pcodeinjectlib
Pcode injection manager.
RangeList nohighptr
Ranges for which high-level pointers are not possible.
CommentDatabase * commentdb
Comments for this architecture.
ConstantPool * cpool
Deferred constant values.
PrintLanguage * print
Current high-level language printer.
vector< PrintLanguage * > printlist
List of high-level language printers supported.
OptionDatabase * options
Options that can be configured.
vector< TypeOp * > inst
Registered p-code instructions.
UserOpManage userops
Specifically registered user-defined p-code ops.
vector< PreferSplitRecord > splitrecords
registers that we would prefer to see split for this processor
vector< LanedRegister > lanerecords
Vector registers that have preferred lane sizes.
ActionDatabase allacts
Actions that can be applied in this architecture.
bool loadersymbols_parsed
True if loader symbols have been read.
Protected Member Functions
void addSpacebase (AddrSpace *basespace, const string &nm, const VarnodeData &ptrdata, int4 truncSize, bool isreversejustified, bool stackGrowth)
Create a new space and associated pointer.
void addNoHighPtr (const Range &rng)
Add a new region where pointers do not exist.
virtual Scope * buildGlobalScope (void)
Build the global scope for this executable.
virtual Translate * buildTranslator (DocumentStorage &store)=0
Build the Translator object.
virtual void buildLoader (DocumentStorage &store)=0
Build the LoadImage object and load the executable image.
virtual PcodeInjectLibrary * buildPcodeInjectLibrary (void)=0
Build the injection library.
virtual void buildTypegrp (DocumentStorage &store)
Build the data-type factory/container.
virtual void buildCommentDB (DocumentStorage &store)
Build the comment database.
virtual void buildConstantPool (DocumentStorage &store)
Build the constant pool.
virtual void buildInstructions (DocumentStorage &store)
Register the p-code operations.
virtual void buildAction (DocumentStorage &store)
Build the Action framework.
virtual void buildContext (DocumentStorage &store)
Build the Context database.
virtual void buildSpecFile (DocumentStorage &store)=0
Load any relevant specification files.
virtual void modifySpaces (Translate *trans)=0
Modify address spaces as required by this Architecture.
virtual void postSpecFile (void)
Let components initialize after Translate is built.
virtual void resolveArchitecture (void)=0
Figure out the processor and compiler of the target executable.
void restoreFromSpec (DocumentStorage &store)
Fully initialize the Translate object.
void fillinReadOnlyFromLoader (void)
Load info about read-only sections.
void initializeSegments ()
Set up segment resolvers.
void cacheAddrSpaceProperties (void)
Calculate some frequently used space properties and cache them.
void parseProcessorConfig (DocumentStorage &store)
Apply processor specific configuration.
void parseCompilerConfig (DocumentStorage &store)
Apply compiler specific configuration.
void parseExtraRules (DocumentStorage &store)
Apply any Rule tags.
void parseDynamicRule (const Element *el)
Apply details of a dynamic Rule object.
ProtoModel * parseProto (const Element *el)
Build a proto-type model from an XML tag.
void parseProtoEval (const Element *el)
Apply prototype evaluation configuration.
void parseDefaultProto (const Element *el)
Apply default prototype model configuration.
void parseGlobal (const Element *el)
Apply global space configuration.
void addOtherSpace (void)
Add OTHER space and all of its overlays to the symboltab.
void parseReadOnly (const Element *el)
Apply read-only region configuration.
void parseVolatile (const Element *el)
Apply volatile region configuration.
void parseReturnAddress (const Element *el)
Apply return address configuration.
void parseIncidentalCopy (const Element *el)
Apply incidental copy configuration.
void parseLaneSizes (const Element *el)
Apply lane size configuration.
void parseStackPointer (const Element *el)
Apply stack pointer configuration.
void parseDeadcodeDelay (const Element *el)
Apply dead-code delay configuration.
void parseFuncPtrAlign (const Element *el)
Apply function pointer alignment configuration.
void parseSpacebase (const Element *el)
Create an additional indexed space.
void parseNoHighPtr (const Element *el)
Apply memory alias configuration.
void parsePreferSplit (const Element *el)
Designate registers to be split.
void parseAggressiveTrim (const Element *el)
Designate how to trim extension p-code ops.
Protected Member Functions inherited from AddrSpaceManager
AddrSpace * restoreXmlSpace (const Element *el, const Translate *trans)
Add a space to the model based an on XML tag.
void restoreXmlSpaces (const Element *el, const Translate *trans)
Restore address spaces in the model from an XML tag.
void setDefaultCodeSpace (int4 index)
Set the default address space (for code)
void setDefaultDataSpace (int4 index)
Set the default address space for data.
void setReverseJustified (AddrSpace *spc)
Set reverse justified property on this space.
void assignShortcut (AddrSpace *spc)
Select a shortcut character for a new space.
void markNearPointers (AddrSpace *spc, int4 size)
Mark that given space can be accessed with near pointers.
void insertSpace (AddrSpace *spc)
Add a new address space to the model.
void copySpaces (const AddrSpaceManager *op2)
Copy spaces from another manager.
void addSpacebasePointer (SpacebaseSpace *basespace, const VarnodeData &ptrdata, int4 truncSize, bool stackGrowth)
Set the base register of a spacebase space.
void insertResolver (AddrSpace *spc, AddressResolver *rsolv)
Override the base resolver for a space.
JoinRecord * findJoinInternal (uintb offset) const
Find JoinRecord for offset in the join space.
Detailed Description
Manager for all the major decompiler subsystems.
An instantiation is tailored to a specific LoadImage, processor, and compiler spec. This class is the owner of the LoadImage, Translate, symbols (Database), PrintLanguage, etc. This class also holds numerous configuration parameters for the analysis process
Constructor & Destructor Documentation
Architecture()
Architecture::Architecture (void)
Construct an uninitialized Architecture.
Set most sub-components to null pointers. Provide reasonable defaults for the configurable options
References aggressive_ext_trim, alias_block_level, PrintLanguageCapability::buildLanguage(), commentdb, context, cpool, defaultfp, defaultReturnAddr, evalfp_called, evalfp_current, flowoptions, funcptr_align, PrintLanguageCapability::getDefault(), infer_pointers, loader, loadersymbols_parsed, max_basetype_size, max_implied_ref, max_term_duplication, min_funcsymbol_size, options, pcodeinjectlib, print, printlist, readonlypropagate, VarnodeData::space, symboltab, translate, trim_recurse_max, and types.
~Architecture()
Architecture::~Architecture (void) virtual
Destructor.
Release resources for all sub-components.
References commentdb, context, cpool, extra_pool_rules, inst, loader, options, pcodeinjectlib, printlist, protoModels, symboltab, translate, and types.
Member Function Documentation
addNoHighPtr()
void Architecture::addNoHighPtr (const Range & rng) protected
Add a new region where pointers do not exist.
This routine is used by the initialization process to add address ranges to which there is never an (indirect) pointer Should only be called during initialization
Parameters
rng is the new range with no aliases to be added
References RangeList::insertRange(), and nohighptr.
Referenced by parseNoHighPtr().
addSpacebase()
void Architecture::addSpacebase (AddrSpace * basespace, const string & nm, const VarnodeData & ptrdata, int4 truncSize, bool isreversejustified, bool stackGrowth) protected
Create a new space and associated pointer.
This process sets up a "register relative" space for this architecture If the name is "stack", this space takes on the role of an "official" stack space Should only be called once during initialization
Parameters
basespace is the address space underlying the stack
nm is the name of the new space
ptrdata is the register location acting as a pointer into the new space
truncSize is the (possibly truncated) size of the register that fits the space
isreversejustified is true if small variables are justified opposite of endianness
stackGrowth is true if a stack implemented in this space grows in the negative direction
References AddrSpaceManager::addSpacebasePointer(), AddrSpace::getDelay(), AddrSpaceManager::insertSpace(), AddrSpaceManager::numSpaces(), AddrSpaceManager::setReverseJustified(), VarnodeData::space, and translate.
Referenced by parseSpacebase(), and parseStackPointer().
buildAction()
void Architecture::buildAction (DocumentStorage & store) protected virtual
Build the Action framework.
This builds the universal Action for function transformation and instantiates the "decompile" root Action
Parameters
store may hold configuration information
References allacts, parseExtraRules(), ActionDatabase::setCurrent(), and universal_action().
Referenced by restoreFromSpec().
buildCommentDB()
void Architecture::buildCommentDB (DocumentStorage & store) protected virtual
Build the comment database.
Build the container that holds comments for executable in this Architecture.
Parameters
store may hold configuration information
Reimplemented in ArchitectureGhidra.
References commentdb.
Referenced by init().
buildConstantPool()
void Architecture::buildConstantPool (DocumentStorage & store) protected virtual
Build the constant pool.
Some processor models (Java byte-code) need a database of constants. The database is always built, but may remain empty.
Parameters
store may hold configuration information
Reimplemented in ArchitectureGhidra.
References cpool.
Referenced by init().
buildContext()
void Architecture::buildContext (DocumentStorage & store) protected virtual
Build the Context database.
This builds the database which holds the status registers setings and other information that can affect disassembly depending on context.
Parameters
store may hold configuration information
Reimplemented in ArchitectureGhidra.
References context.
Referenced by init().
buildGlobalScope()
Scope * Architecture::buildGlobalScope (void) protected virtual
Build the global scope for this executable.
If it does not already exist create the glocal Scope object
Returns
the global Scope object
Reimplemented in ArchitectureGhidra.
References Database::attachScope(), and symboltab.
Referenced by addOtherSpace(), globalify(), and parseGlobal().
buildInstructions()
void Architecture::buildInstructions (DocumentStorage & store) protected virtual
Register the p-code operations.
This registers the OpBehavior objects for all known p-code OpCodes. The Translate and TypeFactory object should already be built.
Parameters
store may hold configuration information
References inst, TypeOp::registerInstructions(), translate, and types.
Referenced by init().
buildLoader()
virtual void Architecture::buildLoader (DocumentStorage & store) protected pure virtual
Build the LoadImage object and load the executable image.
Parameters
store may hold configuration information
Implemented in ArchitectureGhidra, BfdArchitecture, RawBinaryArchitecture, and XmlArchitecture.
Referenced by init().
buildPcodeInjectLibrary()
virtual PcodeInjectLibrary* Architecture::buildPcodeInjectLibrary (void) protected pure virtual
Build the injection library.
This creates the container for p-code injections. It is initially empty.
Returns
the PcodeInjectLibrary object
Implemented in SleighArchitecture, and ArchitectureGhidra.
Referenced by restoreFromSpec().
buildSpecFile()
virtual void Architecture::buildSpecFile (DocumentStorage & store) protected pure virtual
Load any relevant specification files.
Processor/architecture specific configuration files are loaded into the XML store
Parameters
store is the document store that will hold the configuration
Implemented in SleighArchitecture, and ArchitectureGhidra.
Referenced by init().
buildTranslator()
virtual Translate* Architecture::buildTranslator (DocumentStorage & store) protected pure virtual
Build the Translator object.
This builds the main disassembly component for the Architecture This does not initially the engine for a specific processor.
Parameters
store may hold configuration information
Returns
the Translate object
Implemented in SleighArchitecture, and ArchitectureGhidra.
Referenced by restoreFromSpec().
buildTypegrp()
void Architecture::buildTypegrp (DocumentStorage & store) protected virtual
Build the data-type factory/container.
This builds the TypeFactory object specific to this architecture and prepopulates it with the core types. Core types may be pulled from the configuration information, or default core types are used.
Parameters
store contains possible configuration information
Reimplemented in ArchitectureGhidra.
References TypeFactory::cacheCoreTypes(), DocumentStorage::getTag(), TypeFactory::restoreXmlCoreTypes(), TypeFactory::setCoreType(), TYPE_BOOL, TYPE_CODE, TYPE_FLOAT, TYPE_INT, TYPE_UINT, TYPE_UNKNOWN, TYPE_VOID, and types.
Referenced by init().
cacheAddrSpaceProperties()
void Architecture::cacheAddrSpaceProperties (void) protected
Calculate some frequently used space properties and cache them.
Determine the minimum pointer size for the space and whether or not there are near pointers. Set up an ordered list of inferable spaces (where constant pointers can be infered). Inferable spaces include the default space and anything explicitly listed in the cspec <global> tag that is not a register space. An initial list of potential spaces is passed in that needs to be ordered, filtered, and deduplicated.
References AddrSpace::compareByIndex(), AddrSpaceManager::getDefaultCodeSpace(), AddrSpaceManager::getDefaultDataSpace(), AddrSpace::getDelay(), getSegmentOp(), AddrSpace::getType(), inferPtrSpaces, IPTR_SPACEBASE, AddrSpace::isOtherSpace(), AddrSpace::isOverlay(), and AddrSpaceManager::markNearPointers().
Referenced by postSpecFile().
clearAnalysis()
void Architecture::clearAnalysis (Funcdata * fd)
Clear analysis specific to a function.
Throw out the syntax tree, (unlocked) symbols, comments, and other derived information about a single function.
Parameters
fd is the function to clear
References Funcdata::clear(), CommentDatabase::clearType(), commentdb, Comment::warning, and Comment::warningheader.
collectBehaviors()
void Architecture::collectBehaviors (vector< OpBehavior * > & behave) const
Provide a list of OpBehavior objects.
For all registered p-code opcodes, return the corresponding OpBehavior object. The object pointers are provided in a list indexed by OpCode.
Parameters
behave is the list to be populated
References inst.
Referenced by PcodeInjectLibraryGhidra::getBehaviors().
fillinReadOnlyFromLoader()
void Architecture::fillinReadOnlyFromLoader (void) protected
Load info about read-only sections.
The LoadImage may have access information about the executables sections. Query for any read-only ranges and store this information in the property database
References LoadImage::getReadonly(), loader, Varnode::readonly, Database::setPropertyRange(), and symboltab.
Referenced by init().
getLanedRegister()
const LanedRegister * Architecture::getLanedRegister (const Address & loc, int4 size) const
Get LanedRegister associated with storage.
Look-up the laned register record associated with a specific storage location. Currently, the record is only associated with the size of the storage, not its address. If there is no associated record, null is returned.
Parameters
loc is the starting address of the storage location
size is the size of the storage in bytes
Returns
the matching LanedRegister record or null
References lanerecords.
Referenced by ActionVarnodeProps::markLanedVarnode().
getMinimumLanedRegisterSize()
int4 Architecture::getMinimumLanedRegisterSize (void) const
Get the minimum size of a laned register in bytes.
Return a size intended for comparison with a Varnode size to immediately determine if the Varnode is a potential laned register. If there are no laned registers for the architecture, -1 is returned.
Returns
the size in bytes of the smallest laned register or -1.
References lanerecords.
Referenced by ActionVarnodeProps::apply().
getModel()
ProtoModel * Architecture::getModel (const string & nm) const
Get a specific PrototypeModel.
The Architecture maintains the set of prototype models that can be applied for this particular executable. Retrieve one by name. The model must exist or an exception is thrown.
Parameters
nm is the name
Returns
the matching model
References protoModels.
Referenced by ProtoModelMerged::restoreXml(), FuncProto::restoreXml(), and setDefaultModel().
getSegmentOp()
SegmentOp * Architecture::getSegmentOp (AddrSpace * spc) const
Retrieve the segment op for the given space if any.
This method searches for a user-defined segment op registered for the given space.
Parameters
spc is the address space to check
Returns
the SegmentOp object or null
References AddrSpace::getIndex(), UserOpManage::getSegmentOp(), and userops.
Referenced by cacheAddrSpaceProperties().
getSpaceBySpacebase()
AddrSpace * Architecture::getSpaceBySpacebase (const Address & loc, int4 size) const
Get space associated with a spacebase register.
Get the address space associated with the indicated spacebase register. I.e. if the location of the stack pointer is passed in, this routine would return a pointer to the stack space. An exception is thrown if no corresponding space is found.
Parameters
loc is the location of the spacebase register
size is the size of the register in bytes
Returns
a pointer to the address space
References Address::getOffset(), Address::getSpace(), AddrSpaceManager::getSpace(), AddrSpace::getSpacebase(), AddrSpaceManager::numSpaces(), VarnodeData::offset, VarnodeData::size, and VarnodeData::space.
Referenced by RuleLoadVarnode::correctSpacebase().
globalify()
void Architecture::globalify (void)
Mark all spaces as global.
Set all IPTR_PROCESSOR and IPTR_SPACEBASE spaces to be global.
References Database::addRange(), buildGlobalScope(), AddrSpace::getHighest(), AddrSpaceManager::getSpace(), AddrSpace::getType(), IPTR_PROCESSOR, IPTR_SPACEBASE, AddrSpaceManager::numSpaces(), and symboltab.
hasModel()
bool Architecture::hasModel (const string & nm) const
Does this Architecture have a specific PrototypeModel.
Parameters
nm is the name of the model
Returns
true if this Architecture supports a model with that name
References protoModels.
highPtrPossible()
bool Architecture::highPtrPossible (const Address & loc, int4 size) const inline
Are pointers possible to the given location?
The Translate object keeps track of address ranges for which it is effectively impossible to have a pointer into. This is used for pointer aliasing calculations. This routine returns true if it is possible to have pointers into the indicated range.
Parameters
loc is the starting address of the range
size is the size of the range in bytes
Returns
true if pointers are possible
References Address::getSpace(), AddrSpace::getType(), RangeList::inRange(), IPTR_INTERNAL, and nohighptr.
init()
void Architecture::init (DocumentStorage & store)
Load the image and configure architecture.
Create the LoadImage and load the executable to be analyzed. Using this and possibly other initialization information, create all the sub-components necessary for a complete Architecture The DocumentStore may hold previously gleaned configuration information and is used to read in other configuration files while initializing.
Parameters
store is the XML document store
References buildCommentDB(), buildConstantPool(), buildContext(), buildInstructions(), buildLoader(), buildSpecFile(), buildTypegrp(), fillinReadOnlyFromLoader(), postSpecFile(), print, resolveArchitecture(), restoreFromSpec(), and types.
Referenced by RegisterProgram::rawAction(), XmlArchitecture::restoreXml(), RawBinaryArchitecture::restoreXml(), and BfdArchitecture::restoreXml().
initializeSegments()
void Architecture::initializeSegments () protected
Set up segment resolvers.
If any address space supports near pointers and segment operators, setup SegmentedResolver objects that can be used to recover full pointers in context.
References UserOpManage::getSegmentOp(), AddrSpaceManager::insertResolver(), and userops.
Referenced by parseCompilerConfig().
modifySpaces()
virtual void Architecture::modifySpaces (Translate * trans) protected pure virtual
Modify address spaces as required by this Architecture.
If spaces need to be truncated or otherwise changed from processor defaults, this routine performs the modification.
Parameters
trans is the processor disassembly object
Implemented in SleighArchitecture, and ArchitectureGhidra.
Referenced by restoreFromSpec().
nameFunction()
void Architecture::nameFunction (const Address & addr, string & name) const virtual
Pick a default name for a function.
If no better name is available, this method can be used to generate a function name based on its address
Parameters
addr is the address of the function
name will hold the constructed name
References Address::printRaw().
parseAggressiveTrim()
void Architecture::parseAggressiveTrim (const Element * el) protected
Designate how to trim extension p-code ops.
Configure based on the <aggressivetrim> tag, how aggressively the decompiler will remove extension operations.
Parameters
el is the XML element
References aggressive_ext_trim, Element::getAttributeValue(), and xml_readbool().
Referenced by parseCompilerConfig().
parseCompilerConfig()
void Architecture::parseCompilerConfig (DocumentStorage & store) protected
Apply compiler specific configuration.
This looks for the <compiler_spec> tag and sets configuration parameters based on it.
Parameters
store is the document store holding the tag
References addOtherSpace(), archid, InjectPayload::CALLFIXUP_TYPE, context, defaultfp, DocumentStorage::getTag(), initializeSegments(), parseAggressiveTrim(), UserOpManage::parseCallOtherFixup(), TypeFactory::parseDataOrganization(), parseDeadcodeDelay(), parseDefaultProto(), TypeFactory::parseEnumConfig(), parseFuncPtrAlign(), parseGlobal(), parseNoHighPtr(), parsePreferSplit(), parseProto(), parseProtoEval(), parseReadOnly(), parseReturnAddress(), UserOpManage::parseSegmentOp(), parseSpacebase(), parseStackPointer(), pcodeinjectlib, protoModels, ContextDatabase::restoreFromSpec(), PcodeInjectLibrary::restoreXmlInject(), UserOpManage::setDefaults(), TypeFactory::setupSizes(), splitrecords, types, and userops.
Referenced by restoreFromSpec().
parseDeadcodeDelay()
void Architecture::parseDeadcodeDelay (const Element * el) protected
Apply dead-code delay configuration.
Manually alter the dead-code delay for a specific address space, based on a <deadcodedelay> tag.
Parameters
el is the XML element
References Element::getAttributeValue(), AddrSpaceManager::getSpaceByName(), and AddrSpaceManager::setDeadcodeDelay().
Referenced by parseCompilerConfig().
parseDefaultProto()
void Architecture::parseDefaultProto (const Element * el) protected
Apply default prototype model configuration.
There should be exactly one <default_proto> tag that specifies what the default prototype model is. This builds the ProtoModel object and sets it as the default.
Parameters
el is the XML element
References defaultfp, and parseProto().
Referenced by parseCompilerConfig().
parseDynamicRule()
void Architecture::parseDynamicRule (const Element * el) protected
Apply details of a dynamic Rule object.
Recover information out of a <rule> tag and build the new Rule object.
Parameters
el is the XML element
References extra_pool_rules, and Element::getAttributeValue().
Referenced by parseExtraRules().
parseExtraRules()
void Architecture::parseExtraRules (DocumentStorage & store) protected
Apply any Rule tags.
Look for the <experimental_rules> tag and create any dynamic Rule objects it specifies.
Parameters
store is the document store containing the tag
References DocumentStorage::getTag(), and parseDynamicRule().
Referenced by buildAction().
parseFuncPtrAlign()
void Architecture::parseFuncPtrAlign (const Element * el) protected
Apply function pointer alignment configuration.
Pull information from a <funcptr> tag. Turn on alignment analysis of function pointers, some architectures have aligned function pointers and encode extra information in the unused bits.
Parameters
el is the XML element
References funcptr_align, and Element::getAttributeValue().
Referenced by parseCompilerConfig().
parseGlobal()
void Architecture::parseGlobal (const Element * el) protected
Apply global space configuration.
This handles the <global> tag adding an address space (or part of the space) to the global scope. Varnodes in this region will be assumed to be global variables.
Parameters
el is the XML element
References Database::addRange(), buildGlobalScope(), OverlaySpace::getBaseSpace(), AddrSpaceManager::getSpace(), inferPtrSpaces, AddrSpace::isOverlay(), AddrSpaceManager::numSpaces(), Range::restoreXml(), and symboltab.
Referenced by parseCompilerConfig().
parseIncidentalCopy()
void Architecture::parseIncidentalCopy (const Element * el) protected
Apply incidental copy configuration.
Apply information from an <incidentalcopy> tag, which marks a set of addresses as being copied to incidentally. This allows the decompiler to ignore certain side-effects.
Parameters
el is the XML element
References Varnode::incidental_copy, VarnodeData::offset, VarnodeData::restoreXml(), Database::setPropertyRange(), VarnodeData::size, VarnodeData::space, and symboltab.
Referenced by parseProcessorConfig().
parseLaneSizes()
void Architecture::parseLaneSizes (const Element * el) protected
Apply lane size configuration.
Look for <register> tags that have a vector_lane_size attribute. Record these so that the decompiler can split large registers into appropriate lane size pieces.
Parameters
el is the XML element
References lanerecords, and LanedRegister::restoreXml().
Referenced by parseProcessorConfig().
parseNoHighPtr()
void Architecture::parseNoHighPtr (const Element * el) protected
Apply memory alias configuration.
Configure memory based on a <nohighptr> tag. Mark specific address ranges to indicate the decompiler will not encounter pointers (aliases) into the range.
Parameters
el is the XML element
References addNoHighPtr(), and Range::restoreXml().
Referenced by parseCompilerConfig().
parsePreferSplit()
void Architecture::parsePreferSplit (const Element * el) protected
Designate registers to be split.
Configure registers based on a <prefersplit> tag. Mark specific varnodes that the decompiler should automatically split when it first sees them.
Parameters
el is the XML element
References Element::getAttributeValue(), VarnodeData::restoreXml(), VarnodeData::size, and splitrecords.
Referenced by parseCompilerConfig().
parseProcessorConfig()
void Architecture::parseProcessorConfig (DocumentStorage & store) protected
Apply processor specific configuration.
This looks for the <processor_spec> tag and and sets configuration parameters based on it.
Parameters
store is the document store holding the tag
References context, AddrSpace::getIndex(), AddrSpaceManager::getSpaceByName(), DocumentStorage::getTag(), parseIncidentalCopy(), UserOpManage::parseJumpAssist(), parseLaneSizes(), UserOpManage::parseSegmentOp(), parseVolatile(), ContextDatabase::restoreFromSpec(), AddrSpaceManager::setDefaultDataSpace(), and userops.
Referenced by restoreFromSpec().
parseProto()
ProtoModel * Architecture::parseProto (const Element * el) protected
Build a proto-type model from an XML tag.
This handles the <prototype> and <resolveprototype> tags. It builds the ProtoModel object based on the tag and makes it available generally to the decompiler.
Parameters
el is the XML tag element
References protoModels, and ProtoModel::restoreXml().
Referenced by parseCompilerConfig(), and parseDefaultProto().
parseProtoEval()
void Architecture::parseProtoEval (const Element * el) protected
Apply prototype evaluation configuration.
This supports the <eval_called_prototype> and <eval_current_prototype> tag. This determines which prototype model to assume when recovering the prototype for a called function and the current function respectively.
Parameters
el is the XML element
References evalfp_called, evalfp_current, Element::getAttributeValue(), and protoModels.
Referenced by parseCompilerConfig().
parseReadOnly()
void Architecture::parseReadOnly (const Element * el) protected
Apply read-only region configuration.
This applies info from a <readonly> tag marking a specific region of the executable as read-only.
Parameters
el is the XML element
References Varnode::readonly, Range::restoreXml(), Database::setPropertyRange(), and symboltab.
Referenced by parseCompilerConfig().
parseReturnAddress()
void Architecture::parseReturnAddress (const Element * el) protected
Apply return address configuration.
This applies info from <returnaddress> tag and sets the default storage location for the return address of a function.
Parameters
el is the XML element
References defaultReturnAddr, VarnodeData::restoreXml(), and VarnodeData::space.
Referenced by parseCompilerConfig().
parseSpacebase()
void Architecture::parseSpacebase (const Element * el) protected
Create an additional indexed space.
Designate a new index register and create a new address space associated with it, based on a <spacebase> tag.
Parameters
el is the XML element
References addSpacebase(), Element::getAttributeValue(), Translate::getRegister(), AddrSpaceManager::getSpaceByName(), VarnodeData::size, and translate.
Referenced by parseCompilerConfig().
parseStackPointer()
void Architecture::parseStackPointer (const Element * el) protected
Apply stack pointer configuration.
Create a stack space and a stack-pointer register from this <stackpointer> element
Parameters
el is the XML element
References addSpacebase(), AddrSpace::getAddrSize(), Element::getAttributeValue(), Translate::getRegister(), AddrSpaceManager::getSpaceByName(), AddrSpace::isTruncated(), VarnodeData::size, translate, and xml_readbool().
Referenced by parseCompilerConfig().
parseVolatile()
void Architecture::parseVolatile (const Element * el) protected
Apply volatile region configuration.
This applies info from a <volatile> tag marking specific regions of the executable as holding volatile memory or registers.
Parameters
el is the XML element
References UserOpManage::parseVolatile(), Range::restoreXml(), Database::setPropertyRange(), symboltab, userops, and Varnode::volatil.
Referenced by parseProcessorConfig().
printMessage()
virtual void Architecture::printMessage (const string & message) const pure virtual
Print an error message to console.
Write the given message to whatever the registered error stream is
Parameters
message is the error message
Implemented in ArchitectureGhidra, and SleighArchitecture.
Referenced by Scope::addCodeLabel(), Scope::addFunction(), Scope::addMapSym(), Action::issueWarning(), and Rule::issueWarning().
readLoaderSymbols()
void Architecture::readLoaderSymbols (void)
Read any symbols from loader into database.
Symbols do not necessarily need to be available for the decompiler. This routine loads all the load image knows about into the symbol table
References Scope::addFunction(), LoadImageFunc::address, LoadImage::closeSymbols(), LoadImage::getNextSymbol(), loader, loadersymbols_parsed, LoadImageFunc::name, LoadImage::openSymbols(), and symboltab.
restoreFlowOverride()
void Architecture::restoreFlowOverride (const Element * el)
Set flow overrides from XML.
Insert a series of out-of-band flow overrides based on a <flowoverridelist> tag.
Parameters
el is the XML element
References Element::getAttributeValue(), Address::restoreXml(), Override::stringToType(), and symboltab.
Referenced by restoreXml().
restoreFromSpec()
void Architecture::restoreFromSpec (DocumentStorage & store) protected
Fully initialize the Translate object.
Once the processor is known, the Translate object can be built and fully initialized. Processor and compiler specific configuration is performed
Parameters
store will hold parsed configuration information
References buildAction(), buildPcodeInjectLibrary(), buildTranslator(), AddrSpaceManager::copySpaces(), Translate::getAlignment(), UserOpManage::initialize(), Translate::initialize(), AddrSpaceManager::insertSpace(), min_funcsymbol_size, modifySpaces(), AddrSpaceManager::numSpaces(), parseCompilerConfig(), parseProcessorConfig(), pcodeinjectlib, Translate::setDefaultFloatFormats(), translate, and userops.
Referenced by init().
restoreXml()
void Architecture::restoreXml (DocumentStorage & store) virtual
Restore the Architecture state from an XML stream.
Read in all the sub-component state from a <save_state> XML tag When adding stuff to this BEWARE: The spec file has already initialized stuff
Parameters
store is document store containing the parsed root tag
Reimplemented in BfdArchitecture, RawBinaryArchitecture, and XmlArchitecture.
References commentdb, context, cpool, Element::getAttributeValue(), DocumentStorage::getTag(), loadersymbols_parsed, options, pcodeinjectlib, PcodeInjectLibrary::restoreDebug(), restoreFlowOverride(), OptionDatabase::restoreXml(), CommentDatabase::restoreXml(), ConstantPool::restoreXml(), ContextDatabase::restoreXml(), TypeFactory::restoreXml(), Database::restoreXml(), symboltab, types, and xml_readbool().
Referenced by XmlArchitecture::restoreXml(), RawBinaryArchitecture::restoreXml(), and BfdArchitecture::restoreXml().
saveXml()
void Architecture::saveXml (ostream & s) const virtual
Serialize this architecture to XML.
Write the current state of all types, symbols, functions, etc. an XML stream
Parameters
s is the output stream
Reimplemented in BfdArchitecture, RawBinaryArchitecture, and XmlArchitecture.
References a_v_b(), commentdb, context, cpool, ConstantPool::empty(), loadersymbols_parsed, CommentDatabase::saveXml(), ConstantPool::saveXml(), ContextDatabase::saveXml(), TypeFactory::saveXml(), Database::saveXml(), symboltab, and types.
Referenced by XmlArchitecture::saveXml(), RawBinaryArchitecture::saveXml(), and BfdArchitecture::saveXml().
setDefaultModel()
void Architecture::setDefaultModel (const string & nm)
Set the default PrototypeModel.
The default model is used whenever an explicit model is not known or can't be determined.
Parameters
nm is the name of the model to set
References defaultfp, and getModel().
Referenced by OptionDefaultPrototype::apply().
setPrintLanguage()
void Architecture::setPrintLanguage (const string & nm)
Establish a particular output language.
The decompiler supports one or more output languages (C, Java). This method does the main work of selecting one of the supported languages. In addition to selecting the main PrintLanguage object, this triggers configuration of the cast strategy and p-code op behaviors.
Parameters
nm is the name of the language
References PrintLanguage::adjustTypeOperators(), PrintLanguageCapability::buildLanguage(), PrintLanguageCapability::findCapability(), print, printlist, PrintLanguage::setXML(), and types.
Referenced by OptionSetLanguage::apply().
setPrototype()
void Architecture::setPrototype (const PrototypePieces & pieces)
Set the prototype for a particular function.
Establish details of the prototype for a given function symbol
Parameters
pieces holds the raw prototype information and the symbol name
References PrototypePieces::name, and symboltab.
The documentation for this class was generated from the following files:
architecture.hh
architecture.cc