decompiler: TransformOp Class Reference
TransformOp Class Reference
Placeholder node for PcodeOp that will exist after a transform is applied to a function.
#include <transform.hh>
Public Types
enum { op_replacement = 1, op_preexisting = 2, indirect_creation = 4, indirect_creation_possible_out = 8 }
Special annotations on new pcode ops.
Private Member Functions
void createReplacement (Funcdata *fd)
Create the new/modified op this placeholder represents.
bool attemptInsertion (Funcdata *fd)
Try to put the new PcodeOp into its basic block.
Private Attributes
PcodeOp * op
Original op which this is splitting (or null)
PcodeOp * replacement
The new replacement op.
OpCode opc
Opcode of the new op.
uint4 special
Special handling code when creating.
TransformVar * output
Varnode output.
vector< TransformVar * > input
Varnode inputs.
TransformOp * follow
The following op after this (if not null)
Friends
class TransformManager
class TransformVar
Detailed Description
Placeholder node for PcodeOp that will exist after a transform is applied to a function.
Member Enumeration Documentation
anonymous enum
anonymous enum
Special annotations on new pcode ops.
Enumerator
op_replacement
Op replaces an existing op.
op_preexisting
Op already exists (but will be transformed)
indirect_creation
Mark op as indirect creation.
indirect_creation_possible_out
Mark op as indirect creation and possible call output.
Member Function Documentation
attemptInsertion()
bool TransformOp::attemptInsertion (Funcdata * fd) private
Try to put the new PcodeOp into its basic block.
Parameters
fd is the function into which the PcodeOp will be inserted
Returns
true if the op is successfully inserted or already inserted
References CPUI_MULTIEQUAL, TransformManager::fd, follow, opc, Funcdata::opInsertBefore(), Funcdata::opInsertBegin(), and replacement.
createReplacement()
void TransformOp::createReplacement (Funcdata * fd) private
Create the new/modified op this placeholder represents.
Create a new PcodeOp or modify an existing one so that it matches this placeholder description. Go ahead an insert the new PcodeOp into the basic block if possible
Parameters
fd is the function in which to make the modifications
References CPUI_MULTIEQUAL, TransformVar::createReplacement(), TransformManager::fd, follow, input, Funcdata::newOp(), op, op_preexisting, opc, Funcdata::opInsertBefore(), Funcdata::opInsertBegin(), Funcdata::opInsertInput(), Funcdata::opRemoveInput(), Funcdata::opSetOpcode(), Funcdata::opUnsetInput(), output, replacement, and special.
The documentation for this class was generated from the following files:
transform.hh
transform.cc