decompiler: ValueSetRead Class Reference
ValueSetRead Class Reference
A special form of ValueSet associated with the read point of a Varnode.
#include <rangeutil.hh>
Public Member Functions
void compute (void)
Compute this value set.
void printRaw (ostream &s) const
Write a text description of to the given stream.
Private Member Functions
void setPcodeOp (PcodeOp *o, int4 slt)
Establish read this value set corresponds to.
void addEquation (int4 slt, int4 type, const CircleRange &constraint)
Insert an equation restricting this value set.
Private Attributes
int4 typeCode
0=pure constant 1=stack relative
int4 slot
The slot being read.
PcodeOp * op
The PcodeOp at the point of the value set read.
CircleRange range
Range of values or offsets in this set.
CircleRange equationConstraint
Constraint associated with the equation.
int4 equationTypeCode
Type code of the associated equation.
bool leftIsStable
Set to true if left boundary of range didn't change (last iteration)
bool rightIsStable
Set to true if right boundary of range didn't change (last iteration)
Friends
class ValueSetSolver
Detailed Description
A special form of ValueSet associated with the read point of a Varnode.
When a Varnode is read, it may have a more restricted range at the point of the read compared to the full scope. This class officially stores the value set at the point of the read (specified by PcodeOp and slot). It is computed as a final step after the main iteration has completed.
Member Function Documentation
addEquation()
void ValueSetRead::addEquation (int4 slt, int4 type, const CircleRange & constraint) private
Insert an equation restricting this value set.
Parameters
slt is the given slot
type is the constraint characteristic
constraint is the given range
References equationConstraint, equationTypeCode, and slot.
compute()
void ValueSetRead::compute (void)
Compute this value set.
This value set will be the same as the ValueSet of the Varnode being read but may be modified due to additional control-flow constraints
References equationConstraint, equationTypeCode, CircleRange::intersect(), leftIsStable, op, range, rightIsStable, slot, and typeCode.
printRaw()
void ValueSetRead::printRaw (ostream & s) const
Write a text description of to the given stream.
Parameters
s is the stream to print to
References get_opname(), op, CircleRange::printRaw(), range, and typeCode.
setPcodeOp()
void ValueSetRead::setPcodeOp (PcodeOp * o, int4 slt) private
Establish read this value set corresponds to.
Parameters
o is the PcodeOp reading the value set
slt is the input slot the values are coming in from
References equationTypeCode, op, slot, and typeCode.
The documentation for this class was generated from the following files:
rangeutil.hh
rangeutil.cc