decompiler: Action Class Reference
Action Class Reference abstract
Large scale transformations applied to the varnode/op graph.
#include <action.hh>
Public Types
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Public Member Functions
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
virtual Action * clone (const ActionGroupList &grouplist) const =0
Clone the Action.
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 apply (Funcdata &data)=0
Make a single attempt to apply this Action.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
Protected Member Functions
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
Protected Attributes
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Large scale transformations applied to the varnode/op graph.
The base for objects that make changes to the syntax tree of a Funcdata The action is invoked through the apply(Funcdata &data) method. This base class keeps track of basic statistics about how the action is being applied. Derived classes indicate that a change has been applied by incrementing the count field. With OPACTION_DEBUG macro defined, actions support a break point debugging in console mode.
Member Enumeration Documentation
breakflags
enum Action::breakflags
Break points associated with an Action.
Enumerator
break_start
Break at beginning of action.
tmpbreak_start
Temporary break at start of action.
break_action
Break if a change has been made.
ruleflags
enum Action::ruleflags
Boolean behavior properties governing this particular Action.
Enumerator
rule_repeatapply
Apply rule repeatedly until no change.
rule_onceperfunc
Apply rule once per function.
rule_oneactperfunc
Makes a change only once per function.
rule_debug
Print debug messages specifically for this action.
rule_warnings_on
If this action makes a change, issue a warning.
rule_warnings_given
A warning has been issued for this action.
statusflags
enum Action::statusflags
Boolean properties describing the status of an action.
Enumerator
status_start
At start of action.
status_breakstarthit
At start after breakpoint.
status_repeat
Repeating the same action.
status_mid
In middle of action (use subclass status)
status_end
getFuncdata has completed once (for onceperfunc)
status_actionbreak
Completed full action last time but indicated action break.
Constructor & Destructor Documentation
Action()
Action::Action (uint4 f, const string & nm, const string & g)
Base constructor for an Action.
Specify the name, group, and properties of the Action
Parameters
f is the collection of property flags
nm is the Action name
g is the Action group
References basegroup, breakpoint, count_apply, count_tests, flags, name, status, and status_start.
Member Function Documentation
apply()
virtual int4 Action::apply (Funcdata & data) pure virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implemented in ActionPrototypeWarnings, ActionDynamicSymbols, ActionDynamicMapping, ActionCopyMarker, ActionDominantCopy, ActionHideShadow, ActionInferTypes, ActionUnjustifiedParams, ActionOutputPrototype, ActionInputPrototype, ActionMapGlobals, ActionRestructureHigh, ActionRestructureVarnode, ActionLikelyTrash, ActionRestrictLocal, ActionReturnRecovery, ActionActiveReturn, ActionActiveParam, ActionParamDouble, ActionFuncLinkOutOnly, ActionFuncLink, ActionExtraPopSetup, ActionDefaultParams, ActionPrototypeTypes, ActionNormalizeSetup, ActionSwitchNorm, ActionConditionalConst, ActionDeadCode, ActionDeterminedBranch, ActionRedundBranch, ActionDoNothing, ActionUnreachable, ActionNameVars, ActionMarkImplied, ActionMarkExplicit, ActionMergeType, ActionMergeMultiEntry, ActionMergeCopy, ActionMergeAdjacent, ActionMergeRequired, ActionMarkIndirectOnly, ActionNodeJoin, ActionAssignHigh, ActionReturnSplit, ActionSetCasts, ActionFinalStructure, ActionBlockStructure, ActionNonzeroMask, ActionPreferComplement, ActionHeritage, ActionNormalizeBranches, ActionPool, ActionSpacebase, ActionConstbase, ActionDirectWrite, ActionVarnodeProps, ActionDeindirect, ActionConstantPtr, ActionRestartGroup, ActionConditionalExe, ActionShadowVar, ActionMultiCse, ActionGroup, ActionForceGoto, ActionSegmentize, ActionLaneDivide, ActionStackPtrFlow, ActionStartTypes, ActionStartCleanUp, ActionStop, and ActionStart.
Referenced by perform().
checkActionBreak()
bool Action::checkActionBreak (void) protected
Check action breakpoint.
Check if there was an active action breakpoint on this Action
Returns
true if there was an action breakpoint
References break_action, and breakpoint.
Referenced by ActionGroup::apply(), and perform().
checkStartBreak()
bool Action::checkStartBreak (void) protected
Check start breakpoint.
Check if there was an active start break point on this action
Returns
true if there was a start breakpoint
References break_start, breakpoint, and tmpbreak_start.
Referenced by perform().
clone()
virtual Action* Action::clone (const ActionGroupList & grouplist) const pure virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implemented in ActionPrototypeWarnings, ActionDynamicSymbols, ActionDynamicMapping, ActionCopyMarker, ActionDominantCopy, ActionHideShadow, ActionInferTypes, ActionUnjustifiedParams, ActionOutputPrototype, ActionInputPrototype, ActionMapGlobals, ActionRestructureHigh, ActionRestructureVarnode, ActionLikelyTrash, ActionRestrictLocal, ActionReturnRecovery, ActionActiveReturn, ActionActiveParam, ActionParamDouble, ActionFuncLinkOutOnly, ActionFuncLink, ActionExtraPopSetup, ActionDefaultParams, ActionPrototypeTypes, ActionNormalizeSetup, ActionSwitchNorm, ActionConditionalConst, ActionDeadCode, ActionDeterminedBranch, ActionRedundBranch, ActionDoNothing, ActionUnreachable, ActionNameVars, ActionMarkImplied, ActionMarkExplicit, ActionMergeType, ActionMergeMultiEntry, ActionMergeCopy, ActionMergeAdjacent, ActionMergeRequired, ActionMarkIndirectOnly, ActionNodeJoin, ActionAssignHigh, ActionReturnSplit, ActionSetCasts, ActionFinalStructure, ActionBlockStructure, ActionNonzeroMask, ActionPreferComplement, ActionHeritage, ActionNormalizeBranches, ActionPool, ActionSpacebase, ActionConstbase, ActionDirectWrite, ActionVarnodeProps, ActionDeindirect, ActionConstantPtr, ActionRestartGroup, ActionConditionalExe, ActionShadowVar, ActionMultiCse, ActionGroup, ActionForceGoto, ActionSegmentize, ActionLaneDivide, ActionStackPtrFlow, ActionStartTypes, ActionStartCleanUp, ActionStop, and ActionStart.
Referenced by ActionGroup::clone(), ActionRestartGroup::clone(), ActionDatabase::deriveAction(), and ActionDatabase::toggleAction().
disableRule()
bool Action::disableRule (const string & specify)
Disable a specific Rule within this.
An individual Rule can be disabled by name, within this Action. It must be specified by a ':' separated name path, from the root Action down to the specific Rule.
Parameters
specify is the name path
Returns
true if the Rule is successfully disabled
References getSubRule().
Referenced by OptionToggleRule::apply().
enableRule()
bool Action::enableRule (const string & specify)
Enable a specific Rule within this.
An individual Rule can be enabled by name, within this Action. It must be specified by a ':' separated name path, from the root Action down to the specific Rule.
Parameters
specify is the name path
Returns
true if the Rule is successfully enabled
References getSubRule().
Referenced by OptionToggleRule::apply().
getSubAction()
Action * Action::getSubAction (const string & specify) virtual
Retrieve a specific sub-action by name.
If this Action matches the given name, it is returned. If the name matches a sub-action, this is returned.
Parameters
specify is the action name to match
Returns
the matching Action or sub-action
Reimplemented in ActionGroup.
References name.
Referenced by ActionGroup::getSubAction(), setBreakPoint(), and setWarning().
getSubRule()
Rule * Action::getSubRule (const string & specify) virtual
Retrieve a specific sub-rule by name.
Find a Rule, as a component of this Action, with the given name.
Parameters
specify is the name of the rule
Returns
the matching sub-rule
Reimplemented in ActionPool, and ActionGroup.
Referenced by disableRule(), enableRule(), setBreakPoint(), and setWarning().
issueWarning()
void Action::issueWarning (Architecture * glb) protected
Warn that this Action has applied.
If enabled, issue a warning that this Action has been applied
Parameters
glb is the controlling Architecture
References flags, name, Architecture::printMessage(), rule_warnings_given, and rule_warnings_on.
Referenced by perform().
perform()
int4 Action::perform (Funcdata & data)
Perform this action (if necessary)
Run this Action until completion or a breakpoint occurs. Depending on the behavior properties of this instance, the apply() method may get called many times or none. Generally the number of changes made by the action is returned, but if a breakpoint occurs -1 is returned. A successive call to perform() will "continue" from the break point.
Parameters
data is the function being acted on
Returns
the number of changes or -1
References apply(), checkActionBreak(), checkStartBreak(), count, count_apply, count_tests, flags, issueWarning(), lcount, rule_onceperfunc, rule_oneactperfunc, rule_repeatapply, status, status_actionbreak, status_breakstarthit, status_end, status_mid, status_repeat, and status_start.
print()
int4 Action::print (ostream & s, int4 num, int4 depth) const virtual
Print a description of this Action to stream.
The description is suitable for a console mode listing of actions
Parameters
s is the output stream
num is a starting index to associate with the action (and its sub-actions)
depth is amount of indent necessary before printing
Returns
the next available index
Reimplemented in ActionPool, and ActionGroup.
References break_action, break_start, breakpoint, flags, name, rule_onceperfunc, rule_repeatapply, and tmpbreak_start.
Referenced by ActionGroup::print(), and ActionPool::print().
printState()
void Action::printState (ostream & s) const virtual
Print status to stream.
This will the Action name and the next step to execute
Parameters
s is the output stream
Reimplemented in ActionPool, and ActionGroup.
References name, status, status_breakstarthit, status_end, status_mid, status_repeat, and status_start.
Referenced by ActionGroup::printState(), and ActionPool::printState().
printStatistics()
void Action::printStatistics (ostream & s) const virtual
Dump statistics to stream.
Print out the collected statistics for the Action to stream
Parameters
s is the output stream
Reimplemented in ActionPool, and ActionGroup.
References count_apply, count_tests, and name.
Referenced by ActionGroup::printStatistics(), and ActionPool::printStatistics().
reset()
void Action::reset (Funcdata & data) virtual
Reset the Action for a new function.
Parameters
data is the new function this Action may affect
Reimplemented in ActionInferTypes, ActionRestructureVarnode, ActionPool, ActionConstantPtr, ActionRestartGroup, ActionGroup, ActionSegmentize, and ActionStackPtrFlow.
References flags, rule_warnings_given, status, and status_start.
Referenced by ActionGroup::reset(), and ActionPool::reset().
resetStats()
void Action::resetStats (void) virtual
Reset all the counts to zero.
Reset the statistics
Reimplemented in ActionPool, and ActionGroup.
References count_apply, and count_tests.
Referenced by ActionGroup::resetStats(), and ActionPool::resetStats().
setBreakPoint()
bool Action::setBreakPoint (uint4 tp, const string & specify)
Set a breakpoint on this action.
A breakpoint can be placed on this Action or some sub-action by properly specifying the (sub)action name.
Parameters
tp is the type of breakpoint (break_start, break_action, etc.)
specify is the (possibly sub)action to apply the break point to
Returns
true if a breakpoint was successfully set
References breakpoint, getSubAction(), and getSubRule().
setWarning()
bool Action::setWarning (bool val, const string & specify)
Set a warning on this action.
If enabled, a warning will be printed whenever this action applies. The warning can be toggled for this Action or some sub-action by specifying its name.
Parameters
val is the toggle value for the warning
specify is the name of the action or sub-action to toggle
Returns
true if the warning was successfully toggled
References getSubAction(), and getSubRule().
The documentation for this class was generated from the following files:
action.hh
action.cc