decompiler: BlockCopy Class Reference
BlockCopy Class Reference
This class is used to mirror the BlockBasic objects in the fixed control-flow graph for a function.
#include <block.hh>
Public Member Functions
virtual FlowBlock * subBlock (int4 i) const
virtual block_type getType (void) const
virtual void printHeader (ostream &s) const
Print a simple description of this to stream.
virtual void printTree (ostream &s, int4 level) const
Print tree structure of any blocks owned by this.
virtual void printRaw (ostream &s) const
virtual void emit (PrintLanguage *lng) const
Emit the instructions in this FlowBlock as structured code.
virtual const FlowBlock * getExitLeaf (void) const
virtual PcodeOp * lastOp (void) const
virtual bool negateCondition (bool toporbottom)
Flip the condition computed by this.
virtual FlowBlock * getSplitPoint (void)
Get the leaf splitting block.
virtual bool isComplex (void) const
virtual void saveXmlHeader (ostream &s) const
Save basic information as XML attributes.
Public Member Functions inherited from FlowBlock
FlowBlock (void)
Construct a block with no edges.
virtual void markLabelBumpUp (bool bump)
Let hierarchical blocks steal labels of their (first) components.
virtual bool preferComplement (Funcdata &data)
Rearrange this hierarchy to simplify boolean expressions.
virtual int4 flipInPlaceTest (vector< PcodeOp * > &fliplist) const
Test normalizing the conditional branch in this.
virtual void flipInPlaceExecute (void)
Perform the flip to normalize conditional branch executed by this block.
virtual FlowBlock * nextFlowAfter (const FlowBlock *bl) const
Get the leaf FlowBlock that will execute after the given FlowBlock.
virtual void restoreXmlHeader (const Element *el)
Restore basic information for XML attributes.
virtual void restoreXmlBody (List::const_iterator &iter, List::const_iterator enditer, BlockMap &resolver)
Restore details about this FlowBlock from an XML stream.
void saveXmlEdges (ostream &s) const
Save edge information to an XML stream.
void restoreXmlEdges (List::const_iterator &iter, List::const_iterator enditer, BlockMap &resolver)
Restore edges from an XML stream.
void saveXml (ostream &s) const
Write out this to an XML stream.
void restoreXml (const Element *el, BlockMap &resolver)
Restore this from an XML stream.
const FlowBlock * nextInFlow (void) const
Return next block to be executed in flow.
void setGotoBranch (int4 i)
Mark a goto branch.
bool isJumpTarget (void) const
Return true if non-fallthru jump flows into this.
const FlowBlock * getFrontLeaf (void) const
Get the first leaf FlowBlock.
FlowBlock * getFrontLeaf (void)
Get the first leaf FlowBlock.
int4 calcDepth (const FlowBlock *leaf) const
Get the depth of the given component FlowBlock.
bool dominates (const FlowBlock *subBlock) const
Does this block dominate the given block.
bool restrictedByConditional (const FlowBlock *cond) const
Check if the condition from the given block holds for this block.
bool hasLoopIn (void) const
Is there a looping edge coming into this block.
bool hasLoopOut (void) const
Is there a looping edge going out of this block.
int4 getInIndex (const FlowBlock *bl) const
Get the incoming edge index for the given FlowBlock.
int4 getOutIndex (const FlowBlock *bl) const
Get the outgoing edge index for the given FlowBlock.
bool isDecisionOut (int4 i) const
Can this and the i-th output be merged into a BlockIf or BlockList.
bool isDecisionIn (int4 i) const
Can this and the i-th input be merged into a BlockIf or BlockList.
bool isLoopDAGOut (int4 i) const
Is the i-th outgoing edge part of the DAG sub-graph.
bool isLoopDAGIn (int4 i) const
Is the i-th incoming edge part of the DAG sub-graph.
JumpTable * getJumptable (void) const
Get the JumpTable associated this block.
Private Attributes
FlowBlock * copy
The block being mirrored by this (usually a BlockBasic)
Additional Inherited Members
Public Types inherited from FlowBlock
enum block_type {
t_plain, t_basic, t_graph, t_copy,
t_goto, t_multigoto, t_ls, t_condition,
t_if, t_whiledo, t_dowhile, t_switch,
t_infloop
}
The possible block types.
enum block_flags {
f_goto_goto = 1, f_break_goto = 2, f_continue_goto = 4, f_switch_out = 0x10,
f_unstructured_targ = 0x20, f_mark = 0x80, f_mark2 = 0x100, f_entry_point = 0x200,
f_interior_gotoout = 0x400, f_interior_gotoin = 0x800, f_label_bumpup = 0x1000, f_donothing_loop = 0x2000,
f_dead = 0x4000, f_whiledo_overflow = 0x8000, f_flip_path = 0x10000, f_joined_block = 0x20000,
f_duplicate_block = 0x40000
}
Boolean properties of blocks.
enum edge_flags {
f_goto_edge = 1, f_loop_edge = 2, f_defaultswitch_edge = 4, f_irreducible = 8,
f_tree_edge = 0x10, f_forward_edge = 0x20, f_cross_edge = 0x40, f_back_edge = 0x80,
f_loop_exit_edge = 0x100
}
Boolean properties on edges.
Static Public Member Functions inherited from FlowBlock
static block_type nameToType (const string &name)
Get the block_type associated with a name string.
static string typeToName (block_type bt)
Get the name string associated with a block_type.
static bool compareBlockIndex (const FlowBlock *bl1, const FlowBlock *bl2)
Compare FlowBlock by index.
static bool compareFinalOrder (const FlowBlock *bl1, const FlowBlock *bl2)
Final FlowBlock comparison.
static FlowBlock * findCommonBlock (FlowBlock *bl1, FlowBlock *bl2)
Find the common dominator of two FlowBlocks.
static FlowBlock * findCommonBlock (const vector< FlowBlock * > &blockSet)
Find common dominator of multiple FlowBlocks.
Detailed Description
This class is used to mirror the BlockBasic objects in the fixed control-flow graph for a function.
The decompiler does control-flow structuring by making an initial copy of the control-flow graph, then iteratively collapsing nodes (in the copy) into structured nodes. So an instance of this class acts as the mirror of an original basic block within the copy of the graph. During the structuring process, an instance will start with an exact mirror of its underlying basic block's edges, but as the algorithm proceeds, edges may get replaced as neighboring basic blocks get collapsed, and eventually the instance will get collapsed itself and become a component of one of the structured block objects (BlockIf, BlockDoWhile, etc). The block that incorporates the BlockCopy as a component is accessible through getParent().
Member Function Documentation
emit()
virtual void BlockCopy::emit (PrintLanguage * lng) const inline virtual
Emit the instructions in this FlowBlock as structured code.
This is the main entry point, at the control-flow level, for printing structured code.
Parameters
lng is the PrintLanguage that provides details of the high-level language being printed
Reimplemented from FlowBlock.
References PrintLanguage::emitBlockCopy().
getSplitPoint()
virtual FlowBlock* BlockCopy::getSplitPoint (void) inline virtual
Get the leaf splitting block.
If this block ends with a conditional branch, return the deepest component block that performs the split. This component needs to be able to perform flipInPlaceTest() and flipInPlaceExecute()
Returns
the component FlowBlock or NULL if this doesn't end in a conditional branch
Reimplemented from FlowBlock.
References copy, and FlowBlock::getSplitPoint().
negateCondition()
virtual bool BlockCopy::negateCondition (bool toporbottom) inline virtual
Flip the condition computed by this.
Flip the order of outgoing edges (at least). This should also affect the original op causing the condition. Note: we don't have to flip at all levels of the hierarchy only at the top and at the bottom
Parameters
toporbottom is true if this is the top outermost block of the hierarchy getting negated
Returns
true if a change was made to data-flow
Reimplemented from FlowBlock.
References copy, and FlowBlock::negateCondition().
printHeader()
void BlockCopy::printHeader (ostream & s) const virtual
Print a simple description of this to stream.
Only print a header for this single block
Parameters
s is the output stream
Reimplemented from FlowBlock.
References FlowBlock::printHeader().
printTree()
void BlockCopy::printTree (ostream & s, int4 level) const virtual
Print tree structure of any blocks owned by this.
Recursively print out the hierarchical structure of this FlowBlock.
Parameters
s is the output stream
level is the current level of indentation
Reimplemented from FlowBlock.
References copy, and FlowBlock::printTree().
saveXmlHeader()
void BlockCopy::saveXmlHeader (ostream & s) const virtual
Save basic information as XML attributes.
Parameters
s is the output stream
Reimplemented from FlowBlock.
References a_v_i(), copy, and FlowBlock::saveXmlHeader().
The documentation for this class was generated from the following files:
block.hh
block.cc