decompiler: RuleSubvarSext Class Reference
RuleSubvarSext Class Reference
Perform SubvariableFlow analysis triggered by INT_SEXT.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
virtual void reset (Funcdata &data)
Reset this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Private Attributes
int4 isaggressive
Is it guaranteed the root is a sub-variable needing to be trimmed.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Perform SubvariableFlow analysis triggered by INT_SEXT.
Member Function Documentation
applyOp()
int4 RuleSubvarSext::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References calc_mask(), SubvariableFlow::doReplacement(), SubvariableFlow::doTrace(), and isaggressive.
clone()
virtual Rule* RuleSubvarSext::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
getOpList()
void RuleSubvarSext::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_SEXT.
reset()
void RuleSubvarSext::reset (Funcdata & data) virtual
Reset this Rule.
Any state that is specific to a particular function is cleared by this method. This method can be used to initialize a Rule based on a new function it will apply to
Parameters
data is the new function about to be transformed
Reimplemented from Rule.
References isaggressive.
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc