decompiler: JumpValuesRange Class Reference
JumpValuesRange Class Reference
single entry switch variable that can take a range of values
#include <jumptable.hh>
Public Member Functions
virtual void truncate (int4 nm)
virtual uintb getSize (void) const
Return the number of values the variables can take.
virtual bool contains (uintb val) const
Return true if the given value is in the set of possible values.
virtual bool initializeForReading (void) const
Initialize this for iterating over the set of possible values.
virtual bool next (void) const
Advance the iterator, return true if there is another value.
virtual uintb getValue (void) const
Get the current value.
virtual Varnode * getStartVarnode (void) const
Get the Varnode associated with the current value.
virtual PcodeOp * getStartOp (void) const
Get the PcodeOp associated with the current value.
virtual bool isReversible (void) const
Return true if the current value can be reversed to get a label.
virtual JumpValues * clone (void) const
Clone this iterator.
Protected Attributes
CircleRange range
Acceptable range of values for the normalized switch variable.
Varnode * normqvn
Varnode representing the normalized switch variable.
PcodeOp * startop
First PcodeOp in the jump-table calculation.
uintb curval
The current value pointed to be the iterator.
Detailed Description
single entry switch variable that can take a range of values
Member Function Documentation
initializeForReading()
bool JumpValuesRange::initializeForReading (void) const virtual
Initialize this for iterating over the set of possible values.
Returns
true if there are any values to iterate over
Implements JumpValues.
Reimplemented in JumpValuesRangeDefault.
References curval, CircleRange::getSize(), and range.
Referenced by JumpBasic::buildAddresses(), and JumpBasic::buildLabels().
truncate()
void JumpValuesRange::truncate (int4 nm) virtual
The starting value for the range and the step is preserved. The ending value is set so there are exactly the given number of elements in the range.
Parameters
nm is the given number
Implements JumpValues.
References count_leading_zeros(), range, and CircleRange::setRange().
Referenced by JumpBasic::sanityCheck().
The documentation for this class was generated from the following files:
jumptable.hh
jumptable.cc