decompiler: SetOptions Class Reference
SetOptions Class Reference
Command to toggle options within the decompiler.
#include <ghidra_process.hh>
Public Member Functions
virtual void rawAction (void)
Perform the action of the command.
Public Member Functions inherited from GhidraCommand
int4 doit (void)
Configure and execute the command, then send back results.
Public Attributes
bool res
Set to true if the option change succeeded.
Private Member Functions
virtual void loadParameters (void)
Read parameters directing command execution.
virtual void sendResult (void)
Send results of the command (if any) back to the Ghidra client.
Private Attributes
Document * doc
The XML option document.
Additional Inherited Members
Protected Attributes inherited from GhidraCommand
istream & sin
The input stream from the Ghidra client.
ostream & sout
The output stream to the Ghidra client.
ArchitectureGhidra * ghidra
The Architecture on which to perform the command.
int4 status
Meta-command to system (0=wait for next command, 1=terminate process)
Detailed Description
Command to toggle options within the decompiler.
The decompiler supports configuration of a variety of named options that affect everything from how code is transformed to how it is displayed (See ArchOption). The command expects 2 string parameters: the encoded integer id of the program, and an XML document containing an <optionslist> tag. The <optionslist> tag contains one child tag for each option to be configured. The command returns a single character message, 't' or 'f', indicating whether the configuration succeeded.
Member Function Documentation
loadParameters()
void SetOptions::loadParameters (void) private virtual
Read parameters directing command execution.
This method reads an id selecting the Architecture to act on, but it can be overloaded to read any set of data from the Ghidra client to configure how the command is executed. Individual parameters are read using the method protocol.
Reimplemented from GhidraCommand.
References doc, GhidraCommand::loadParameters(), ArchitectureGhidra::readXMLStream(), and GhidraCommand::sin.
rawAction()
void SetOptions::rawAction (void) virtual
Perform the action of the command.
Configuration is assumed to have happened, and this object can immediately begin examining and manipulating data under the active Architecture object to perform the command.
Implements GhidraCommand.
References doc, GhidraCommand::ghidra, Architecture::options, res, and OptionDatabase::restoreXml().
sendResult()
void SetOptions::sendResult (void) private virtual
Send results of the command (if any) back to the Ghidra client.
This method sends any warnings accumulated during execution back, but it can be overloaded to send back any kind of information. Individual records are sent using the message protocol.
Reimplemented from GhidraCommand.
References res, GhidraCommand::sendResult(), GhidraCommand::sout, and ArchitectureGhidra::writeStringStream().
The documentation for this class was generated from the following files:
ghidra_process.hh
ghidra_process.cc