decompiler: RulePtrsubCharConstant Class Reference
RulePtrsubCharConstant Class Reference
Cleanup: Set-up to print string constants.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Private Member Functions
bool pushConstFurther (Funcdata &data, TypePointer *outtype, PcodeOp *op, int4 slot, uintb val)
Try to push constant pointer further.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Cleanup: Set-up to print string constants.
If a SUBPIECE refers to a global symbol, the output of the SUBPIECE is a (char *), and the address is read-only, then get rid of the SUBPIECE in favor of printing a constant string.
Member Function Documentation
applyOp()
int4 RulePtrsubCharConstant::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References CPUI_COPY, TypeSpacebase::getAddress(), TypeSpacebase::getMap(), PcodeOp::getSlot(), Scope::isReadOnly(), Funcdata::newConstant(), Funcdata::opDestroy(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), pushConstFurther(), TYPE_PTR, TYPE_SPACEBASE, and Varnode::updateType().
clone()
virtual Rule* RulePtrsubCharConstant::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
getOpList()
void RulePtrsubCharConstant::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_PTRSUB.
pushConstFurther()
bool RulePtrsubCharConstant::pushConstFurther (Funcdata & data, TypePointer * outtype, PcodeOp * op, int4 slot, uintb val) private
Try to push constant pointer further.
Given a PTRSUB has been collapsed to a constant COPY of a string address, try to collapse descendant any PTRADD.
Parameters
data is the function being analyzed
outtype is the data-type associated with the constant
op is the putative descendant PTRADD
slot is the input slot receiving the collapsed PTRSUB
val is the constant pointer value
Returns
true if the descendant was collapsed
References CPUI_COPY, CPUI_PTRADD, Funcdata::newConstant(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and Varnode::updateType().
Referenced by applyOp().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc