decompiler: SleighArchitecture Class Reference
SleighArchitecture Class Reference
An Architecture that uses the decompiler's native SLEIGH translation engine.
#include <sleigh_arch.hh>
Public Member Functions
SleighArchitecture (const string &fname, const string &targ, ostream *estream)
Construct given executable file.
void saveXmlHeader (ostream &s) const
Write out (as XML) basic attributes of the active executable.
void restoreXmlHeader (const Element *el)
Restore from XML basic attributes of an executable.
virtual void printMessage (const string &message) const
Print an error message to console.
virtual string getDescription (void) const
Public Member Functions inherited from Architecture
Architecture (void)
Construct an uninitialized Architecture.
void init (DocumentStorage &store)
Load the image and configure architecture.
ProtoModel * getModel (const string &nm) const
Get a specific PrototypeModel.
bool hasModel (const string &nm) const
Does this Architecture have a specific PrototypeModel.
bool highPtrPossible (const Address &loc, int4 size) const
Are pointers possible to the given location?
AddrSpace * getSpaceBySpacebase (const Address &loc, int4 size) const
Get space associated with a spacebase register.
const LanedRegister * getLanedRegister (const Address &loc, int4 size) const
Get LanedRegister associated with storage.
int4 getMinimumLanedRegisterSize (void) const
Get the minimum size of a laned register in bytes.
void setDefaultModel (const string &nm)
Set the default PrototypeModel.
void clearAnalysis (Funcdata *fd)
Clear analysis specific to a function.
void readLoaderSymbols (void)
Read any symbols from loader into database.
void collectBehaviors (vector< OpBehavior * > &behave) const
Provide a list of OpBehavior objects.
SegmentOp * getSegmentOp (AddrSpace *spc) const
Retrieve the segment op for the given space if any.
void setPrototype (const PrototypePieces &pieces)
Set the prototype for a particular function.
void setPrintLanguage (const string &nm)
Establish a particular output language.
void globalify (void)
Mark all spaces as global.
void restoreFlowOverride (const Element *el)
Set flow overrides from XML.
virtual ~Architecture (void)
Destructor.
virtual void saveXml (ostream &s) const
Serialize this architecture to XML.
virtual void restoreXml (DocumentStorage &store)
Restore the Architecture state from an XML stream.
virtual void nameFunction (const Address &addr, string &name) const
Pick a default name for a function.
Public Member Functions inherited from AddrSpaceManager
AddrSpaceManager (void)
Construct an empty address space manager.
virtual ~AddrSpaceManager (void)
Destroy the manager.
int4 getDefaultSize (void) const
Get size of addresses for the default space.
AddrSpace * getSpaceByName (const string &nm) const
Get address space by name.
AddrSpace * getSpaceByShortcut (char sc) const
Get address space from its shortcut.
AddrSpace * getIopSpace (void) const
Get the internal pcode op space.
AddrSpace * getFspecSpace (void) const
Get the internal callspec space.
AddrSpace * getJoinSpace (void) const
Get the joining space.
AddrSpace * getStackSpace (void) const
Get the stack space for this processor.
AddrSpace * getUniqueSpace (void) const
Get the temporary register space for this processor.
AddrSpace * getDefaultCodeSpace (void) const
Get the default address space of this processor.
AddrSpace * getDefaultDataSpace (void) const
Get the default address space where data is stored.
AddrSpace * getConstantSpace (void) const
Get the constant space.
Address getConstant (uintb val) const
Get a constant encoded as an Address.
Address createConstFromSpace (AddrSpace *spc) const
Create a constant address encoding an address space.
Address resolveConstant (AddrSpace *spc, uintb val, int4 sz, const Address &point, uintb &fullEncoding) const
Resolve a native constant into an Address.
int4 numSpaces (void) const
Get the number of address spaces for this processor.
AddrSpace * getSpace (int4 i) const
Get an address space via its index.
AddrSpace * getNextSpaceInOrder (AddrSpace *spc) const
Get the next contiguous address space.
JoinRecord * findAddJoin (const vector< VarnodeData > &pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
JoinRecord * findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
void setDeadcodeDelay (AddrSpace *spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
void truncateSpace (const TruncationTag &tag)
Mark a space as truncated from its original size.
Address constructFloatExtensionAddress (const Address &realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
Address constructJoinAddress (const Translate *translate, const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz)
Build a logical whole from register pairs.
void renormalizeJoinAddress (Address &addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
Static Public Member Functions
static string normalizeProcessor (const string &nm)
Try to recover a language id processor field.
static string normalizeEndian (const string &nm)
Try to recover a language id endianess field.
static string normalizeSize (const string &nm)
Try to recover a language id size field.
static string normalizeArchitecture (const string &nm)
Try to recover a language id string.
static void scanForSleighDirectories (const string &rootpath)
Scan directories for SLEIGH specification files.
static void shutdown (void)
Shutdown this SleighArchitecture and free all resources.
Static Public Attributes
static FileManage specpaths
Known directories that contain .ldefs files.
Protected Member Functions
virtual Translate * buildTranslator (DocumentStorage &store)
Build the Translator object.
virtual PcodeInjectLibrary * buildPcodeInjectLibrary (void)
Build the injection library.
virtual void buildSpecFile (DocumentStorage &store)
Load any relevant specification files.
virtual void modifySpaces (Translate *trans)
Modify address spaces as required by this Architecture.
virtual void resolveArchitecture (void)
Figure out the processor and compiler of the target executable.
Protected Member Functions inherited from Architecture
void addSpacebase (AddrSpace *basespace, const string &nm, const VarnodeData &ptrdata, int4 truncSize, bool isreversejustified, bool stackGrowth)
Create a new space and associated pointer.
void addNoHighPtr (const Range &rng)
Add a new region where pointers do not exist.
virtual Scope * buildGlobalScope (void)
Build the global scope for this executable.
virtual void buildLoader (DocumentStorage &store)=0
Build the LoadImage object and load the executable image.
virtual void buildTypegrp (DocumentStorage &store)
Build the data-type factory/container.
virtual void buildCommentDB (DocumentStorage &store)
Build the comment database.
virtual void buildConstantPool (DocumentStorage &store)
Build the constant pool.
virtual void buildInstructions (DocumentStorage &store)
Register the p-code operations.
virtual void buildAction (DocumentStorage &store)
Build the Action framework.
virtual void buildContext (DocumentStorage &store)
Build the Context database.
virtual void postSpecFile (void)
Let components initialize after Translate is built.
void restoreFromSpec (DocumentStorage &store)
Fully initialize the Translate object.
void fillinReadOnlyFromLoader (void)
Load info about read-only sections.
void initializeSegments ()
Set up segment resolvers.
void cacheAddrSpaceProperties (void)
Calculate some frequently used space properties and cache them.
void parseProcessorConfig (DocumentStorage &store)
Apply processor specific configuration.
void parseCompilerConfig (DocumentStorage &store)
Apply compiler specific configuration.
void parseExtraRules (DocumentStorage &store)
Apply any Rule tags.
void parseDynamicRule (const Element *el)
Apply details of a dynamic Rule object.
ProtoModel * parseProto (const Element *el)
Build a proto-type model from an XML tag.
void parseProtoEval (const Element *el)
Apply prototype evaluation configuration.
void parseDefaultProto (const Element *el)
Apply default prototype model configuration.
void parseGlobal (const Element *el)
Apply global space configuration.
void addOtherSpace (void)
Add OTHER space and all of its overlays to the symboltab.
void parseReadOnly (const Element *el)
Apply read-only region configuration.
void parseVolatile (const Element *el)
Apply volatile region configuration.
void parseReturnAddress (const Element *el)
Apply return address configuration.
void parseIncidentalCopy (const Element *el)
Apply incidental copy configuration.
void parseLaneSizes (const Element *el)
Apply lane size configuration.
void parseStackPointer (const Element *el)
Apply stack pointer configuration.
void parseDeadcodeDelay (const Element *el)
Apply dead-code delay configuration.
void parseFuncPtrAlign (const Element *el)
Apply function pointer alignment configuration.
void parseSpacebase (const Element *el)
Create an additional indexed space.
void parseNoHighPtr (const Element *el)
Apply memory alias configuration.
void parsePreferSplit (const Element *el)
Designate registers to be split.
void parseAggressiveTrim (const Element *el)
Designate how to trim extension p-code ops.
Protected Member Functions inherited from AddrSpaceManager
AddrSpace * restoreXmlSpace (const Element *el, const Translate *trans)
Add a space to the model based an on XML tag.
void restoreXmlSpaces (const Element *el, const Translate *trans)
Restore address spaces in the model from an XML tag.
void setDefaultCodeSpace (int4 index)
Set the default address space (for code)
void setDefaultDataSpace (int4 index)
Set the default address space for data.
void setReverseJustified (AddrSpace *spc)
Set reverse justified property on this space.
void assignShortcut (AddrSpace *spc)
Select a shortcut character for a new space.
void markNearPointers (AddrSpace *spc, int4 size)
Mark that given space can be accessed with near pointers.
void insertSpace (AddrSpace *spc)
Add a new address space to the model.
void copySpaces (const AddrSpaceManager *op2)
Copy spaces from another manager.
void addSpacebasePointer (SpacebaseSpace *basespace, const VarnodeData &ptrdata, int4 truncSize, bool stackGrowth)
Set the base register of a spacebase space.
void insertResolver (AddrSpace *spc, AddressResolver *rsolv)
Override the base resolver for a space.
JoinRecord * findJoinInternal (uintb offset) const
Find JoinRecord for offset in the join space.
Static Protected Member Functions
static void collectSpecFiles (ostream &errs)
Gather specification files in normal locations.
Protected Attributes
ostream * errorstream
Error stream associated with this SleighArchitecture.
Private Member Functions
bool isTranslateReused (void)
Test if last Translate object can be reused.
Static Private Member Functions
static void loadLanguageDescription (const string &specfile, ostream &errs)
Read a SLEIGH .ldefs file.
Private Attributes
int4 languageindex
Index (within LanguageDescription array) of the active language.
string filename
Name of active load-image file.
string target
The language id of the active load-image.
Static Private Attributes
static Sleigh * last_sleigh = (Sleigh *)0
Last Translate object used by a SleighArchitecture.
static int4 last_languageindex
Index of the LanguageDescription associated with the last Translate object.
static vector< LanguageDescription > description
List of languages we know about.
Additional Inherited Members
Public Attributes inherited from Architecture
string archid
ID string uniquely describing this architecture.
int4 trim_recurse_max
How many levels to let parameter trims recurse.
int4 max_implied_ref
Maximum number of references to an implied var.
int4 max_term_duplication
Max terms duplicated without a new variable.
int4 max_basetype_size
Maximum size of an "integer" type before creating an array type.
int4 min_funcsymbol_size
Minimum size of a function symbol.
bool aggressive_ext_trim
Aggressively trim inputs that look like they are sign extended.
bool readonlypropagate
true if readonly values should be treated as constants
bool infer_pointers
True if we should infer pointers from constants that are likely addresses.
vector< AddrSpace * > inferPtrSpaces
Set of address spaces in which a pointer constant is inferable.
int4 funcptr_align
How many bits of alignment a function ptr has.
uint4 flowoptions
options passed to flow following engine
int4 alias_block_level
Aliases blocked by 0=none, 1=struct, 2=array, 3=all.
vector< Rule * > extra_pool_rules
Extra rules that go in the main pool (cpu specific, experimental)
Database * symboltab
Memory map of global variables and functions.
ContextDatabase * context
Map from addresses to context settings.
map< string, ProtoModel * > protoModels
Parsed forms of possible prototypes.
ProtoModel * defaultfp
Parsed form of default prototype.
VarnodeData defaultReturnAddr
Default storage location of return address (for current function)
ProtoModel * evalfp_current
Function proto to use when evaluating current function.
ProtoModel * evalfp_called
Function proto to use when evaluating called functions.
TypeFactory * types
List of types for this binary.
const Translate * translate
Translation method for this binary.
LoadImage * loader
Method for loading portions of binary.
PcodeInjectLibrary * pcodeinjectlib
Pcode injection manager.
RangeList nohighptr
Ranges for which high-level pointers are not possible.
CommentDatabase * commentdb
Comments for this architecture.
ConstantPool * cpool
Deferred constant values.
PrintLanguage * print
Current high-level language printer.
vector< PrintLanguage * > printlist
List of high-level language printers supported.
OptionDatabase * options
Options that can be configured.
vector< TypeOp * > inst
Registered p-code instructions.
UserOpManage userops
Specifically registered user-defined p-code ops.
vector< PreferSplitRecord > splitrecords
registers that we would prefer to see split for this processor
vector< LanedRegister > lanerecords
Vector registers that have preferred lane sizes.
ActionDatabase allacts
Actions that can be applied in this architecture.
bool loadersymbols_parsed
True if loader symbols have been read.
Detailed Description
An Architecture that uses the decompiler's native SLEIGH translation engine.
Any Architecture derived from this knows how to natively read in:
a compiled SLEIGH specification (.sla)
a processor specification file (.pspec), and
a compiler specification file (.cspec)
Generally a language id (i.e. x86:LE:64:default) is provided, then this object is able to automatically load in configuration and construct the Translate object.
Constructor & Destructor Documentation
SleighArchitecture()
SleighArchitecture::SleighArchitecture (const string & fname, const string & targ, ostream * estream)
Construct given executable file.
Prepare this SleighArchitecture for analyzing the given executable image. Full initialization, including creation of the Translate object, still must be performed by calling the init() method.
Parameters
fname is the filename of the given executable image
targ is the optional language id or other target information
estream is a pointer to an output stream for writing error messages
References errorstream, filename, and target.
Member Function Documentation
buildPcodeInjectLibrary()
PcodeInjectLibrary * SleighArchitecture::buildPcodeInjectLibrary (void) protected virtual
Build the injection library.
This creates the container for p-code injections. It is initially empty.
Returns
the PcodeInjectLibrary object
Implements Architecture.
References Translate::getUniqueBase(), and Architecture::translate.
buildSpecFile()
void SleighArchitecture::buildSpecFile (DocumentStorage & store) protected virtual
Load any relevant specification files.
Processor/architecture specific configuration files are loaded into the XML store
Parameters
store is the document store that will hold the configuration
Implements Architecture.
References Architecture::archid, description, LowlevelError::explain, XmlError::explain, LanguageDescription::getCompiler(), isTranslateReused(), languageindex, DocumentStorage::openDocument(), DocumentStorage::registerTag(), and specpaths.
buildTranslator()
Translate * SleighArchitecture::buildTranslator (DocumentStorage & store) protected virtual
Build the Translator object.
This builds the main disassembly component for the Architecture This does not initially the engine for a specific processor.
Parameters
store may hold configuration information
Returns
the Translate object
Implements Architecture.
References Architecture::context, isTranslateReused(), languageindex, last_languageindex, last_sleigh, and Architecture::loader.
collectSpecFiles()
void SleighArchitecture::collectSpecFiles (ostream & errs) static protected
Gather specification files in normal locations.
This is run once when spinning up the decompiler. Look for the root .ldefs files within the normal directories and parse them. Use these to populate the list of language ids that are supported.
Parameters
errs is an output stream for writing error messages
References description, loadLanguageDescription(), and specpaths.
Referenced by XmlArchitecture::buildLoader(), RawBinaryArchitecture::buildLoader(), and BfdArchitecture::buildLoader().
isTranslateReused()
bool SleighArchitecture::isTranslateReused (void) private
Test if last Translate object can be reused.
If the current languageindex matches the last_languageindex, try to reuse the previous Sleigh object, so we don't reload the .sla file.
Returns
true if it can be reused
References languageindex, last_languageindex, and last_sleigh.
Referenced by buildSpecFile(), and buildTranslator().
loadLanguageDescription()
void SleighArchitecture::loadLanguageDescription (const string & specfile, ostream & errs) static private
Read a SLEIGH .ldefs file.
Any <language> tags are added to the LanguageDescription array
Parameters
specfile is the filename of the .ldefs file
errs is an output stream for printing error messages
References description, and xml_tree().
Referenced by collectSpecFiles().
modifySpaces()
void SleighArchitecture::modifySpaces (Translate * trans) protected virtual
Modify address spaces as required by this Architecture.
If spaces need to be truncated or otherwise changed from processor defaults, this routine performs the modification.
Parameters
trans is the processor disassembly object
Implements Architecture.
References description, languageindex, and AddrSpaceManager::truncateSpace().
normalizeArchitecture()
string SleighArchitecture::normalizeArchitecture (const string & nm) static
Try to recover a language id string.
Try to normalize the target string into a valid language id. In general the target string must already look like a language id, but it can drop the compiler field and be a little sloppier in its format.
Parameters
nm is the given target string
Returns
the normalized language id
References normalizeEndian(), normalizeProcessor(), and normalizeSize().
Referenced by resolveArchitecture().
normalizeEndian()
string SleighArchitecture::normalizeEndian (const string & nm) static
Try to recover a language id endianess field.
Given an architecture target string try to recover an appropriate endianness string for use in a normalized language id.
Parameters
nm is the given target string
Returns
the endianness field
Referenced by normalizeArchitecture().
normalizeProcessor()
string SleighArchitecture::normalizeProcessor (const string & nm) static
Try to recover a language id processor field.
Given an architecture target string try to recover an appropriate processor name for use in a normalized language id.
Parameters
nm is the given target string
Returns
the processor field
Referenced by normalizeArchitecture().
normalizeSize()
string SleighArchitecture::normalizeSize (const string & nm) static
Try to recover a language id size field.
Given an architecture target string try to recover an appropriate size string for use in a normalized language id.
Parameters
nm is the given target string
Returns
the size field
Referenced by normalizeArchitecture().
printMessage()
virtual void SleighArchitecture::printMessage (const string & message) const inline virtual
Print an error message to console.
Write the given message to whatever the registered error stream is
Parameters
message is the error message
Implements Architecture.
References errorstream.
Referenced by resolveArchitecture().
restoreXmlHeader()
void SleighArchitecture::restoreXmlHeader (const Element * el)
Restore from XML basic attributes of an executable.
Parameters
el is the root XML element
References filename, Element::getAttributeValue(), and target.
Referenced by XmlArchitecture::restoreXml(), RawBinaryArchitecture::restoreXml(), and BfdArchitecture::restoreXml().
saveXmlHeader()
void SleighArchitecture::saveXmlHeader (ostream & s) const
Write out (as XML) basic attributes of the active executable.
Parameters
s is the XML output stream
References a_v(), filename, and target.
Referenced by XmlArchitecture::saveXml(), RawBinaryArchitecture::saveXml(), and BfdArchitecture::saveXml().
scanForSleighDirectories()
void SleighArchitecture::scanForSleighDirectories (const string & rootpath) static
Scan directories for SLEIGH specification files.
This assumes a standard "Ghidra/Processors/*&zwj;/data/languages" layout. It scans for all matching directories and prepares for reading .ldefs files.
Parameters
rootpath is the root path of the Ghidra installation
References specpaths.
The documentation for this class was generated from the following files:
sleigh_arch.hh
sleigh_arch.cc