decompiler: PrintLanguageCapability Class Reference
PrintLanguageCapability Class Reference abstract
Base class for high-level language capabilities.
#include <printlanguage.hh>
Public Member Functions
virtual void initialize (void)
Complete initialization of an extension point.
virtual PrintLanguage * buildLanguage (Architecture *glb)=0
Build the main PrintLanguage object corresponding to this capability.
Static Public Member Functions
static PrintLanguageCapability * getDefault (void)
Retrieve the default language capability.
static PrintLanguageCapability * findCapability (const string &name)
Find a language capability by name.
Static Public Member Functions inherited from CapabilityPoint
static void initializeAll (void)
Finish initialization for all extension points.
Protected Attributes
string name
Unique identifier for language capability.
bool isdefault
Set to true to treat this as the default language.
Static Private Attributes
static vector< PrintLanguageCapability * > thelist
The static array of registered high-level languages.
Additional Inherited Members
Protected Member Functions inherited from CapabilityPoint
CapabilityPoint (void)
Construct extension capability exactly once.
Detailed Description
Base class for high-level language capabilities.
This class is overridden to introduce a new high-level language back-end to the system. A static singleton is instantiated to automatically register the new capability with the system. A static array keeps track of all the registered capabilities.
The singleton is registered with a name, which the user can use to select the language, and it acts as a factory for the main language printing class for the capability, which must be derived from PrintLanguage. The factory method for the capability to override is buildLanguage().
Member Function Documentation
buildLanguage()
virtual PrintLanguage* PrintLanguageCapability::buildLanguage (Architecture * glb) pure virtual
Build the main PrintLanguage object corresponding to this capability.
An Architecture will call this once. All decompiling from this Architecture will use this same emitter.
Parameters
glb is the Architecture that will own the new emitter
Returns
the instantiated PrintLanguage emittter
Implemented in PrintCCapability, and PrintJavaCapability.
Referenced by Architecture::Architecture(), and Architecture::setPrintLanguage().
findCapability()
PrintLanguageCapability * PrintLanguageCapability::findCapability (const string & name) static
Find a language capability by name.
Parameters
name is the language name to search for
Returns
the matching language capability or NULL
References name, and thelist.
Referenced by Architecture::setPrintLanguage().
getDefault()
PrintLanguageCapability * PrintLanguageCapability::getDefault (void) static
Retrieve the default language capability.
This retrieves the capability with its isdefault field set or the first capability registered.
Returns
the default language capability
References thelist.
Referenced by Architecture::Architecture().
initialize()
void PrintLanguageCapability::initialize (void) virtual
Complete initialization of an extension point.
This method is implemented by each extension so it can do specialized integration
Implements CapabilityPoint.
References isdefault, and thelist.
The documentation for this class was generated from the following files:
printlanguage.hh
printlanguage.cc