decompiler: RuleSLess2Zero Class Reference
RuleSLess2Zero Class Reference
Simplify INT_SLESS applied to 0 or -1.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Private Member Functions
static Varnode * getHiBit (PcodeOp *op)
Get the piece containing the sign-bit.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Simplify INT_SLESS applied to 0 or -1.
Forms include:
0 s< V * -1 => V s< 0
V * -1 s< 0 => 0 s< V
-1 s< SUB(V,#hi) => -1 s< V
SUB(V,#hi) s< 0 => V s< 0
-1 s< ~V => V s< 0
~V s< 0 => -1 s< V
(V & 0xf000) s< 0 => V s< 0
-1 s< (V & 0xf000) => -1 s< V -CONCAT(V,W) s< 0 => V s< 0 --1 s< CONCAT(V,W) => -1 s> V`
There is a second set of forms where one side of the comparison is built out of a high and low piece, where the high piece determines the sign bit:
-1 s< (hi + lo) => -1 s< hi
(hi + lo) s< 0 => hi s< 0
Member Function Documentation
applyOp()
int4 RuleSLess2Zero::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References calc_mask(), CPUI_INT_AND, CPUI_INT_EQUAL, CPUI_INT_MULT, CPUI_INT_NEGATE, CPUI_INT_NOTEQUAL, CPUI_PIECE, CPUI_SUBPIECE, getHiBit(), Varnode::loneDescend(), Funcdata::newConstant(), Funcdata::opSetInput(), and Funcdata::opSetOpcode().
clone()
virtual Rule* RuleSLess2Zero::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
getHiBit()
Varnode * RuleSLess2Zero::getHiBit (PcodeOp * op) static private
Get the piece containing the sign-bit.
If the given PcodeOp pieces together 2 Varnodes only one of which is determining the high bit, return that Varnode.
Parameters
op is the given PcodeOp
Returns
the Varnode holding the high bit
References calc_mask(), CPUI_INT_ADD, CPUI_INT_OR, and CPUI_INT_XOR.
Referenced by applyOp().
getOpList()
void RuleSLess2Zero::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_SLESS.
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc