decompiler: RuleDivOpt Class Reference
RuleDivOpt Class Reference
Convert INT_MULT and shift forms into INT_DIV or INT_SDIV.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Public Member Functions
static Varnode * findForm (PcodeOp *op, int4 &n, uintb &y, int4 &xsize, OpCode &extopc)
Check for INT_(S)RIGHT and/or SUBPIECE followed by INT_MULT.
Static Private Member Functions
static uintb calcDivisor (uintb n, uint8 y, int4 xsize)
Calculate the divisor.
static void moveSignBitExtraction (Varnode *firstVn, Varnode *replaceVn, Funcdata &data)
Replace sign-bit extractions from the first given Varnode with the second Varnode.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Convert INT_MULT and shift forms into INT_DIV or INT_SDIV.
The unsigned and signed variants are:
sub((zext(V)*c)>>n, 0) => V / (2^n/(c-1))
sub((sext(V)*c)s>>n, 0) => V s/ (2^n/(c-1))
Member Function Documentation
applyOp()
int4 RuleDivOpt::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References calcDivisor(), CPUI_INT_ADD, CPUI_INT_DIV, CPUI_INT_SDIV, CPUI_INT_SEXT, CPUI_INT_SRIGHT, CPUI_INT_ZEXT, CPUI_SUBPIECE, findForm(), moveSignBitExtraction(), Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::opInsertBefore(), Funcdata::opSetInput(), and Funcdata::opSetOpcode().
calcDivisor()
uintb RuleDivOpt::calcDivisor (uintb n, uint8 y, int4 xsize) static private
Calculate the divisor.
Given the multiplicative encoding y and the n, the power of 2, Compute:
divisor = 2^n / (y-1)
Do some additional checks on the parameters as an optimized encoding of a divisor.
Parameters
n is the power of 2
y is the multiplicative coefficient
xsize is the maximum power of 2
Returns
the divisor or 0 if the checks fail
References power2Divide().
Referenced by applyOp().
clone()
virtual Rule* RuleDivOpt::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
findForm()
Varnode * RuleDivOpt::findForm (PcodeOp * op, int4 & n, uintb & y, int4 & xsize, OpCode & extopc) static
Check for INT_(S)RIGHT and/or SUBPIECE followed by INT_MULT.
Look for the forms:
sub(ext(X) * #y,#c) or
sub(ext(X) * #y,#c) >> n or
(ext(X) * #y) >> n
Looks for truncation/multiplication consistent with an optimized division. The truncation can come as either a SUBPIECE operation and/or right shifts. The numerand and the amount it has been extended is discovered. The extension can be, but doesn't have to be, an explicit INT_ZEXT or INT_SEXT. If the form doesn't match NULL is returned. If the Varnode holding the extended numerand matches the final operand size, it is returned, otherwise the unextended numerand is returned. The total truncation, the multiplicative constant, the numerand size, and the extension type are all passed back.
Parameters
op is the root of the expression
n is the reference that will hold the total number of bits of truncation
y will hold the multiplicative constant
xsize will hold the number of (non-zero) bits in the numerand
extopc holds whether the extension is INT_ZEXT or INT_SEXT
Returns
the extended numerand if possible, or the unextended numerand, or NULL
References count_leading_zeros(), CPUI_INT_MULT, CPUI_INT_RIGHT, CPUI_INT_SEXT, CPUI_INT_SRIGHT, CPUI_INT_ZEXT, CPUI_MAX, and CPUI_SUBPIECE.
Referenced by applyOp().
getOpList()
void RuleDivOpt::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_RIGHT, CPUI_INT_SRIGHT, and CPUI_SUBPIECE.
moveSignBitExtraction()
void RuleDivOpt::moveSignBitExtraction (Varnode * firstVn, Varnode * replaceVn, Funcdata & data) static private
Replace sign-bit extractions from the first given Varnode with the second Varnode.
Look for either:
V >> 0x1f
V s>> 0x1f
Parameters
firstVn is the first given Varnode
replaceVn is the Varnode to replace it with in each extraction
data is the function holding the Varnodes
References CPUI_INT_RIGHT, CPUI_INT_SRIGHT, and Funcdata::opSetInput().
Referenced by applyOp().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc