decompiler: ScopeGhidra Class Reference
ScopeGhidra Class Reference
An implementation of the Scope interface by querying a Ghidra client for Symbol information.
#include <database_ghidra.hh>
Public Member Functions
ScopeGhidra (ArchitectureGhidra *g)
Constructor.
void lockDefaultProperties (void)
Lock in the default state of the boolean property map.
virtual void clear (void)
Clear all symbols from this scope.
virtual SymbolEntry * addSymbol (const string &name, Datatype *ct, const Address &addr, const Address &usepoint)
Add a new Symbol to this Scope, given a name, data-type, and a single mapping.
virtual string buildVariableName (const Address &addr, const Address &pc, Datatype *ct, int4 &index, uint4 flags) const
Given an address and data-type, build a suitable generic symbol name.
virtual string buildUndefinedName (void) const
Build a formal undefined name, used internally when a Symbol is not given a name.
virtual void setAttribute (Symbol *sym, uint4 attr)
Set boolean Varnode properties on a Symbol.
virtual void clearAttribute (Symbol *sym, uint4 attr)
Clear boolean Varnode properties on a Symbol.
virtual void setDisplayFormat (Symbol *sym, uint4 attr)
Set the display format for a Symbol.
virtual SymbolEntry * findAddr (const Address &addr, const Address &usepoint) const
Find a Symbol at a given address and usepoint.
virtual SymbolEntry * findContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest Symbol containing the given memory range.
virtual SymbolEntry * findClosestFit (const Address &addr, int4 size, const Address &usepoint) const
Find Symbol which is the closest fit to the given memory range.
virtual Funcdata * findFunction (const Address &addr) const
Find the function starting at the given address.
virtual ExternRefSymbol * findExternalRef (const Address &addr) const
Find an external reference at the given address.
virtual LabSymbol * findCodeLabel (const Address &addr) const
Find a label Symbol at the given address.
virtual Funcdata * resolveExternalRefFunction (ExternRefSymbol *sym) const
Convert an external reference to the referenced function.
virtual SymbolEntry * findOverlap (const Address &addr, int4 size) const
Find first Symbol overlapping the given memory range.
virtual void findByName (const string &name, vector< Symbol * > &res) const
Find a Symbol by name within this Scope.
virtual bool isNameUsed (const string &name) const
Check if the given name is used within this scope.
virtual MapIterator begin (void) const
Beginning iterator to mapped SymbolEntrys.
virtual MapIterator end (void) const
Ending iterator to mapped SymbolEntrys.
virtual list< SymbolEntry >::const_iterator beginDynamic (void) const
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::const_iterator endDynamic (void) const
Ending iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator beginDynamic (void)
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator endDynamic (void)
Ending iterator to dynamic SymbolEntrys.
virtual void clearCategory (int4 cat)
Clear all symbols of the given category from this scope.
virtual void clearUnlockedCategory (int4 cat)
Clear unlocked symbols of the given category from this scope.
virtual void clearUnlocked (void)
Clear all unlocked symbols from this scope.
virtual void restrictScope (Funcdata *f)
Convert this to a local Scope.
virtual void removeSymbolMappings (Symbol *symbol)
Remove all SymbolEntrys from the given Symbol.
virtual void removeSymbol (Symbol *symbol)
Remove the given Symbol from this Scope.
virtual void renameSymbol (Symbol *sym, const string &newname)
Rename a Symbol within this Scope.
virtual void retypeSymbol (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol within this Scope.
virtual string makeNameUnique (const string &nm) const
Produce a version of the given symbol name that won't collide with other names in this Scope.
virtual void saveXml (ostream &s) const
Write out this as a <scope> XML tag.
virtual void restoreXml (const Element *el)
Restore this Scope from a <scope> XML tag.
virtual void printEntries (ostream &s) const
Dump a description of all SymbolEntry objects to a stream.
virtual int4 getCategorySize (int4 cat) const
Get the number of Symbols in the given category.
virtual Symbol * getCategorySymbol (int4 cat, int4 ind) const
Retrieve a Symbol by index within a specific category.
virtual void setCategory (Symbol *sym, int4 cat, int4 ind)
Set the category and index for the given Symbol.
Public Member Functions inherited from Scope
Scope (const string &nm, Architecture *g)
Construct an empty scope, given a name and Architecture.
virtual ~Scope (void)
Destructor.
virtual bool inScope (const Address &addr, int4 size, const Address &usepoint) const
Query if the given range is owned by this Scope.
void queryByName (const string &name, vector< Symbol * > &res) const
Look-up symbols by name.
Funcdata * queryFunction (const string &name) const
Look-up a function by name.
SymbolEntry * queryByAddr (const Address &addr, const Address &usepoint) const
Get Symbol with matching address.
SymbolEntry * queryContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest containing Symbol.
SymbolEntry * queryProperties (const Address &addr, int4 size, const Address &usepoint, uint4 &flags) const
Find a Symbol or properties at the given address.
Funcdata * queryFunction (const Address &addr) const
Look-up a function by address.
Funcdata * queryExternalRefFunction (const Address &addr) const
Look-up a function thru an external reference.
LabSymbol * queryCodeLabel (const Address &addr) const
Look-up a code label by address.
Scope * resolveScope (const string &name) const
Find a child Scope of this.
Scope * discoverScope (const Address &addr, int4 sz, const Address &usepoint)
Find the owning Scope of a given memory range.
void saveXmlRecursive (ostream &s, bool onlyGlobal) const
Save all contained scopes as an XML stream.
void overrideSizeLockType (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol that is sizelocked.
void resetSizeLockType (Symbol *sym)
Clear a Symbol's size-locked data-type.
bool isSubScope (const Scope *scp) const
Is this a sub-scope of the given Scope.
string getFullName (void) const
Get the full name of this Scope.
void getNameSegments (vector< string > &vec) const
Get the fullname of this in segments.
void getScopePath (vector< Scope * > &vec) const
Get the ordered list of parent scopes to this.
bool isNameUsed (const string &nm, const Scope *op2) const
Is the given name in use within given scope path.
const Scope * findDistinguishingScope (const Scope *op2) const
Find first ancestor of this not shared by given scope.
Symbol * addSymbol (const string &name, Datatype *ct)
Add a new Symbol without mapping it to an address.
SymbolEntry * addMapPoint (Symbol *sym, const Address &addr, const Address &usepoint)
Map a Symbol to a specific address.
Symbol * addMapSym (const Element *el)
Add a mapped Symbol from a <mapsym> XML tag.
FunctionSymbol * addFunction (const Address &addr, const string &nm)
Create a function Symbol at the given address in this Scope.
ExternRefSymbol * addExternalRef (const Address &addr, const Address &refaddr, const string &nm)
LabSymbol * addCodeLabel (const Address &addr, const string &nm)
Create a code label at the given address in this Scope.
Symbol * addDynamicSymbol (const string &nm, Datatype *ct, const Address &caddr, uint8 hash)
Create a dynamically mapped Symbol attached to a specific data-flow.
string buildDefaultName (Symbol *sym, int4 &base, Varnode *vn) const
Create a default name for the given Symbol.
bool isReadOnly (const Address &addr, int4 size, const Address &usepoint) const
Is the given memory range marked as read-only.
Private Member Functions
Symbol * dump2Cache (Document *doc) const
Parse a response into the cache.
Symbol * removeQuery (const Address &addr) const
Process a query that missed the cache.
void processHole (const Element *el) const
Process a response describing a hole.
Scope * createNewScope (const string &nm, Scope *par) const
Create a global namespace Scope.
Scope * reresolveScope (const vector< string > &path) const
Find the Scope that will contain a result Symbol.
virtual void addRange (AddrSpace *spc, uintb first, uintb last)
Add a memory range to the ownership of this Scope.
virtual void removeRange (AddrSpace *spc, uintb first, uintb last)
Remove a memory range from the ownership of this Scope.
virtual void addSymbolInternal (Symbol *sym)
Put a Symbol into the name map.
virtual SymbolEntry * addMapInternal (Symbol *sym, uint4 exfl, const Address &addr, int4 off, int4 sz, const RangeList &uselim)
Create a new SymbolEntry for a Symbol given a memory range.
virtual SymbolEntry * addDynamicMapInternal (Symbol *sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList &uselim)
Create a new SymbolEntry for a Symbol given a dynamic hash.
Private Attributes
ArchitectureGhidra * ghidra
Architecture and connection to the Ghidra client.
ScopeInternal * cache
An internal cache of previously fetched Symbol objects.
RangeList holes
List of (queried) memory ranges with no Symbol in them.
vector< int4 > spacerange
List of address spaces that are in the global range.
partmap< Address, uint4 > flagbaseDefault
Default boolean properties on memory.
bool cacheDirty
Is flagbaseDefault different from cache.
Additional Inherited Members
Protected Member Functions inherited from Scope
SymbolEntry * addMap (const SymbolEntry &entry)
Integrate a SymbolEntry into the range maps.
Static Protected Member Functions inherited from Scope
static const Scope * stackAddr (const Scope *scope1, const Scope *scope2, const Address &addr, const Address &usepoint, SymbolEntry **addrmatch)
Query for Symbols starting at a given address, which match a given usepoint.
static const Scope * stackContainer (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackClosestFit (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackFunction (const Scope *scope1, const Scope *scope2, const Address &addr, Funcdata **addrmatch)
static const Scope * stackExternalRef (const Scope *scope1, const Scope *scope2, const Address &addr, ExternRefSymbol **addrmatch)
static const Scope * stackCodeLabel (const Scope *scope1, const Scope *scope2, const Address &addr, LabSymbol **addrmatch)
Protected Attributes inherited from Scope
Architecture * glb
Architecture of this scope.
string name
Name of this scope.
Funcdata * fd
(If non-null) the function which this is the local Scope for
uint4 uniqueId
Unique id for the scope, for deduping scope names, assigning symbol ids.
Detailed Description
An implementation of the Scope interface by querying a Ghidra client for Symbol information.
This object is generally instantiated once for an executable and acts as the global scope for the decompiler. Queries for symbol information are forwarded to the Ghidra client and the response is cached. This object fields queries for all scopes above functions. Responses may be for Symbol objects that are not global but belong to sub-scopes, like namespace and function Scopes. This object will build any new Scope or Funcdata, object as necessary and stick the Symbol in, returning as if the new Scope had caught the query in the first place.
Constructor & Destructor Documentation
ScopeGhidra()
ScopeGhidra::ScopeGhidra (ArchitectureGhidra * g)
Constructor.
Parameters
g is the Architecture and connection to the Ghidra client
References cache, cacheDirty, and ghidra.
Member Function Documentation
addDynamicMapInternal()
virtual SymbolEntry* ScopeGhidra::addDynamicMapInternal (Symbol * sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList & uselim) inline private virtual
Create a new SymbolEntry for a Symbol given a dynamic hash.
The SymbolEntry is specified in terms of a hash and usepoint, which describe how to find the temporary Varnode holding the symbol value.
Parameters
sym is the given Symbol being mapped
exfl are any boolean Varnode properties
hash is the given dynamic hash
off is the byte offset of the new SymbolEntry (relative to the whole Symbol)
sz is the number of bytes occupied by the Varnode
uselim is the given usepoint
Returns
the newly created SymbolEntry
Implements Scope.
addMapInternal()
virtual SymbolEntry* ScopeGhidra::addMapInternal (Symbol * sym, uint4 exfl, const Address & addr, int4 off, int4 sz, const RangeList & uselim) inline private virtual
Create a new SymbolEntry for a Symbol given a memory range.
The SymbolEntry is specified in terms of a memory range and usepoint
Parameters
sym is the given Symbol being mapped
exfl are any boolean Varnode properties specific to the memory range
addr is the starting address of the given memory range
off is the byte offset of the new SymbolEntry (relative to the whole Symbol)
sz is the number of bytes in the range
uselim is the given usepoint (which may be invalid)
Returns
the newly created SymbolEntry
Implements Scope.
addRange()
void ScopeGhidra::addRange (AddrSpace * spc, uintb first, uintb last) private virtual
Add a memory range to the ownership of this Scope.
Parameters
spc is the address space of the range
first is the offset of the first byte in the range
last is the offset of the last byte in the range
Reimplemented from Scope.
References Scope::addRange(), AddrSpace::getIndex(), and spacerange.
addSymbol()
SymbolEntry * ScopeGhidra::addSymbol (const string & name, Datatype * ct, const Address & addr, const Address & usepoint) virtual
Add a new Symbol to this Scope, given a name, data-type, and a single mapping.
The Symbol object will be created with the given name and data-type. A single mapping (SymbolEntry) will be created for the Symbol based on a given storage address for the symbol and an address for code that accesses the Symbol at that storage location.
Parameters
name is the new name of the Symbol
ct is the data-type of the new Symbol
addr is the starting address of the Symbol storage
usepoint is the point accessing that storage (may be invalid)
Returns
the SymbolEntry matching the new mapping
Reimplemented from Scope.
References Scope::addSymbol(), cache, and Scope::name.
addSymbolInternal()
virtual void ScopeGhidra::addSymbolInternal (Symbol * sym) inline private virtual
Put a Symbol into the name map.
Parameters
sym is the preconstructed Symbol
Implements Scope.
buildUndefinedName()
virtual string ScopeGhidra::buildUndefinedName (void) const inline virtual
Build a formal undefined name, used internally when a Symbol is not given a name.
Returns
a special internal name that won't collide with other names in this Scope
Implements Scope.
References ScopeInternal::buildUndefinedName(), and cache.
buildVariableName()
virtual string ScopeGhidra::buildVariableName (const Address & addr, const Address & pc, Datatype * ct, int4 & index, uint4 flags) const inline virtual
Given an address and data-type, build a suitable generic symbol name.
Parameters
addr is the given address
pc is the address at which the name is getting used
ct is a data-type used to inform the name
index is a reference to an index used to make the name unique, which will be updated
flags are boolean properties of the variable we need the name for
Returns
the new variable name
Implements Scope.
References ScopeInternal::buildVariableName(), and cache.
createNewScope()
Scope * ScopeGhidra::createNewScope (const string & nm, Scope * par) const private
Create a global namespace Scope.
Ghidra may report that a Symbol is in a namespace. This method creates a dedicated Scope object to hold such a Symbol. The immediate parent for the new Scope must already exist.
Parameters
nm is the name of the new namespace
par is the parent Scope
Returns
the new namespace Scope
References Database::attachScope(), ghidra, and Architecture::symboltab.
Referenced by reresolveScope().
dump2Cache()
Symbol * ScopeGhidra::dump2Cache (Document * doc) const private
Parse a response into the cache.
Build the global object described by the XML document and put it in the cache. The XML can either be a <hole> tag, describing the absence of symbols at the queried address, or one of the symbol tags
Parameters
doc is the XML document
Returns
the newly constructed Symbol or NULL if there was a hole
References Scope::addMapSym(), cache, cacheDirty, LowlevelError::explain, Element::getAttributeValue(), Symbol::getFirstWholeMap(), FunctionSymbol::getFunction(), ghidra, Scope::glb, holes, RangeList::insertRange(), processHole(), Scope::queryByName(), Varnode::readonly, reresolveScope(), Address::restoreXml(), Database::setPropertyRange(), Architecture::symboltab, and Varnode::volatil.
Referenced by removeQuery(), and resolveExternalRefFunction().
findAddr()
SymbolEntry * ScopeGhidra::findAddr (const Address & addr, const Address & usepoint) const virtual
Find a Symbol at a given address and usepoint.
Parameters
addr is the given address
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implements Scope.
References cache, ScopeInternal::findAddr(), ScopeInternal::findContainer(), Symbol::getMapEntry(), and removeQuery().
findByName()
virtual void ScopeGhidra::findByName (const string & name, vector< Symbol * > & res) const inline virtual
Find a Symbol by name within this Scope.
If there are multiple Symbols with the same name, all are passed back.
Parameters
name is the name to search for
res will contain any matching Symbols
Implements Scope.
findClosestFit()
virtual SymbolEntry* ScopeGhidra::findClosestFit (const Address & addr, int4 size, const Address & usepoint) const inline virtual
Find Symbol which is the closest fit to the given memory range.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implements Scope.
findCodeLabel()
LabSymbol * ScopeGhidra::findCodeLabel (const Address & addr) const virtual
Find a label Symbol at the given address.
Parameters
addr is the given address
Returns
the matching LabSymbol or NULL
Implements Scope.
References Scope::addCodeLabel(), cache, ScopeInternal::findAddr(), ScopeInternal::findCodeLabel(), ArchitectureGhidra::getCodeLabel(), and ghidra.
findContainer()
SymbolEntry * ScopeGhidra::findContainer (const Address & addr, int4 size, const Address & usepoint) const virtual
Find the smallest Symbol containing the given memory range.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implements Scope.
References cache, ScopeInternal::findClosestFit(), Symbol::getMapEntry(), Address::getOffset(), and removeQuery().
findExternalRef()
ExternRefSymbol * ScopeGhidra::findExternalRef (const Address & addr) const virtual
Find an external reference at the given address.
Parameters
addr is the given address
Returns
the matching ExternRefSymbol or NULL
Implements Scope.
References cache, ScopeInternal::findContainer(), ScopeInternal::findExternalRef(), and removeQuery().
findFunction()
Funcdata * ScopeGhidra::findFunction (const Address & addr) const virtual
Find the function starting at the given address.
Parameters
addr is the given starting address
Returns
the matching Funcdata object or NULL
Implements Scope.
References cache, Scope::fd, ScopeInternal::findContainer(), ScopeInternal::findFunction(), FunctionSymbol::getFunction(), and removeQuery().
findOverlap()
virtual SymbolEntry* ScopeGhidra::findOverlap (const Address & addr, int4 size) const inline virtual
Find first Symbol overlapping the given memory range.
Parameters
addr is the starting address of the given range
size is the number of bytes in the range
Returns
an overlapping SymbolEntry or NULL if none exists
Implements Scope.
getCategorySize()
virtual int4 ScopeGhidra::getCategorySize (int4 cat) const inline virtual
Get the number of Symbols in the given category.
Parameters
cat is the Symbol category
Returns
the number in that category
Implements Scope.
getCategorySymbol()
virtual Symbol* ScopeGhidra::getCategorySymbol (int4 cat, int4 ind) const inline virtual
Retrieve a Symbol by index within a specific category.
Parameters
cat is the Symbol category
ind is the index (within the category) of the Symbol
Returns
the indicated Symbol or NULL if no Symbol with that index exists
Implements Scope.
isNameUsed()
virtual bool ScopeGhidra::isNameUsed (const string & name) const inline virtual
Check if the given name is used within this scope.
Only this scope is checked. If one or more symbols exist with the given name, true is returned.
Parameters
name is the given name to check for
Returns
true if the name is used within this scope
Implements Scope.
lockDefaultProperties()
void ScopeGhidra::lockDefaultProperties (void) inline
Lock in the default state of the boolean property map.
When this Scope gets created, parsing of .pspec and .cspec files may lay down property information about memory before any the load-image is consulted. This method locks creates a copy of this state of memory, so the decompiler can reset to it before decompiling a new function.
References cacheDirty, flagbaseDefault, ghidra, and Architecture::symboltab.
Referenced by ArchitectureGhidra::postSpecFile().
makeNameUnique()
virtual string ScopeGhidra::makeNameUnique (const string & nm) const inline virtual
Produce a version of the given symbol name that won't collide with other names in this Scope.
Parameters
nm is the given name
Returns
return a unique version of the name
Implements Scope.
processHole()
void ScopeGhidra::processHole (const Element * el) const private
Process a response describing a hole.
The Ghidra client can respond to a query negatively by sending a <hole> tag, which describes the (largest) range of addresses containing the query address that do not have any Symbol mapped to them. This object stores this information in the holes map, which it consults to avoid sending queries for the same unmapped address repeatedly. The tag may also contain boolean property information about the memory range, which also gets stored.
Parameters
el is the <hole> element
References cacheDirty, Element::getAttributeValue(), ghidra, holes, RangeList::insertRange(), Varnode::readonly, Range::restoreXml(), Database::setPropertyRange(), Architecture::symboltab, Varnode::volatil, and xml_readbool().
Referenced by dump2Cache().
removeQuery()
Symbol * ScopeGhidra::removeQuery (const Address & addr) const private
Process a query that missed the cache.
Determine if the given address should be sent to the Ghidra client at all, by checking the hole map and other factors. If it passes, send the query to the client, process the result, and update the cache. If a Symbol is ultimately recovered, return it.
Parameters
addr is the address to potentially query
Returns
the matching Symbol or NULL if there is hole
References dump2Cache(), AddrSpace::getIndex(), ArchitectureGhidra::getMappedSymbolsXML(), Address::getSpace(), ghidra, holes, RangeList::inRange(), and spacerange.
Referenced by findAddr(), findContainer(), findExternalRef(), and findFunction().
removeRange()
virtual void ScopeGhidra::removeRange (AddrSpace * spc, uintb first, uintb last) inline private virtual
Remove a memory range from the ownership of this Scope.
Parameters
spc is the address space of the range
first is the offset of the first byte in the range
last is the offset of the last byte in the range
Reimplemented from Scope.
reresolveScope()
Scope * ScopeGhidra::reresolveScope (const vector< string > & path) const private
Find the Scope that will contain a result Symbol.
The Ghidra client reports a namespace path associated with Symbol. Determine if this Scope already exists in the cache and built it if it isn't. This may mean creating a new namespace Scope.
Parameters
path is absolute path to the desired Scope
Returns
the Scope matching the path.
References cache, createNewScope(), Scope::glb, Scope::resolveScope(), and Architecture::symboltab.
Referenced by dump2Cache().
resolveExternalRefFunction()
Funcdata * ScopeGhidra::resolveExternalRefFunction (ExternRefSymbol * sym) const virtual
Convert an external reference to the referenced function.
Parameters
sym is the Symbol marking the external reference
Returns
the underlying Funcdata object or NULL if none exists
Implements Scope.
References cache, dump2Cache(), Scope::fd, ScopeInternal::findFunction(), ArchitectureGhidra::getExternalRefXML(), Symbol::getFirstWholeMap(), FunctionSymbol::getFunction(), ghidra, Database::mapScope(), Scope::stackFunction(), and Architecture::symboltab.
restrictScope()
virtual void ScopeGhidra::restrictScope (Funcdata * f) inline virtual
Convert this to a local Scope.
Attach this to the given function, which makes this the local scope for the function
Parameters
f is the given function to attach to
Reimplemented from Scope.
retypeSymbol()
virtual void ScopeGhidra::retypeSymbol (Symbol * sym, Datatype * ct) inline virtual
Change the data-type of a Symbol within this Scope.
If the size of the Symbol changes, any mapping (SymbolEntry) is adjusted
Parameters
sym is the given Symbol
ct is the new data-type
Implements Scope.
setCategory()
virtual void ScopeGhidra::setCategory (Symbol * sym, int4 cat, int4 ind) inline virtual
Set the category and index for the given Symbol.
Parameters
sym is the given Symbol
cat is the category to set for the Symbol
ind is the index position to set (within the category)
Implements Scope.
The documentation for this class was generated from the following files:
database_ghidra.hh
database_ghidra.cc