decompiler: LanedRegister Class Reference
LanedRegister Class Reference
Describes a (register) storage location and the ways it might be split into lanes.
#include <transform.hh>
Classes
class LanedIterator
Class for iterating over possible lane sizes.
Public Types
typedef LanedIterator const_iterator
Iterator over possible lane sizes for this register.
Public Member Functions
bool restoreXml (const Element *el, const AddrSpaceManager *manage)
Restore object from XML stream.
Private Attributes
int4 wholeSize
Size of the whole register.
uint4 sizeBitMask
A 1-bit for every permissible lane size.
Friends
class LanedIterator
Detailed Description
Describes a (register) storage location and the ways it might be split into lanes.
Member Function Documentation
restoreXml()
bool LanedRegister::restoreXml (const Element * el, const AddrSpaceManager * manage)
Restore object from XML stream.
Read XML of the form <register name=".." vector_lane_sizes=".."/>
Parameters
el is the particular register tag
manage is used to map register names to storage info
Returns
true if the XML description provides lane sizes
References Element::getAttributeValue(), VarnodeData::restoreXml(), VarnodeData::size, sizeBitMask, VarnodeData::space, and wholeSize.
Referenced by Architecture::parseLaneSizes().
The documentation for this class was generated from the following files:
transform.hh
transform.cc