decompiler: RulePullsubMulti Class Reference
RulePullsubMulti Class Reference
Pull SUBPIECE back through MULTIEQUAL.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Public Member Functions
static void minMaxUse (Varnode *vn, int4 &maxByte, int4 &minByte)
Compute minimum and maximum bytes being used.
static void replaceDescendants (Varnode *origVn, Varnode *newVn, int4 maxByte, int4 minByte, Funcdata &data)
static bool acceptableSize (int4 size)
Return true if given size is a suitable truncated size.
static Varnode * buildSubpiece (Varnode *basevn, uint4 outsize, uint4 shift, Funcdata &data)
Build a SUBPIECE of given base Varnode.
static Varnode * findSubpiece (Varnode *basevn, uint4 outsize, uint4 shift)
Find a predefined SUBPIECE of a base Varnode.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Pull SUBPIECE back through MULTIEQUAL.
Member Function Documentation
acceptableSize()
bool RulePullsubMulti::acceptableSize (int4 size) static
Return true if given size is a suitable truncated size.
Parameters
size is the given size
Returns
true if it is acceptable
Referenced by applyOp(), and RulePullsubIndirect::applyOp().
applyOp()
int4 RulePullsubMulti::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References acceptableSize(), buildSubpiece(), calc_mask(), CPUI_INT_SEXT, CPUI_INT_ZEXT, CPUI_MULTIEQUAL, findSubpiece(), minMaxUse(), Funcdata::newOp(), Funcdata::newVarnodeOut(), Funcdata::opInsertBegin(), Funcdata::opSetAllInput(), Funcdata::opSetOpcode(), Address::renormalize(), and replaceDescendants().
buildSubpiece()
Varnode * RulePullsubMulti::buildSubpiece (Varnode * basevn, uint4 outsize, uint4 shift, Funcdata & data) static
Build a SUBPIECE of given base Varnode.
The PcodeOp is constructed and inserted near the definition of the base Varnode.
Parameters
basevn is the given base Varnode
outsize is the required truncated size in bytes
shift is the number of least significant bytes to truncate
data is the function being analyzed
Returns
the output Varnode of the new SUBPIECE
References CPUI_SUBPIECE, VarnodeData::getAddr(), AddrSpace::isBigEndian(), Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::newVarnodeOut(), Funcdata::opInsertAfter(), Funcdata::opInsertBegin(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), Address::renormalize(), VarnodeData::size, and VarnodeData::space.
Referenced by applyOp(), and RulePullsubIndirect::applyOp().
clone()
virtual Rule* RulePullsubMulti::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
findSubpiece()
Varnode * RulePullsubMulti::findSubpiece (Varnode * basevn, uint4 outsize, uint4 shift) static
Find a predefined SUBPIECE of a base Varnode.
Given a Varnode and desired dimensions (size and shift), search for a preexisting truncation defined in the same block as the original Varnode or return NULL
Parameters
basevn is the base Varnode
outsize is the desired truncation size
shift if the desired truncation shift
Returns
the truncated Varnode or NULL
References CPUI_SUBPIECE.
Referenced by applyOp(), and RulePullsubIndirect::applyOp().
getOpList()
void RulePullsubMulti::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_SUBPIECE.
minMaxUse()
void RulePullsubMulti::minMaxUse (Varnode * vn, int4 & maxByte, int4 & minByte) static
Compute minimum and maximum bytes being used.
For bytes in given Varnode pass back the largest and smallest index (lsb=0) consumed by an immediate descendant.
Parameters
vn is the given Varnode
maxByte will hold the index of the maximum byte
minByte will hold the index of the minimum byte
References CPUI_SUBPIECE.
Referenced by applyOp(), and RulePullsubIndirect::applyOp().
replaceDescendants()
void RulePullsubMulti::replaceDescendants (Varnode * origVn, Varnode * newVn, int4 maxByte, int4 minByte, Funcdata & data) static
Replace given Varnode with (smaller) newVn in all descendants
If minMaxUse() indicates not all bytes are used, this should always succeed
Parameters
origVn is the given Varnode
newVn is the new Varnode to replace with
maxByte is the maximum byte immediately used in origVn
minByte is the minimum byte immediately used in origVn
data is the function being analyzed
References CPUI_COPY, CPUI_SUBPIECE, Funcdata::newConstant(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), and Funcdata::opSetOpcode().
Referenced by applyOp(), and RulePullsubIndirect::applyOp().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc