decompiler: Datatype Class Reference
Datatype Class Reference abstract
The base datatype class for the decompiler.
#include <type.hh>
Public Member Functions
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
Datatype (int4 s, type_metatype m, const string &n)
Construct the base data-type providing size, meta-type, and name.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual int4 compare (const Datatype &op, int4 level) const
Compare for functional equivalence.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual Datatype * clone (void) const =0
Clone the data-type.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlBasic (ostream &s) const
Save basic data-type properties.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
Protected Types
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32
}
Boolean properties of datatypes.
Protected Member Functions
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
virtual void restoreXml (const Element *el, TypeFactory &typegrp)
Restore data-type from XML.
Static Protected Member Functions
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
Protected Attributes
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Friends
class TypeFactory
struct DatatypeCompare
Detailed Description
The base datatype class for the decompiler.
Used for symbols, function prototypes, type propagation etc.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Boolean properties of datatypes.
Enumerator
coretype
This is a basic type which will never be redefined.
chartype
ASCII character data.
enumtype
An enumeration type (as well as an integer)
poweroftwo
An enumeration type where all values are of 2^^n form.
utf16
16-bit wide chars in unicode UTF16
utf32
32-bit wide chars in unicode UTF32
Member Function Documentation
compare()
int4 Datatype::compare (const Datatype & op, int4 level) const virtual
Compare for functional equivalence.
Compare this with another data-type. 0 (equality) means the data-types are functionally equivalent (even if names differ) Smaller types come earlier. More specific types come earlier.
Parameters
op is the data-type to compare with this
level is maximum level to descend when recursively comparing
Returns
negative, 0, positive depending on ordering of types
Reimplemented in TypeSpacebase, TypeCode, TypeStruct, TypeEnum, TypeArray, and TypePointer.
References compareDependency().
Referenced by TypePointer::compare(), DatatypeNameCompare::operator()(), and typeOrderBool().
compareDependency()
int4 Datatype::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Ordering of data-types for the main TypeFactory container. Comparison only goes down one-level in the component structure, before just comparing pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented in TypeSpacebase, TypeCode, TypeStruct, TypeEnum, TypeArray, and TypePointer.
References chartype, coretype, flags, metatype, and size.
Referenced by compare(), TypeFactory::findAdd(), DatatypeCompare::operator()(), and TypeFactory::restoreXmlTypeNoRef().
getSubType()
Datatype * Datatype::getSubType (uintb off, uintb * newoff) const virtual
Recover component data-type one-level down.
Given an offset into this data-type, return the component data-type at that offset. Also, pass back a "renormalized" offset suitable for recursize getSubType() calls: i.e. if the original offset hits the exact start of the sub-type, 0 is passed back. If there is no valid component data-type at the offset, return NULL and pass back the original offset
Parameters
off is the offset into this data-type
newoff is a pointer to the passed-back offset
Returns
a pointer to the component data-type or NULL
Reimplemented in TypeSpacebase, TypeStruct, and TypeArray.
Referenced by RuleStructOffset0::applyOp(), RulePtrsubUndo::applyOp(), TypeFactory::downChain(), SymbolEntry::getSizedType(), ActionInferTypes::propagateRef(), RangeHint::reconcile(), Funcdata::syncVarnodesWithSymbols(), and RulePtrArith::transformPtr().
hashName()
uint8 Datatype::hashName (const string & nm) static protected
Produce a data-type id by hashing the type name.
If a type id is explicitly provided for a data-type, this routine is used to produce an id based on a hash of the name. IDs produced this way will have their sign-bit set to distinguish it from other IDs.
Parameters
nm is the type name to be hashed
Referenced by TypeFactory::getBase(), TypeFactory::getTypeChar(), TypeFactory::getTypeCode(), TypeFactory::getTypeEnum(), TypeFactory::getTypeStruct(), TypeFactory::getTypeUnicode(), TypeFactory::getTypeVoid(), restoreXmlBasic(), TypeFactory::restoreXmlType(), TypeFactory::restoreXmlTypeNoRef(), and TypeFactory::setName().
printRaw()
void Datatype::printRaw (ostream & s) const virtual
Print a description of the type to stream.
Print a raw description of the type to stream. Intended for debugging. Not intended to produce parsable C.
Parameters
s is the output stream
Reimplemented in TypeCode, TypeArray, and TypePointer.
References name, and size.
Referenced by MapState::addRange(), TypeFactory::findAdd(), HighVariable::printInfo(), Varnode::printInfo(), and TypePointer::printRaw().
restoreXml()
void Datatype::restoreXml (const Element * el, TypeFactory & typegrp) protected virtual
Restore data-type from XML.
Restore a Datatype object from an XML element
Parameters
el is the XML element
typegrp is the underlying TypeFactory that will hold the new object
Reimplemented in TypeSpacebase, TypeCode, TypeStruct, TypeEnum, TypeArray, TypePointer, and TypeUnicode.
References restoreXmlBasic().
Referenced by TypeFactory::restoreXmlTypeNoRef().
restoreXmlBasic()
void Datatype::restoreXmlBasic (const Element * el) protected
Recover basic data-type properties.
Restore the basic properties (name,size,id) of a data-type from an XML element Properties are read from the attributes of the element
Parameters
el is the XML element
References coretype, flags, Element::getAttributeValue(), hashName(), id, metatype, name, size, string2metatype(), and xml_readbool().
Referenced by restoreXml(), TypeUnicode::restoreXml(), and TypeFactory::restoreXmlTypeWithCodeFlags().
saveXml()
void Datatype::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented in TypeSpacebase, TypeCode, TypeStruct, TypeEnum, TypeArray, TypePointer, TypeVoid, TypeUnicode, and TypeChar.
References saveXmlBasic().
Referenced by CPoolRecord::saveXml(), ProtoStoreInternal::saveXml(), FuncProto::saveXml(), TypeFactory::saveXmlCoreTypes(), and saveXmlRef().
saveXmlBasic()
void Datatype::saveXmlBasic (ostream & s) const
Save basic data-type properties.
Write out basic data-type properties (name,size,id) as XML attributes. This routine presumes the initial tag is already written to the stream.
Parameters
s is the stream to write to
References a_v(), a_v_b(), a_v_i(), coretype, flags, metatype, metatype2string(), name, and size.
Referenced by saveXml(), TypeChar::saveXml(), TypeUnicode::saveXml(), TypePointer::saveXml(), and TypeSpacebase::saveXml().
saveXmlRef()
void Datatype::saveXmlRef (ostream & s) const
Write an XML reference of this to stream.
Write a simple reference to this data-type as an XML <typeref> tag, which only encodes the name and id.
Parameters
s is the stream to write to
References a_v(), metatype, name, saveXml(), and TYPE_VOID.
Referenced by Symbol::saveXmlBody().
typeOrderBool()
int4 Datatype::typeOrderBool (const Datatype & op) const inline
Order this with -op-, treating bool data-type as special.
Order data-types, with special handling of the bool data-type. Data-types are compared using the normal ordering, but bool is ordered after all other data-types. A return value of 0 indicates the data-types are the same, -1 indicates that this is prefered (ordered earlier), and 1 indicates this is ordered later.
Parameters
op is the other data-type to compare with this
Returns
-1, 0, or 1
References compare(), metatype, and TYPE_BOOL.
The documentation for this class was generated from the following files:
type.hh
type.cc