decompiler: CastStrategy Class Reference
CastStrategy Class Reference abstract
A strategy for applying type casts.
#include <cast.hh>
Public Types
enum IntPromotionCode {
NO_PROMOTION = -1, UNKNOWN_PROMOTION = 0, UNSIGNED_EXTENSION = 1, SIGNED_EXTENSION = 2,
EITHER_EXTENSION = 3
}
Types of integer promotion.
Public Member Functions
void setTypeFactory (TypeFactory *t)
Establish the data-type factory.
virtual int4 localExtensionType (const Varnode *vn) const =0
Decide on integer promotion by examining just local properties of the given Varnode.
virtual int4 intPromotionType (const Varnode *vn) const =0
Calculate the integer promotion code of a given Varnode.
virtual bool checkIntPromotionForCompare (const PcodeOp *op, int4 slot) const =0
Check if integer promotion forces a cast for the given comparison op and slot.
virtual bool checkIntPromotionForExtension (const PcodeOp *op) const =0
Check if integer promotion forces a cast for the input to the given extension.
virtual bool isExtensionCastImplied (const PcodeOp *op, const PcodeOp *readOp) const =0
Is the given ZEXT/SEXT cast implied by the expression its in?
virtual Datatype * castStandard (Datatype *reqtype, Datatype *curtype, bool care_uint_int, bool care_ptr_uint) const =0
Does there need to be a visible cast between the given data-types.
virtual Datatype * arithmeticOutputStandard (const PcodeOp *op)=0
What is the output data-type produced by the given integer arithmetic operation.
virtual bool isSubpieceCast (Datatype *outtype, Datatype *intype, uint4 offset) const =0
Is truncating an input data-type, producing an output data-type, considered a cast.
virtual bool isSubpieceCastEndian (Datatype *outtype, Datatype *intype, uint4 offset, bool isbigend) const =0
Is the given data-type truncation considered a cast, given endianess concerns.
virtual bool isSextCast (Datatype *outtype, Datatype *intype) const =0
Is sign-extending an input data-type, producing an output data-type, considered a cast.
virtual bool isZextCast (Datatype *outtype, Datatype *intype) const =0
Is zero-extending an input data-type, producing an output data-type, considered a cast.
Protected Attributes
TypeFactory * tlst
Type factory associated with the Architecture.
int4 promoteSize
Size of int data-type, (size that integers get promoted to)
Detailed Description
A strategy for applying type casts.
A cast operation in C or other languages masks a variety of possible low-level conversions, such as extensions, truncations, integer to floating-point, etc. On top of this, languages allow many of these types of operations to be implied in the source code, with no explicit token representing the conversion. Conversions happen automatically for things like integer promotion, between different sizes (of integers), and between signed and unsigned data-type variants.
This class is the API for making four kinds of decisions:
Do we need a cast operator for a given assignment
Does the given conversion operation need to be represented as a cast
Does the given extension or comparison match with the expected level of integer promotion
What data-type is produced by a particular integer arithmetic operation
Member Enumeration Documentation
IntPromotionCode
enum CastStrategy::IntPromotionCode
Types of integer promotion.
For many languages, small integers are automatically promoted to a standard size. The decompiler describes how an expression is or will be affected by integer promotion, using these codes
Enumerator
NO_PROMOTION
There is no integer promotion.
UNKNOWN_PROMOTION
The type of integer promotion cannot be determined.
UNSIGNED_EXTENSION
The value is promoted using unsigned extension.
SIGNED_EXTENSION
The value is promoted using signed extension.
EITHER_EXTENSION
The value is promoted using either signed or unsigned extension.
Member Function Documentation
arithmeticOutputStandard()
virtual Datatype* CastStrategy::arithmeticOutputStandard (const PcodeOp * op) pure virtual
What is the output data-type produced by the given integer arithmetic operation.
Parameters
op is the given operation
Returns
the output data-type
Implemented in CastStrategyC.
Referenced by TypeOpIntAdd::getOutputToken(), TypeOpIntSub::getOutputToken(), TypeOpInt2Comp::getOutputToken(), TypeOpIntNegate::getOutputToken(), TypeOpIntXor::getOutputToken(), TypeOpIntAnd::getOutputToken(), TypeOpIntOr::getOutputToken(), and TypeOpIntMult::getOutputToken().
castStandard()
virtual Datatype* CastStrategy::castStandard (Datatype * reqtype, Datatype * curtype, bool care_uint_int, bool care_ptr_uint) const pure virtual
Does there need to be a visible cast between the given data-types.
The cast is from a current data-type to an expected data-type. NULL is returned if no cast is required, otherwise the data-type to cast to (usually the expected data-type) is returned.
Parameters
reqtype is the expected data-type
curtype is the current data-type
care_uint_int is true if we care about a change in signedness
care_ptr_uint is true if we care about conversions between pointers and unsigned values
Returns
NULL to indicate no cast, or the data-type to cast to
Implemented in CastStrategyJava, and CastStrategyC.
Referenced by ActionSetCasts::castOutput(), TypeOp::getInputCast(), TypeOpCopy::getInputCast(), TypeOpLoad::getInputCast(), TypeOpStore::getInputCast(), TypeOpEqual::getInputCast(), TypeOpNotEqual::getInputCast(), TypeOpIntSless::getInputCast(), TypeOpIntSlessEqual::getInputCast(), TypeOpIntLess::getInputCast(), TypeOpIntLessEqual::getInputCast(), TypeOpIntZext::getInputCast(), TypeOpIntSext::getInputCast(), TypeOpIntRight::getInputCast(), TypeOpIntSright::getInputCast(), TypeOpIntDiv::getInputCast(), TypeOpIntSdiv::getInputCast(), TypeOpIntRem::getInputCast(), TypeOpIntSrem::getInputCast(), TypeOpPtradd::getInputCast(), and TypeOpPtrsub::getInputCast().
checkIntPromotionForCompare()
virtual bool CastStrategy::checkIntPromotionForCompare (const PcodeOp * op, int4 slot) const pure virtual
Check if integer promotion forces a cast for the given comparison op and slot.
Compute to what level the given slot has seen integer promotion and if a cast is required before the comparison operator makes sense.
Parameters
op is the given comparison operator
slot is the input slot being tested
Returns
true if a cast is required before comparing
Implemented in CastStrategyC.
Referenced by TypeOpEqual::getInputCast(), TypeOpNotEqual::getInputCast(), TypeOpIntSless::getInputCast(), TypeOpIntSlessEqual::getInputCast(), TypeOpIntLess::getInputCast(), and TypeOpIntLessEqual::getInputCast().
checkIntPromotionForExtension()
virtual bool CastStrategy::checkIntPromotionForExtension (const PcodeOp * op) const pure virtual
Check if integer promotion forces a cast for the input to the given extension.
Compute to what level the given slot has seen integer promotion and if a cast is required before the extension operator makes sense.
Parameters
op is the given extension operator INT_ZEXT or INT_SEXT
Returns
true if a cast is required before extending
Implemented in CastStrategyC.
Referenced by TypeOpIntZext::getInputCast(), and TypeOpIntSext::getInputCast().
intPromotionType()
virtual int4 CastStrategy::intPromotionType (const Varnode * vn) const pure virtual
Calculate the integer promotion code of a given Varnode.
Recursively examine the expression defining the Varnode as necessary
Parameters
vn is the given Varnode
Returns
the IntPromotionCode
Implemented in CastStrategyC.
Referenced by TypeOpIntRight::getInputCast(), TypeOpIntSright::getInputCast(), TypeOpIntDiv::getInputCast(), TypeOpIntSdiv::getInputCast(), TypeOpIntRem::getInputCast(), and TypeOpIntSrem::getInputCast().
isExtensionCastImplied()
virtual bool CastStrategy::isExtensionCastImplied (const PcodeOp * op, const PcodeOp * readOp) const pure virtual
Is the given ZEXT/SEXT cast implied by the expression its in?
We've already determined that the given ZEXT or SEXT op can be viewed as a natural cast operation. Determine if the cast is implied by the expression its and doesn't need to be printed.
Parameters
op is the given ZEXT or SEXT PcodeOp
readOp is the PcodeOp consuming the output of the extensions (or null)
Returns
true if the op as a cast does not need to be printed
Implemented in CastStrategyC.
Referenced by PrintC::opIntSext(), and PrintC::opIntZext().
isSextCast()
virtual bool CastStrategy::isSextCast (Datatype * outtype, Datatype * intype) const pure virtual
Is sign-extending an input data-type, producing an output data-type, considered a cast.
Data-types must be provided from the input and output of an INT_SEXT operation.
Parameters
outtype is the output data-type
intype is the input data-type
Returns
true if the INT_SEXT should be represented as a cast
Implemented in CastStrategyC.
Referenced by PrintC::opIntSext().
isSubpieceCast()
virtual bool CastStrategy::isSubpieceCast (Datatype * outtype, Datatype * intype, uint4 offset) const pure virtual
Is truncating an input data-type, producing an output data-type, considered a cast.
Data-types must be provided from the input and output of a SUBPIECE operation.
Parameters
outtype is the output data-type
intype is the input data-type
offset is number of bytes truncated by the SUBPIECE
Returns
true if the SUBPIECE should be represented as a cast
Implemented in CastStrategyC.
Referenced by PrintC::opSubpiece().
isSubpieceCastEndian()
virtual bool CastStrategy::isSubpieceCastEndian (Datatype * outtype, Datatype * intype, uint4 offset, bool isbigend) const pure virtual
Is the given data-type truncation considered a cast, given endianess concerns.
This is equivalent to isSubpieceCast() but where the truncation is accomplished by pulling bytes directly out of memory. We assume the input data-type is layed down in memory, and we pull the output value starting at a given byte offset.
Parameters
outtype is the output data-type
intype is the input data-type
offset is the given byte offset (into the input memory)
isbigend is true if the address space holding the memory is big endian.
Returns
true if the truncation should be represented as a cast
Implemented in CastStrategyC.
Referenced by PrintC::pushPartialSymbol().
isZextCast()
virtual bool CastStrategy::isZextCast (Datatype * outtype, Datatype * intype) const pure virtual
Is zero-extending an input data-type, producing an output data-type, considered a cast.
Data-types must be provided from the input and output of an INT_ZEXT operation.
Parameters
outtype is the output data-type
intype is the input data-type
Returns
true if the INT_ZEXT should be represented as a cast
Implemented in CastStrategyJava, and CastStrategyC.
Referenced by PrintC::opIntZext().
localExtensionType()
virtual int4 CastStrategy::localExtensionType (const Varnode * vn) const pure virtual
Decide on integer promotion by examining just local properties of the given Varnode.
Parameters
vn is the given Varnode
Returns
an IntPromotionCode (excluding NO_PROMOTION)
Implemented in CastStrategyC.
setTypeFactory()
void CastStrategy::setTypeFactory (TypeFactory * t)
Establish the data-type factory.
Sets the TypeFactory used to produce data-types for the arithmeticOutputStandard() method
Parameters
t is the TypeFactory
References promoteSize, and tlst.
The documentation for this class was generated from the following files:
cast.hh
cast.cc