decompiler: ActionPool Class Reference
ActionPool Class Reference
A pool of Rules that apply simultaneously.
#include <action.hh>
Public Member Functions
virtual ~ActionPool (void)
Destructor.
void addRule (Rule *rl)
Add a Rule to the pool.
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
Private Member Functions
int4 processOp (PcodeOp *op, Funcdata &data)
Apply the next possible Rule to a PcodeOp.
Private Attributes
vector< Rule * > allrules
The set of Rules in this ActionPool.
vector< Rule * > perop [CPUI_MAX]
Rules associated with each OpCode.
PcodeOpTree::const_iterator op_state
Current PcodeOp up for rule application.
int4 rule_index
Iterator over Rules for one OpCode.
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
A pool of Rules that apply simultaneously.
This class groups together a set of Rules as a formal Action. Rules are given an opportunity to apply to every PcodeOp in a function. Usually rule_repeatapply is enabled for this action, which causes all Rules to apply repeatedly until no Rule can make an additional change.
Member Function Documentation
addRule()
void ActionPool::addRule (Rule * rl)
Add a Rule to the pool.
This method should only be invoked during construction of this ActionPool A single Rule is added to the pool. The Rule's OpCode is inspected by this method.
Parameters
rl is the Rule to add
References allrules, Rule::getOpList(), and perop.
Referenced by clone(), and universal_action().
apply()
int4 ActionPool::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implements Action.
References Funcdata::beginOpAll(), Funcdata::endOpAll(), op_state, processOp(), rule_index, Action::status, and Action::status_mid.
clone()
Action * ActionPool::clone (const ActionGroupList & grouplist) const virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implements Action.
References addRule(), allrules, Rule::clone(), and Action::flags.
getSubRule()
Rule * ActionPool::getSubRule (const string & specify) virtual
Retrieve a specific sub-rule by name.
Find a Rule, as a component of this Action, with the given name.
Parameters
specify is the name of the rule
Returns
the matching sub-rule
Reimplemented from Action.
References allrules, and Action::name.
print()
int4 ActionPool::print (ostream & s, int4 num, int4 depth) const virtual
Print a description of this Action to stream.
The description is suitable for a console mode listing of actions
Parameters
s is the output stream
num is a starting index to associate with the action (and its sub-actions)
depth is amount of indent necessary before printing
Returns
the next available index
Reimplemented from Action.
References allrules, Action::break_action, and Action::print().
printState()
void ActionPool::printState (ostream & s) const virtual
Print status to stream.
This will the Action name and the next step to execute
Parameters
s is the output stream
Reimplemented from Action.
References Action::printState(), Action::status, and Action::status_mid.
printStatistics()
void ActionPool::printStatistics (ostream & s) const virtual
Dump statistics to stream.
Print out the collected statistics for the Action to stream
Parameters
s is the output stream
Reimplemented from Action.
References allrules, and Action::printStatistics().
processOp()
int4 ActionPool::processOp (PcodeOp * op, Funcdata & data) private
Apply the next possible Rule to a PcodeOp.
This method attempts to apply each Rule to the current PcodeOp Action breakpoints are checked if the Rule successfully applies. 0 is returned for no breakpoint, -1 if a breakpoint occurs. If a breakpoint did occur, an additional call to processOp() will pick up where it left off before the breakpoint. The PcodeOp iterator is advanced.
Parameters
op is the current PcodeOp
data is the function being transformed
Returns
0 if no breakpoint, -1 otherwise
References Rule::applyOp(), Rule::checkActionBreak(), Action::count, Rule::count_apply, Rule::count_tests, Rule::issueWarning(), op_state, perop, and rule_index.
Referenced by apply().
reset()
void ActionPool::reset (Funcdata & data) virtual
Reset the Action for a new function.
Parameters
data is the new function this Action may affect
Reimplemented from Action.
References allrules, and Action::reset().
resetStats()
void ActionPool::resetStats (void) virtual
Reset all the counts to zero.
Reset the statistics
Reimplemented from Action.
References allrules, and Action::resetStats().
The documentation for this class was generated from the following files:
action.hh
action.cc