decompiler: RuleOrPredicate Class Reference
RuleOrPredicate Class Reference
Simplify predication constructions involving the INT_OR operator.
#include <condexe.hh>
Classes
struct MultiPredicate
A helper class to mark up predicated INT_OR expressions.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Private Member Functions
int4 checkSingle (Varnode *vn, MultiPredicate &branch, PcodeOp *op, Funcdata &data)
Check for the alternate form, tmp1 = (val2 == 0) ? val1 : 0;.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Simplify predication constructions involving the INT_OR operator.
In this form of predication, two variables are set based on a condition and then ORed together. Both variables may be set to zero, or to some other value, based on the condition and the zero values are such that at least one of the variables is zero.
tmp1 = cond ? val1 : 0;
tmp2 = cond ?  0 : val2;
result = tmp1 | tmp2;
The RuleOrPredicate simplifies this to
if (cond) result = val1; else result = val2;
or to be precise
newtmp = val1 ? val2;                       // Using a new MULTIEQUAL
result = newtmp;
In an alternate form we have
tmp1 = (val2 == 0) ? val1 : 0
result = tmp1 | val2;
again, one of val1 or val2 must be zero, so this gets replaced with
tmp1 = val1 ? val2
result = tmp1
Member Function Documentation
applyOp()
int4 RuleOrPredicate::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References RuleOrPredicate::MultiPredicate::cbranch, checkSingle(), PcodeOp::compareOrder(), RuleOrPredicate::MultiPredicate::condBlock, CPUI_COPY, CPUI_MULTIEQUAL, RuleOrPredicate::MultiPredicate::discoverCbranch(), RuleOrPredicate::MultiPredicate::discoverPathIsTrue(), RuleOrPredicate::MultiPredicate::discoverZeroSlot(), Funcdata::newOp(), Funcdata::newUniqueOut(), RuleOrPredicate::MultiPredicate::op, Funcdata::opInsertBegin(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), RuleOrPredicate::MultiPredicate::otherVn, ConditionMarker::verifyCondition(), RuleOrPredicate::MultiPredicate::zeroBlock, RuleOrPredicate::MultiPredicate::zeroPathIsTrue, and RuleOrPredicate::MultiPredicate::zeroSlot.
checkSingle()
int4 RuleOrPredicate::checkSingle (Varnode * vn, MultiPredicate & branch, PcodeOp * op, Funcdata & data) private
Check for the alternate form, tmp1 = (val2 == 0) ? val1 : 0;.
We know we have the basic form
tmp1 = cond ?  val1 : 0;
result = tmp1 | other;
So we just need to check that other plays the role of val2. If we match the alternate form, perform the simplification
Parameters
vn is the candidate other Varnode
branch holds the basic form
op is the INT_OR p-code op
data is the function being analyzed
Returns
1 if the form was matched and simplified, 0 otherwise
References CPUI_COPY, RuleOrPredicate::MultiPredicate::discoverCbranch(), RuleOrPredicate::MultiPredicate::discoverConditionalZero(), RuleOrPredicate::MultiPredicate::discoverPathIsTrue(), RuleOrPredicate::MultiPredicate::op, Funcdata::opRemoveInput(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), RuleOrPredicate::MultiPredicate::zeroPathIsTrue, and RuleOrPredicate::MultiPredicate::zeroSlot.
Referenced by applyOp().
clone()
virtual Rule* RuleOrPredicate::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
getOpList()
void RuleOrPredicate::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_OR, and CPUI_INT_XOR.
The documentation for this class was generated from the following files:
condexe.hh
condexe.cc