decompiler: Scope Class Reference
Scope Class Reference abstract
A collection of Symbol objects within a single (namespace or functional) scope.
#include <database.hh>
Public Member Functions
Scope (const string &nm, Architecture *g)
Construct an empty scope, given a name and Architecture.
virtual ~Scope (void)
Destructor.
virtual MapIterator begin (void) const =0
Beginning iterator to mapped SymbolEntrys.
virtual MapIterator end (void) const =0
Ending iterator to mapped SymbolEntrys.
virtual list< SymbolEntry >::const_iterator beginDynamic (void) const =0
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::const_iterator endDynamic (void) const =0
Ending iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator beginDynamic (void)=0
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator endDynamic (void)=0
Ending iterator to dynamic SymbolEntrys.
virtual void clear (void)=0
Clear all symbols from this scope.
virtual void clearCategory (int4 cat)=0
Clear all symbols of the given category from this scope.
virtual void clearUnlocked (void)=0
Clear all unlocked symbols from this scope.
virtual void clearUnlockedCategory (int4 cat)=0
Clear unlocked symbols of the given category from this scope.
virtual bool inScope (const Address &addr, int4 size, const Address &usepoint) const
Query if the given range is owned by this Scope.
virtual void removeSymbolMappings (Symbol *symbol)=0
Remove all SymbolEntrys from the given Symbol.
virtual void removeSymbol (Symbol *symbol)=0
Remove the given Symbol from this Scope.
virtual void renameSymbol (Symbol *sym, const string &newname)=0
Rename a Symbol within this Scope.
virtual void retypeSymbol (Symbol *sym, Datatype *ct)=0
Change the data-type of a Symbol within this Scope.
virtual void setAttribute (Symbol *sym, uint4 attr)=0
Set boolean Varnode properties on a Symbol.
virtual void clearAttribute (Symbol *sym, uint4 attr)=0
Clear boolean Varnode properties on a Symbol.
virtual void setDisplayFormat (Symbol *sym, uint4 attr)=0
Set the display format for a Symbol.
virtual SymbolEntry * findAddr (const Address &addr, const Address &usepoint) const =0
Find a Symbol at a given address and usepoint.
virtual SymbolEntry * findContainer (const Address &addr, int4 size, const Address &usepoint) const =0
Find the smallest Symbol containing the given memory range.
virtual SymbolEntry * findClosestFit (const Address &addr, int4 size, const Address &usepoint) const =0
Find Symbol which is the closest fit to the given memory range.
virtual Funcdata * findFunction (const Address &addr) const =0
Find the function starting at the given address.
virtual ExternRefSymbol * findExternalRef (const Address &addr) const =0
Find an external reference at the given address.
virtual LabSymbol * findCodeLabel (const Address &addr) const =0
Find a label Symbol at the given address.
virtual SymbolEntry * findOverlap (const Address &addr, int4 size) const =0
Find first Symbol overlapping the given memory range.
virtual void findByName (const string &name, vector< Symbol * > &res) const =0
Find a Symbol by name within this Scope.
virtual bool isNameUsed (const string &name) const =0
Check if the given name is used within this scope.
virtual Funcdata * resolveExternalRefFunction (ExternRefSymbol *sym) const =0
Convert an external reference to the referenced function.
virtual string buildVariableName (const Address &addr, const Address &pc, Datatype *ct, int4 &index, uint4 flags) const =0
Given an address and data-type, build a suitable generic symbol name.
virtual string buildUndefinedName (void) const =0
Build a formal undefined name, used internally when a Symbol is not given a name.
virtual string makeNameUnique (const string &nm) const =0
Produce a version of the given symbol name that won't collide with other names in this Scope.
virtual void saveXml (ostream &s) const =0
Write out this as a <scope> XML tag.
virtual void restoreXml (const Element *el)=0
Restore this Scope from a <scope> XML tag.
virtual void printEntries (ostream &s) const =0
Dump a description of all SymbolEntry objects to a stream.
virtual int4 getCategorySize (int4 cat) const =0
Get the number of Symbols in the given category.
virtual Symbol * getCategorySymbol (int4 cat, int4 ind) const =0
Retrieve a Symbol by index within a specific category.
virtual void setCategory (Symbol *sym, int4 cat, int4 ind)=0
Set the category and index for the given Symbol.
virtual SymbolEntry * addSymbol (const string &name, Datatype *ct, const Address &addr, const Address &usepoint)
Add a new Symbol to this Scope, given a name, data-type, and a single mapping.
void queryByName (const string &name, vector< Symbol * > &res) const
Look-up symbols by name.
Funcdata * queryFunction (const string &name) const
Look-up a function by name.
SymbolEntry * queryByAddr (const Address &addr, const Address &usepoint) const
Get Symbol with matching address.
SymbolEntry * queryContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest containing Symbol.
SymbolEntry * queryProperties (const Address &addr, int4 size, const Address &usepoint, uint4 &flags) const
Find a Symbol or properties at the given address.
Funcdata * queryFunction (const Address &addr) const
Look-up a function by address.
Funcdata * queryExternalRefFunction (const Address &addr) const
Look-up a function thru an external reference.
LabSymbol * queryCodeLabel (const Address &addr) const
Look-up a code label by address.
Scope * resolveScope (const string &name) const
Find a child Scope of this.
Scope * discoverScope (const Address &addr, int4 sz, const Address &usepoint)
Find the owning Scope of a given memory range.
void saveXmlRecursive (ostream &s, bool onlyGlobal) const
Save all contained scopes as an XML stream.
void overrideSizeLockType (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol that is sizelocked.
void resetSizeLockType (Symbol *sym)
Clear a Symbol's size-locked data-type.
bool isSubScope (const Scope *scp) const
Is this a sub-scope of the given Scope.
string getFullName (void) const
Get the full name of this Scope.
void getNameSegments (vector< string > &vec) const
Get the fullname of this in segments.
void getScopePath (vector< Scope * > &vec) const
Get the ordered list of parent scopes to this.
bool isNameUsed (const string &nm, const Scope *op2) const
Is the given name in use within given scope path.
const Scope * findDistinguishingScope (const Scope *op2) const
Find first ancestor of this not shared by given scope.
Symbol * addSymbol (const string &name, Datatype *ct)
Add a new Symbol without mapping it to an address.
SymbolEntry * addMapPoint (Symbol *sym, const Address &addr, const Address &usepoint)
Map a Symbol to a specific address.
Symbol * addMapSym (const Element *el)
Add a mapped Symbol from a <mapsym> XML tag.
FunctionSymbol * addFunction (const Address &addr, const string &nm)
Create a function Symbol at the given address in this Scope.
ExternRefSymbol * addExternalRef (const Address &addr, const Address &refaddr, const string &nm)
LabSymbol * addCodeLabel (const Address &addr, const string &nm)
Create a code label at the given address in this Scope.
Symbol * addDynamicSymbol (const string &nm, Datatype *ct, const Address &caddr, uint8 hash)
Create a dynamically mapped Symbol attached to a specific data-flow.
string buildDefaultName (Symbol *sym, int4 &base, Varnode *vn) const
Create a default name for the given Symbol.
bool isReadOnly (const Address &addr, int4 size, const Address &usepoint) const
Is the given memory range marked as read-only.
Protected Member Functions
virtual void restrictScope (Funcdata *f)
Convert this to a local Scope.
virtual void addRange (AddrSpace *spc, uintb first, uintb last)
Add a memory range to the ownership of this Scope.
virtual void removeRange (AddrSpace *spc, uintb first, uintb last)
Remove a memory range from the ownership of this Scope.
virtual void addSymbolInternal (Symbol *sym)=0
Put a Symbol into the name map.
virtual SymbolEntry * addMapInternal (Symbol *sym, uint4 exfl, const Address &addr, int4 off, int4 sz, const RangeList &uselim)=0
Create a new SymbolEntry for a Symbol given a memory range.
virtual SymbolEntry * addDynamicMapInternal (Symbol *sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList &uselim)=0
Create a new SymbolEntry for a Symbol given a dynamic hash.
SymbolEntry * addMap (const SymbolEntry &entry)
Integrate a SymbolEntry into the range maps.
Static Protected Member Functions
static const Scope * stackAddr (const Scope *scope1, const Scope *scope2, const Address &addr, const Address &usepoint, SymbolEntry **addrmatch)
Query for Symbols starting at a given address, which match a given usepoint.
static const Scope * stackContainer (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackClosestFit (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackFunction (const Scope *scope1, const Scope *scope2, const Address &addr, Funcdata **addrmatch)
static const Scope * stackExternalRef (const Scope *scope1, const Scope *scope2, const Address &addr, ExternRefSymbol **addrmatch)
static const Scope * stackCodeLabel (const Scope *scope1, const Scope *scope2, const Address &addr, LabSymbol **addrmatch)
Protected Attributes
Architecture * glb
Architecture of this scope.
string name
Name of this scope.
Funcdata * fd
(If non-null) the function which this is the local Scope for
uint4 uniqueId
Unique id for the scope, for deduping scope names, assigning symbol ids.
Private Member Functions
void attachScope (Scope *child)
Attach a new child Scope to this.
void detachScope (ScopeMap::iterator iter)
Detach a child Scope from this.
Private Attributes
RangeList rangetree
Range of data addresses owned by this scope.
Scope * parent
The parent scope.
ScopeMap children
Sorted list of child scopes.
Friends
class Database
class ScopeCompare
Detailed Description
A collection of Symbol objects within a single (namespace or functional) scope.
This acts as a traditional Symbol container, allowing them to be accessed by name, but it also keeps track of how a Symbol is mapped into memory. It allows a Symbol to be looked up by its location in memory, which is sensitive to the address of the code accessing the Symbol.
Capabilities include:
Search for Symbols
By name
By storage address
By type of Symbol
Containing a range
Overlapping a range
Insert or remove a Symbol
Add or remove SymbolEntry objects which associate Symbols with storage and the code that accesses it
Modify properties of a Symbol
A scope also supports the idea of ownership of memory. In theory, for a Symbol in the scope, at the code locations where the Symbol storage is valid, the scope owns the storage memory. In practice, a Scope object knows about memory ranges where a Symbol might be discovered. For instance, the global Scope usually owns all memory in the ram address space.
Member Function Documentation
addCodeLabel()
LabSymbol * Scope::addCodeLabel (const Address & addr, const string & nm)
Create a code label at the given address in this Scope.
A LabSymbol is created and mapped to the given address.
Parameters
addr is the given address to map to
nm is the name of the symbol/label
Returns
the new LabSymbol
References addMapPoint(), addSymbolInternal(), glb, Architecture::printMessage(), and queryContainer().
Referenced by ScopeGhidra::findCodeLabel().
addDynamicMapInternal()
virtual SymbolEntry* Scope::addDynamicMapInternal (Symbol * sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList & uselim) protected pure virtual
Create a new SymbolEntry for a Symbol given a dynamic hash.
The SymbolEntry is specified in terms of a hash and usepoint, which describe how to find the temporary Varnode holding the symbol value.
Parameters
sym is the given Symbol being mapped
exfl are any boolean Varnode properties
hash is the given dynamic hash
off is the byte offset of the new SymbolEntry (relative to the whole Symbol)
sz is the number of bytes occupied by the Varnode
uselim is the given usepoint
Returns
the newly created SymbolEntry
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by addDynamicSymbol(), and addMap().
addDynamicSymbol()
Symbol * Scope::addDynamicSymbol (const string & nm, Datatype * ct, const Address & caddr, uint8 hash)
Create a dynamically mapped Symbol attached to a specific data-flow.
The Symbol is created and mapped to a dynamic hash and a code address where the Symbol is being used.
Parameters
nm is the name of the Symbol
ct is the data-type of the Symbol
caddr is the code address where the Symbol is being used
hash is the dynamic hash
Returns
the new Symbol
References addDynamicMapInternal(), addSymbolInternal(), Address::getOffset(), Address::getSpace(), RangeList::insertRange(), Address::isInvalid(), and Varnode::mapped.
Referenced by Funcdata::buildDynamicSymbol().
addExternalRef()
ExternRefSymbol * Scope::addExternalRef (const Address & addr, const Address & refaddr, const string & nm)
Create an external reference at the given address in this Scope
An ExternRefSymbol is created and mapped to the given address and stores a reference address to the actual function.
Parameters
addr is the given address to map the Symbol to
refaddr is the reference address
nm is the name of the symbol/function
Returns
the new ExternRefSymbol
References addMapPoint(), addSymbolInternal(), Symbol::flags, Varnode::readonly, and SymbolEntry::symbol.
addFunction()
FunctionSymbol * Scope::addFunction (const Address & addr, const string & nm)
Create a function Symbol at the given address in this Scope.
The FunctionSymbol is created and mapped to the given address. A Funcdata object is only created once FunctionSymbol::getFunction() is called.
Parameters
addr is the entry address of the function
nm is the name of the function, within this Scope
Returns
the new FunctionSymbol object
References addMapPoint(), addSymbolInternal(), glb, Architecture::min_funcsymbol_size, name, Architecture::printMessage(), and queryContainer().
Referenced by Architecture::readLoaderSymbols().
addMap()
SymbolEntry * Scope::addMap (const SymbolEntry & entry) protected
Integrate a SymbolEntry into the range maps.
The mapping is given as an unintegrated SymbolEntry object. Memory may be specified in terms of join addresses, which this method must unravel. The offset, size, and extraflags fields of the SymbolEntry are not used. In particular, the SymbolEntry is assumed to map the entire Symbol.
Parameters
entry is the given SymbolEntry
Returns
a SymbolEntry which has been fully integrated
References addDynamicMapInternal(), addMapInternal(), SymbolEntry::addr, Varnode::addrtied, AddrSpaceManager::findJoin(), Symbol::flags, VarnodeData::getAddr(), Symbol::getBytesConsumed(), Address::getOffset(), glb, SymbolEntry::hash, Address::isBigEndian(), Address::isInvalid(), Address::isJoin(), Varnode::mapped, Varnode::persist, Varnode::precishi, Varnode::precislo, VarnodeData::size, SymbolEntry::symbol, Architecture::symboltab, and SymbolEntry::uselimit.
Referenced by addMapPoint(), and addMapSym().
addMapInternal()
virtual SymbolEntry* Scope::addMapInternal (Symbol * sym, uint4 exfl, const Address & addr, int4 off, int4 sz, const RangeList & uselim) protected pure virtual
Create a new SymbolEntry for a Symbol given a memory range.
The SymbolEntry is specified in terms of a memory range and usepoint
Parameters
sym is the given Symbol being mapped
exfl are any boolean Varnode properties specific to the memory range
addr is the starting address of the given memory range
off is the byte offset of the new SymbolEntry (relative to the whole Symbol)
sz is the number of bytes in the range
uselim is the given usepoint (which may be invalid)
Returns
the newly created SymbolEntry
Implemented in ScopeInternal, ScopeGhidraNamespace, and ScopeGhidra.
Referenced by addMap().
addMapPoint()
SymbolEntry * Scope::addMapPoint (Symbol * sym, const Address & addr, const Address & usepoint)
Map a Symbol to a specific address.
Create a new SymbolEntry that maps the whole Symbol to the given address
Parameters
sym is the Symbol
addr is the given address to map to
usepoint is a point at which the Symbol is accessed at that address
Returns
the SymbolEntry representing the new mapping
References addMap(), SymbolEntry::addr, Address::getOffset(), Address::getSpace(), RangeList::insertRange(), Address::isInvalid(), and SymbolEntry::uselimit.
Referenced by addCodeLabel(), addExternalRef(), addFunction(), addSymbol(), and ScopeInternal::retypeSymbol().
addMapSym()
Symbol * Scope::addMapSym (const Element * el)
Add a mapped Symbol from a <mapsym> XML tag.
A tag describing the Symbol is parsed first, followed by sequences of <addr> or <hash> and <rangelist> which define 1 or more mappings of the Symbol The new Symbol and SymbolEntry mappings are integrated into this Scope
Parameters
el is the <mapsym> XML element
Returns
the new Symbol
References addMap(), addSymbolInternal(), glb, Architecture::min_funcsymbol_size, Architecture::printMessage(), removeSymbol(), SymbolEntry::restoreXml(), and Symbol::restoreXml().
Referenced by ScopeGhidra::dump2Cache(), and ScopeInternal::restoreXml().
addRange()
void Scope::addRange (AddrSpace * spc, uintb first, uintb last) protected virtual
Add a memory range to the ownership of this Scope.
Parameters
spc is the address space of the range
first is the offset of the first byte in the range
last is the offset of the last byte in the range
Reimplemented in ScopeGhidra.
References RangeList::insertRange(), and rangetree.
Referenced by ScopeGhidra::addRange(), and Database::addRange().
addSymbol() [1/2]
Symbol * Scope::addSymbol (const string & name, Datatype * ct)
Add a new Symbol without mapping it to an address.
The Symbol is created and added to any name map, but no SymbolEntry objects are created for it.
Parameters
name is the name of the new Symbol
ct is a data-type to assign to the new Symbol
Returns
the new Symbol object
References addSymbolInternal(), and name.
addSymbol() [2/2]
SymbolEntry * Scope::addSymbol (const string & name, Datatype * ct, const Address & addr, const Address & usepoint) virtual
Add a new Symbol to this Scope, given a name, data-type, and a single mapping.
The Symbol object will be created with the given name and data-type. A single mapping (SymbolEntry) will be created for the Symbol based on a given storage address for the symbol and an address for code that accesses the Symbol at that storage location.
Parameters
name is the new name of the Symbol
ct is the data-type of the new Symbol
addr is the starting address of the Symbol storage
usepoint is the point accessing that storage (may be invalid)
Returns
the SymbolEntry matching the new mapping
Reimplemented in ScopeGhidra.
References addMapPoint(), addSymbolInternal(), and name.
Referenced by ScopeGhidra::addSymbol(), ScopeLocal::createEntry(), ScopeLocal::fakeInputSymbols(), Funcdata::linkSymbol(), Funcdata::mapGlobals(), and ProtoStoreSymbol::setInput().
addSymbolInternal()
virtual void Scope::addSymbolInternal (Symbol * sym) protected pure virtual
Put a Symbol into the name map.
Parameters
sym is the preconstructed Symbol
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by addCodeLabel(), addDynamicSymbol(), addExternalRef(), addFunction(), addMapSym(), and addSymbol().
attachScope()
void Scope::attachScope (Scope * child) private
Attach a new child Scope to this.
Attach the child as an immediate sub-scope of this. Take responsibility of the child's memory: the child will be freed when this is freed. May throw RecovError if there is a duplicate name issue
Parameters
child is the Scope to make a child
References children, getFullName(), name, parent, and uniqueId.
Referenced by Database::attachScope().
buildDefaultName()
string Scope::buildDefaultName (Symbol * sym, int4 & base, Varnode * vn) const
Create a default name for the given Symbol.
Create default name given information in the Symbol and possibly a representative Varnode. This method extracts the crucial properties and then uses the buildVariableName method to construct the actual name.
Parameters
sym is the given Symbol to name
base is an index (which may get updated) used to uniquify the name
vn is an optional (may be null) Varnode representative of the Symbol
Returns
the default name
References Varnode::addrtied, buildVariableName(), fd, SymbolEntry::getFirstUseAddress(), Varnode::getHigh(), Symbol::getMapEntry(), Varnode::getUsePoint(), Varnode::input, Varnode::isAddrTied(), and Address::isInvalid().
Referenced by ActionNameVars::apply(), and ScopeInternal::assignDefaultNames().
buildUndefinedName()
virtual string Scope::buildUndefinedName (void) const pure virtual
Build a formal undefined name, used internally when a Symbol is not given a name.
Returns
a special internal name that won't collide with other names in this Scope
Implemented in ScopeInternal, and ScopeGhidra.
buildVariableName()
virtual string Scope::buildVariableName (const Address & addr, const Address & pc, Datatype * ct, int4 & index, uint4 flags) const pure virtual
Given an address and data-type, build a suitable generic symbol name.
Parameters
addr is the given address
pc is the address at which the name is getting used
ct is a data-type used to inform the name
index is a reference to an index used to make the name unique, which will be updated
flags are boolean properties of the variable we need the name for
Returns
the new variable name
Implemented in ScopeInternal, ScopeLocal, and ScopeGhidra.
Referenced by buildDefaultName(), and Funcdata::mapGlobals().
detachScope()
void Scope::detachScope (ScopeMap::iterator iter) private
Detach a child Scope from this.
The indicated child Scope is deleted
Parameters
iter points to the Scope to delete
References children.
Referenced by Database::deleteScope(), and Database::deleteSubScopes().
discoverScope()
Scope * Scope::discoverScope (const Address & addr, int4 sz, const Address & usepoint)
Find the owning Scope of a given memory range.
Discover a sub-scope or containing Scope of this, that owns the given memory range at a specific usepoint. Note that ownership does not necessarily mean there is a known symbol there.
Parameters
addr is the starting address of the memory range
sz is the number of bytes in the range
usepoint is a point at which the memory is getting accesses
References glb, inScope(), Address::isConstant(), Database::mapScope(), and Architecture::symboltab.
Referenced by Funcdata::mapGlobals(), and ProtoStoreSymbol::setInput().
findAddr()
virtual SymbolEntry* Scope::findAddr (const Address & addr, const Address & usepoint) const pure virtual
Find a Symbol at a given address and usepoint.
Parameters
addr is the given address
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by stackAddr().
findByName()
virtual void Scope::findByName (const string & name, vector< Symbol * > & res) const pure virtual
Find a Symbol by name within this Scope.
If there are multiple Symbols with the same name, all are passed back.
Parameters
name is the name to search for
res will contain any matching Symbols
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by queryByName().
findClosestFit()
virtual SymbolEntry* Scope::findClosestFit (const Address & addr, int4 size, const Address & usepoint) const pure virtual
Find Symbol which is the closest fit to the given memory range.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by stackClosestFit().
findCodeLabel()
virtual LabSymbol* Scope::findCodeLabel (const Address & addr) const pure virtual
Find a label Symbol at the given address.
Parameters
addr is the given address
Returns
the matching LabSymbol or NULL
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by stackCodeLabel().
findContainer()
virtual SymbolEntry* Scope::findContainer (const Address & addr, int4 size, const Address & usepoint) const pure virtual
Find the smallest Symbol containing the given memory range.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by stackContainer().
findDistinguishingScope()
const Scope * Scope::findDistinguishingScope (const Scope * op2) const
Find first ancestor of this not shared by given scope.
Any two scopes share at least the global scope as a common ancestor. We find the first scope that is not in common. The scope returned will always be an ancestor of this. If this is an ancestor of the other given scope, then null is returned.
Parameters
op2 is the other given Scope
Returns
the first ancestor Scope that is not in common or null
References getScopePath(), and parent.
Referenced by Symbol::getResolutionDepth().
findExternalRef()
virtual ExternRefSymbol* Scope::findExternalRef (const Address & addr) const pure virtual
Find an external reference at the given address.
Parameters
addr is the given address
Returns
the matching ExternRefSymbol or NULL
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by stackExternalRef().
findFunction()
virtual Funcdata* Scope::findFunction (const Address & addr) const pure virtual
Find the function starting at the given address.
Parameters
addr is the given starting address
Returns
the matching Funcdata object or NULL
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by stackFunction().
findOverlap()
virtual SymbolEntry* Scope::findOverlap (const Address & addr, int4 size) const pure virtual
Find first Symbol overlapping the given memory range.
Parameters
addr is the starting address of the given range
size is the number of bytes in the range
Returns
an overlapping SymbolEntry or NULL if none exists
Implemented in ScopeInternal, and ScopeGhidra.
getCategorySize()
virtual int4 Scope::getCategorySize (int4 cat) const pure virtual
Get the number of Symbols in the given category.
Parameters
cat is the Symbol category
Returns
the number in that category
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by ProtoStoreSymbol::clearInput(), and ProtoStoreSymbol::getNumInputs().
getCategorySymbol()
virtual Symbol* Scope::getCategorySymbol (int4 cat, int4 ind) const pure virtual
Retrieve a Symbol by index within a specific category.
Parameters
cat is the Symbol category
ind is the index (within the category) of the Symbol
Returns
the indicated Symbol or NULL if no Symbol with that index exists
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by ProtoStoreSymbol::clearInput(), ProtoStoreSymbol::getInput(), and ProtoStoreSymbol::setInput().
getNameSegments()
void Scope::getNameSegments (vector< string > & vec) const
Get the fullname of this in segments.
Put the names of this and all its parent Scopes into an array in order. The name of the first entry will generally be the name of the global Scope
Parameters
vec is the array in which to store the names
References name, and parent.
Referenced by ScopeInternal::saveXml().
getScopePath()
void Scope::getScopePath (vector< Scope * > & vec) const
Get the ordered list of parent scopes to this.
Put the parent scopes of this into an array in order, starting with the global scope. This scope itself will not be in the array.
Parameters
vec is storage for the array of scopes
References parent.
Referenced by findDistinguishingScope().
inScope()
virtual bool Scope::inScope (const Address & addr, int4 size, const Address & usepoint) const inline virtual
Query if the given range is owned by this Scope.
All bytes in the range must be owned, and ownership can be informed by particular code that is accessing the range.
Parameters
addr is the starting address of the range
size is the number of bytes in the range
usepoint is the code address at which the given range is being accessed (may be invalid)
Returns
true if this Scope owns the memory range
References RangeList::inRange(), and rangetree.
Referenced by discoverScope(), stackAddr(), stackClosestFit(), stackCodeLabel(), stackContainer(), stackFunction(), and Funcdata::syncVarnodesWithSymbols().
isNameUsed() [1/2]
virtual bool Scope::isNameUsed (const string & name) const pure virtual
Check if the given name is used within this scope.
Only this scope is checked. If one or more symbols exist with the given name, true is returned.
Parameters
name is the given name to check for
Returns
true if the name is used within this scope
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by Symbol::getResolutionDepth(), and isNameUsed().
isNameUsed() [2/2]
bool Scope::isNameUsed (const string & nm, const Scope * op2) const
Is the given name in use within given scope path.
Test for the presence of a symbol with the given name in either this scope or an ancestor scope up to but not including the given terminating scope. If the name is used true is returned.
Parameters
nm is the given name to test
op2 is the terminating ancestor scope (or null)
References isNameUsed(), name, and parent.
isReadOnly()
bool Scope::isReadOnly (const Address & addr, int4 size, const Address & usepoint) const
Is the given memory range marked as read-only.
Check for Symbols relative to this Scope that are marked as read-only, and look-up properties of the memory in general.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is a point where the range is getting accessed
Returns
true if the memory is marked as read-only
References queryProperties(), and Varnode::readonly.
Referenced by RulePtrsubCharConstant::applyOp().
isSubScope()
bool Scope::isSubScope (const Scope * scp) const
Is this a sub-scope of the given Scope.
Does the given Scope contain this as a sub-scope.
Parameters
scp is the given Scope
Returns
true if this is a sub-scope
References parent.
makeNameUnique()
virtual string Scope::makeNameUnique (const string & nm) const pure virtual
Produce a version of the given symbol name that won't collide with other names in this Scope.
Parameters
nm is the given name
Returns
return a unique version of the name
Implemented in ScopeInternal, and ScopeGhidra.
overrideSizeLockType()
void Scope::overrideSizeLockType (Symbol * sym, Datatype * ct)
Change the data-type of a Symbol that is sizelocked.
Change (override) the data-type of a sizelocked Symbol, while preserving the lock. An exception is thrown if the new data-type doesn't fit the size.
Parameters
sym is the locked Symbol
ct is the data-type to change the Symbol to
References Symbol::type.
queryByAddr()
SymbolEntry * Scope::queryByAddr (const Address & addr, const Address & usepoint) const
Get Symbol with matching address.
Within a sub-scope or containing Scope of this, find a Symbol that is mapped to the given address, where the mapping is valid at a specific usepoint.
Parameters
addr is the given address
usepoint is the point at which code accesses that address (may be invalid)
Returns
the matching SymbolEntry
References glb, Database::mapScope(), stackAddr(), and Architecture::symboltab.
queryByName()
void Scope::queryByName (const string & name, vector< Symbol * > & res) const
Look-up symbols by name.
Starting from this Scope, look for a Symbol with the given name. If there are no Symbols in this Scope, recurse into the parent Scope. If there are 1 (or more) Symbols matching in this Scope, add them to the result list
Parameters
name is the name to search for
res is the result list
References findByName(), name, parent, and queryByName().
Referenced by ScopeGhidra::dump2Cache(), Funcdata::findHigh(), queryByName(), and queryFunction().
queryCodeLabel()
LabSymbol * Scope::queryCodeLabel (const Address & addr) const
Look-up a code label by address.
Within a sub-scope or containing Scope of this, find a label Symbol at the given address.
Parameters
addr is the given address
Returns
the LabSymbol object, or NULL if it doesn't exist
References glb, Database::mapScope(), stackCodeLabel(), and Architecture::symboltab.
queryContainer()
SymbolEntry * Scope::queryContainer (const Address & addr, int4 size, const Address & usepoint) const
Find the smallest containing Symbol.
Within a sub-scope or containing Scope of this, find the smallest Symbol that contains a given memory range and can be accessed at a given usepoint.
Parameters
addr is the given starting address of the memory range
size is the number of bytes in the range
usepoint is a point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
References glb, Database::mapScope(), stackContainer(), and Architecture::symboltab.
Referenced by addCodeLabel(), addFunction(), and Funcdata::linkSymbolReference().
queryExternalRefFunction()
Funcdata * Scope::queryExternalRefFunction (const Address & addr) const
Look-up a function thru an external reference.
Given an address, search for an external reference. If no Symbol is found and this Scope does not own the address, recurse searching in the parent Scope. If an external reference is found, try to resolve the function it refers to and return it.
Parameters
addr is the given address where an external reference might be
Returns
the referred to Funcdata object or NULL if not found
References glb, Database::mapScope(), resolveExternalRefFunction(), stackExternalRef(), and Architecture::symboltab.
queryFunction() [1/2]
Funcdata * Scope::queryFunction (const Address & addr) const
Look-up a function by address.
Within a sub-scope or containing Scope of this, find a function starting at the given address.
Parameters
addr is the starting address of the function
Returns
the Funcdata object of the matching function, or NULL if it doesn't exist
References glb, Database::mapScope(), stackFunction(), and Architecture::symboltab.
queryFunction() [2/2]
Funcdata * Scope::queryFunction (const string & name) const
Look-up a function by name.
Starting with this Scope, find a function with the given name. If there are no Symbols with that name in this Scope at all, recurse into the parent Scope.
Parameters
name if the name to search for
Returns
the Funcdata object of the matching function, or NULL if it doesn't exist
References FunctionSymbol::getFunction(), name, and queryByName().
Referenced by ScopeInternal::resolveExternalRefFunction().
queryProperties()
SymbolEntry * Scope::queryProperties (const Address & addr, int4 size, const Address & usepoint, uint4 & flags) const
Find a Symbol or properties at the given address.
Similarly to queryContainer(), this searches for the smallest containing Symbol, but whether a known Symbol is found or not, boolean properties associated with the memory range are also search for and passed back.
Parameters
addr is the starting address of the range
size is the number of bytes in the range
usepoint is a point at which the memory range is accessed (may be invalid)
flags is a reference used to pass back the boolean properties of the memory range
Returns
the smallest SymbolEntry containing the range, or NULL
References Varnode::addrtied, SymbolEntry::getAllFlags(), glb, Varnode::mapped, Database::mapScope(), Varnode::persist, stackContainer(), and Architecture::symboltab.
Referenced by ScopeLocal::fakeInputSymbols(), isReadOnly(), Funcdata::linkSymbol(), Funcdata::mapGlobals(), Funcdata::newVarnode(), Funcdata::newVarnodeOut(), and Funcdata::setVarnodeProperties().
removeRange()
void Scope::removeRange (AddrSpace * spc, uintb first, uintb last) protected virtual
Remove a memory range from the ownership of this Scope.
Parameters
spc is the address space of the range
first is the offset of the first byte in the range
last is the offset of the last byte in the range
Reimplemented in ScopeGhidra.
References rangetree, and RangeList::removeRange().
Referenced by Database::removeRange().
resetSizeLockType()
void Scope::resetSizeLockType (Symbol * sym)
Clear a Symbol's size-locked data-type.
Replace any overriding data-type type with the locked UNKNOWN type of the correct size. The data-type is cleared, but the lock is preserved.
Parameters
sym is the Symbol to clear
References TypeFactory::getBase(), glb, Symbol::type, TYPE_UNKNOWN, and Architecture::types.
Referenced by ScopeInternal::clearUnlocked(), and ScopeInternal::clearUnlockedCategory().
resolveExternalRefFunction()
virtual Funcdata* Scope::resolveExternalRefFunction (ExternRefSymbol * sym) const pure virtual
Convert an external reference to the referenced function.
Parameters
sym is the Symbol marking the external reference
Returns
the underlying Funcdata object or NULL if none exists
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by queryExternalRefFunction().
resolveScope()
Scope * Scope::resolveScope (const string & name) const
Find a child Scope of this.
Look for the (last) immediate child of this with a given name
Parameters
name is the child's name
Returns
the child Scope or NULL if there is no child with that name
References children, and name.
Referenced by ScopeGhidra::reresolveScope(), Database::resolveScope(), Database::resolveScopeSymbolName(), and Database::restoreXml().
restrictScope()
void Scope::restrictScope (Funcdata * f) protected virtual
Convert this to a local Scope.
Attach this to the given function, which makes this the local scope for the function
Parameters
f is the given function to attach to
Reimplemented in ScopeGhidra.
References fd.
Referenced by ScopeLocal::ScopeLocal().
retypeSymbol()
virtual void Scope::retypeSymbol (Symbol * sym, Datatype * ct) pure virtual
Change the data-type of a Symbol within this Scope.
If the size of the Symbol changes, any mapping (SymbolEntry) is adjusted
Parameters
sym is the given Symbol
ct is the new data-type
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by ProtoStoreSymbol::setInput().
saveXmlRecursive()
void Scope::saveXmlRecursive (ostream & s, bool onlyGlobal) const
Save all contained scopes as an XML stream.
This Scope and all of its sub-scopes are saved as a sequence of <scope> tags in post order. For each Scope, the saveXml() method is invoked.
Parameters
s is the output stream
onlyGlobal is true if only non-local Scopes should be saved
References children, and saveXml().
Referenced by Funcdata::saveXml(), and Database::saveXml().
setCategory()
virtual void Scope::setCategory (Symbol * sym, int4 cat, int4 ind) pure virtual
Set the category and index for the given Symbol.
Parameters
sym is the given Symbol
cat is the category to set for the Symbol
ind is the index position to set (within the category)
Implemented in ScopeInternal, and ScopeGhidra.
Referenced by ProtoStoreSymbol::clearInput(), and ProtoStoreSymbol::setInput().
stackAddr()
const Scope * Scope::stackAddr (const Scope * scope1, const Scope * scope2, const Address & addr, const Address & usepoint, SymbolEntry ** addrmatch) static protected
Query for Symbols starting at a given address, which match a given usepoint.
Searching starts at a first scope, continuing thru parents up to a second scope, which is not queried. If a Scope controls the memory at that address, the Scope object is returned. Additionally, if a symbol matching the criterion is found, the matching SymbolEntry is passed back.
Parameters
scope1 is the first Scope where searching starts
scope2 is the second Scope where searching ends
addr is the given address to search for
usepoint is the given point at which the memory is being accessed (can be an invalid address)
addrmatch is used to pass-back any matching SymbolEntry
Returns
the Scope owning the address or NULL if none found
References findAddr(), inScope(), and Address::isConstant().
Referenced by queryByAddr().
stackClosestFit()
const Scope * Scope::stackClosestFit (const Scope * scope1, const Scope * scope2, const Address & addr, int4 size, const Address & usepoint, SymbolEntry ** addrmatch) static protected
Query for a Symbol which most closely matches a given range and usepoint
Searching starts at a first scope, continuing thru parents up to a second scope, which is not queried. If a Scope controls the memory in the given range, the Scope object is returned. Among symbols that overlap the given range, the SymbolEntry which most closely matches the starting address and size is passed back.
Parameters
scope1 is the first Scope where searching starts
scope2 is the second Scope where searching ends
addr is the starting address of the given range
size is the number of bytes in the given range
usepoint is the point at which the memory is being accessed (can be an invalid address)
addrmatch is used to pass-back any matching SymbolEntry
Returns
the Scope owning the address or NULL if none found
References findClosestFit(), inScope(), and Address::isConstant().
stackCodeLabel()
const Scope * Scope::stackCodeLabel (const Scope * scope1, const Scope * scope2, const Address & addr, LabSymbol ** addrmatch) static protected
Query for a label Symbol for a given address.
Searching starts at a first scope, continuing thru parents up to a second scope, which is not queried. If a Scope controls the memory in the given range, the Scope object is returned. If there is a label at that address, pass back the corresponding LabSymbol object
Parameters
scope1 is the first Scope where searching starts
scope2 is the second Scope where searching ends
addr is the given address
addrmatch is used to pass-back any matching Symbol
Returns
the Scope owning the address or NULL if none found
References findCodeLabel(), inScope(), and Address::isConstant().
Referenced by queryCodeLabel().
stackContainer()
const Scope * Scope::stackContainer (const Scope * scope1, const Scope * scope2, const Address & addr, int4 size, const Address & usepoint, SymbolEntry ** addrmatch) static protected
Query for a Symbol containing a given range which is accessed at a given usepoint
Searching starts at a first scope, continuing thru parents up to a second scope, which is not queried. If a Scope controls the memory in the given range, the Scope object is returned. If a known Symbol contains the range, the matching SymbolEntry is passed back.
Parameters
scope1 is the first Scope where searching starts
scope2 is the second Scope where searching ends
addr is the starting address of the given range
size is the number of bytes in the given range
usepoint is the point at which the memory is being accessed (can be an invalid address)
addrmatch is used to pass-back any matching SymbolEntry
Returns
the Scope owning the address or NULL if none found
References findContainer(), inScope(), and Address::isConstant().
Referenced by queryContainer(), and queryProperties().
stackExternalRef()
const Scope * Scope::stackExternalRef (const Scope * scope1, const Scope * scope2, const Address & addr, ExternRefSymbol ** addrmatch) static protected
Query for an external reference Symbol starting at the given address
Searching starts at a first scope, continuing thru parents up to a second scope, which is not queried. If a Scope controls the memory in the given range, the Scope object is returned. If an external reference is found at the address, pass back the matching ExternRefSymbol
Parameters
scope1 is the first Scope where searching starts
scope2 is the second Scope where searching ends
addr is the given address
addrmatch is used to pass-back any matching Symbol
Returns
the Scope owning the address or NULL if none found
References findExternalRef(), and Address::isConstant().
Referenced by queryExternalRefFunction().
stackFunction()
const Scope * Scope::stackFunction (const Scope * scope1, const Scope * scope2, const Address & addr, Funcdata ** addrmatch) static protected
Query for a function Symbol starting at the given address
Searching starts at a first scope, continuing thru parents up to a second scope, which is not queried. If a Scope controls the memory in the given range, the Scope object is returned. If a FunctionSymbol is found at the given address, the corresponding Funcdata object is passed back.
Parameters
scope1 is the first Scope where searching starts
scope2 is the second Scope where searching ends
addr is the given address where the function should start
addrmatch is used to pass-back any matching function
Returns
the Scope owning the address or NULL if none found
References fd, findFunction(), inScope(), and Address::isConstant().
Referenced by queryFunction(), and ScopeGhidra::resolveExternalRefFunction().
The documentation for this class was generated from the following files:
database.hh
database.cc