decompiler: coreaction.hh File Reference
coreaction.hh File Reference
Core decompilation actions which are indepedent of any particular architecture.
#include "ruleaction.hh"
#include "blockaction.hh"
#include "funcdata.hh"
Classes
class ActionStart
Gather raw p-code for a function.
class ActionStop
Do any post-processing after decompilation.
class ActionStartCleanUp
Start clean up after main transform phase.
class ActionStartTypes
Allow type recovery to start happening.
class ActionStackPtrFlow
Analyze change to the stack pointer across sub-function calls.
class ActionLaneDivide
Find Varnodes with a vectorized lane scheme and attempt to split the lanes.
class ActionSegmentize
Make sure pointers into segmented spaces have the correct form.
class ActionForceGoto
Apply any overridden forced gotos.
class ActionMultiCse
Perform Common Sub-expression Elimination on CPUI_MULTIEQUAL ops.
class ActionShadowVar
Check for one CPUI_MULTIEQUAL input set defining more than one Varnode.
class ActionConstantPtr
Check for constants, with pointer type, that correspond to global symbols.
class ActionDeindirect
Eliminate locally constant indirect calls.
class ActionVarnodeProps
Transform based on Varnode properties, such as read-only and volatile.
class ActionDirectWrite
Mark Varnodes built out of legal parameters.
class ActionConstbase
Search for input Varnodes that have been officially provided constant values.
class ActionSpacebase
Mark Varnode objects that hold stack-pointer values and set-up special data-type.
class ActionHeritage
Build Static Single Assignment (SSA) representation for function.
class ActionNonzeroMask
Calculate the non-zero mask property on all Varnode objects.
class ActionSetCasts
Fill-in CPUI_CAST p-code ops as required by the casting strategy.
class ActionAssignHigh
Assign initial high-level HighVariable objects to each Varnode.
class ActionMarkIndirectOnly
Mark illegal Varnode inputs used only in CPUI_INDIRECT ops.
class ActionMergeRequired
Make required Varnode merges as dictated by CPUI_MULTIEQUAL, CPUI_INDIRECT, and addrtied property.
class ActionMergeAdjacent
Try to merge an op's input Varnode to its output, if they are at the same storage location.
class ActionMergeCopy
Try to merge the input and output Varnodes of a CPUI_COPY op.
class ActionMergeMultiEntry
Try to merge Varnodes specified by Symbols with multiple SymbolEntrys.
class ActionMergeType
Try to merge Varnodes of the same type (if they don't hold different values at the same time)
class ActionMarkExplicit
Find explicit Varnodes: Varnodes that have an explicit token representing them in the output.
struct ActionMarkExplicit::OpStackElement
This class holds a single entry in a stack used to traverse Varnode expressions.
class ActionMarkImplied
Mark all the implied Varnode objects, which will have no explicit token in the output.
struct ActionMarkImplied::DescTreeElement
This class holds a single entry in a stack used to forward traverse Varnode expressions.
class ActionNameVars
Choose names for all high-level variables (HighVariables)
struct ActionNameVars::OpRecommend
This class is a record in a database used to store and lookup potential names.
class ActionUnreachable
Remove unreachable blocks.
class ActionDoNothing
Remove blocks that do nothing.
class ActionRedundBranch
Get rid of redundant branches: duplicate edges between the same input and output block.
class ActionDeterminedBranch
Remove conditional branches if the condition is constant.
class ActionDeadCode
Dead code removal. Eliminate dead p-code ops.
class ActionConditionalConst
Propagate conditional constants.
class ActionSwitchNorm
Normalize jump-table construction.
class ActionNormalizeSetup
Prepare function prototypes for "normalize" simplification.
class ActionPrototypeTypes
Lay down locked input and output data-type information.
class ActionDefaultParams
Find a prototype for each sub-function.
class ActionExtraPopSetup
Define formal link between stack-pointer values before and after sub-function calls.
class ActionFuncLink
Prepare for data-flow analysis of function parameters.
class ActionFuncLinkOutOnly
Prepare for data-flow analysis of function parameters, when recovery isn't required.
class ActionParamDouble
Deal with situations that look like double precision parameters.
class ActionActiveParam
Determine active parameters to sub-functions.
class ActionActiveReturn
Determine which sub-functions have active output Varnodes.
class ActionReturnRecovery
Determine data-flow holding the return value of the function.
class ActionRestrictLocal
Restrict possible range of local variables.
class ActionLikelyTrash
Get rid of registers with trash values.
class ActionRestructureVarnode
Create symbols that map out the local stack-frame for the function.
class ActionRestructureHigh
Create symbols that map out the local stack-frame for the function.
class ActionMapGlobals
Create symbols for any discovered global variables in the function.
class ActionInputPrototype
Calculate the prototype for the function.
class ActionOutputPrototype
Set the (already) recovered output data-type as a formal part of the prototype.
class ActionUnjustifiedParams
Adjust improperly justified parameters.
class ActionInferTypes
Infer and propagate data-types.
class ActionHideShadow
Locate shadow Varnodes and adjust them so they are hidden.
class ActionDominantCopy
Replace COPYs from the same source with a single dominant COPY.
class ActionCopyMarker
Mark COPY operations between Varnodes representing the object as non-printing.
class ActionDynamicMapping
Attach dynamically mapped symbols to Varnodes in time for data-type propagation.
class ActionDynamicSymbols
Make final attachments of dynamically mapped symbols to Varnodes.
class ActionPrototypeWarnings
Add warnings for prototypes that aren't modeled properly.
class PropagationState
A class that holds a data-type traversal state during type propagation.
class PcodeOpEdge
Class representing a term in an additive expression.
class TermOrder
A class for ordering Varnode terms in an additive expression.
Functions
void universal_action (Architecture *conf)
The generic decompilation action.
void build_defaultactions (ActionDatabase &allacts)
Build the default actions.
Detailed Description
Core decompilation actions which are indepedent of any particular architecture.
These are the internal actions. They are guaranteed to not to invalidate covers. (if they do they must check the covers themselves)
Function Documentation
build_defaultactions()
void build_defaultactions (ActionDatabase & allacts)
Build the default actions.
Build the default root Actions: decompile, jumptable, normalize, paramid, register, firstpass
Parameters
allacts is the database that will hold the root Actions
References ActionDatabase::setGroup().
Referenced by universal_action().
universal_action()
void universal_action (Architecture * conf)
The generic decompilation action.
Construct the universal Action that contains all possible components
Parameters
conf is the Architecture that will use the Action
References ActionGroup::addAction(), ActionPool::addRule(), Architecture::allacts, build_defaultactions(), Architecture::extra_pool_rules, AddrSpaceManager::getStackSpace(), ActionDatabase::registerUniversal(), Action::rule_onceperfunc, and Action::rule_repeatapply.
Referenced by Architecture::buildAction().