decompiler: funcdata.hh File Reference
funcdata.hh File Reference
Utilities for processing data structures associated with a single function.
#include "architecture.hh"
#include "override.hh"
#include "heritage.hh"
#include "merge.hh"
#include "dynamic.hh"
Classes
class Funcdata
Container for data structures associated with a single function.
class PcodeEmitFd
A p-code emitter for building PcodeOp objects.
class AncestorRealistic
Helper class for determining if Varnodes can trace their value from a legitimate source.
class AncestorRealistic::State
Node in a depth first traversal of ancestors.
Functions
int4 opFlipInPlaceTest (PcodeOp *op, vector< PcodeOp * > &fliplist)
Trace a boolean value to a set of PcodeOps that can be changed to flip the boolean value.
void opFlipInPlaceExecute (Funcdata &data, vector< PcodeOp * > &fliplist)
Perform op-code flips (in-place) to change a boolean value.
PcodeOp * earliestUseInBlock (Varnode *vn, BlockBasic *bl)
Get the earliest use/read of a Varnode in a specified basic block.
PcodeOp * cseFindInBlock (PcodeOp *op, Varnode *vn, BlockBasic *bl, PcodeOp *earliest)
Find a duplicate calculation of a given PcodeOp reading a specific Varnode.
PcodeOp * cseElimination (Funcdata &data, PcodeOp *op1, PcodeOp *op2)
Perform a Common Subexpression Elimination step.
void cseEliminateList (Funcdata &data, vector< pair< uintm, PcodeOp * > > &list, vector< Varnode * > &outlist)
Perform Common Subexpression Elimination on a list of Varnode descendants.
Detailed Description
Utilities for processing data structures associated with a single function.
Function Documentation
cseEliminateList()
void cseEliminateList (Funcdata & data, vector< pair< uintm, PcodeOp * > > & list, vector< Varnode * > & outlist)
Perform Common Subexpression Elimination on a list of Varnode descendants.
The list consists of PcodeOp descendants of a single Varnode paired with a hash value. The hash serves as a primary test for duplicate calculations; if it doesn't match the PcodeOps aren't common subexpressions. This method searches for hash matches then does secondary testing and eliminates any redundancy it finds.
Parameters
data is the function being modified
list is the list of (hash, PcodeOp) pairs
outlist will hold Varnodes produced by duplicate calculations
References cseElimination(), PcodeOp::isCseMatch(), and Funcdata::isHeritaged().
Referenced by RuleSelectCse::applyOp().
cseElimination()
PcodeOp* cseElimination (Funcdata & data, PcodeOp * op1, PcodeOp * op2)
Perform a Common Subexpression Elimination step.
Assuming the two given PcodeOps perform the identical operation on identical operands (depth 1 functional equivalence) eliminate the redundancy. Return the remaining (dominating) PcodeOp. If neither op dominates the other, both are eliminated, and a new PcodeOp is built at a commonly accessible point.
Parameters
data is the function being modified
op1 is the first of the given PcodeOps
op2 is the second given PcodeOp
Returns
the dominating PcodeOp
References FlowBlock::findCommonBlock(), Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newVarnodeOut(), Funcdata::opDestroy(), Funcdata::opInsertEnd(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and Funcdata::totalReplace().
Referenced by cseEliminateList().
cseFindInBlock()
PcodeOp* cseFindInBlock (PcodeOp * op, Varnode * vn, BlockBasic * bl, PcodeOp * earliest)
Find a duplicate calculation of a given PcodeOp reading a specific Varnode.
We only match 1 level of calculation. Additionally the duplicate must occur in the indicated basic block, earlier than a specified op.
Parameters
op is the given PcodeOp
vn is the specific Varnode that must be involved in the calculation
bl is the indicated basic block
earliest is the specified op to be earlier than
Returns
the discovered duplicate PcodeOp or NULL
References functionalEqualityLevel().
Referenced by RuleMultiCollapse::applyOp(), and RulePushMulti::findSubstitute().
earliestUseInBlock()
PcodeOp* earliestUseInBlock (Varnode * vn, BlockBasic * bl)
Get the earliest use/read of a Varnode in a specified basic block.
Parameters
vn is the Varnode to search for
bl is the specified basic block in which to search
Returns
the earliest PcodeOp reading the Varnode or NULL
Referenced by RulePushMulti::applyOp(), and RuleMultiCollapse::applyOp().
opFlipInPlaceExecute()
void opFlipInPlaceExecute (Funcdata & data, vector< PcodeOp * > & fliplist)
Perform op-code flips (in-place) to change a boolean value.
The precomputed list of PcodeOps have their op-codes modified to facilitate the flip.
Parameters
data is the function being modified
fliplist is the list of PcodeOps to modify
References CPUI_BOOL_AND, CPUI_BOOL_OR, CPUI_COPY, CPUI_INT_LESSEQUAL, CPUI_INT_SLESSEQUAL, CPUI_MAX, get_booleanflip(), PcodeOp::getSlot(), Funcdata::opDestroy(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), Funcdata::opSwapInput(), and Funcdata::replaceLessequal().
Referenced by ActionNormalizeBranches::apply(), and BlockIf::preferComplement().
opFlipInPlaceTest()
int4 opFlipInPlaceTest (PcodeOp * op, vector< PcodeOp * > & fliplist)
Trace a boolean value to a set of PcodeOps that can be changed to flip the boolean value.
The boolean Varnode is either the output of the given PcodeOp or the first input if the PcodeOp is a CBRANCH. The list of ops that need flipping is returned in an array
Parameters
op is the given PcodeOp
fliplist is the array that will hold the ops to flip
Returns
0 if the change normalizes, 1 if the change is ambivalent, 2 if the change does not normalize
References CPUI_BOOL_AND, CPUI_BOOL_NEGATE, CPUI_BOOL_OR, CPUI_CBRANCH, CPUI_FLOAT_EQUAL, CPUI_FLOAT_NOTEQUAL, CPUI_INT_EQUAL, CPUI_INT_LESS, CPUI_INT_LESSEQUAL, CPUI_INT_NOTEQUAL, CPUI_INT_SLESS, CPUI_INT_SLESSEQUAL, and Varnode::loneDescend().
Referenced by ActionNormalizeBranches::apply(), and BlockBasic::flipInPlaceTest().